- src/dev-requirements.txt
- src/makefile
- src/os_setup.py
- src/setup.py
This merge request:
* Adds support for specifying multiple version requirements for OS-level and Python packages in the setup script.
* Utilizes this new ability for specifying the version requirements for Pylint and its Astroid library.
* Adds support for specifying the verbosity of messages during setup, via the standard setup.py command line options for verbosity (-q, -v and their long versions).
It has been tested on RHEL 6.7 at this point with some manually created scenarios, and on the Travis CI (with its default scenario of most packages not being installed).
Please review.
> Setup: Multiple version requirements & verbosity control

- pywbem/cim_obj.py
This change removes a number of pylint warnings for a single module. The changes include
1. add docstrings
2. change number of single character names to multicharacter
3. add # pylint disable on many things.
This does not change any code other than the variable names.
> Initial cleanup of cim_obj for pylint issues.

- .travis.yml
- setup.py
This is to test the rebased fixes in PyWBEM's fork of M2Crypto.
There is only one fix remaining that was found to be required.
These fixes only affect installability of PyBEM, so testing with
python setup.py install_os
should be sufficient.
The counter-test by using the upstream M2Crypto version on RedHat based distros, to verify that  the original problem still exists, would also be good. To test that, change the following in PyWBEM's setup.py:
'dependency_links': [
-            "git+https://github.com/pywbem/m2crypto@amfix_rebased#egg=M2Crypto"
+            "git+https://gitlab.com/m2crypto/m2crypto#egg=M2Crypto"
],
> Using rebased M2Crypto fork

- pywbem/cim_constants.py
- pywbem/cim_http.py
- pywbem/cim_types.py
- pywbem/cim_xml.py
Cleaned up cim_constants.py, cim_http.py and cim_types.py.  Note that this does not remove all pylint issues but significantly reduces the number for these modules.
The end result is:
cim_constants                          0
cim_types                                 0
pywbem.cim_http               Total: 24
---------------------------------------
(protected-access)                   3
(line-too-long)                          7
(unnecessary-lambda)            1
(no-member)                          5
(fixme)                                    2
(not-an-iterable)                     1
(redefined-variable-type)        1
(deprecated-lambda)              1
(bad-builtin)                            1
(dangerous-default-value)      1
(using-constant-test)               1 …
> Clean up pylint for selected modules

- pywbem/tupleparse.py
Cleaned up tupleparser so only a few issues remain in pylint output.  Note that I cleaned up a number
of things that andy actually disabled for now in pylint.rc so there are a lot of changes.
Issues in current pylint.log after chages are:
W:405, 0: TODO: Currently disabled, figure out how to reenable (fixme)
W:561, 0: TODO: Verify these errno numbers on Windows vs. Linux (fixme)
W:243,16: Access to a protected member _path of a client class (protected-access)
W:246,12: Access to a protected member _path of a client class (protected-access)
W:247,11: Access to a protected member _path of a client class (protected-access)
W:250, 0: Dangerous default value [] as argument (dangerous-default-value)
E:335,15: Instance of 'HTTPBaseConnection' has no 'sock' member (no-member)
E:336,19: Instance …
> pylint changes to tupleparser

- pywbem/wbemcli.py
- testsuite/test_cim_http.py
- testsuite/test_cim_obj.py
Cleaned up wbemcli to better understand it.  Note that this is really incomplete in that the doc strings are minimal but there are other issues behind that.  Primarily pylints and docstrings.
Cleaned up the test_* simply because there were so many trivial issues, primarly formatting, etc. No code changes at all. I did pylint disable invalid_names which seemed logical since a lot of the variables are single character and these are test programs.
> pylint cleanup of wbemcli, test_cim_http, test_cim_xml

- pywbem/cim_obj.py
- pywbem/cim_operations.py
- pywbem/cim_xml.py
- pywbem/cimxml_parse.py
- pywbem/tupleparse.py
- pywbem/tupletree.py
- testsuite/test_cim_xml.py
- testsuite/test_client.py
- testsuite/test_tupleparse.py
Number of mostly cleanup including adding some docstrings, rename some variables, bunch of
disables, etc.  Did some changes to the testsuite also primarily multiple line alignment.
Passed tests locally.  Note that count is down to 599 and I added at least 10 new TODOs
Summary with this change is as follows:
Count of messages per module summary
======================================
pywbem.mof_compiler                240
test_nocasedict                     44
pywbem.cim_obj                      33
test_cim_obj                        32
pywbem.tupleparse                   32
pywbem.cim_xml                      29
test_mof_compiler                   29
test_cim_xml                        27
test_cimxmlparse                    24
test_client                         22
pywbem.cimxml_parse …
> Pylintfixes4 misc fixes to reduce pylint count

- setup.py
As of today, the master branch of the [upstream M2Crypto repo](https://gitlab.com/m2crypto/m2crypto) has all fixes that we had in our [pywbem/m2crypto fork](https://github.com/pywbem/m2crypto), so the next version of M2Crypto after its current 0.23.0 will have them all.
The change in this PR changes PyWBEM's `setup.py` to install M2Crypto from the master branch of its upstream repo, instead of using our own fork.
If the official next version of M2Crypto gets released before PyWBEM 0.8.0, we should change that again to install that version from PyPI.
> Changed M2Crypto install source to master branch of its upstream repo.

- pywbem/cim_operations.py
Remove the unsupported statements in the docstrings for the class and qualifier operations in cim_operations.py.  While there are no end-end tests, general testing is sufficient to assure that they do generally work.
> Remove the unsupported comments issue #75

- pywbem/cimxml_parse.py
Replaced the definition of class `ParseError` in sub-module `cimxml_parse.py` by an import of `ParseError` from `tupleparse`.
> Fixes #71: Two classes ParseError defined

- .gitignore
- coveragerc
- makefile
- setup.py
This uses the Python "coverage" package, and its py.test plugin "pytest-cov".
The setup script was updated to automatically install it in development mode.
The coverage report is part of the stdout when running py.test, e.g. with `make test`.
> Fixes #60: Add support for measuring and reporting test coverage

- testsuite/test_client.py
- testsuite/test_client/enumerateinstances.yaml
This change modifies test_client to allow lists for the result: yaml so that we can list multiple instances for the response.
Then it adds enumerateinstances.yaml as a new test.
Passes tests with python 27 and 3
Note that as with other of these tests:
1. The data is somewhat artifical, in particular on responses and in some cases simpler than what an
actual server returns.
2. We are testing only a subset of the current possible alternatives.
But this does test the basic paths of enumerateInstances with both multiple, single, and no instance returns and a number of the possible error paths.
Needs:
1. More options on the in put parameters, in particular the propertylist
2. more of the possible data in the responses (ex. include class origin, etc.)
Changed the overall coverage by about +1%
> Changes to test_client.py for list in result: and yaml for enum insts.

- testsuite/test_mof_compiler.py
Issue #80 notes that we are using a very old version of the cim schema as part of our tests.
This pull requests updates the cim schema to be downloaded to the current version of the schema
and also changes it from the experimental to the final version since there is no real guarantee that the experimental compiles.
Note that it makes a couple of other changes to eliminate pylint messages in imports, constant names, and indenting.
> Modifications to compiler test to use later version of schema, issue #80

- testsuite/run_cim_operations.py
This fixes a number of issues with this code including:
1. exception handling syntax
2. The cmd line argument processing. Allso added new options.
3. A number of the tests
4. Lots of pylints.
However, I am not yet complete.  In particular, I think it will fail tests (the internal_test) with python 3 and there are issues with the classVerifier class and its verifiers.
Note that it does pass just about all of the tests in openpegasus which is a validation that most things work.  However, there are a number of unimplemented tests and the execquery fails for because we do not implement the query mechanism for classes in the repository.
> Fixes #87: Fix run_operations.py issues

- testsuite/test_cim_operations.py
This file currently adds only one new file and one test, the test on check_utf_8...
function in cim_operations.  This was originally in
run_cim_operations.py but is not really an end-end test so more logical
here in test_cim_operations.py to run under tests. Note that this
code bypasses a number of the tests with python3 since they fail with
message about finding an int. These tests run in python2 but fail in
python3
Put temporary bypass for bunch of tests with python 3. They fail but pass with python 2
> Add test for functions in cim_operations.py module

- .gitignore
- makefile
- tools/pycmp.py
- tools/pycmp_0.7.0.sh
This PR adds a tool `pycmp.py` in a new `tools` directory, which compares two versions of PyWBEM w.r.t. their public interfaces. It generates a report on stdout. Invoke with --help for usage help.
It also adds a shell script `tools/pycmp_0.7.0.sh` which creates the files from PyWBEM 0.7.0 in a temp directory, removes setup.py (not part of the package) and wbemcli.py (cannot be imported in 0.7.0), and invokes `pycmp.py` to produce a report in the current directory. The shell script must be invoked in the root directory of the repo.
> Added tool pycmp.py to compare public interface between versions

- pywbem/cim_obj.py
- pywbem/cim_types.py
The following functions have been removed from the external API (i.e. they have been removed from `__all__`):
pywbem.cim_obj.tocimobj
pywbem.cim_obj.tocimxml
pywbem.cim_types.atomic_to_cim_xml
pywbem.cim_types.cimtype
pywbem.cim_types.type_from_name
None of them should be needed by normal client code. For example, client code should not have to deal with CIM-XML representations.
Note that most CIM object classes have a `tomof()` method.
> Fixes #77: Removed unnecessary functions in cim_obj/cim_types from external API

- tools/pycmp_0.7.0.sh
This should fix the problem that Karl reported in PR #83.
The `pycmp_*.sh` shell script now installs the "twisted" Python package before invoking the `pycmp.py` script.
> Fixed pycmp_0.7.0.sh script by installing twisted package.

- pywbem/NEWS
- pywbem/__init__.py
- setup.py
Updated NEWS file with recent changes.
Bumped version to 0.8.0.
This PR addresses the "release issue" #59.
> Release version 0.8.0 (on hold)

- makefile
- pywbem/__init__.py
- pywbem/_version.py
- setup.py
This reduces the two definitions to one, in order to simplify the version definition (for this git repo; the pywbem.github.io repo will be dealt with separately).
The new place is a new file `pywbem/_version.py`, which gets:
- imported into by `pywbem/__init__.py` for pywbem users (a new import).
- read as Python code without importing by `setup.py` (new code in setup.py).
Already existing usages of the version, just to be complete:
- grepped for `__version__` by makefile, and then used in various ways, e.g. for distribution directory and file name (that existed before, and was just adjusted to use the new file).
- used by the Epydoc-built documentation (that existed before and did not needed to be adjusted).
> Moved definition of package version into a single place: pywbem/_version.py

- pywbem/mof_compiler.py
- pywbem/wbemcli.py
This PR migrated the `mof_compiler.py` and `wbemcli.py` modules to use argparse instead or optparse. It assumes that argparse is available also on Python 2.6 (it was added only in Python 2.7, but the package is available on most Linux distros).
Interesting review points:
- The help message; Invoke: `./mof_compiler -h` and `./wbemcli -h`
- Is argparse in Python 2.6 available on distro xyz.
> Fixes #69: Migrated mof_compiler and wbemcli to argparse and improved help messages.

- pywbem/NEWS.md
- pywbem/cim_obj.py
- pywbem/cim_operations.py
- pywbem/cim_types.py
- testsuite/test_cim_obj.py
Details, from the commit message:
- Changed the return value of `repr()` for `WBEMConnection`, CIM type
classes (e.g. `Sint8`, `CIMDateTime`), and CIM object classes
(e.g. `CIMInstance`) so that they now return all attributes in a
reasonable order, and are suitable for debugging.
- Clarified in the description of `CIMClassName.__str__()` and
`CIMInstanceName.__str__()` that they return the WBEM URI representation
of the class path and instance path.
- Changed the return value of `str()` for CIM object classes
(e.g. `CIMProperty`) so that they now return a short set of the most
important attributes for human consumption.
Specifically, this resulted in the following changes:
- For `CIMProperty`, reduced the complete set of attributes to a short set.
- For `CIMParameter`, added the attribute …
> Fixes #93: Changes for repr() and str() of several classes.

- pywbem/__init__.py
- pywbem/cim_http.py
- pywbem/cim_obj.py
- pywbem/cim_operations.py
- pywbem/cim_types.py
- pywbem/cim_xml.py
- pywbem/mof_compiler.py
- pywbem/tupleparse.py
- pywbem/wbemcli.py
This PR was triggered by Karl's comment 2 on issue #93, and then evolved in some more docstring changes.
Details, from the combined commit messages:
- Resolved nearly all Eydoc warnings.
- Added class names to all docstrings of `cim_obj` classes (see Karl's comment 2 on issue #93).
- Moved CIM-XML DTD definitions in `tupleparse.py` from Python comments into the docstrings.
- In `mof_compiler._print_logger()`, changed name of `str_` argument to `msg`, to avoid Epydoc warning about unresolved link target. This is an internal function so this should not be a problem for users.
> Resolved Epydoc warnings and improved docstrings.

- pywbem/cim_obj.py
- testsuite/run_cim_operations.py
- testsuite/test_cim_obj.py
Adds code for embedded instance tomof, generalizes mof indent, sets mof indent
from 7 to 4, fixes several places where line overflows 80 col.
Adds constants to control indent and uses them to generate
indented mof.
Handles properties with arrays of values so that they do
not overflow max line length.
Add more tests to test_cim_obj.py for mof output of classes
and instances.
Remove special tests added to run_cim_operations.py that should be part of this commit/pr. Will be in separate branch
Adds one optional test to run_cim_operations.py
NOTE: I think that I had another embedinstance branch but this branch covers the error in embedded instance
Somehow I got too much into one branch, both the embedded instance fix and the clean up of mof output formatting.
> Save in process work to clean up mof indent issues #110 and #147

- setup.py
This PR solves issue #157 by changing the os-level dependencies 'zip' and 'unzip' to 'tar', to match the type of distribution archive that is being built. This was forgotten when moving back to the `.tar.gz` archive format in v0.8.1.
I have verified that a 'tar' package exists on the distros supported for os-level dependencies, and have tested `python setup.py develop_os` on CentOS 6.7 and Ubuntu 14.04.
> Fixes #157: Changed os-level dependency 'zip' and 'unzip' to 'tar' (stable_0.8)

- pywbem/cim_operations.py
- pywbem/wbemcli.py
I think this PR completely addresses the issues described in #34. Please review to that extent.
Also, make sure to run operations that have the IncludeClassOrigin parameter against SFCB and OpenPegasus, as well as EnumerateClasses.
The improvements in wbemcli required a fix in `cim_operations.imethodcall()` where any parameters that are `None` are now omitted from the request. They were running into issue #154, which is hereby also fixed. I think this change is safe to make, because if it is not made, None in any case leads to the ValueError exception described in #154.
Details from the commit message:
* Fixed issue that passing param=None to imethodcall() causes ValueError.
* Added help, added missing functionality.
- Added an interactive help function `Help()` / `h()` and hinted to it …
> Fixes #34, fixes #154: Various improvements to wbemcli + None parameter fix

- docs/conf.py
- docs/index.rst
- rtd-requirements.txt
- setup.py
This PR shows the last commit of the `master` branch in the "Changes" section of the Sphinx documentation, if the package version is a development version. Because development versions are not increased, this identifies the level of documentation when in development.
Please review.
> Show last commit in 'Changes' section of Sphinx documentation

- docs/changes.rst
- pywbem/cim_obj.py
- testsuite/test_cim_obj.py
Fixed the problem and extended the testcases in the `DictTest` class in `test_cim_obj.py` so that the problem would have been found. Also, changed from hard-coding the expected dict values to passing them in.
Ready for merging, please review.
> Fixes #185: Fixed KeyError when iterating over CIMInstance or CIMInstanceName.

- coveragerc
This PR changes `coveragerc` to enable the reporting of missing coverage lines, when running `make test`.
Please review.
> Enable missing coverage lines

- os_setup.py
- setup.py
This adds support for manually installing pywbem on Linux Mint (=Ubuntu). Otherwise it would be:
$ python setup.py install_os
running install_os
install_os: Installing prerequisite OS packages for platform: linuxmint
Processing OS package requirement: libssl-dev>=1.0.1
Processing OS package requirement: g++>=4.4
Testing for availability of Swig >=2.0 in PATH...
Swig is available in PATH; testing its version...
Installed Swig version is sufficient: 2.0.11
Processing OS package requirement: python-dev
Processing OS package requirement: git>=1.7
Error: This platform (linuxmint) is not supported for installation of OS packages.
The following OS packages need to be verified and installed manually, if missing:
libssl-dev >=1.0.1
g++ >=4.4
python-dev
git >=1.7
error: Errors occurred (see …
> Add support for Linux Mint

- docs/compiler.rst
- pywbem/mof_compiler.py
Ready to be merged. PLease review.
Details:
- Changed exception `MOFParseError` to be derived from `pywbem.Error` (was previously derived from `ValueError`).
- Added `BaseRepositoryConnection` to external MOF compiler API.
- Minor text changes in MOF compiler API documentation.
> Minor doc improvements for MOF compiler API; rebased MofParseError.

- pywbem/cim_obj.py
- pywbem/mof_compiler.py
- testsuite/test_mof_compiler.py
- testsuite/testmofs/qualifiers.mof
- testsuite/testmofs/test_types.mof
- testsuite/unittest_extensions.py
This PR re-establishes the change that was lost by accident in PR #206.
Ready for merge. Please review.
- In `tocimobj()`, values with CIM type name 'string' were just returned. This did not step up to the promise of returning the CIM-XML representation, which must be a unicode string. Added code that ensures that the returned value is a unicode string, even when providing a byte string as input.
- CIM datatype char16 was not supported in `tocimobj()` and in the MOF compiler. Added support for 'char16'.
- If the MOF compiler encounters an unknown alias name, it raises a CIMError with status code CIM_ERR_FAILED and status description 'Unknown alias: <alias-name>'. The alias name was taken from the wrong tuple member, causing another exception to be raised. …
> Fixes #171 (try 2): Fixed errors and added tests for MOF lexer in mof_compiler.

- pywbem/cim_obj.py
- testsuite/test_nocasedict.py
Ready for merging. Please review.
The NocaseDict ordering problems described in issue #210 are commented out with a TODO to re-enable them if one wants to work on them.
Besides that, other tests have been added that increase test coverage for NocaseDict.
I thought for consistency, it would be good to add tuple (with items tuple(key,value)) as a possible input to the ctor of NocaseDict (it already supported list with items tuple(key,value)).
> Added tuple as possible input type for NocaseDict; Added and improved testcases for NocaseDict.

- pywbem/cim_obj.py
- pywbem/mof_compiler.py
- testsuite/test_client.py
- testsuite/test_client/getalltypes.yaml
- testsuite/test_mof_compiler.py
- testsuite/testmofs/qualifiers.mof
- testsuite/testmofs/test_types.mof
- testsuite/unittest_extensions.py
This PR is now ready for merge. Please review.
It adds the YAML file `getalltypes.yaml` which contains a simple test case: A GetInstance operation returning one instance that has one property of every possible CIM datatype, including char16 and an embedded instance.
The PR needed to fix an error in the test_client.py test driver, whereby the dict of properties was not correctly converted into CIM objects.
> Initial stab at testing all property types incl. emb.inst.

- docs/changes.rst
- docs/intro.rst
- makefile
- pywbem/cim_obj.py
Follows the deprecation policy added in PR #248.
Please review.
> 207 Deprecated `value` instance variable and ctor parameter of `CIMParameter`

- docs/changes.rst
- docs/intro.rst
- makefile
- pywbem/cim_operations.py
Follows the deprecation policy added in PR #248.
Please review.
> Fixes #196: Deprecated imethodcall() and methodcall().

- docs/changes.rst
- pywbem/cim_obj.py
- testsuite/test_cim_obj.py
…omof() output drops array indicator
The mof should output an array indicator "[]" when CIMParameter is_array
is set and with the array size if array_size is not None.  The code
correctly issues the one if array size is set but ignores the array
indicator output if only is_array is set.
The CIMMethod.tomof() was outputting an extra \n after last method.
> Fixes #263: tomof() output of CIMClass / CIMMethod / CIMParameter drops array indicator

- docs/intro.rst
Please review.
Note: This change already includes what the additions from the ``listener`` branch conform to, with a TODO to be finalized / adjusted / removed once that branch gets merged.
> Fixes #259: Added section 'Standards conformance' to documentation

- docs/changes.rst
- pywbem/cim_operations.py
- testsuite/test_client.py
Ready to be merged. Please review!
Details:
- Added an optional `namespace` parameter to the `WBEMConnection.CreateInstance()` method, for consistency with other methods, and to have an explicit alternative to the namespace in the path component of  the `NewInstance` parameter.
- The `ClassName` parameter of several operation methods can be specified as both a string and a `CIMClassName` object. In the latter case, a namespace in that object was ignored so far. Now, it is honored. This affects the following `WBEMConnection` methods: `EnumerateInstanceNames`, `EnumerateInstances`, `EnumerateClassNames`, `EnumerateClasses`, `GetClass`, `DeleteClass`.
- In the `WBEMConnection.ModifyInstance()` method, the class names in the instance and path component of the `ModifiedInstance` parameter are …
> Fixes #197: Fixed issues with namespace and path in WBEMConnection methods

- docs/changes.rst
- pywbem/cim_obj.py
- pywbem/cim_types.py
- testsuite/test_nocasedict.py
Fix issue #210.
Work in progress, not ready to be merged.
At this point, this PR contains improved testcases for dictionary ordering (ordering between two dictionaries, that is), that verify the ordering behavior between two standard Python dictionaries. The corresponding test runs for NocaseDict are disabled.
> Fixes #210: Deprecate ordering comparisons for NocaseDict and CIM objects

- INSTALL.md
- os_setup.py
- setup.py
This PR is ready to be merged. Please review.
It addresses issue #280 by explaining how to establish the OS-level prerequisites such as Swig.
Details:
- Fixed description in `INSTALL.md` to correctly describe how to establish OS-level prerequisites.
- Improved Swig installation code by reinstalling Swig if it was installed but still cannot be found in PATH (e.g. if the installation was tampered with).
- Removed dependency on git (this was a leftover from when M2Crypto needed to be obtained from its development repo).
> Improved installation and its description for Swig failures.

- docs/changes.rst
- pywbem/__init__.py
This PR was created in order to address a side issues described in issue #179.
This PR targets the 0.9 (master) release stream, PR #291 will target the 0.8 release stream.
> Added runtime check for minimum Python 3 version 3.4 (for master branch)

- pywbem/NEWS
- pywbem/cim_http.py
- pywbem/cim_operations.py
This PR makes some decisions on the discussion points stated in issue #288, and should be seen as a proposal on how to address them.
Otherwise, ready to be merged. Please review.
- In `wbem_request()`, changed catching of `Exception` to `SocketErrors` to avoid secondary `IndexError` on access of `exc.args[0]`.
- Added debug prints if ECONNRESET or EPIPE are encountered. The debug prints are disabled by default and can be enabled by setting `conn.debug=True`. In support of that, passed 'conn.debug` to `wbem_request()`.
- In our copy of httplib `send()` in `HTTPBaseConnection`, merged the latest code (which supports data objects that have a read() method - which probably is not used in pywbem).
- Added Todo entry for turning the quick fix of having …
> Fixes #288: IndexError when handling exception from send()); Added debug prints for those ignored exceptions.

- examples/listen.py
This PR fixes issue #302 for the examples/listen.py script. Because that is currently only in the listener branch, this PR targets that branch.
Ready to be merged, please review.
- This fixes issue 302 for the examples/listen.py script, by accessing the error code no longer by array subscription, but by accessing the errno attribute.
- Also, established compatibility between the different exceptions raised before and starting with Python 3.3 (IOError vs FileNotFoundError).
> Fixed FileNotFoundError not subscriptable problem in examples/listen.py for Python 3

- docs/changes.rst
- wbemcli
Ready to be merged - please review. This solves the issue for the master branch.
- This fixes issue #302 for the wbemcli command, by accessing the error code no longer by array subscription, but by accessing the errno attribute.
- Also, established compatibility between the different exceptions raised before and starting with Python 3.3 (IOError vs FileNotFoundError).
> Fixed FileNotFoundError not subscriptable problem in wbemcli for Python 3

- pywbem/NEWS
- pywbem/wbemcli.py
Ready to be merged - please review. This fixes the issue for the stable_0.8 branch. Otherwise, same as PR #303.
- This fixes issue #302 for the wbemcli command, by accessing the error code no longer by array subscription, but by accessing the errno attribute.
- Also, established compatibility between the different exceptions raised before and starting with Python 3.3 (IOError vs FileNotFoundError).
> Fixes #302: Fixed FileNotFoundError not subscriptable problem in wbemcli for Python 3

- pywbem/NEWS
- pywbem/cim_http.py
This PR rolls PR #179 back to v0.8.
Please test.
- Separated the code paths for Python 2 using M2Crypto and Python 3 using standard Python SSL.
- This fixed issue #150 (Socket error: check_hostname requires server_hostname).
- The callback passed in the WBEMConnection verify_callback parameter is no longer being called in Python 3, because standard Python SSL does not support a callback. In Python 2, it continues to be called.
- The hostname in the server certificate is now being verified against the connection hostname, in Python 3 (That already worked in Python 2). There are still differences in the quality of the hostname matching across the different Python versions. The description of that is part of issue #277.
- The tunnel support is not currently in …
> Fixes #150, Fixes #274, Fixes #288: Fixed issues in SSL support for Python 3.

- docs/changes.rst
- pywbem/cim_obj.py
- testsuite/test_cim_obj.py
Small code change and adds test. The issue is marked required for 0.9.0. Included update to changes.rst
> issue #289 fix error in property tomof() of datetime values

- docs/changes.rst
- testsuite/run_cim_operations.py
Adds and expands tests in this test file. 
1. Expanded enumeratInstances to many tests
2. Added tests to a number of other operations.
3. Added TODOs where we probably want to expand next
3. Added tests for the server itself (interop namespace, etc.). Note that this does NOT use the new
Server class.  We need to add those tests also but wanted to close this work out
4. Add test subclass for openpegasus and some tests that are specifically OpenPegasus including
a class that return all property types.
5. Expanded the cli parameters for more clarification and to add some of the https parameters.
> Expand run cim operations

- .travis.yml
- setup.py
Please review quickly, because this is needed as a basis to get the other PR checks running again.
- Added dependency to `ordereddict` PyPI package to `develop_requires` argument of setup script when running on Python 2.6.
- In Travis CI control file, moved some build commands from the "install" section to "script" section, in order to continue when they fail.
- In Travis CI control file, printed debug information about version and content of the GitPython package (temporary change until GitPython 2.0.4 gets released).
- In Travis CI control file, disabled `make builddoc` step when running on Python 2.6 (temporary change until GitPython 2.0.4 gets released).
> Temporary workaround for issue 331 with Travis CI running on Python 2.6

- .travis.yml
- docs/changes.rst
- pywbem/cim_operations.py
- setup.py
Please review.
I tested only with `make test`, plus the Travis CI test runs fine, so please run your real test, Karl.
* Issue #322: When the ObjectName argument was passed as a class name string,
the target namespace was incorrectly determined to be the class name,
instead of using the default namespace of the connection (as documented).
This was fixed by splitting the namespace extraction function into one for
namespaces and one for object names.
> FIxes #322: Fixed problem in class-level associator operations that namespace was classname

- docs/changes.rst
- mof_compiler
- pywbem/mof_compiler.py
- testsuite/run_cim_operations.py
- testsuite/test_mof_compiler.py
Fixed this issue and added tests to confirm behavior.  The one discussion item is that in addition to removing the function that forced the toinstance flavor if the tosubclass flavor was set, we also allow the toinstance to be set specifically if it is set in the mof.  
**DISCUSSION**: Should we allow the mof writer to ever input with the toinstance flavor set either on qualifier declaration, or class.  To me it would probably never be used but seems logical.
> Fixes #193: Remove toinstance flavor

- examples/enuminstances.py
Adds an example of EnumerateInstances with ability for command line to define host, namespace, classname, user, password and display of exceptions. Note that this example displays details of CIMError.
Tried to keep this simple by not using argparse.  That creates a messy cmd line but wanted to keep the example simple and still allow it to be used against both a predefined server/class and also allow the user to work against arbitary server/class.
> issue # 324 Adds an example of EnumerateInstances with ability for command line

- docs/changes.rst
- docs/client.rst
- docs/intro.rst
- pywbem/cim_operations.py
This PR updates the description of the `WBEMConnection` constructor somewhat, and mainly adds a new section "Security Considerations" in the WBEM Client Library API.
This PR is ready to be merged. Please review (This is best done via `make builddoc` and reading the HTML output).
> Fixes #277: Added description of authentication types in WBEM client API

- docs/changes.rst
- pywbem/cim_obj.py
- testsuite/test_cim_obj.py
fixes existing tests that did not include this parameter. Adds test to
confirm that the new test on return_type works.  adds to changes.rst
Sorry for the bad pr last night.   Can only guess that I must have branched frop the pull ops branch.
> fix issue #264 adds test for Null to CIMMethod return_type

- docs/changes.rst
- pywbem/cim_obj.py
- testsuite/run_cim_operations.py
Extends test on input to allow both tuple and list. Extends tests in
run_cimoperations.py for more complete testing of propertylist and
some other tests.
Adds specific test for tuple input for propertylist.
Adds comment to changes.rst
This specifically allows the tuple as input.  Couple of minor issues here:
1. Do we really want to allow the tuple?
2. the tuple with single entry is a mess (requires a comma after the entry
3. If you do a tuple instead of a list with a single entry, it actually goes through but generates xml error because the tuple is not being handled as a tuple in cim_obj.py
4. Documentation defines list in some places and iterable in others.
> issue# 347 Allow tuple as input for PropertyList parameter in cim_operations

- .travis.yml
- os_setup.py
- setup.py
GitHub 2.0.5 has been released yesterday, and includes the fix needed for Python 2.6 (of using OrderedDict from ordereddict, if not available in collections).
Unfortunately, GitPython 2.0.5 introduced a new issue for Python 2.6, see [GitPython issue 457](https://github.com/gitpython-developers/GitPython/issues/457), so `make builddoc` still needs to be disabled for the time being.
This PR is still ready to be merged, and a future PR can re-enable `make builddoc` on Python 2.6.
Please review.
- Updated the setup script to require Gitpython 2.0.5.
- Updated the Travis CI control file to remove the debug displaying of the GitPython version.
- In os_setup, changed Python installer to use XML-RPC API of new PyPI warehouse site to fix issues with old PyPI site.
- …
> Use GitPython 2.0.5 and improve Python installer

- docs/changes.rst
- docs/intro.rst
- examples/pullenuminstances.py
- pywbem/cim_operations.py
- pywbem/tupleparse.py
- testsuite/run_cim_operations.py
- testsuite/test_client.py
- testsuite/test_client/openenuminstances.yaml
This commit includes OpenEnumerateInstancesWithPath,
PullInstancesWithPath, CloseEnumeration, OpenEnumerateInstancePaths,
and PullInstancePaths. The documentation is defined for all but
OpenEnumerateInstancePaths and PullInstancePaths.
The mock test is broken but there is a first set of tests in
run_cimoperations.py that executes a number of variations of
OpenEnumerateInstancePaths with pull and close against OpenPegasus.
NOT READY FOR MERGE.
Here is first cut of part ready for review and comment.  In particular, this currently fails mock and only about hallf of operaitons there.  Since the documentaiton for each operation is enormous would like to get the first one clean (OpenEnumerateInstances) before doing the other opens.
Also some code is hacky and we should discuss the enum_context …
> Fixes #9, Fixes #329: implement DMTF Pull Operations with tests

- pywbem/cim_operations.py
Never make last minute change without full test. Fixed variable mispelling that I made at last minute and did not run through complete test set.  Also removes a few trailing spaces.
> Fixes #358 Correct variable mispelling in OpenExecQuery

- pywbem/cim_http.py
Teste manually with this simple patch and a hack to pegasus that disables responses so server accepts requests but does not respond.
Captured details in issue #215 but the general conclusion is:
1. enabling does not kill the server. It passes python 2 and 3 tests on my system.
2. It does cause the client to timeout with m2crypto.  However, the timeout times can run from correct to 300% of correct. (i.e. a 4 sec timeout causes timeout in from 4 to 12 seconds with most in 4 sec.)
3. We have another issue in that in when https verification is set we get a verification error exception and not a timeout exception.  See the details recorded in the issue
I had to do this manually since there is no automatic way to set the pegasus server to delay responses right now, it was a code hack.
I want to …
> WIP fixes #215 enable the timeout for m2crypto

- testsuite/test_client.py
- testsuite/test_client/networkerror.yaml
Extends test_client.py to add new callback for socket.timeout and
creates a first use of this function in a test that executes the timeout
exception return.
NOTE: Test marked HTTP because there is an issue with timeout and
HTTPS. See issue # 363
> fixes #364 Extend test_client.py to handle timeout exception and add test.

- docs/changes.rst
- docs/client.rst
- makefile
- pywbem/__init__.py
- pywbem/_recorder.py
- pywbem/cim_http.py
- pywbem/cim_operations.py
**Ready to be merged** even though this is only a first stage in addressing issue #351.
Please review and test.
The purpose of merging this stage now is that the changes in cim_operations are large but still simple, and we should not mix that with small but difficult changes. Also, merging this stage allows testing with it, and that gives higher confidence.
The implementation provides a working operation recording, but the class that will produce the `test_client` yaml testcases at this point only outputs a debug print.
- Added `_recorder` module with abstract base class `BaseOperationRecorder` and testcase generator class `TestClientRecorder` and a few helper classes.
- Added `operation_recorder` instance variable to the `WBEMConnection` class that allows to …
> Issue #351: Initial stab at operation recording support.

- testsuite/run_cim_operations.py
- testsuite/test_client/README.md
Documented the extension to test_client yaml for pull operations in the
README.md file
Added option to run_cimoperation.py to separate out long-running
operations so we can do short test and long test. It is new option on
the cmd line and tests that are long_running have a special decorator.
We also cleaned up the pull tests and corrected some issues in all of
the tests.  Part of this was to add some common functions that compare
lists of instances and paths for equality.
Note that the long tests (-l option) now take several minutes whereas
short tests take about 30 seconds.
> fixes #361 Add doc on test_client yaml extension & extend run_operations.py

- pywbem/mof_compiler.py
- testsuite/test_mof_compiler.py
Adds new test for mof roundtrip.  At this point, this test fails in the recompile; we get a number of compile errors during the recompile and I have not been able to isolate them.  We do have issues in the mof output apparently
When we can get through the recompile we can recombine this with the more schema test so that we only have to compile the schema one time, reducing the test time significantly.  I am keeping it separate to be sure that the FullSchema test actually runs.
We have two choices
1. add this test to master now and accept that we get failures
2. Try to get the mof output completely fixed.
NOTE: I thought that this would be easy but the output is very large and the placing of errors does not yet appear logical.
NOTE: I tried to figure out how to run the compile test one …
> Mof roundtrip test test added to mof_compile

- docs/changes.rst
- examples/pegasusindicationtest.py
This is a complete of an in process listener with a client that
generates a number of indications for that listener and then
closes the server and finally exits.
Please review code.  Also see below for issue (pegasus or this
dropping indications)
Note that this does process indications but there is a problem
here between pegasus and this example.  We never receive the
number of indications expected.  At this point we can review and
even commit but there is an issue somewhere between 
pegasus and the listener in losing indications. 
Andy please review the code to be sure it matches your needs and
requirements for good code and the listener requirements.
Thus, for example, I put a listener.log in the process_indications
function  and used logger throughout.  Here is an example display …
> An example of indication management that runs against openPegasus

- docs/changes.rst
- wbemcli
Adds each operation with its parameters and detailed help to wbemcli.
This includes all of the pull operations.
Added note to changes.rst.
Note that not all have been tested however since that is a manual
operation.
I am not happy with the prefixes. First there are so many of them I cannot remember them and second, it really does not work to manually type these things in one at a time; the sequences timeout before you get the second part typed in.  But in any case, this is the logical extension to wbemcli for each pull operation.
> fixes #241 Add the individual pull operations to wbemcli

- .travis.yml
- setup.py
Ready to be merged (if Travis succeeds).
Please review.
> Fixes #331: Require Gitpython 2.0.6 and re-enable make builddoc on py26

- docs/changes.rst
- pywbem/_server.py
Please review.
Details: The root cause for showing `root/PG_Interop` as the Interop nanmespace for OpenPegasus was that that was the attempted namespace name, and the current code used the attempted name if successful.
This has been changed to inspect the returned CIM_Namespace instance paths and to use their `Name` keybinding, if possible. Otherwise, the attempted name is still used.
> Fixes #377: Incorrect lexical case of Interop namespace name with OpenPegasus

- docs/changes.rst
- docs/config.rst
- docs/index.rst
- makefile
- pywbem/__init__.py
- pywbem/cim_types.py
- pywbem/config.py
Please review.
This PR introduces a `pywbem.config` module for setting config variables.
It defines a first config variable `ENFORCE_INTEGER_RANGE` that controls whether the value range of CIM integer types is enforced or not.
The config variables are documented in a new chapter "Configuration".
> Fixes #381: Added support for a config variable to control enforcing the value range of CIM integer types

- pywbem/cim_http.py
Please review.
The reason the change loig is not updated with a fix entry, is that this error never showed up to the user, because in our case, the data object never has a ` read()` method.
> Fixes #389: Changing 'array' to 'list' in cim_http.py

- docs/changes.rst
- testsuite/run_cim_operations.py
This is a single test in in run_cimoperations.py that creates and deletes server, listener, subscription, filter.  It does not process indications nor test for errors.  It does verify that the host has the defined filter and subscription and that it deletes them.  We need to add more tests but wanted to get the basic structure running.  Note that this test runs only against pegasus because it depends on a particular class/provider (pegasus validates subscriptions against providers)
> Fixes #379: Add test to execute listener code

- docs/changes.rst
- examples/explore.py
- pywbem/_server.py
- testsuite/run_cim_operations.py
Review requested but DO NOT commit since have couple more cleanups if you agree with function.
I used this to add another function to server.  Please review to see if you approve.  This gets
a set of profiles with a single request which seemed like a logical simplification.
I used it in the explore example.
It is not ready to commit now.  1 Have the old function I wrote in the example code and have not
done test for it.  But if you agree the next steps are simple and will complete it.
> Fixes #378: Multiple profile example and add select_profiles function

- testsuite/run_cim_operations.py
1. Add dict entry for yamlfile. Avoids error when option not used.
2. Fixed issue that I apparently had missed before where
was using function from PyWBEMServerClass in PyWBEMListenerClass
but not subclassing the tests.
These were minor issues just to get tests running.
> fixes #399 Minor fixes to run_cim_operations.py

- .gitignore
- docs/changes.rst
- docs/client.rst
- docs/intro.rst
- docs/mof_compiler.help.txt
- pywbem/cim_http.py
- pywbem/cim_operations.py
- pywbem/exceptions.py
Ready to be merged. Please review
Details:
- Authentication errors are now always raised as `AuthError`. (OpenWBEM raised `ConnectionError` in one case).
- Any other bad HTTP responses are now raised as a new exception `HTTPError`.
- `HTTPError` and `CIMError` now have a ctor to improve documentation and to verify at least the number of args.
> Fixes #370, fixes #371: Cleaned up exception handling in `WBEMOperation` methods.

- docs/changes.rst
- docs/mof_compiler.help.txt
- pywbem/mof_compiler.py
- testsuite/test_mof_compiler.py
- testsuite/testmofs/test_instance.mof
- testsuite/testmofs/test_types.mof
Issues agreed on I hope and fixed. **Ready For Review** with update 2 July morning.
When instances were created by the compiler, it got information from the
corresponding class but put the instance property values into the class
itself since the compiler was not copying the properties from the class to the instance.
Separated these so the instance properties go into the instance. This means:
1. We are not trashing the class when we do an instance compile.
2. Each instance receives its own properties if compiling more than one instance. Before the property values for the last instance compiled went into all instances and the class.
3. Originally it build instances with all properties from the class and included whatever value was in the class itself. Now only properties defined in the mof …
> Fixes #402: Modify compiler to separate class properties from instance properties

- examples/listen.py
- examples/pegasusindicationtest.py
- examples/send_indication.sh
- examples/send_indications.py
- pywbem/_listener.py
- pywbem/cim_http.py
- testsuite/run_cim_operations.py
Pls Review. Ready for Merge. 3 July 2016 
This pr corrects issues that were causing massive indication lost between pegasus server and listeners.  Specifically this fixes some issues in the listener that was causing responses to get lost and some issues in the tests that were causing failures with pegasus indications.
It creates a new test sender in python sendIndications.py in the example directory and fixes some errors in listener just to be sure the issue was not with the shell script sender.
Modifies the send_indication.sh to send multiple indications and adds argument parser for better understanding.  NOTE: Not really sure we need this in the future.  the corresponding sendIndications.py is parallel in operation and does not depend on curl, and will be more complete.
The good news is …
> Fixes #375: Missing indications

- docs/client.rst
- docs/mof_compiler.help.txt
- makefile
- pywbem/_listener.py
- pywbem/_recorder.py
- pywbem/_server.py
- pywbem/cim_constants.py
- pywbem/cim_http.py
- pywbem/cim_obj.py
- pywbem/cim_operations.py
- pywbem/cim_types.py
- pywbem/exceptions.py
- pywbem/mof_compiler.py
This one ended up to cover more than originally was intended.
There are these code (=non-docu) changes:
- Changed name of namedtuple item 'QueryResultClass' in result of `OpenQueryInstances()` to 'query_class'.
- Made `DEFAULT_CA_CERT_PATHS` constant in `cim_http` module public and documented it. It was referenced in the description of `WBEMConnection()`.
The rest are docu-only changes:
- Added missing information about paths in returned objects to all operations (it was missing in most of them). This was the actual reason for this change.
- Added missing information about paths in input objects in all operations (it was missing in only a few).
- Fixed incorrect description of `host` attribute of `CIMInstanceName` and …
> Fixes #354: Added info about paths in returned objects, and other docu fixes

- docs/changes.rst
- testsuite/run_operationtimeouts.py
- testsuite/test_client.py
- testsuite/test_client/README.md
- testsuite/test_client/networkerror.yaml
**Ready for review.**   Added a new file to test timeouts against pegasus and they work across the board (see run_operationtimeouts.py.) Added options to test_client.py to ignore tests and one to execute a single test. Added a new mock test for timeouts but since there are issues with python 2 I had to add a new attribute to the yaml to ignore python versions for particular test cases.
As a freebie I added a simple way to execute a single test in test_client.py
Passes both the mock tests and the run_.. tests. now.
The following is notes on the original issues we were having.
Note per that issue I was originally getting a cert error instead of a socket error  when testing a mock connection timeout with https.   However, it redoing the test today, I started getting the following with …
> Fixes #363: Add test to newtworkerror.yaml for https timeout

- docs/changes.rst
- pywbem/_listener.py
- testsuite/run_cim_operations.py
Ready For Review:
Adds two new functions to Listener.  These simply get the instances from
the corresponding CIM Class in the server so that a client can get
the server side of all of the various subscription classes.
COMMENT: I thought about adding a filter mechanism to this so you could filter by regex against particular properties (name, etc.) but concluded that if we want to filter lets make it a separate function.
Also, I am asking whether we should be getting the paths for these or the instances themselves but for the moment simply got the paths.  
DISCUSSION OF FUTURE REQUIREMENTS: should we add function or option to get instances rather than paths???
> fixes issue #421 Add functions to get listener destination and subscriptions from Server

- examples/pegasusindicationtest.py
- pywbem/_listener.py
- testsuite/run_cim_operations.py
Ready for review:
Andreas: you may elect to put this on off until you finish restructuring listener
Adds an optional user defined string id to the listener
definition an another one to the filter definition.
The listener id is prepended to the name of all destination and
listener objects if it exists.  The filter id is prepended to the
name property of all filters after the listener id.
These are an informal mechanism for the user to identify instances
of filters and destination ojects that it has registered with the
WBEM server.
Nothing is prepended if these attributes are None
> fixes issue #420 Add an optional string id to listener and filter

- docs/changes.rst
- mof_compiler
- pywbem/mof_compiler.py
- testsuite/test_mof_compiler.py
- testsuite/testmofs/parse_error03.mof
**Andy:** Ready for Review. See one question below.
Note: resubmitted with fix for issue#204 added since that is a test for new MOFParseError exception.
Note: For Tuesday and Wednesday morning travis repeatedly failed.  However, it passed completely as of about 13:00 US CDT Wednesday.
Adds attributes at the class level for the MOFParseError class and
cleans up the error processing. This identifies the attributes,
centralizes
how they are acquired (several are acquired from the parser token
returned).  It prints out the same error message as before these
changes.
Adds a simple test for conflicting flavors (tosubclass and restricted or enableoverride and disable override). Also adds tests for case insensitivity in flavors and invalid flavor names.
Note that this does NOT test for conflicts …
> fixes issues #169 and #204 Clean up MofParseError Class and test conflicting flavors

- os_setup.py
The `make develop` target invokes `python setup.py develop` which accesses Pypi in order to verify availability of dependent packages. This currently fails because the new Pypi warehoue at pypi.io moved to pypi.org and the old site returns a HTTP 301 "Redirect" status which the xmlrpc client used to access it does not handle.
The fix is to simply use the new site directly.
This fixes the Travis CI errors we currently have.
> Fixed '301 Redirect' error when 'make develop' accesses pypi.

- testsuite/test_client/enumerateinstancenames.yaml
- testsuite/test_client/enumerateinstances.yaml
The tests cover all successful cases, including special handling of input parameters (namespace and classname) and output parameters (namespace set in returned path), and the documented server-originated error cases.
Any other error cases are not covered; they should be covered in separate test cases, because they are not so much specific to an operation.
> Fixes #153: Completed test_client test cases for EnumerateInstances and EnumerateInstanceNames

- README.md
- docs/changes.rst
- docs/client.rst
- docs/compiler.rst
- docs/conf.py
- docs/config.rst
- docs/index.rst
- docs/intro.rst
- docs/listener.rst
- docs/server.rst
- docs/tutorial.rst
- docs/utilities.rst
- pywbem/__init__.py
- pywbem/_listener.py
- pywbem/_server.py
- pywbem/_version.py
- pywbem/cim_constants.py
- pywbem/cim_obj.py
- pywbem/cim_operations.py
- pywbem/cim_types.py
- pywbem/cim_xml.py
- pywbem/config.py
- pywbem/mof_compiler.py
- setup.py
This PR makes a number of changes in the documentation, that I think are needed before we release v0.9.0.
Details:
- Moved "Package version" chapter from "WBEM client library API" section into
"Introduction" section.
- Fixed missing and incorrect anchors in `client.rst`.
- Refactored package docu (module docstring in `__init.py__`), by moving
(and improving) information about namespaces and external symbols into a new
chapter "Python namespaces" in the "Introduction" section, and by moving the
introduction of the chapters to the WBEM client library API into `client.rst`,
adding the entry for "Security Considerations".
- Improved the introduction text of the "WBEM server API", "WBEM listener
API", and "MOF compiler API" chapters.
- For `ValueMapping`, corrected …
> Improved and fixed documentation.

- pywbem/cim_obj.py
- testsuite/run_cim_operations.py
Change to output MOF per dsp0004  for tomof() of an embeddedinstance  property rather than than xml.  Add test to run_cimoperations.py for the mof.  See DSP0004, Appendix F1.
> Fixes  #147: Change CIMProperty tomof output for embeddedinst

- pywbem/cim_obj.py
- pywbem/mof_compiler.py
Initial commit had an accidentally folded comment causing build failures.  Update committed.
Documents the issues with flavors and the defaults required. Also adds
todo to consider removal of toinstance in future
> Fixes #203: Document limitations of flavors

- pywbem/cim_obj.py
We deprecated the use of `CIMParameter.value`, and so we should not show it in `__str__()` and `__repr__()`. Besides that, accessing it in these functions would cause a `DeprecationWarning` to be issued.
PR #467 already removed the item in the change log that was stating that `value` was added to `CIMParameter.__str__()`.
> Removed `value` from str() and repr() of CIMParameter

- examples/listen.py
- examples/send_indications.py
1. Correct some minor issues in listen.py including a)lowercase the
object name since it is easier to type, b) add status function c) enable
output of indication with logging function. d) add thread protection to
the processing function
2. Extend the send_indications.py example to allow https indications.
However, this is currently set to force verify=false so that the client
does not verify the server cert because the requests code does not like
our current cert (it is unhappy about a name element). Will have to recreate the
tmp.pem to pass requests ssl
Again marked this as 0.9.0 optional.  Certainly not required since these are examples and
do not show up in the pip.
> Fixes #481: Changes to examples for indications

- README.md
... and translated "2 months after 0.9.0" into "early november" as the estimated date for 0.10.0.
> Cleaned out v0.9.0 project plans from README file.

- docs/conf.py
- docs/tutorial.rst
Please review.
Best way to review this is building the documentation using `make builddoc` and looking at the Tutorials page of the documentation.
> Fixes #470: Make usage of Jupyter tutorials more obvious

- pywbem/_subscription_manager.py
Corrected just plain code error.  Meant that remove subscription does not actually remove subscription from server.
Think I need to do more through indication test since the test should have caught this.  But will make that part of general cleanup
Note that this is actually a BUG and should go into version 0.9.1.  However, we probably have a few days since I would not expect much use of the new code immediatly.
> Fixes #500: Correct var used before setting issue

- appveyor.yml
- makefile
- tox.ini
This one must be merged in order to fix the current failures of the Appveyor service.
Details:
- Added appveyor.yml file, loosely based upon the one from the distro project.
- Added pywin environment to tox.ini file.
- Removed `make clobber` from commands in tox.ini file.
- Added uninistall of pbr on py26 to commands in tox.ini file.
- Improved description in makefile about prereqs.
- Disabled the tox command in appveyor.yml file, for now, to fix the TODOs (OS-level prereqs for Windows).
> Added support for Windows CI on Appveyor service - currently disabled.

- flake8.rc
- makefile
- setup.py
Adds flake8 as lint tool to setup.py and makefile. 
It is executed as a component of check:. However
whereas pylint is python 2 only, flake8 is both
python2 and python 3.
Includes a first rc file. The rc file was created primarily to reduce those minor warnings, etc.
that are found many times.  This reduces the size of the file from about
140k to 40 k for the moment. One change to the config file was to set the line length to 80 from 79 because apparently we have pylint set to 80 so this does not show extra warnings like that.
All of the excluded warnings are documented in the pyflake8.log with comments defining what
is being warned.
Note that this does NOT include any of the many flake8 extra plugins.
> Fixes #512: Add flake8 as lint test to the make and setup.py.

- tools/pycmp.py
- tools/pycmp_0.7.0.sh
Please review.
The pycmp tool is only for the developers of pywbem. To see the tool in action, run the `tools/pycmp_0.7.0.sh` shell script and look at the generated `pycmp*.log` file, which reports the compatibility of the external API of pywbem between the work directory and 0.7.0.
> Fixed logic errors in pycmp compatibility check tool.

- docs/changes.rst
- pywbem/cim_http.py
- pywbem/exceptions.py
- testsuite/test_exceptions.py
Please review.
Details:
- Added the `pywbem.Error` base exception class to the `pywbem.cim_http` namespace where it existed in 0.7.0, for compatibility reasons.
- In the description of `CIMError`, clarified that accessing the exception object itself by index or slice will be delegated to its `args` instance variable.
- In the description of `CIMError`, clarified that `args[1]` is the *input* status description, not the value of the `status_description` property. The difference is that the latter defaults to a standard text if it is
not provided as input, but `args[1]` does not (for compatibility reasons).
- Added a unit testcase `test_exceptions.py` for the exceptions module.
> Fixes #511: Fixed compatibility issue with Error; Clarified CIMError; Added exceptions unit test

- docs/changes.rst
- pywbem/cim_http.py
- pywbem/exceptions.py
- testsuite/test_exceptions.py
This PR rolls back the fix for issue #511 into the 0.9 fix stream.
Details:
- Added the `pywbem.Error` base exception class to the `pywbem.cim_http` namespace where it existed in 0.7.0, for compatibility reasons.
- In the description of `CIMError`, clarified that accessing the exception object itself by index or slice will be delegated to its `args` instance variable.
- In the description of `CIMError`, clarified that `args[1]` is the *input* status description, not the value of the `status_description` property. The difference is that the latter defaults to a standard text if it is
not provided as input, but `args[1]` does not (for compatibility reasons).
- Added a unit testcase `test_exceptions.py` for the exceptions module.
> For 0.9: Fixed compatibility issue with Error; Clarified CIMError; Added exceptions unit test

- appveyor.yml
- testsuite/test_indicationlistener.py
- tox.ini
After many trial&error attempts, this PR is now ready for merge. Please review.
This PR fixes the installation of the Python lxml package on Windows in the Appveyor CI environment by manually downloading the binary libraries needed for the lxml build that happens during its Python installation.
It also disables the test case with sending 1000 indications in `testsuite/test_indicationlistener.py`, because that takes about 30min. Not sure what causes this slowness. The Appveyor CI environment is generally very fast (generally faster than Travis CI, it seems).
> Appveyor CI - Fixed installation of lxml install prereqs and enabled tests.

- .travis.yml
- README.md
- appveyor.yml
- testsuite/test_indicationlistener.py
- tox.ini
Please review.
This PR rolls the Appveyor changes from PR #525 into v0.9.
In addition, this PR adds support for the Coveralls service to v0.9.
> Added Appveyor CI and Coveralls support for 0.9.

- testsuite/run_cim_operations.py
Please Review
Issue #401 brought up the question of whether we should clean out the yaml file before each use (with some other issues).  However, the conclusion is that there is not an issue in the recorder itself since it starts with an open file.
Previously run_cimoperations.py  just appended to an existing file making the tests messy.  Note that the issue itself now requires no change to _recorder.py
I used this pr to fix the yaml file lifecycle in run_cimoperations.py  and as an easy way to close the issue.  I don't think there is any issue with the r_recorder itself but we were not cleaning out the old yaml file in cim_operations so added code to create a backup if the file exists so we start each run_cim_operations.py test with an empty yaml file.
Note that this does not create a …
> fixes #401: Modify run_cimoperations.py to rename yaml file before each test

- makefile
Please review.
The change causes the PyLint make rule to fail for error messages and fatal messages (and invocation errors). other types of messages are ignored.
At this point, the failure is ignored (using a dash with the make command), so this change is just a preparation for when we want to activate it.
> Added severity-sensitive return code checking for PyLint in makefile.

- .flake8
- os_setup.py
- pywbem/__init__.py
- pywbem/_listener.py
- pywbem/_server.py
- pywbem/_subscription_manager.py
- pywbem/cim_constants.py
- pywbem/cim_http.py
- pywbem/cim_obj.py
- pywbem/cim_operations.py
- pywbem/cim_types.py
- pywbem/cim_xml.py
- pywbem/mof_compiler.py
- setup.py
- testsuite/compat_args.py
- testsuite/run_cim_operations.py
- testsuite/run_operationtimeouts.py
- testsuite/test_cim_obj.py
- testsuite/test_cim_operations.py
- testsuite/test_cim_xml.py
- testsuite/test_client.py
- testsuite/test_exceptions.py
- testsuite/test_indicationlistener.py
- testsuite/test_mof_compiler.py
- testsuite/test_nocasedict.py
- testsuite/test_tupleparse.py
Ready for review.  I may have one more change today.
Cleans up a number of flake8 issues. This reduces the flake8 count from
about 200 to about 50 messages.
Currently the flake8 message summary is as follows:
```
3     E131 continuation line unaligned for hanging indent
33    E501 line too long (115 > 80 characters)
1     F401 '._version.__version__' imported but unused
8     F821 undefined name 'basestring'
1     F841 local variable 'insts_enum' is assigned to but never used
2     W601 .has_key() is deprecated, use 'in'
```
the E501 cover two issues:
1. A bunch of long lines in cim_operations.py in the table but we do not want to exclude this from the whole module.  flake8 has an issue with trying to ignore selected groups of code and further these are all in a comment and that causes …
> Cleanup of flake8 and pylint issues

- .flake8
- os_setup.py
- pywbem/_listener.py
- pywbem/_recorder.py
- pywbem/_server.py
- pywbem/_subscription_manager.py
- pywbem/cim_http.py
- pywbem/cim_obj.py
- pywbem/cim_operations.py
- pywbem/cim_types.py
- pywbem/cim_xml.py
- pywbem/mof_compiler.py
- pywbem/tupleparse.py
- setup.py
- testsuite/run_cim_operations.py
- testsuite/run_operationtimeouts.py
- testsuite/test_cim_http.py
- testsuite/test_cim_obj.py
- testsuite/test_cim_operations.py
- testsuite/test_cim_xml.py
- testsuite/test_client.py
- testsuite/test_mof_compiler.py
- testsuite/test_nocasedict.py
- testsuite/test_tupleparse.py
- testsuite/test_valuemapping.py
- testsuite/unittest_extensions.py
Ready for review
Removes a large number of flake8 messages.  Also fixed a few formatting issues noted by pylint but this did not really change pylint message count much.  Note that the current number of messages from flake8 is about the same but we now enabled the E502 error (there were over 400 of them)
This is completely aesthetic but makes the code cleaner.
the flake 8 message log summary is now:
3     E131 continuation line unaligned for hanging indent
33    E501 line too long (115 > 80 characters)
1     F401 '._version.__version__' imported but unused
2     F821 undefined name 'ResourceWarning'
1     F841 local variable 'insts_enum' is assigned to but never used
2     W601 .has_key() is deprecated, use 'in'
A number of these I just do not know how to resolve because of the way flake8 …
> fixes #542 redundant backslash flake8

- setup.py
> Fixes #550: Pin GitPython at 2.0.8 due to issues on Python 2.6.

- setup.py
Fixes issue #550 for stable 0.9 branch.
> Fixes 550 for pywbem 0.9: Pin GitPython at 2.0.8 due to issues on Python 2.6.

- pywbem/cim_operations.py
Small leftover from the previous flake8 PR.
I'll merge it once it passes the CI tests.
> Moved disabling of flake8 E501 to outside of the docstring in cim_operations.py

- testsuite/run_enum_performance.py
run_enum_performance.py generates a table of the relative performance of
EnumerateInstances vs. OpenEnumerateInstances/PullInstancesWithPath
performance over a range of MaxObjectCount, Response instance sizes,
and total number of instances in the response.
This generates the following table:
```
Operation  Response   RespSize   MaxObjCnt  Request    Time        inst/sec  
Count      Bytes      Request    Count                            
Enum       1          100        na         na         0:00:00.058 017.08    
Open/Pull  1          100        1          1          0:00:00.057 017.48    
Open/Pull  1          100        100        1          0:00:00.059 016.84    
Open/Pull  1          100        1000       1          0:00:00.059 016.84    
Enum       100        100        na …
```
> fixes #564 Adds a executable to the testsuite to test pull performance

- docs/mof_compiler.help.txt
- os_setup.py
1. Issues with 2 lines after function or class. This is new to
flake8 version 3.2.0
2. Issue with both # pylint and $ noqa on same line.
Found another pylint syntax # pylint: enable=...
that helps with this issue. This probably new to
flake8 3.2.0.
> Fixes #575 A number of new flake8 issues

- docs/wbemcli.help.txt
- examples/test_wbemcli_script.sh
- examples/wbemcli_display_args.py
- examples/wbemcli_quit.py
- examples/wbemcli_server.py
- wbemcli
Ready for final review: waiting on pr 576 to fix checks failure.
WIP but the current code works and there is a first example of a script. that does work.  The first script just sets up the wbemserver object including a valuemap so that the user has all that available.
I created some examples and put them into examples.  The script test-wbemcli-script.sh executes a simple example that does not require a running server (just displays the args for wbemcli).  Note that I made args into ARGS global to do this for this demo.
This could be expanded to actually do something useful and we could have any number of example scriptlets if we thought this was useful. Remember at this point this is prototype.
Further, since it will allow executing the script and quitting so that it never actually starts …
> WIP fixes #563 add wbemcli script capability.

- docs/wbemcli.help.txt
- wbemcli
Ready for review. Complete and two +1 votes.
This fixes formatting of the argparse desc and epilog by adding a custom
formatter that has multiple  formatters.  I am not sure how far I trust
this fix in the future but found the proposal on stackoverflow and it is
also recommended solution. in a python issue. That is documented in the
code
In addition it:
- expanded the desc slightly.
- changes main and main call to get script name from args.
- fixes an issue with a missing parameter on the openQueryInstances
operation definition in wbemcli. This issue popped up during testing
with on pylint (this actually showed up after I had run a number of
pylints that did not show the error) but it announced that the rc
attribute for ClassName did not exist.
There may be more effective ways to do this …
> fixes #558 Correct formating of argparse epilog

- docs/changes.rst
- setup.py
> Fixes #556 for 0.9: Added git as an OS-level dependency for development.

- docs/changes.rst
- setup.py
For some unknown reason, PR #582 never arrived in branch `stable_0.9` even though it was merged.
Therefore, relaunching that PR now.
> Redo #556: Added git as an OS-level dependency for development.

- pywbem/tupletree.py
This PR fixes the SAX parse error that showed up on Python 2.6 starting on 2016-12-01, by applying the same fix that was already implemented for Python 3.4: Encode the unicode string into a byte string.
So far, this fix is not needed on Python 2.7 and Python 3.5, for unknown reasons.
The symptom is that `test_tupleparse.py` fails in the test run on Python 2.6 with:
```
SAXParseException: "<unknown>:1:1: not well-formed (invalid token)"
```
If you encounter this, use this PR via one of these:
- rebase your PR on the branch of this PR (as long as it is not yet merged)
- rebase your PR on master (once this PR has been merged)
- cherry-pick the commit of this PR into your branch
> Fixed SAX parse error with unicode strings on Python 2.6.

- docs/changes.rst
- pywbem/_subscription_manager.py
This rolls back a fix from PR #583 into v0.9.
Details:
- In remove_all_servers(), fixed an AttributeError (str has no 'url' attribute).
- In remove_server() and in remove_all_servers(), fixed dictionary iteration errors where dictionary items were deleted but the iteration was based upon an iterator over the dictionary. Fixed that by making the loop based upon a copied list of the dictionary keys.
> Fixed AttributeError and dict iteration errors in remove_all_servers and remove_server

- pywbem/tupletree.py
- wbemcli
This PR is now ready to be reviewed.
It contains many docstring changes, but also a few code fixes.
- Removed long global function names (e.g. `EnumerateInstances`), and kept the short names (e.g. `ei`).
- Fixed missing `ns` parameter of `ci()`.
- Fixed incorrect invocation of underlying operation in several short functions:
- `orip()` invoked `OpenReferenceInstances()`.
- `oaip()` invoked `OpenAssociatorInstances()` and incorrectly had `iq`, `ico`, `pl` parameters.
- Fixed incorrect position of `rc` parameter in `oqi()` function.
- In `mc()`, removed returning the result of the underlying operation that doesn't return anything.
- Fixed errors in docstrings and improved the docstrings of the short functions.
> Fixes #548: Fixes and improvements to global ops functions in wbemcli

- docs/changes.rst
- pywbem/_subscription_manager.py
- testsuite/run_cim_operations.py
Also, corrected DSP1054 references in the docs of `WBEMSubscriptionManager`.
The only testcase is in `run_cim_operations.py`, and I did not test with it.
> Fixes #407: Added context manager capability to WBEMSubscriptionManager

- docs/changes.rst
- pywbem/cim_operations.py
- testsuite/run_cim_operations.py
- testsuite/testclient/enumerateinstances.yaml
Please Review:
This adds a test  to the operations that use PropertyList that allows a single string to be passed as a property list as well as an iterable.  Previously a single string caused an
XML error. Now it is mapped to a list.
Also adds tests to run_cimoperations.py and mock (for enumerateinstances)
> Add test to cim_operations with PropertyList attribute.

- docs/changes.rst
- pywbem/_recorder.py
Please review.
Details:
- Added enable() and disable() methods to class BaseOperationRecorder, and changed the invocaiton of the record() method such that it only happens when the recorder is enabled.
- by default, the recorder is enabled.
- for completeness, added a property enabled that indicates whether the recorder is currently enabled.
> Fixes #493: Added support to the operation recorder for an on/off switch.

- examples/wbemcli_server.py
- pywbem/_subscription_manager.py
- testsuite/run_cim_operations.py
Ready for review:
Fixed several issues in the new sub mgr and the tests for this in run_cimoperations.py
1. Correct code issues in subscription manager. See the issue for details of the fixes.
2. Correct some tests that were failing in run_cimoperations.py, mostly the move to use return instances rather than paths.
3. Minor extension to an example
Note that there is some crossover between the fixes to run_cimoperations.py and some other fixes to
cim_operations.py from the pr for issue #466 (implementing the iter functions). There may be a couple of conflicts which we will sort out when we try to merge.
> Fix # 616 Some issues with the latest subscription manager

- examples/wbemcli_count_instances.py
Ready for review. Reduced to one script
I wrote the first one to try to gather information for extending run_cim_operations.py for better assocation tests and ended up generalizing it.
This also establishes a couple of limitations to this -s scripting capability:
1. User cannot add new parameters to the cmdline for the script.
The  script is:
1. wbemcli_count_instances.py Scans a server and generates overall information on the namespaces
and the number of classes, instances throughout the server.  Note that
this is tuned to OpenPegasus right now in that it includes a list of classes
where the enumerate operations actually kill the server.  These are
really internal and test classes within pegasus but it is clear that
pegasus does not protect itself in these cases since accessing from a …
> Add example scriptlet.

- docs/changes.rst
- examples/enumerator_generator.py
- examples/pullenuminstances.py
- pywbem/cim_operations.py
- pywbem/config.py
- testsuite/run_cim_operations.py
- testsuite/test_client.py
- testsuite/testclient/openqueryinstances.yaml
**STATUS 11 Dec:** for review: All functions implemented along with a _use... parameter for each.  Removed the method to set use_pull_operations.  Some initial code for these operations is now in run_cim operations but have more work there.  I have not yet sorted out how to test this through mock yet. First goal is complete test with run_cimoperations.py I have at least a day of adding tests just in run_cim_operations.py
Added almost all basic tests (except invoke method) to run_cimoperations.py so we are exercising at least the main paths. Working now to try to get them into mock but still trying to sort out how to handle the generate response(probably use it to drive a for loop)
**Discussion:** The IterQueryInstances works but want to discuss the fact that what I did is a hack. Using …
> Fixes #466: Implements the enumerate generator methods

- docs/changes.rst
- docs/tutorial.rst
- pywbem/cim_operations.py
Details:
- In the operations table, and in each operation description, marked
the Iter...() methods as experimental.
- Fixed a table issie in the tutorial section.
- Moved examples in descriptions of Iter...() functions to the end.
- Fixed a formatting error in the description of the MaxObjectCount parameter
of some Iter...() functions.
> Fixes #625: Marked Iter functions as experimental and some docs fixes.

- examples/wbemcli_clean_subscriptions.py
- examples/wbemcli_view_subscriptions.py
Ready for review and commit:
I used these extensively in testing of the subscription manager changes.
Allowed me to see what was done and clean up the server easily.
At the same time they demo the weakness of the scriplets.
The scriptlets are:
1. View counts and paths for subscriptions, filters, destinations on a server
2. Remove all subscriptions, filters, destinations on a server.
Note: They do not use subscription manager today because I did them to help test the changes.
Probably should update to use subscription manager before committing.
Second they do not pass flake8 because of the ein, etc. functions from wbemcli.  Not importing anything to get around that.
> Two more working examples of scriptlets for wbemcli

- os_setup.py
- setup.py
**COMMENT:** 18 Dec.Went back through the tests installing to system yesterday
and it worked, both for python 3 and python 3.   I did it using sudo - cd pywbem dir; make develop; make all.  Still get the ContextualVersionConflict at the end of develop but sudo make all works
Since there had been a lot of detailed output yesterday I went back through the whole thing again today and except for the ContextualVersionConflict message (and lots of warnings from the compile of m2crypto and yaml the sudo based make develop, make build make all worked fine again for
both python 2 and 3.  ( think I forgot to uncheck test needed yesterday)
We realize that there are so many variations of installation of the base requirements for python in Centos 7 that others may get some other results but as far as …
> Fixes #556: More tolerance and improved diagnostics in os_setup.py 

- pywbem/cim_operations.py
- testsuite/run_cim_operations.py
- testsuite/test_cim_obj.py
- testsuite/test_client.py
- testsuite/testclient/createclass.yaml
- testsuite/testclient/deleteclass.yaml
- testsuite/testclient/deletequalifier.yaml
- testsuite/testclient/execquery.yaml
- testsuite/testclient/modifyclass.yaml
- testsuite/testclient/pullinstancepaths.yaml
- testsuite/testclient/pullinstances.yaml
- testsuite/testclient/pullinstanceswithpath.yaml
- testsuite/testclient/setqualifierdecl.yaml
**Status:** Ready for Review. 
This gets us up to 66% coverage so all this was about 1.4 % gain
Adds mock tests for CreateClass, DeleteClass, ModifyClass, SetQualifier,
DeleteQualifier, and ExecQuery.
Adds unittests to test_cim_obj.py for CIMQualifierDeclaration. This was part of getting
the mock tests running for setqualifier, etc.
Adds tests  to run_cim_operation.py for CreateClass, DeleteClass, ModifyClass, SetQualifier,
DeleteQualifier.
Corrects an error in CIM_operations where recorder was being called with
incorrect type.
At this point we have at least minimal mock tests for every operation  and most of them have both
success and fail tests.
There are several mock tests marked ignore_test for the following reasons(5 tests are marked ignore out of over 200 separate tests):
1. The …
> fixes #620 and #643 Add testclient tests and add cim_obj tests

- coveragerc
- makefile
Create optional detailed line by line report output showing code coverage.
Adds an optional environment variable for the make file to control
output of a detailed line by line coverage report in html   If this
variable is set (export PYWBEM_COVERAGE_REPORT = true) html output is
generated in the directory coverage_html that shows the files in the
pywbem directory with coloring for which lines are covered and missed.
This also creates temporary files with the suffix ,cover in
pywbem/pywbem directory.  All these files are destroyed by clobber.
We made this an optional variable because it is only needed occasionally
when working on coverage issues. There is no need to generate these
reports for every make test.
To generate the reports:
1) set the env var (export PYWBEM_COVERAGE_REPORT=true …
> Fixes #649: coverage html report

- pywbem/_recorder.py
Karl tested. See below: I voted +1 on this based on the test.
This PR improves the diganostics for issue #588, but does not solve it.
Please reproduce the issue and report the results.
KS marked this update needed since I made comments
> Improved diagnostics when PyYAML cannot represent an object.

- pywbem/_recorder.py
- pywbem/cim_operations.py
- testsuite/test_client.py
Status: WIP. Code complete for change of yaml entry name but we have to add code to prcess named tuples ouput in the recorder.
Adds code to recorder to output yaml section definition of 'pullresult:' for pull operations that return tuples of info  vs. 'result:' for other operations
Also does small code cleanup in test_client.py so reduce code in hope that
we can reduce the result and pullresult to a single type in the future.
Adds options to identify pull operations in cim_operations call to recorder.
> Fixes #648, fixes #601: WIP: Pull Operations yaml uses keyword 'pullresult' rather than 'result'

- docs/changes.rst
- pywbem/cim_operations.py
- testsuite/run_cim_operations.py
- testsuite/testclient/pullinstancepaths.yaml
- testsuite/testclient/pullinstances.yaml
- testsuite/testclient/pullinstanceswithpath.yaml
This parameter was inconsistent between the different cim_operations.py pull...
operations methods (was keyword in 2 of the methods). The PR made it positional for all 3 operations.  Also added validation for the parameters for these operations (Context and MaxObjectCount).
Added tests to mock tests for the new method validation and modified
run_cim_operations.py to match the changes in cim_operations.py. Note
that these changes should not impact clients since the keyword parameter
is still accepted and the tests we added should be caught by the server
or pywbem code in any case.
> Fixes 656: MaxObjectCount parameter of Pull operations inconsistent

- pywbem/_recorder.py
- pywbem/cim_xml.py
- testsuite/run_cim_operations.py
- testsuite/testclient/setqualifierdecl.yaml
Fixes the toyaml function to pass correct key case when converting from NoCaseDict to OrderedDictionary.
Adds tests to test_cimobj for this
We also cleaned all pylint messages out of _recorder.py. All of the changes were variable name changes or setting disable.
Fixes the data in testclient for setQualifier to correctly reflect what
the request and response should reflect (CLASS, not class).
Extends test in run_cim_operations.py
> Fixes #646 Change recorder to fix issue of scope names case lose

- docs/changes.rst
- pywbem/cim_operations.py
- testsuite/run_cim_operations.py
- testsuite/testclient/pullinstancepaths.yaml
- testsuite/testclient/pullinstances.yaml
- testsuite/testclient/pullinstanceswithpath.yaml
Fixes 656: MaxObjectCount parameter of Pull operations inconsistent
backported to 0.10.0 release. Backported with git cherry-pick
Failed two tests becuase of communication issues, not the code
> fixes #656 Backport pull request #658 from pywbem/issue#656-pullops-maxobjcount

- docs/changes.rst
- pywbem/cim_obj.py
- testsuite/test_cim_obj.py
Adds consistency tests for the multiple constructor paramters (is_array vs array_size and is_array vs. value is a list).
Add comment to changes.rst
> Fixes #645: Extension to test for valid qualifier declaration constructor parameters

- .travis.yml
- appveyor.yml
- docs/changes.rst
- docs/intro.rst
- os_setup.py
- setup.py
- testsuite/test_nocasedict.py
- tools/debug_dll_dependencies.bat
- tox.ini
- uninstall_pbr_on_py26.py
Please review.
This one was larger than expected (with Python 3.6-specific errors on Linux and Windows, and with Windows-specific errors on Python 3.x that needed to be fixed).
Also, I had to document a limitation that Python 2.6 on Windows is not supported (because we use M2Crypto from the M2CryptoWin32/64 package, which does not support Python 2.6), and that 64-bit Python on Windows is not supported or at least was not tested.
> Fixes #661: Added Python 3.6 to Travis CI and 3.4-3.6 to Appveyor CI

- docs/changes.rst
- pywbem/_recorder.py
- pywbem/cim_operations.py
- testsuite/run_cim_operations.py
1. Moved cim_operations from using except/else pattern for the
request methods to using except/finally.  This eliminates one of
the recorder calls. It was applied to all of the request methods.  This meant
setting the exc and return value to None at the beginning of each method but
reduces the recorder call to one in the finally clause.
2. Fixed part of issue#676, returns named ret where it should be
ret_dict because I needed the fix to really check the change to use
finally.  I crossed this one off the comments in issue #676
3. Fixed an issue in run_cim_operations.py that was causing a test
failure. It was not tied to this fix but was a) a case where pegasus returns an invokemethod of 1 and we were testing for zero and 2 cases where we have difference between instancenames in the …
> Fixes #680: Move CIM Operations methods from except/else to except/finally

- docs/changes.rst
- pywbem/cim_obj.py
- pywbem/mof_compiler.py
- testsuite/test_mof_compiler.py
1. Added keybindings to instance alias in compiler. The compiler not produces keybinding in the path and the alias table for instance definitions that include alias.  Before in only produced the class component of the path. That meant that other instances that used the alias did not get a complete instance alias.
2. Added test for instance alias - Added test for this in test_mof_comp
3. Fixed documentation issue in cim_obj.py
> Fixes #677, fixes #679: Compiler inst alias and cim_obj doc missing alias keybinding definition.

- docs/changes.rst
- docs/client.rst
- makefile
- pywbem/__init__.py
- pywbem/_statistics.py
- pywbem/cim_http.py
- pywbem/cim_operations.py
- testsuite/run_cim_operations.py
- testsuite/test_client.py
- testsuite/test_statistics.py
- testsuite/testclient/README.md
- testsuite/testclient/associatorinstances.yaml
- testsuite/testclient/createinstance.yaml
- testsuite/testclient/enumerateclasses.yaml
- testsuite/testclient/enumerateinstancenames.yaml
- testsuite/testclient/enumerateinstances.yaml
- testsuite/testclient/getinstance.yaml
- testsuite/testclient/openenumerateinstanceswithpath.yaml
- testsuite/testclient/pullinstanceswithpath.yaml
- wbemcli.py
Keeps time statistics on cim_operations.  This keeps statistics on time to
execute and request/response sizes for the cim operations.
Implements a Statistics class and connects cim_operations to that class to record execution time, request size, and reply size in that class for each operation type.  It saves count, avg time, request size, response size in and exception count in that class for each WBEM operation type by name.
The Statistics class provides for snapshotting and resetting the statistics in addition to the functions to record each new statistics with start_time() and stop_time()
NOTE: At this point the statistics are not really general.  The class OperationStatistics specializes the statistics for the operations and their is no provision for another class with its …
> Fixes #761: Create classes for keeping statistics and add statistics

- docs/concepts.rst
- docs/index.rst
Created the section to the documentation and set the overview sections
from the notebooks into this section.   Once this is committed I will remove that material from
the notebooks so that they are primarily examples.
Andy: We probably need to agree on the sections.  I layed out sections for the concepts in the document except that I think we should get all the way to profiles and the profiles section is not there.
There are a lot of TODOs where sections are empty at this point
Add note about profiles. We need at least a short description
> [WIP] Fixes #697: Create concepts section to docs

- docs/changes.rst
- pywbem/cim_types.py
- testsuite/test_cim_types.py
> Fixes #698: Made CIMDateTime always timezone-aware, re-enabled test_cim_types.py

- pywbem/cim_obj.py
Only changes in an internal docstring, to clarify what the function does.
> Fixes #312: Clarified MOF escaping in internal docstring of mofstr().

- docs/changes.rst
- pywbem/_statistics.py
- pywbem/cim_http.py
- pywbem/cim_operations.py
- testsuite/run_cim_operations.py
- testsuite/test_statistics.py
Extend pywbem to get WBEMServerResponseTime from server and include as new attribute/property in WBEMConnection (last_server_response_time) and new statistic in statistics.
1. Extend cim_http.py to capture optional WBEM_ServerResponseTime header
and convert from microseconds to seconds.
2.Extend cim_operations to add new attribute _server_response_time and
new property server_response_time that holds either None or the server
response time in seconds.
3. Extend statistics to include this statistic and display it in reports
if it is provided by the wbem server.
4. Extend run_cimoperations.py to display the last_server_response_time
if it exists.
Adds entry to changes.rst
> Fixes #687: Implement handling of WBEMServerResponseTime

- docs/changes.rst
- testsuite/run_cim_operations.py
Code incorrectly mapped str to bytes in run_cimoperations.py for iter test.  This was an error in test code, not a case of incorrect typing in base code as far as I can tell.  Note that the code was checking for namespace and forcing it to unicode so underneath there was a case where the namespace is bytes for some condition in some test.  I still have not caught that.
> fixes #718 Correct Error in run_cimoperations.py with iter... tests

- docs/changes.rst
- pywbem/_recorder.py
- testsuite/run_cim_operations.py
- testsuite/test_client.py
- testsuite/test_recorder.py
1. Documented that if an already open file is supplied to the
TestClientRecorder, it must be a text file.
2. Since creating text files is messy in python 2/3 we added a static
method (open_file) to the recorderthat will open the file and return the
handle.
ex:
```
fp = TestFileRecorder.open_file('yamloutputfile', 'a')
```
will open a test file for append.
We did NOT add any check to be sure that the file handle provided to the
TestClientRecorder __init__ function is, in fact defined as a text file.
> Fixes #700: Fix issue with recorder creating non-text files

- docs/changes.rst
- wbemcli.bat
Adds line to the bat file to return exit code.
This was originally part of pr#691 but that has been withdrawn in favor of a number of smaller prs.
Note that there is no test for this change. That will be part of another pr
> Fixes #727: Extend wbemcli.bat to exit with exit level.

- pywbem/cim_constants.py
- setup.py
This circumvents the issue with flake8 3.4.0 that causes some of the other PRs to fail.
> Circumvented issue with flake8 3.4.0.

- .travis.yml
- docs/changes.rst
- pywbem/cim_constants.py
- setup.py
This fixes issue where coveralls forced installation of old version of
coverage that causes problems with other tests because of deprecation
warnings it issues.  The problem was fixed after version 4.03 of
coverage
We had to directly change .travis.yml to reinstall/update coverage after
the installation in the setup and reinstallation as a coveralls
dependency with an old version.
We added the version to setup.py but that is mostly for documentation.
Added comment to changes.rst
> Fixes #734: Fix issue with old version of coverage

- docs/changes.rst
- docs/compiler.rst
- docs/utilities.rst
- pywbem/mof_compiler.py
1. Added comment about issue with property/etc. names that are also
compiler keywords.
2. Minor edits to the mof compiler doc to clarify some phrases.
3. Changed some section names in the rst documentation to separate
the mof compiler class from the mof compiler cmd line.
4. Added note to changes.rst
> Fixes #62: Add documentation on limitations of pywbem compiler.

- docs/changes.rst
- docs/client.rst
Moved documentation on operation recorder in client.rst so it has its
own section and kept the old subsection just as info about usage.
Added entry to changes.rst
> Fixes #741: Move documentation on operation recorder

- .travis.yml
> Fixes #750: Temp fix for opensslconf.h not found on py26 and ubuntu 14.04

- .gitignore
Reason for this change is that on CygWin, the vi editor leaves files around that end with tilde. They should be ignored in git.
> Ignoring files ending with tilde.

- docs/changes.rst
- pywbem/cim_obj.py
- pywbem/cim_operations.py
- testsuite/test_cim_obj.py
- testsuite/testclient/associatorclasses.yaml
- testsuite/testclient/embeddedobjects.yaml
- testsuite/testclient/getclass.yaml
- testsuite/testclient/referencesclass.yaml
One particular review point would be that the CIM-XML and MOF representations of a class returned by the respective methods of `CIMClass` do not allow representing the class path we now added to `CIMClass`. That is not necessarily a problem, but it is inconsistent.
> Fixes #349: Added class path to CIMClass

- docs/changes.rst
- os_setup.py
> Tolerated incorrect Unicode characters in os_setup.py output.

- docs/changes.rst
- os_setup.py
- pywbem/cim_obj.py
- testsuite/test_nocasedict.py
**Note:** This PR is on top of PR #758.
> Made ordering of array items within CIM objects reliable in repr() and str()

- pywbem/_logging.py
This error was triggered by the release of six 1.11.0, but was caused by pywbem incorrectly using both `six.with_metaclass()` and setting the `__metaclass__` attribute.
Ready for review and merge, once it passes all tests.
> Fixes #765: Fixed TypeError: Error when calling the metaclass bases

- docs/changes.rst
- setup.py
This PR addresses issue #768 by pinning wheel to <0.30.0 when installing on Python 2.6.
> Fixes #768: Pinned wheel to <0.30.0 for Python 2.6.

- docs/changes.rst
- mof_compiler
- os_setup.py
- pywbem/_server.py
- pywbem/_subscription_manager.py
- pywbem/cim_obj.py
- pywbem/cim_operations.py
- pywbem/cim_types.py
- pywbem/mof_compiler.py
- pywbem/tupleparse.py
- testsuite/run_cim_operations.py
- testsuite/test_client.py
- testsuite/wbemcli_quit_script.py
- wbemcli.py
Removed a number of issues found by pylint including:
1. The issue with unnecessary else. Changed most of those to use the
ternary form
2. The len(condition) issue which can be generally replaced with 
if blah:
for cases were something must exist in iterable and 
if not blah:
if the interable should be empty or None.
3. Couple of pylint messages that pylint is now marking as obsolete.
> pylint cleanup

- pywbem/cim_obj.py
- pywbem/cim_operations.py
A recent change attempted to improve links to class NocaseDict
by using ":class:`~pywbem.cim_obj.NocaseDict`". However, NocaseDict
is not fully documented, and only a section with title and link target
"NocaseDict" exist. Therefore, reverted that change to again use
"`NocaseDict`_" for linking, as before.
> Undid recent change for linking to NocaseDict.

- docs/changes.rst
- os_setup.py
- pywbem/_statistics.py
- pywbem/_subscription_manager.py
- pywbem/cim_constants.py
- testsuite/test_cim_types.py
- testsuite/test_cim_xml.py
- testsuite/test_exceptions.py
- testsuite/test_indicationlistener.py
- testsuite/test_nocasedict.py
- testsuite/test_tupleparse.py
- testsuite/test_tupletree.py
- testsuite/test_valuemapping.py
- testsuite/unittest_extensions.py
1. Add comments to all functions, methods, classes.
2. Disabled number of variable-not-used pylint warnings
3. Disabled several no-else-return where we did not want to modify the
code
4. Removed empty lines at end of module
5. Set disable=redefined-outer-name especially in test_cim_types and
other tests where we are uising pytest and fixtures.
6 Disabled several exception too broad
Made comment in changes.rst
Takes about 150 lines off of pylint.log (643 down to about 480 lines)
> Clear a number of pylint issues

- os_setup.py
- pywbem/_recorder.py
- pywbem/_statistics.py
- pywbem/cim_http.py
- pywbem/cim_operations.py
- pywbem/cim_xml.py
- pywbem/mof_compiler.py
- pywbem/tupleparse.py
- setup.py
- testsuite/run_cim_operations.py
- testsuite/test_client.py
- testsuite/test_exceptions.py
- testsuite/test_mof_compiler.py
- testsuite/test_recorder.py
- testsuite/test_statistics.py
- testsuite/unittest_extensions.py
This change cleans up or hides several more minor pylint issues.  
Note that there is one change in the tests where it removes a one line test because that test appears to do nothing except cause a lint (unused variable).  See test_exceptions.py line 198
I consider this an extension of issue #808, cleaning up pylint issues.
One change was to remove several disable=redefined-variable-type comments because apparently that particular message is no longer in pylint.
Modifies some methods to staticmethod in unittest_extensions to get rid of pylint warnings.
There was one change where the pylint message is defined before and after the line of code once iwht the text and the second time with the warning code.  For some reason the first was not working and I used the code the second time because …
> Fixes #808: Fix more pylint issues

- docs/changes.rst
- pywbem/cim_obj.py
This PR has been reduced to contain only the changes for making the public attributes into gettable & settable properties. Further improvements such as checks or conversions will be left to future PRs.
Probably the best way to review this is to build the documentation (`make builddoc`) and to review the documentation of the CIM objects (init parameters and all properties).
> Fixes #761: Changed public attributes to properties in classes of cim_obj.py.

- pywbem/_listener.py
> Pylint: Fixed name of parm in overriding log_message()

- testsuite/test_nocasedict.py
> Pylint: Fixed parm names in overridden assertion method in test_nocasedict.

- pywbem/cim_obj.py
> Pylint: Disabled check for redefined type arg in cim_obj.

- docs/changes.rst
- pywbem/cim_operations.py
1. Did not include the IncludeQualifiers parameter in two calls to the
underlying functions from the Itermethods (references and associators)
2. Used the name=value call defintion for the calls from
IterQueryInstances to ExecQuery and OpenQueryInstances.  While not
incorrect, these are required parameters so this is confusing in the
code and also means that the mock returns Name=value rather than value
for the test on method input.  I propose that we change these to remove
the Name= component.
> Fixes #833: issues with WBEMConnection iter methods

- appveyor.yml
It recently started failing on the command "env | sort" which is a stupid copy from Linux. See for example this [Appveyor log](https://ci.appveyor.com/project/andy-maier/pywbem/build/1.0.1362/job/kdbqmjafov08t1mm).
> Added fix for Appveyor display of environment.

- docs/changes.rst
- pywbem/cim_operations.py
- testsuite/test_itermethods.py
Done but rebased from pr #833 to pick up issues we found in WBEMConnection
Adds the file testsuite/test_itermethods.py that executes tests using
pytest on  the iter... methods in WBEMConnection since these
methods were not really tested with the test_client.py tests and only the
main paths were tested with run_cimoperations.py
Implements tests for:
1. Force use of original method including parametrized input parameters 
2. Force use of new open method with parametrized input parameters
3. Use open and return and then use open/pull and return
4. Fail if force to original method and that returns error.
5. Test for invalid maxobjectcount since this one is specifically tested in the iter methods
Tests we do not have:
1. We do not have a test for close.
2. We do not have failure tests for a …
> Fixes #818: Add tests for the iter operations

- testsuite/test_itermethods.py
I did not file an issue on this one.  It is simply the cleaner way to test CIMError exceptions under pytest that we discussed in the last telecon. No other changes and not documented in changes.rst since is really part of the original issue filed.
> Clean up use of with pytest... in test_itermethods

- docs/changes.rst
- pywbem/cim_operations.py
- testsuite/test_cim_operations.py
- testsuite/test_client.py
- testsuite/testclient/pullinstancepaths.yaml
Fixes for andy's comments done.
Removed WIP status
1. Fixed the issue in the function noted in pr #813.  However we fixed
it with different code than the original pr.
2. Created a complete test for this function.
3. Converted  other tests in test_operation.py to pytest.
5. Added note to changes.rst
If we agree to this, we should also close pr #813
This code is ready for review.  I have one more test I would like to add but the complexity of the parametrize is defeating me right now.  Note that this appears to be a fairly complete test and also actually found an error in one of the test_client YAML files (had TFALSE where should have been FALSE).
> Fixes #844: Fix issue with _get_rslt_params documented in issue #844

- DEVELOP.md
The first commit only removed the erronously mentioned ` irecv` namespace.
The second commit addresses karl's comment by removing the entire namespace section from DEVELOP.md because we have one in the Development section of the docs.
> Fixes #874: Removed irecv namespace and entire namespace section in DEVELOP.md

- pywbem/cim_operations.py
This is now ready for review and merge, as the discussion point in issue #782 has been resolved.
> Fixes #782: Made use_pull_operations attribute a read-only property

- pywbem/cim_obj.py
- testsuite/test_cim_obj.py
**Note:** This PR is on top of PR #886.
Ready for review and merge, except that issue #899 still contains a discussion point.
This PR has become somewhat larger than intended, plus it caused some Todos to be added that I'd like to leave in for now, and resolve later (because they drive some more changes like converting test cases from unittest2 to pytest, or adding expected warnings to testcase definitions).
> Fixes #899: Deprecated CIMInstance.property_list

- .travis.yml
- makefile
This PR fixes a recent Travis build issue. See #915 for details and options how to resolve.
This PR changes the Travis customization to perform a full repo clone, which also clones the repo tags.
Ready for merge, if the PR succeeds.
> Issue #915: Travis build issue with missing tags

- docs/changes.rst
- pywbem/cim_obj.py
- testsuite/test_cim_obj.py
> Fixes #901, Fixes #902: Clarified method return types and improved CIMMethod.tomof()

- docs/changes.rst
- pywbem/cim_obj.py
- pywbem/cim_types.py
- testsuite/test_cim_obj.py
Note that the deprecation was added during development of 0.12.0, so it was not released yet.
> Fixes #910: Undo the deprecation of providing keybinding values as int+float

- docs/changes.rst
- pywbem/cim_http.py
- pywbem/cim_operations.py
This change should be tested against a real environment, and local authentication should be used.
**Note:** PR #922 is on top of this PR and has changes in exception handling. The two changes can be tested together by using PR #922.
> Fixes #895: Fixed local authentication for OpenWBEM and OpenPegasus

- docs/changes.rst
- pywbem/cim_obj.py
- testsuite/test_cim_obj.py
This is part 1 of a number of updates to the `tomof()` methods of the CIM object classes.
This PR was originally intended to address issue #900, but that will now be done by a subsequent part.
> Improvements and fixes in CIM object's tomof(), part 1

- docs/changes.rst
- pywbem/mof_compiler.py
- testsuite/test_mof_compiler.py
Changed compiler to let CIMinstanceName stringify keybinding values.
Added test for compile of association instances with reference property
keys which is what was broken.
> Fixes #936, association class with alias breaks mof_compiler

- testsuite/test_itermethods.py
Minor change to eliminate print from test code.
> Eliminate print in test_itermethods.pyu

- minimum-constraints.txt
- requirements.txt
Because this fixes an error that happened during the transition to pbr and requirements files, which is not yet released, a change log entry is not needed.
> Added 'ordereddict' package to reqs for py26 again

- MANIFEST.in
- docs/changes.rst
- docs/index.rst
- docs/mocksupport.rst
- makefile
- pywbem/cim_operations.py
- pywbem_mock/__init__.py
- pywbem_mock/_wbemconnection_mock.py
- testsuite/dmtf_mof_schema_def.py
- testsuite/run_cim_operations.py
- testsuite/test_mof_compiler.py
- testsuite/test_wbemconnection_mock.py
Initial implementation of pywbem_mock.   
This implements mocks of all of the WBEMConnection methods that contact
the wbem server with a local repository that responds to the requests with data from the repository.
This is not a complete implementation of a WBEMserver and
therefore creates a number of simplifications that are documented in the documentation page
**Status Sat 6 jan 2018:**
Note that this fixes the test failure from Friday.  That was bad code compounded by fact that each python version has different ordering for dictionaries.  V 3.4 ordering caught my instance properties error that depended on property ordering by accident.
1. Implementation complete and coverage is up to about 90%.  There are a number of tests to add but we know that the paths generally work.  The only …
> Issue #838 (part1): Implement mock of WBEMConnection

- pywbem/cim_operations.py
Corrects an error in definition of the Context parameter for Pull.
operations and adds some clarification. Also adds examples for
OpenEnumerateInstances and OpenEnumerateInstancePaths.
No code changes.
Also fixes a couple of issues with sphinx documentation.  In particular
one issue where a
**Experimental:* appears as the first line of a doc string generates an error and does not implement the strong emphasis.  I moved that line below
a previous line in the text.
> Fixes #956: Correct documentation for EnumerationContext

- docs/changes.rst
- pywbem/cim_obj.py
- testsuite/test_nocasedict.py
> Fixed lexical case when iterating over CIMInstance/CIMInstanceName

- dev-requirements.txt
- minimum-constraints.txt
- testsuite/pytest_extensions.py
- testsuite/test_nocasedict.py
Ready for review and merge. This change is used by the hashing support (PR #960).
The testcase-table driven testing requires to write the same kind of code over and over again, that 
handles warnings and expected exceptions. In the four execution paths, the code to be tested must be coded each time separately, so that it shows up four times.
This change puts all the boilerplate code into a decorator named 'test_function' in a new module 'pytest_extensions.py'.
To demonstrate the new decorator, the testcases for testing equality for NocaseDict has been converted to use the new concept.
> (1) Testing: Added test_function decorator

- docs/appendix.rst
- docs/changes.rst
- docs/client.rst
- pywbem/cim_obj.py
- pywbem/cim_types.py
- testsuite/test_cim_obj.py
- testsuite/test_nocasedict.py
Background: In order to be able to compare sets containing CIM objects correctly for equality, the CIM object classes and CIMDateTime need a hashing function. Reason is that the standard hashing function is based upon id() and therefore does not satisfy the requirement for hashable objects, namely that the hash value must be equal if the objects are considered equal.
This functionality will be needed for the upcoming support for order-preserving child elements (PR #955).
**DICSUSSION:**
* **Karl:**  I have one real issue with this.  Up to now, the hashing was a class object ID which could be used to determine if a and b were really the same object.  We are modifying this so that the objects are the same if the data is the same. …
> (1) Added support for hashing of CIM objects

- docs/changes.rst
- pywbem/cim_http.py
- pywbem/cim_obj.py
- testsuite/test_cim_obj.py
> Fixes #943: Changed instance/class path str() back to historical format

- docs/changes.rst
- pywbem/cim_types.py
This PR was triggered by the support of CIM object hashing, but is really independent of that.
> Added cautionary text for equality/hash on floats

- docs/changes.rst
- pywbem/mof_compiler.py
- testsuite/test_mof_compiler.py
- testsuite/testmofs/test_instance.mof
- testsuite/testmofs/test_types.mof
> Fixes #974: Added support for binary,octal,hex number formats in MOF compiler

- docs/changes.rst
- pywbem/_recorder.py
- testsuite/test_recorder.py
> Fixes #702, #588: Fixed support for CIMDateTime / timedelta in TestClientRecorder

- docs/appendix.rst
- docs/changes.rst
- pywbem/cim_obj.py
- pywbem/mof_compiler.py
- testsuite/run_cim_operations.py
- testsuite/test_cim_obj.py
- testsuite/test_mof_compiler.py
- testsuite/test_nocasedict.py
- testsuite/test_recorder.py
- testsuite/test_wbemconnection_mock.py
**Note:** This PR contains a change for the pywbem_mock testcases (in a separate commit).
> Fixes #941: (1) Preserved order when iterating child elements of CIM objects

- docs/appendix.rst
- docs/changes.rst
- pywbem/cim_obj.py
- pywbem/mof_compiler.py
- testsuite/run_cim_operations.py
- testsuite/test_cim_obj.py
- testsuite/test_mof_compiler.py
- testsuite/test_nocasedict.py
- testsuite/test_recorder.py
- testsuite/test_wbemconnection_mock.py
**Note:** This PR is on top of PR #967.
> (3) Make tomof() generate child elements in preserved order

- docs/mocksupport.rst
- pywbem/cim_operations.py
- pywbem_mock/_wbemconnection_mock.py
- testsuite/test_wbemconnection_mock.py
InvokeMethod implementation.
Ready for review and merge
Includes:
1. subscribe_method - Method that adds method subscription to repository by (namespace, classname, methodname, call_back_method_name)
2. Implementation of InvokeMethod itself (i.e. _mock_call mock) That gets the  method subscription info from the repo and calls the method to be invoked.
3. definition of the input params and return for the method to be invoked. 
Input parameters to the callback are:  
<handle of repo>, MethodName, LocalObject, Namespace, Input_Params.
The callback executor returns
(return_value, Dict of OutputParameters)
4. Modification to cim_operations.py.InvokeMethod to move some low level code from InvokeMethod to _methodcall so that the response to InvokeMethod from _methodcall is simply the tuple of …
> Fixes #871: InvokeMethod mock support

- docs/changes.rst
- pywbem/_server.py
- testsuite/test_valuemapping.py
> Fixes #992: Fixed the use of hard coded value limits in ValueMapping

- makefile
- pywbem_mock/_wbemconnection_mock.py
- testsuite/run_uprint.py
- testsuite/test_uprint.bat
- testsuite/test_uprint.sh
- testsuite/test_wbemconnection_mock.py
This fixes `_uprint()` as discussed in PR #1006, and adds corresponding tests to Travis and Appveyor.
Instead of merging this PR, it can be cherry-picked into the branch of PR #1006.
> Fixed _uprint() and added tests

- docs/changes.rst
- docs/intro.rst
- pywbem/tupleparse.py
- testsuite/test_tupleparse.py
**Note:** This PR is on top of PR #1045.
> Fixes #1033: (8) Added toleration support for xml:lang attributes in tupleparser

- .gitignore
Not clear which component creates the `.pytest_cache` directory (presumably pytest), but in any case, it should be excluded for Git.
> Added .pytest_cache to .gitignore

- docs/changes.rst
- pywbem/tupleparse.py
- testsuite/test_tupleparse.py
> Fixes #1032: Empty boolean values in returned CIM-XML now issue UserWarning

- docs/changes.rst
- pywbem/tupleparse.py
> Fixes #1055: Removed toleration of invalid REFERENCECLASS attr on PROPERTY.ARRAY

- docs/changes.rst
- pywbem/cim_obj.py
- testsuite/test_cim_obj.py
- testsuite/test_tupleparse.py
> Fixes #1035: Reference values in CIM objects can now be class paths

- docs/changes.rst
- pywbem/tupleparse.py
- testsuite/test_tupleparse.py
> Fixes #1040: Check for invalid values of boolean attributes of SCOPE in tupleparser

- pywbem/cim_http.py
- pywbem/cim_obj.py
- pywbem/cim_operations.py
- pywbem/mof_compiler.py
- pywbem/tupleparse.py
- testsuite/test_tupletree.py
If a TODO has an associated issue number, the date and initials are removed to save space in the line; any history etc. can then be seen in the issue. TODOs that are removed by pending PRs have not been touched to avoid merge conflicts.
> Cleaned up the TODO entries in pywbem package

- docs/changes.rst
- pywbem/cim_obj.py
- pywbem/tupleparse.py
- testsuite/test_tupleparse.py
> Fixes #1038: Rejecting void method return types in tupleparser

- docs/changes.rst
- pywbem/cim_obj.py
- pywbem/mof_compiler.py
- pywbem_mock/_wbemconnection_mock.py
- testsuite/test_cim_obj.py
- testsuite/test_wbemconnection_mock.py
Updated with comments from Friday 9 Feb.  Note that I made one change that we had not discussed. The previous from_instance defaulted to getting property value from class if strict=false and no property in instance.  Removed the code so it simply does not put that property into the keybindings.
DISCUSSION if you would prefer the original.
Cleaned up tests for get_class and enumerateclasses to more throughly test the lo, iq, and ico attributes.
This and some other test changes to get rid of TODOs  sort of bumped up the test count from 650 to 900. 
1. Modified logging
2. Removed the write to file from mofcompiler errors.  Now writes error
information to stdout.
3. Modified the compiler error message format. New format is:
Syntax error:NoFile:3:24
Qualifier Association : boolean = false, …
> Fixes #1069: Cleanup TODOs in FakeWBEMConnection; Added from_instance()

- pywbem/mof_compiler.py
> Fixes #853: Documented alias-related limitations of MOF compiler

- docs/changes.rst
- pywbem/cim_obj.py
- pywbem/tupleparse.py
- testsuite/test_cim_obj.py
- testsuite/test_tupleparse.py
- testsuite/testclient/embeddedinstances.yaml
- testsuite/testclient/embeddedobjectclasses.yaml
- testsuite/testclient/embeddedobjectinstances.yaml
- testsuite/testclient/enumeratequalifiers.yaml
- testsuite/testclient/getclass.yaml
- testsuite/testclient/getqualifier.yaml
> Fixes #1039: Fixed default and returned values of propagated & flavor attrs of CIM objects

- testsuite/run_cim_operations.py
- testsuite/test_indicationlistener.py
1. Built try blocks around all methods that create listeners so we are
certain to always destroy listeners at the end of each test.
2. Build context manager around most uses of Subscription manager to
automatically clean up if we do not clean up manually.
3. Move a number of function to common methods that were being repeated
in individual methos.
The enumerateinstances with deep inheritance test that fails was confirmed
as a server problem in that 1. Instance return includes properties from
superclass that it should not include. 2. Pegasus trace shows correct
value for de and lo getting to server.  Change message slightly to
state that it is just a warning.
There appears to be an issue in OpenPegasus when you set up multiples of exactly the same
subscription.  The provider appears to …
> Cleaned up run_cimoperations.py PyWBEMListenerClass

- pywbem/tupleparse.py
> Fixes #1092: Avoid UserWarning for unordered scopes in CIMQualifierDeclaration

- docs/changes.rst
- pywbem/_listener.py
- testsuite/test_indicationlistener.py
Note that on Windows, starting a second listener on the same port does not raise an exception (as shown by the `test_port_in_use()` test case). There is no test case that verifies whether this actually works on Windows.
> Fixes #1090: Improvements for port in use handling and other cleanup in listener

- pywbem/cim_operations.py
Note: The order of operations in this change is now consistent with the order of the pywbem functions available within wbemcli as updated by PR #1108.
> Docs: Reordered WBEMConnection methods in table

- dev-requirements.txt
> Fixes #1121: Nailed version of tornado to below 5.0 to accomodate older ssl

- testsuite/run_cim_operations.py
- testsuite/run_operationtimeouts.py
In testing I found some code ordering issues that cause exceptions in
particular conditions.  Mostly putting to much code in try block so that
a variable was not set when exception was executed.
> Code errors in run_operations.py and run_operationtimeouts.py

- pywbem/cim_obj.py
Add to documentation that IncludeQualifiers should be True.
This is just a cautionary note since the setting in a server is implementation dependent if you do not set this and that could mean creating path with no keybindings.
> Add comment on docstring of CIMInstanceName from_string method

- docs/changes.rst
- pywbem/_server.py
> Fixes #1145: Fixed that get_central_instances() continues on CIM_ERR_METHOD_NOT_FOUND

- docs/changes.rst
- testsuite/test_wbemserverclass.py
Creates a new test module, test_serverclass.py that executes a unit test on the WBEMServer class using pywbem_mock.
This creates a number of instances and executes the WBEMServer methods against the mock. Note that in order to do this I created a method in the test code inst_from_class that creates instances given the class (which must be in the repository) and a dictionary of propertyname/propertyvalue that fills out each instance.
I also created a method that builds the class repository in the mock wbem server given only the classes that will be used in the test (the mof compiler finds all super classes).  This reduces the repository load time from multiple seconds to milliseconds since It only installs about 10 classes for this test.
Right now tests all of the calls for brands, …
> Add unit test for WBEMserver class based on pywbem_mock.

- docs/changes.rst
- pywbem/mof_compiler.py
- testsuite/test_mof_compiler.py
Fix issue where compile_string that starts with include filefails the compile, cannot find the classes in the include file.
I fixed the issue and added tests for compiling partial pragma include files both as a file and as a string.
However, as we noted in issue #1160, the dependency finder mechanism in the compiler is still broken as it will not figure out that EmbeddedInstance classes or references are not compiled and, will in fact successfully complete a pragma or class compile while with these dependent classes completly missing.
This pr does not test for those dependency but sets up tests we can extend easily with the pr for issue #1138.  
Shakespeare in our world(From MacBeth.   'Out dammed bugs! Out I say!'.
> Fixes #1138: Compile mof based on pragma include file from compile_string

- docs/changes.rst
- docs/intro.rst
- docs/mocksupport.rst
- pywbem/mof_compiler.py
- pywbem_mock/_wbemconnection_mock.py
**Note:** When reviewing, please pay particular attention to the description of the behavior w.r.t. prerequisite CIM objects in the mock repository. That is different for:
* add_cimobjects()
* compile_...()
* the WBEM operation methods
and also different between lite mode and full mode of the mock repository.
I don't think that is correctly described yet for all those cases.
**COMMENTS:** I tried to review and compare with code.  A few new comments but we are getting close enough that it is probably time to close this out and approve.  This gets harder and harder to review and we do more comments on top of comments and try to review the doc/code/built doc.
I actually think the next step in documentation will be as we try to …
> Docs: Improved mock support chapter

- pywbem/_recorder.py
- pywbem_mock/_wbemconnection_mock.py
- testsuite/test_recorder.py
Added code to honor all attributes of detail_level for connection log.  This initially failed because of issue # 1181.  So  I moved the _response_delay attribute set to before the superclass init and for me that eliminated the issue.
Sorry, originally created this from another branch which sort of made a mess of the files changed.
Adds some more tests, cleans up some pylint issues in test_recorder.py and cleans up the setup method (it was repeated in subclasses) for the log tests.
DISCUSSION: Is this a legitimate way to get around issue #1181 (just moving the object attribute to before the call to the superclass ctor?  If so, Just turn off discussion.
Andy: I think it is legitimate. Turning off discussion needed, and merging.
> Fixes #1184 fix connection log detail_level

- pywbem/_logging.py
For details, see the commit message. Note particularly, that the log_dest default was only changed for configure_logger() (not for the string version) and that the default log filename of that function was not changed to None.
> Fixes #1180 Changed default log_dest in config_logger() to None

- docs/mocksupport.rst
- pywbem/_logging.py
In _logging removed example that uses basicconfig and expanded text on some of the
others
Minor changes to mock doc. Changed word module to
subpackage since pywbem_mock is not a module. From other
doc it appears that it can be called either a subfolder
or a subpackage.
> Changes to docs for _logging.py and mock

- pywbem/_logging.py
- pywbem/cim_operations.py
- testsuite/test_logging.py
- testsuite/test_recorder.py
A particular review point might be the default of propagate=False, which is probably right, but incompatible to before w.r.t. log propagation. That's why the testcases needed to be adjusted.
> Fixes #1186 Added 'propagate' parameter to log config functions

- DEVELOP.md
- README_PYPI.rst
- docs/changes.rst
- docs/wbemcli.help.txt
- makefile
- setup.cfg
Add wbemcli.py to makefile dependents list that makes docs/wbemcli_help_txt file in makefile
add comment to changes.rst
**TODO:** This one should probably be backed up to 0.12.2
> fixes #1205 docs/wbemcli)help-txt not uptodate

- docs/changes.rst
- pywbem/mof_compiler.py
- testsuite/test_mof_compiler.py
- testsuite/testmofs/test_refs.mof
Review needed based on update with comments fixed.
Adds capability to find missing class dependencies(cases where a class is defined as a requirement in another class declaration to try to find the depend classes in the compile search path and compile them.
This includes finding reference classnames defined in reference properties and parameters (i.e CIM_ManagedElement REF parent) and the classes for embedded instances in the compile  search path
if they are not already in the repository.  This works with any WBEM server repository implementation that returns CIM_ERR_INVALID_PARAMETER or CIM_ERR_FAILED if the class defined in the dependency is not in the repository.
This pr extends MOFWBEMConnection to generate a CIM_ERR_INVALID_PARAMETER exception if
the class for a REF defined in a …
> fixes #1160 Enhance MOF compiler and missing dependent classes resolution logic

- docs/changes.rst
- pywbem/_valuemapping.py
- testsuite/test_valuemapping.py
I'd like to point out some possible review points:
* What should be the datatype of the integer values returned by `tobinary()` (e.g. `Uint16` as in the current PR or simply `int`)?
**COMMENT:** Karl will go back to the test we created. Since we do not lose anything by returning the exact cim type of the element, we agree that this is the best solution.
* What should `tobinary()` return for the Values string of the unclaimed marker? (e.g. `None` as in the current PR, or some representation of all unclaimed integer values)?
CONCLUSION: Returning the None is much simpler and seems to be the most logical.
NEW QUESTION; What about an enumeration option.   Andy will look at the possibility. DONE.
> fixes #1153 Added support to ValueMapping for translating to binary and iterating

- pywbem/mof_compiler.py
- testsuite/test_mof_compiler.py
Fixes error in mof_compiler CIMError description text where the classname and
reference classname were inverted in the message and the () not added to
call.
Corrected message is:
Parameter value(s) invalid: Class u'MY_ClassDoesNotexist' referenced by element u'Group' of class u'My_BadAssoc' in namespace 'root/test' does not exist
Did not include in the issues list since this is change to change in this version.
> Fixes #1228 Fixes Error in mof_compiler CIMError Description text

- docs/changes.rst
- pywbem/mof_compiler.py
- testsuite/test_mof_compiler.py
WIP - I want to go back and sort out where it adds line_no, etc. to CIMError.
Changes use of args[0] in mof_compiler to status_code and args[1] to status_dscription.
The simple changes have all been made and it passes tests now.
> Fixes #1221 mof_compiler change use of args[0] etc.

- dev-requirements.txt
- docs/changes.rst
> Fixed Travis issue on py26 with format of empty field error.

- dev-requirements.txt
- minimum-constraints.txt
- testsuite/pytest_extensions.py
- testsuite/test_cim_obj.py
- testsuite/test_cim_types.py
- testsuite/test_nocasedict.py
- testsuite/test_tupleparse.py
> Issue #1201 Added improved test_function_new decorator

- docs/changes.rst
- pywbem/_nocasedict.py
- pywbem/cim_obj.py
- pywbem_mock/_wbemconnection_mock.py
> Fixes #1251 Clarified and improved copy() methods of NocaseDict and CIM objects

- docs/changes.rst
- pywbem/cim_obj.py
- pywbem_mock/_wbemconnection_mock.py
This pr rolls back PR #1255 into 0.12.3.
> Clarified and improved copy() methods of NocaseDict and CIM objects (for 0.12.3)

- docs/changes.rst
- pywbem_mock/_wbemconnection_mock.py
Fixes issue in Fake_invokemethod where we are returning
CIM_ERR_NOT_FOUND rather than CIM_ERR_METHOD_NOT_FOUND.  Also
reorganizes order of the tests to be more logical and adds one more test
to validate that the
class_origin is correct.  The problem occurs in WBEMServer where the
method that gets the central instances expects CIM_ERR_METHOD_NOT_FOUND.
This should also be in release 0.12.3
> fixes #1256 Correct issue in pywbem_mock with incorrect CIMError return

- docs/changes.rst
- pywbem_mock/_wbemconnection_mock.py
- testsuite/test_wbemconnection_mock.py
See commit for documentation.
This pr cherrypicks pr #1260 where we had a CIMError defined wrong in the Fake_InvokeMethod and with the deepcopy changes we hit that issue which caused the WBEMServer tests to fail.
NOTE: I think we want to put this in 0.12.3 also.
> Fixes #1253 Fix issue with deepcopy of objects in _wbemconnection_mock

- docs/changes.rst
- pywbem_mock/_wbemconnection_mock.py
- testsuite/test_wbemconnection_mock.py
- testsuite/test_wbemserverclass.py
NOTE: This also cherry-picks the pr that fixes the issue with DEFAULT_NAMESPACE #1260  so that the
test runs.
This is a simple change that modifies the method that builds the repo from using a string with pragmas to using the FakedWbemconneciton method compile_dmtf_schema. I would not even worry about t his normally but I want to commonize the process for testing the subscription manager and the wbemserver class since the subscription manager requires the wbemserver.  I am trying to get some small pieces pushed so they can be committed and merged this week.
> Modify test process that builds repo for test_wbemserverclass.py

- PKG-INFO
- docs/changes.rst
- pywbem_mock/_wbemconnection_mock.py
- testsuite/test_wbemconnection_mock.py
This fixes the issues documented in issue #1271 where there was a param
acquisition name that lower case instead of mixed case (Should have been
ClassName) and a test for invalid classname on EnumerateClassNames and
EnumerateClasses was mising.
This also removes two print statements that should not have been in the
code (printed out the error for the two methods that are not
implemented)
and fixed one pylint issue.
We added tests to cover the new code for ClassName not in repo.
Added note to changes.rst
> fixes #1271 - Issue with mock EnumerateClassNames and EnumerateClasses

- docs/changes.rst
- pywbem_mock/_wbemconnection_mock.py
- testsuite/simple_mock_add_obj.py
- testsuite/simple_mock_model.mof
- testsuite/test_wbemcli.py
- wbemcli.py
This adds a parameter --mock_server to the command line parameters of
wbemcli to allow wbemcli to be used with the pywbem_mock environment.
This also adds one new constructor parameter to FakedWBEMConnection,
timeout that the WBEMConnection can use to return the timeout exception
if this value is set and is of a lower value than the response_delay
time which would indicate that the server delayed longer than the client
timeout setting
It also adds a test of the wbemcli new parameter to test_wbemcli.py and
a simple mof file to be used in that test.
Adds initial tests. Adds tests for the new parameters which means two new files in testsuite. This DOES NOT convert test_wbemcli.py to pytest.
Adds entry under enhancements to changes.rst
> Fixes #1268 Add input parameter to wbemcli to allow mocking a server

- pywbem_mock/_wbemconnection_mock.py
change all the raises CIMError in _wbemconnection_mock to use %r in place of %s for all classnames, property names, namespace names, etc.
This was per our discussion that this eliminates issues of possible exceptions if there are illegal unicode characters in the text of things like classnames, namespaces, etc.
DISCUSSION: Does the format command protect __str__ output so that in place of using the __repl__ we could just use format and still output the __str__ definitions??
> Changes to messages in _wbemconnection_mock to use %r in place of

- testsuite/instance_from_class_method.py
- testsuite/test_wbemconnection_mock.py
- testsuite/test_wbemserverclass.py
- testsuite/wbemserver_mock.py
Will do more refactor as part of using this as driver for test_subscriptionmanager.py
Refactors the test so that a mock of wbemserver can be use for this and other tests and adds two new files:
1. instance_from_class_method.py - Temporary localization of the
instance_from_class method until we get it accepted.  This keeps the
tests running until we get this added method accepted as a new method in
ICMInstance.
2. teststuite/wbemserver_mock.py which isolates all the code to generate
the mock for the wbem server.  Since the wbem server mock is required to
run the WbemServer class in any mock this simplifies building this
component.
3. Modifications to test_wbemserverclass.py to work with the two new
files.
I want to refactor so we separate profile and central class creation into a common …
> Refactor test_wbemserverclass.py

- docs/changes.rst
- pywbem/_subscription_manager.py
- testsuite/test_subscriptionmanager.py
Add a new test for the subscription manager based on pywbem_mock.
See Commit message for details.  
At this point it demonstrates that we can use the mock_repository to manage subscriptions for the mock repository and use the mock_wbemserver code to define a wbemserver  I propose
we review this and then create new issue to create remainder of tests including error tests. This already covers a lot of the code in subscription manager.
This also fixes one code issue found during these tests, a use of the .format with python 2.6 that was causing the tests to fail on python 2.6.  See issue #1279
> fixes #1250 add subscription mgr test

- docs/changes.rst
- pywbem/mof_compiler.py
> Fixes #1292 Added type check to MOFCompiler init for search_args

- PKG-INFO
- docs/changes.rst
- docs/wbemcli.help.txt
- pywbem/cim_obj.py
- pywbem/config.py
- testsuite/test_cim_obj.py
This is ready for review and merge. See commit for details
> Fixes #1298 null value keybindings

- docs/changes.rst
- pywbem/cim_obj.py
- testsuite/test_cim_obj.py
This PR rolls back PR #1313 into pywbem 0.12.
> 0.12: Fixed IndexError in tomof() of some CIM objects on empty array value

- PKG-INFO
- docs/changes.rst
- pywbem/cim_obj.py
- testsuite/test_cim_obj.py
> Fixes #1312 Fixed IndexError in tomof() of some CIM objects on empty array value

- docs/changes.rst
- pywbem/_server.py
- pywbem/_subscription_manager.py
- pywbem/cim_http.py
- pywbem/cim_operations.py
- pywbem/exceptions.py
- pywbem/mof_compiler.py
- testsuite/test_cim_operations.py
- testsuite/test_exceptions.py
- testsuite/test_recorder.py
What is needed for this PR, is a test on a life server.
The first three commits implement having the connection information in the pywbem exceptions, plus some preparatory changes. Each of these three commits is separate logical step and is best reviewed separately. They were part of the first review.
Compared to the first review, I had to change the connection information that is added to the pywbem exceptions, from adding the entire WBEMConnection object, to adding just the connection ID string. Reason was that in cim_http.py, the connection ID was available but not the connection object, and I did not want to change that there. This change in the exception classes (to take the connection ID string instead of the WBEMConnection object) is done in the fourth …
> Added connection information to exceptions

- docs/changes.rst
- docs/intro.rst
- pywbem_os_setup.bat
This fixes the recent Appveyor issue where it cannot execute Win32OpenSSL_....exe.
This is needed by all other PRs and therefore has been set to priority.
> Upgraded Win32 OpenSSL from 1.1.0h to 1.1.0i

- docs/changes.rst
- testsuite/test_wbemcli.py
- wbemcli.py
Somewhere we completely forgot this operation.  I only added it because
I needed to test it since we are getting some strange results from
run_cimoperations.py in another pr and I wanted to confirm or discard
that some conclusions.
Note: There is no test since the test_wbemcli.py tests only initialization, etc. not the individual operations.
Add new entry to changes.doc
> Issue #1332 Add ExecQuery Operation to wbemcli as shortcut eqy.

- docs/changes.rst
- pywbem/cim_operations.py
- testsuite/test_itermethods.py
Fixes issue #1334 where the parameters for QueryLanguage and Query were
reversed in the ExecQuery call that is the fallback if the
OpenQueryInstances fails or use_pull_operations is False.
Also fixes test results for this test (also reversed) and adds comment
to changes.rst
> issue #1334 - Fix issue where IterQueryInstances params reversed

- docs/changes.rst
- pywbem/cim_operations.py
- testsuite/test_itermethods.py
This PR rolls the fix to issue #1334 from PR #1335 back into the 0.12 fix stream.
Please do a quick review.
> 0.12:  issue #1334 - Fix issue where IterQueryInstances params reversed

- .travis.yml
- PKG-INFO
- appveyor.yml
- dev-requirements.txt
- docs/changes.rst
- docs/intro.rst
- minimum-constraints.txt
- pywbem/_nocasedict.py
- pywbem/cim_types.py
- requirements.txt
- rtd-requirements.txt
- setup.cfg
- testsuite/test_nocasedict.py
Python 3.7 has been released on 2018-06-28. This PR adds Python 3.7 support to pywbem, and also fixes #1337 as part of that.
> Fixes #1337 Added support for Python 3.7

- docs/changes.rst
- pywbem/tupleparse.py
Testcases have not been added at this point, there was an existing TODO to add testcases for IRETURNVALUE.
> Fixes #1347 Fixed missing VALUE.OBJETWTHLOCALPATH in IRETURNVALUE

- docs/changes.rst
- pywbem/mof_compiler.py
- testsuite/test_logging.py
- testsuite/test_mof_compiler.py
This extension is necessary as a basis for using WBEMServer.create_namespace() in MOFCompiler (see PR #1339).
> Added passing WBEMConnection as handle to MOFCompiler

- docs/changes.rst
- testsuite/run_cim_operations.py
Ready for review except for python 2.7 failure in getting plugin
Fix test for enumerateinstances deepinheritance option.
Original test could not really test enumerateinstances DeepInheritance.
Created simpler test that just does EnumerateInstances on
CIM_ManagedElement and determines the number of properties.  Without
DeepInheritance, there should be no more properties than in class. With
DeepInhertance, Pegasus at least has many instance that have more
properties than CIM_Managed element so finds some instances with
property count gt the number of properties in CIM_ManagedElement.
> Fixes #477: Poor test in run_cim_operations

- .gitignore
- .travis.yml
- dev-requirements.txt
- docs/changes.rst
- makefile
This PR rolls back some logistical changes into 0.12:
* Adjusted exclusion of CIM schema to new names (part of PR #1220)
* Excluded .DS_Store files from git. (PR #1233)
* Fixes #1288 Eliminated confusing pbr import error message in make (PR #1289, just one commit)
* Fixed determination of package version for Linux. (PR #1294)
* Fixes #1371: Pinned version of pytest-cov to <2.6 (PR #1370)
* Change log for pinning pytest-cov version to <2.6 (PR #1375)
> 0.12: Various logistical rollbacks into 0.12

- PKG-INFO
- docs/changes.rst
- pywbem_mock/_wbemconnection_mock.py
- testsuite/test_wbemconnection_mock.py
Ready for review
See commit messages for details.  
Note: The changes to the mocker code are minor. The changes to the tests are more significant in that  this adds a significant number of tests and it was easier to rewrite some of the tests rather than to continue to extend them directly.
NOTE: We also cleaned up one issue where we had been using strings to define CIM_ERR... messages in the tests and changed all of that to use the status_code variables directly.
> Fixes #1355: Issues with case insensitivity on classnames in pywbem_mock

- pywbem_mock/_wbemconnection_mock.py
- testsuite/test_wbemconnection_mock.py
Corrects a number of minor issues in test_wbmemconnection.py and standardizes some of the tests. It also removes a couple of commented print statements from pywbem_mock/_wbemconnection_mock.py. Generally these were things we saw when preparing the rollback for #1355 and it was easiest to clean them up now.
It does not add tests.
See commit for details.
> Minor fixes I did not catch in fixes for issue #1355

- docs/changes.rst
- pywbem/cim_types.py
- testsuite/test_cim_types.py
- testsuite/test_recorder.py
Needs to be rolled back into 0.12.
> Fixes #1379: Added support for asterisks to CIMDateTime

- docs/changes.rst
- pywbem/cim_types.py
- testsuite/test_cim_types.py
- testsuite/test_recorder.py
This PR rolls back PR #1381 into 0.12.6.
> 0.12: Added support for asterisks to CIMDateTime (rollback from 0.13.0)

- docs/changes.rst
- pywbem/mof_compiler.py
- testsuite/test_mof_compiler.py
See commit for details
Extended the seach_paths ctor parameter to allow single string as input
and cvt to iterable.  Also added test for this.
Removed one TODO because it had been incorporated into a test (see test
test_error_search).
> Fixes issue #1227. mof compiler search path extended to allow string

- pywbem/_nocasedict.py
- pywbem/_recorder.py
- pywbem/_statistics.py
- pywbem/cim_obj.py
- pywbem/cim_operations.py
- pywbem/cim_types.py
- pywbem/cim_xml.py
- pywbem/exceptions.py
- pywbem_mock/_dmtf_cim_schema.py
- pywbem_mock/_wbemconnection_mock.py
- testsuite/test_cim_operations.py
- testsuite/test_wbemconnection_mock.py
- testsuite/wbemserver_mock.py
This PR is a follow up to PR #1419 and makes sure that the one-line descriptions that are now in the automatically generated method and attribute tables, are meaningful.
> Docs: Improvements for method and attribute lists and other imprs.

- rtd-requirements.txt
This makes the Python package versions used for Sphinx runs on RTD consistent with development.
> Fixed minimum versions for RTD Sphinx runs

- docs/changes.rst
- pywbem/cim_operations.py
- testsuite/test_cim_operations.py
> Removed deprecation of setting WBEMConnection.default_namespace

- .gitignore
- docs/changes.rst
- makefile
- testsuite/end2end/pytest_end2end.py
- testsuite/end2end/server_file.py
- testsuite/end2end/server_file_example.yml
- testsuite/end2end/test_interop.py
To use the end2end support:
1. Create a `testsuite/end2end/server_file.yml` file, e.g. by copying the example file and adjusting it.
2. Run `TESTSERVER=xxx make end2end` to test against server or server group `xxx`.
COMMENT: I think you mean:
make end2end TESTSERVER=xxx
Ready for review and for serious test against real WBEM servers.
TODO:
* Unit testcases for `server_file.py` and `pytest_end2end.py`
> Added support for end2end testing against real WBEM servers

- docs/changes.rst
- docs/client.rst
- docs/client/warnings.rst
- pywbem/__init__.py
- pywbem/_warnings.py
- pywbem/exceptions.py
- testsuite/test_exceptions.py
- testsuite/test_warnings.py
This is a small fixup after merging PR #1539.
Also, there is the following **discussion point**:
* The warning class has been named `ServerWarning`, but it is defined as: "indicates an issue with the WBEM server that has been tolerated by pywbem". With that definition, a class name of `ToleratedServerIssueWarning` would be more appropriate. Discuss which name to use finally.
> Moved new warning classes into separate module and added to docs

- docs/changes.rst
- pywbem/_utils.py
- pywbem/_valuemapping.py
- pywbem/cim_obj.py
- testsuite/test_utils.py
- testsuite/test_valuemapping.py
@KSchopmeyer It would be good to test this in the environment where you encountered issue #1547.
> Fixes #1547: Added support for binary,octal,hex values to ValueMapping

- docs/changes.rst
- pywbem/_server.py
**How to test against a real server:**
* No other commits needed on top of the branch of `andy/add-interop-to-namespaces`
* Specifically, PR #1550 is not needed for this test.
* Have `testsuite/end2end/server_file.yml` set up so that the default server is the server nicknamed "Fujitsu" that had the behavior of not including the Interop namespace in the enumeration result.
* Issue:
```
make end2end
grep ToleratedServerIssueWarning end2end_*.log
```
* Verify that the make succeeds and that there is one occurrence of `ToleratedServerIssueWarning`.
> Fixes #1430: Added Interop namespace to set of all namespaces in WBEMServer, if missing

- docs/changes.rst
- pywbem/_server.py
- testsuite/test_wbemserverclass.py
- testsuite/wbemserver_mock.py
**Note: This PR is on top of PR #1550. Review only the delta.**
This PR splits off the addition of the 'reference_direction' parameter from Karl's PR #1533, but does not yet add the methods to automatically determine that direction.
> Specify reference direction in WBEMServer.get_central_instances()

- testsuite/test_cim_obj.py
No review needed, only changes in testcases.
> Eliminated warning about NocaseDict and order in test_cim_obj.py

- docs/changes.rst
- pywbem/tupleparse.py
Ready for review, test and merge.
Note: This should be end2end tested at least with the Brocade server in the SMI-S testlab.
> Fixes #1564: Added toleration support for CIM-XML responses with empty TYPE attr

- docs/changes.rst
- pywbem/cim_operations.py
Ready for review, test, and merge.
Testing: `make end2end` on at least the Dell/Compellent, EMC3, EMC4 servers.
> Fixes #1568: Setting last_raw_request/response independent of debug

- docs/changes.rst
- pywbem/cim_operations.py
- pywbem/exceptions.py
- testsuite/testclient/conftest.py
This is the second part of improvements on ParseError.
Particular review items:
* The `str()`of ParseError now includes the CIM-XML response, which may get quite lengthy.
* It does not contain the CIM-XML request, because that is not normally needed to understand what is going on.
Testing: It would be good to run this PR with `make end2end` against the smigood group.
> Add CIM-XML request and response data to CIM/XMLParseError

- docs/changes.rst
- pywbem/_server.py
- testsuite/test_wbemserverclass.py
Because this change is expected to match more profiles in the SMI-S testlab than before, it is suggested to run the end2end test.
> Fixes #1551: Case-insensitive profile names / orgs / versions

- makefile
- testsuite/end2end/_utils.py
- testsuite/end2end/pytest_end2end.py
- testsuite/end2end/test_profile_snia_server.py
Testing: `make end2end` against the smigood group. Please compare the total execution time to before the change.
> Split end2end profile testcases & cache objects for reuse

- testsuite/end2end/assertions.py
- testsuite/end2end/test_profile_snia_smis.py
This PR adds an end2end test that asserts that the tree of referenced profiles under a top level specification has no shared or circular references.
Testing: This test is likely to fail on most implementations, because they tend to have RP instances per profile document, and not per profile implementation.
**Discussion point:** Need to discuss how central instances are supposed to be discovered from an RP instance if the same RP instance represents multiple profile implementations.
Update: I created issue #1588 for this discussion point.
> Fixes #1582: End2end: Added testcases for SMI-S top level specification

- dev-requirements.txt
- docs/changes.rst
- minimum-constraints.txt
> Fixes #1592: Pinned lxml to <4.3.0 for Python 2.6

- docs/changes.rst
- pywbem/cim_http.py
- pywbem/cim_obj.py
- pywbem/tupleparse.py
- testsuite/end2end/pytest_end2end.py
- testsuite/end2end/test_profile_generic.py
- testsuite/end2end/test_profile_snia_server.py
- testsuite/test_tupleparse.py
> Fixes #1595: Made warnings consistent in pywbem and end2end

- .travis.yml
Since yesterday, there are occasionally strange failure patterns in
some PRs. They only show up in the Travis "push" runs, and happen for
all jobs within the run. The Travis "pr" run is fine, as is the Appveyor
run. When merging such PRs, the Travis run on the merged master runs fine.
Examples:
PR #1598: https://travis-ci.org/pywbem/pywbem/builds/478256455
PR #1596: https://travis-ci.org/pywbem/pywbem/builds/478657486
PR #1591: https://travis-ci.org/pywbem/pywbem/builds/478658486
PR #1406: https://travis-ci.org/pywbem/pywbem/builds/478658809
It turns out the reason for this was the depth of the shallow git
checkout that is done by Travis. The branches that failed had just
exceeded 200 commits since the last tag (0.12.0), and the depth
parameter in .travis.yml was 200.
This change fixes …
> Fixes #1600: Fixed strange failure pattern in Travis

- testsuite/end2end/_utils.py
- testsuite/end2end/assertions.py
- testsuite/end2end/pytest_end2end.py
- testsuite/end2end/test_profile_generic.py
- testsuite/end2end/test_profile_snia_server.py
- testsuite/end2end/test_profile_snia_smis.py
- testsuite/end2end/test_server.py
Particular review items may be:
* Approach for asserted version of WBEM operations by adding class `WBEMConnectionAsserted`. Alternatively, this could be done similarly to how it is done for `WBEMServer`, by generalizing `server_func_asserted()`and `server_prop_asserted()`.
Testing: end2end test on Brocade or Brocade1 server. pytest should no longer show the re-raise traceback of the ValueError exceptions for invalid integers, but a single AssertionError.
> End2end: Raising AssertionError for all failures; Improved exc msg

- docs/changes.rst
- pywbem_mock/_dmtf_cim_schema.py
> Fixed location of CIM Schema MOF file archive on DMTF site

- docs/changes.rst
- docs/mocksupport.rst
- pywbem_mock/_wbemconnection_mock.py
Fixes two errors in documentation of mock.
1. method_callback_interface reversed two parameters. This was only in the interface definition. The
code and test code is correct.
2. Error in example of compile_dmtf_schema in mocksupport.rst.  Misnamed and parameters not correct.
This PR changes no executing code.
> Fixes #1614 - Fix order of method_callback parameters

- tests/dtd/DSP0203_2.2.0.dtd
- tests/dtd/DSP0203_2.3.1.dtd
- tests/dtd/DSP0203_2.4.0.dtd
- tests/unittest/pywbem/test_cim_obj.py
- tests/unittest/pywbem/test_cim_xml.py
- tests/unittest/utils/validate.py
> Fixes #1602: Cleanup of CIM-XML DTD validation and use recent DTD version

- tests/end2endtest/test_profile_generic.py
- tests/profiles/profiles.yml
I don't think an end2end test is needed for this one.
> Removed notion of pattern profiles from end2end tests

- docs/changes.rst
- tests/unittest/pywbem/test_cim_obj.py
- tests/unittest/utils/validate.py
> Fixed #1603: Improved testing of tocimxml() and tocimxmlstr() of CIM objects

- docs/changes.rst
- pywbem/_statistics.py
- tests/unittest/pywbem/test_statistics.py
See commit message for detailed info.
Adds a new method to statistics to clear the statistics for a connection,.
In working on another pr that involved using statistics, I realized that there was no method to clear the statistics for a connection so created this.
> Add method to reset statistics

- tests/manualtest/run_enum_performance.py
This is part of answering issue #1630 
Extend test that compares enum and pull operations to determine how much time is spent in server vs in parser for responses.
NOTE: This code is now completely dependent on a WBEM server that
includes a class and method that will generate instance responses with
size and number of instances defined by a method that is part of
that class.  I.e. OpenPegasus.
We can chose to review and commit this code as is or just use it to gather data on the response timing issue.
> Extend the manual test run_enum_performance.py to gather info

- tests/end2endtest/utils/pytest_extensions.py
- tests/end2endtest/utils/server_definition_file.py
- tests/server_definitions/example_server_definition_file.yml
- try/run_central_instances.py
Adds a test script currently being used  to test get_central_classes and
the reference difference algorithms to its own branch.
Revamped to use the profile file and server_file from end2end.  I suggest we commit this as it is only a temporary test tool. 
NOTE: This depends on the implementation of get_centralinstances and the difference method defined in pr #1411.
NOTE: This script has been update for the new tests diretory structure and uses the ServerDefinitionFile and ServerDefinition classes from that work.
> Adds a test script to the try directory.

- .travis.yml
- dev-requirements.txt
- docs/changes.rst
- makefile
- minimum-constraints.txt
Note that pylint is generally not run in travis build except for the manual-ci-run. I have rebased it on this change, so have a look there for pylint results and how it runs.
> Fixes #1640: Added support for running pylint also on Python 3.x

- .travis.yml
- appveyor.yml
- docs/changes.rst
- docs/intro.rst
- makefile
- pywbem_os_setup.bat
- pywbem_os_setup.sh
- tests/unittest/utils/cmd_line_test_utils.py
- tests/unittest/utils/validate.py
- tools/package_version.py
- tools/python_bitsize.py
- tools/python_version.py
- tools/retry.bat
- tox.ini
Test: Raamesh wantes to test this on native Windows, see issue #1631.
> Fixes #1631: Moved make shell commands into scripts for Windows

- docs/changes.rst
- makefile
This is a minor change to makefile to remove the cover files from the pywbem_mock package as it does now from the pywbem package. This is a development issue only so there is no need to do rollback to 13, etc.
> Extend makefile to remove cover files from pywbem_mock

- minimum-constraints.txt
- requirements.txt
- rtd-requirements.txt
- tests/end2endtest/utils/pytest_extensions.py
- tests/unittest/utils/cmd_line_test_utils.py
This fixes the current errors on Travis for Python 2.6.
For details, see the commit messages.
> Fixes for Python 2.6 (PyYAML version, format strings)

- docs/changes.rst
- pywbem/__init__.py
- setup.cfg
- setup.py
The test that the new pip based Python version check actually works was made with a Python version requirement that required >=2.7 and thus was expected to fail on Python 2.6. The failing installs on Python 2.6 can be seen in this Travis run:
https://travis-ci.org/pywbem/pywbem/builds/507180522
> Improved Python version checking by using 'python_requires' keyword

- docs/changes.rst
- pywbem/cim_operations.py
- pywbem/tupleparse.py
- tests/unittest/pywbem/test_cim_operations.py
- tests/unittest/pywbem/test_mof_compiler.py
- tests/unittest/pywbem/test_tupleparse.py
See commit messages for details.
Adds tests to test_tupleparser in those areas where the coverage shows missing, primarily in the methods that are used only by the server.  Note that leaves a bunch of TODOs for other methods that are not tested in test_tupleparser.py but that show tested in the coverage report.
It also adds test for the mof compiler to pick up a few obvious holes in the coverage (second commit)
All this only picks up coverage 1 %.
> Some changes to improve coverage.

- PKG-INFO
- pywbem/mof_compiler.py
- pywbem/tupleparse.py
- tests/end2endtest/utils/assertions.py
- tests/end2endtest/utils/pytest_extensions.py
The change in tupleparser (change from two compares to in [...] and
assertions (remove useless else) change code. The others only change
pylint comments.
This gets us down to about 100 pylint comments not counting TODO and XXX
comments.
> Fix several pylint issues in compiler, tupleparse, and tests.

- docs/changes.rst
- pywbem/mof_compiler.py
Modify mof_compiler to remove unused productions for
associationDeclaration, IndicationDeclaration, and the association
features lists
The pywbem compiler YACC includes productions for association declaration
and indication declaration.  While these are defined in DSP0004,
in this compiler they are never used because the the order of
executing the CreateClass production was classDeclaration,
associationDeclaration, indicationDeclaration and the syntax of
association and indication declarations is really a subset of the
class declaration.
Since the association and Indication abnf definitions are the same
syntax as the class declaration except that the keywords "Indication"
/ "Association" (i.e. the qualifiers association and indication) are the
first entry in the qualifier list, the pywbem …
> Modify mof_compiler.py to remove unused production defs.

- tests/manualtest/run_enum_performancesimple.py
Add a file that executes a simple test of the response time for
EnumerateInstances and Open/Pull enumerate instances. This test does not
use any of the functionality added since pywbem 0.10.0 and only measures
the overall request response time.  This was done to allow it to be used
to measure response time changes between versions.
It executes only against the OpenPegasus server because it uses a
special provider in that server that generates response sizes and
response counts (number of instances returned) based on a method sent to
the server.
The primary goal of this test to be able to conduct a test over a range
of versions of pywbem and compare the results.
> Add simple enum performance manual test

- docs/changes.rst
- makefile
This PR resolves some of the issues reported in issue #1714.
> 0.14: Temporary fix for pytest option --pythonwarnings in end2end tests

- docs/changes.rst
- makefile
This is a temporary fix for a part of the issues reported in issue #1714.
Issue #1720 has been opened to find a permanent solution.
This PR has been rolled back to 0.14.2 in PR #1723.
> 01 Fixed --pythonwarnings option for pytest in end2end tests

- docs/changes.rst
- pywbem/_server.py
This PR has been rolled back to 0.14.2 in PR #1726.
> 03 Changed GetCentralInstances methodology to be bypassed by default

- dev-requirements.txt
This PR rolls the fix in PR #1708 (0.14.1) forward into master.
> Pinned Sphinx to below 2.0.0 also for py3.5+

- docs/changes.rst
- tests/profiles/profiles.yml
This PR resolves some of the issues reported in issue #1714.
**Discussion point:** Complete the details for the Cascading profile. Using CIM_ComputerSystem for both central and scoping class, which consistent with what I found in a particular storage array. Asked Mike for clarification.
Update: Mike explained the situation with the Cascading profile, i.e. that in the version it appeared the central and scoping classes were not specified in the profile yet. Updated the PR with his suggestions. It is now ready to go. The end2end tests pass with the storage array I tested against.
> 0.14: Added and fixed profile definitions for end2end tests

- docs/changes.rst
- pywbem/tupleparse.py
1. Remove six  usage in tupleparser.py
1. Change from using isinstance() to using type() in tupleparser.
This change seemed to actually gain  significant performance at least
for python 3.
3. Change function that created set to create list because
faster.  This actually seemed to gain some performance.
NOTE: This involves moving from using isinstance() to type() for this performance sensitive code and so we should really be sure that there are no issues.  The reason this was considered at all is that the isinstance had become one of the largest time consumers in the response_performance test as of version 0.14.0
I did not mark this for review since I am still doing testing, ex. against OpenPegasus. but am marking it now..
> Add changes to gain more performance:

- docs/changes.rst
- docs/notebooks/iterablecimoperations.ipynb
Fixes the example of the use of IterQueryInstances in the Jupyter
notebook iterablecimoperations.ipynb where the example tried to iterate
the returned result rather than the generator property of the returned
result.  This also expanded the documentation for this example.
> fixes issue #1741 Jupyter Note book example broken

- docs/changes.rst
- pywbem_mock/_wbemconnection_mock.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
Found issue with case sensitivity of test for property list on EnumerateInstances with conn_lite=False.
Fixed the issue and also cleaned up some other tests when I figured out how we could do both the
conn_lite=True and conn_lite=False tests in a single test. Did not work for this particular test however.
This is clearly a bug
> Fix issue in mocker with property list on EnumerateInstance

- dev-requirements.txt
- docs/changes.rst
- minimum-constraints.txt
This PR rolls back PR #1757 into 0.14, with the exception that the `requests` package is not being upgraded on Python 2.6.
> 0.14: Upgraded minimum versions of dependent packages: requests, urllib3, bleach

- tests/manualtest/run_response_performance.py
Fix issue in this manual test when used with pywbem tests version 0.12
and earlier.  We were comparing a string and integer.
This is an issue in a manual test only but it is a bug.  I propose that if we do another pywbem 14.x release we include this fix backport
> Fix issue in run_response_performance.py

- dev-requirements.txt
- docs/changes.rst
- minimum-constraints.txt
**Note: This PR is on top of #1760. Review only the last commit with the delta.**
The issues were reported as follows, by the `safety` package:
```
╞══════════════════════════════════════════════════════════════════════════════╡
│ REPORT                                                                       │
│ checked 106 packages, using default DB                                       │
╞════════════════════════════╤═══════════╤══════════════════════════╤══════════╡
│ package                    │ installed │ affected                 │ ID       │
╞════════════════════════════╧═══════════╧══════════════════════════╧══════════╡
│ requests                   │ 2.19.1    │ <=2.19.1                 │ 36546    │ …
```
> Upgraded minimum versions of dependent packages: requests, urllib3, bleach

- docs/changes.rst
- docs/tutorial.rst
Added a reference in the table of notebooks to the mock notebook.  I thought I had done it for v 0.13.0 but found in a demo that it was missing.
I also marked this for rollback but I have another but to submit and since this is low priority, I propose we wait for my other bug before any minor revision release.
> Add ref in doc to pywbem_mock Jupyter notebook

- docs/changes.rst
- docs/tutorial.rst
We had created the Jupyter notebook for this tutorial earlier this year
but I neglected to include it in the table of notebooks in the
tutorial.rst file.
Add a section for the table of notebooks
To make the documentation on tutorials clearer, I added a section "table
of Jupyter notebooks" so that can be clearly seen from the table of
contents from the documentation.
> 0.14: Add ref in doc to pywbem_mock Jupyter notebook

- docs/changes.rst
- pywbem/cim_http.py
The method load_cert is incorrect for python 3.  The correct method
should be load_cert_chain(...). The load_cert(...) method is from
M2Crypto
NOTE: We need to write a test for OpenPegasus to test certs.  see issue # 1778
Currently there is no test of certs in the unit, client, or openpegasus
tests.
> Fixes #1769: AttributeError when using connection certificates on Python 3

- dev-requirements.txt
- docs/changes.rst
> Removed pinning of docutils as new variant of 0.15 was released today

- dev-requirements.txt
- docs/changes.rst
Roll back PR #1796 into 0.14.5.
> 0.14: Removed pinning of docutils as new variant of 0.15 was released today

- docs/changes.rst
- tests/manualtest/run_cim_operations.py
Extends the tests in the IterEnumInstances class that execute tests to compare traditional, pull, and iter results to add tests for LocalOnly and IncludeQualifier with enum and IncludeQualifier with Associators and References.
NOTE: As of this morning it does catch the LocalOnly issue (only a couple of years to late).
Propose rollback logical since we will make further changes to 1.0.0.
> Add tests for LocalOnly & IncludeQualifiers to manual test

- dev-requirements.txt
- docs/changes.rst
This rolls back PR #1808 to pywbem 0.14
> Pinned lxml to <4.4.0

- dev-requirements.txt
- docs/changes.rst
> Pinned pytest to 5.0.0 for Python<3.5

- docs/changes.rst
- tests/manualtest/run_cim_operations.py
- tests/manualtest/run_operationtimeouts.py
- tests/unittest/pywbem/test_mof_compiler.py
> Test: Fixed errors on Python 2.6 about unnamed format replacements

- dev-requirements.txt
- docs/changes.rst
This PR rolls back PR #1813 into 0.14.
> 0.14: Pinned pytest to 5.0.0 for Python<3.5

- docs/changes.rst
- tests/manualtest/run_cim_operations.py
- tests/manualtest/run_operationtimeouts.py
- tests/unittest/pywbem/test_mof_compiler.py
This PR rolls back PR #1812 into 0.14.
> 0.14: Test: Fixed errors on Python 2.6 about unnamed format replacements

- tests/unittest/test_wbemcli.py
- wbemcli.py
Fixes the formatting of the wbemcl  mock-server help option to fit into 80 col terminal and modifies test of the help output.
> Fixes #1826: Format of wbemcli option

- PKG-INFO
- tests/unittest/test_wbemcli.py
This PR picks the commit "Handle wbemcli naming" from Tony's PR #1815.
> 0.14: Fix tests to support flexible wbemcli naming

- tests/__init__.py
- tests/unittest/pywbem/test_cim_obj.py
> 0.14: Test: Print pywbem path and version and no longer CHECK_0_12_0

- docs/changes.rst
- pywbem_os_setup.sh
> Fixes #1844: 0.14: Fixed the issue with 'dnf makecache fast' during pywbem_os_setup.sh on Fedora

- .travis.yml
- pywbem_os_setup.sh
Note that the changes are all on OS-X which is not enabled in the standard set of platforms on Travis. So to review how the change runs on OS-X, the manual-ci-run branch in PR #791 has been rebased on this PR here. Look at its Travis runs for details.
> Fixes #1800: Fixed pyzmq install error on Travis with MacOS 10.13 / Python 3.7

- docs/changes.rst
- pywbem_mock/_wbemconnection_mock.py
> 0.14: Fixed case sensitive class name in ModifyInstance mock support

- docs/changes.rst
- makefile
> Fixes #1720: Test: Enabled Python warning suppression again and fixed make variable name

- docs/changes.rst
- makefile
Rolls back PR #1868 into 0.14.6. No review needed.
> 0.14: Test: Enabled Python warning suppression again and fixed make variable name

- dev-requirements.txt
- docs/changes.rst
- minimum-constraints.txt
- requirements.txt
Rolls back PR #1870 into 0.14.6, but is slightly more complex because of py2.6. support. Still, no review needed, IMO.
> 0.14: Fixed minimum version of testfixtures, pytest and PyYAML

- pywbem_mock/_wbemconnection_mock.py
> Fixes #1872: Fixed time.clock() deprecation

- pywbem_mock/_wbemconnection_mock.py
Rolls back PR #1873 into 0.14.6.
> 0.14: Fixed time.clock() deprecation

- docs/changes.rst
- docs/wbemcli.help.txt
- pywbem_mock/_wbemconnection_mock.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
Fixes issue where the case of properties on CreateInstance keeps the
case of the property in the instance, not the case of the property in
the class.
This is not disallowed in the specs as far as I can tell but it is
unsightly.
We simply modify any property names where the case is different to be
the case as defined in the class.
This is going to be fun.  I marked for rollback assuming that it is rollback to 0.15.0.
> Fixes #1883: Property case on create instance

- docs/changes.rst
- pywbem_mock/_wbemconnection_mock.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
Fixes issue with case sensitivity of property names in modify instance.
Note that we refactored code slightly in the method to eliminate an
unnecessary pair of list comprehenshions and make internal var
names clearer.
Adds test for the documented condtion and removes one duplicated
test.
> Fixes #1887: Mock Modify Instance property case sensitivity

- docs/changes.rst
- pywbem/mof_compiler.py
The compiler and some server implementations (i.e implementations of BaseWBEMConnection) together could lose a a new instance being created with "instance of" because the compiler is
missing an exception. If the server returns ALREADY_EXISTS on CreateInstance and the subsequent ModifyInstance that is executed within the compiler returns anything but NOT_SUPPORTED, the compiler just drops the instance.
This adds that exception .
Note that this does not test the change because the problem does not
occur with the default MOFWBEMConnection test class in the mof compiler.
It always appends new instances even if their paths are the same.
To test the change we would have to add a new subclass to MOFWBEMConnection that implemented a way for CreateInstance to return ALREADY_EXISTS.  Note that this …
> Fixes issue # 1890 - duplicate instance compile loses instance

- docs/changes.rst
- pywbem_mock/_mockmofwbemconnection.py
- pywbem_mock/_wbemconnection_mock.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
Fixes issue # 1852 where our implementation of MOFWBEMConnection allows multiple instances to be compiled with the same instance name.
This makes one significant change in mock in that it moves from using a list to manage the instances for each namespace to a dictionary and creates single points to access the instancesrepo for add, modify, get, and delete.
See commit for details.
> Fixes #1852: Fix issue with duplicate instances from Compiler

- .travis.yml
Rolls back PR #1904 into 0.15.0
> 0.15: Enabled coveralls on Travis for all event types and branches

- .travis.yml
- appveyor.yml
- dev-requirements.txt
- docs/changes.rst
- minimum-constraints.txt
- pywbem/cim_types.py
- setup.py
- tests/unittest/pywbem/test_cim_types.py
- tests/unittest/utils/validate.py
- tox.ini
This PR contains the content of PR #1914 as well as other changes to enable Python 3.8.
At this point, the Python 3.8 tests are enabled only for Travis. For Appveyor, the changes are also in ths PR, but commented out, because Appveyor does not yet have Python 3.8 support. However, I suggest to go forward with this PR, since Appveyor can be easily enabled by another change, once Python 3.8 supports gets added there in the future.
> Fixes #1913 and #1879: Added support for Python 3.8 (Appveyor still commented out)

- pywbem/tupletree.py
- tests/functiontest/conftest.py
- tests/functiontest/invalidresponseerror.yaml
For details, see commit message. Ready for review.
Note, I don't think that rollback to 0.15.0 is needed.
> Fixes #44: Added function testcases for invalid surrogates in HTTP response body

- docs/changes.rst
- pywbem/cim_operations.py
Rolls back PR #1922 into 0.15.0.
> 0.15: Clarified namespace/host are ignored when Result/AssocClass are CIMInstanceName

- docs/changes.rst
- tests/end2endtest/test_profile_generic.py
- tests/end2endtest/test_profile_snia_server.py
- tests/end2endtest/test_profile_snia_smis.py
- tests/end2endtest/utils/pytest_extensions.py
- tests/profiles/profiles.yml
For details, see the commit message. Ready for review.
I don't think this should to be rolled back to 0.15.
> Fixes #1554: Added profile version to end2end profile definitions

- docs/changes.rst
- pywbem/cim_operations.py
For details, see commit message. Ready for review.
> Fixes #1907: Clarified namespace/host are ignored when Result/AssocClass are CIMInstanceName

- docs/changes.rst
- pywbem/_nocasedict.py
- pywbem/cim_types.py
- tests/unittest/pywbem/test_nocasedict.py
> Fixes #1926: Removed ordering of NocaseDict, CIMInstanceName, CIMInstance, CIMClass

- docs/changes.rst
- docs/utilities.rst
- docs/wbemcli.help.txt
- tests/unittest/test_wbemcli.py
- wbemcli.py
This PR addresses the deprecation part of issue #1932 for 0.15.0.
> 0.15: Deprecated the wbemcli command.

- dev-requirements.txt
- docs/changes.rst
- minimum-constraints.txt
Rolls back PR #1947 into 0.15.0
> 0.15: Workaround for pywin32 issue on Appveyor python 2.7 32-bit

- docs/changes.rst
- mof_compiler
Rolls back PR #1943 to 0.15.0.
> 0.15: Add --log to mof_compiler options (#1943)

- docs/changes.rst
- pywbem_mock/_wbemconnection_mock.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
Comment mark for MOF was incorrect so the output could not be recompiled
without changes.  was #; changed to //
> Fixes #1951: pywbem_mock display_repository cmt mark.

- docs/changes.rst
- pywbem_mock/_wbemconnection_mock.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
Rolls back PR #1952 into 0.15.0.
> 0.15: Fixes #1951: pywbem_mock display_repository cmt mark.

- pywbem_mock/_wbemconnection_mock.py
- tests/unittest/pywbem_mock/conftest.py
- tests/unittest/pywbem_mock/test_complexassoc.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
See commit text for details.
NOTE: I added one piece of code to the tests that is disabled unless a flag is set.  This saves the request for each test as a pywbemcli command and puts the results in the file also.  I am using that to test against openpegasus with this complex association and compare results.
> Fixes #1917: Issues with mock assocs

- dev-requirements.txt
- docs/conf.py
- docs/index.rst
- docs/mof_compiler.help.txt
- minimum-constraints.txt
- rtd-requirements.txt
This pr incorporates the sphinx fulltoc extension into the pywbem documentation so that the full  top level table of contents always shows on the sidebar menu
It should be noted that apparently this extension does not support the
toctree maxdepth directive however.  In otherwords you see the level 3 section entries in the sidebar menu.
Per the github page, the support for this extension appears to be
minimal (i.e. no new commits in a year or so despite both issues and
prs.) There is one outstanding pr that was a first cut at fixing the
maxdepth issue but no comments exist for this pr.
**DISCUSSION:**
1. Are we worried about the question of supporting the maxdepth of the shinx toctree?  If so we will have to do something like fork that repo and patch it.
See …
> Fixes #1941: documentation full TOC

- docs/changes.rst
- tests/utils.py
> Fixes #1933: Fixed that local tests skipped MOF tests if mof*tab files did not exist

- docs/changes.rst
- pywbem_mock/_mockmofwbemconnection.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
Modifies the CreateInstance in pywbem_mock/_mockmofwbemconnection.py to:
1. Verify that all key properties from the class are in the instance.
We want to be sure all instances in the mock repository have complete
paths.
2. If the instance path or keybindings are not in the newinstance,
create the instance path and insert it into the instance.
3. Add tests specifically for this change.
> Fixes #1958: Mocker adds path to new instance on CreateInstance

- docs/changes.rst
- tests/utils.py
This PR rolls back PR #1961 into 0.15.0
> 0.15: Fixed that local tests skipped MOF tests if mof*tab files did not exist

- docs/changes.rst
- pywbem_mock/_mockmofwbemconnection.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
This PR rolls back PR #1962 into 0.15.0.
> 0.15: Fixes #1958: Mocker adds path to new instance on CreateInstance

- appveyor.yml
- tox.ini
This PR enabled Python 3.8 for native Windows to checkout whether it is now supported on Appveyor.
Python 3.7 and 3.8 for CygWin on Appveyor is still commented out.
> Fixes #1879: Enabled py38 for native Windows in Appveyor

- appveyor.yml
- tox.ini
Rolls back PR #1939 to 0.15.0.
> 0.15: Enabled py38 for native Windows in Appveyor

- appveyor.yml
- docs/changes.rst
Note that while this PR contains the fix, it does not test it on CygWin with Python 2.7, because that environment is not tested normally. It is tested though in the manual-ci-run branch. That branch has been rebased on this PR to pick up the fix. See there for test results.
> Fixes #1945: Fixed python2.7 command not found in CygWin in Appveyor

- appveyor.yml
- docs/changes.rst
This PR rolls back PR #1949 into 0.15.0.
> 0.15: Fixed python2.7 command not found in CygWin in Appveyor

- docs/changes.rst
- mof_compiler
- pywbem/mof_compiler.py
- tests/unittest/pywbem/test.mof
- tests/unittest/pywbem/test_mof_compiler.py
Fixed issue where mof_compiler does not write new instances to the implementation defined by the conn attribute.  It wasgetting from that repo but writing new class and instances to the cache defined by MOFWBEMConnection.
ANDY: This changes a basic perception of MOFCompiler class, the use of MOFWBEMConnection as the handle when the conn constructor parameter exists and is a WBEMConnection class or subclass.
This PR bypasses the the MOFWBEMConnection completely when conn is specified on MOF_Compiler by removing the line in MOFCompiler.__init__ that defines the handle as MOFWBEMConnection. Note that there is an alternative where we use this intermediate and then transfer all of the newly created instances to the conn repository if the compile is successful, i.e. make a single compile …
> Fixes #1956: mof_compiler does not send CreateInstance, CreateClass to conn

- docs/changes.rst
- mof_compiler
- pywbem/mof_compiler.py
- tests/unittest/pywbem/test.mof
- tests/unittest/pywbem/test_mof_compiler.py
Rolls back PR #1957 into 0.15.0.
> 0.15: Fixes #1956: mof_compiler does not send CreateInstance, CreateClass to conn (#1957)

- docs/changes.rst
- pywbem/mof_compiler.py
- tests/manualtest/run_mof_compiler_script.sh
- tests/unittest/pywbem/test_mof_compiler.py
Fixes issue with mof_compiler and rolback.  See commit for details
> Fixes #1158: mofcomp rollback of test.mof fails

- docs/changes.rst
- pywbem/mof_compiler.py
- tests/manualtest/run_mof_compiler_script.sh
- tests/unittest/pywbem/test_mof_compiler.py
Rolls back PR #1944 into 0.15.0.
> 0.15: Fixes #1158: mofcomp rollback of test.mof with mof_compiler fails

- dev-requirements.txt
- docs/changes.rst
- minimum-constraints.txt
- tests/unittest/pywbem/test_mof_compiler.py
- tests/unittest/pywbem/test_recorder.py
No need to roll this forward to master, because usage of unittest2 had alredy been removed earlier from master.
> 0.16: Fixes #2003: Removed usage of unittest2 except when on py26

- docs/changes.rst
- pywbem/mof_compiler.py
- tests/unittest/pywbem/test_mof_compiler.py
- tests/utils.py
Rolls back PR #2006 into 0.16.0.
> 0.16: Silenced MOFCompiler for verbose=False; Fixed moftab version check

- docs/changes.rst
- pywbem/mof_compiler.py
See commit message - Note that I fixed it differently than agreed.
> Fixes #1998: Fixed that the MOFCompiler can be created with handle=None

- docs/changes.rst
- pywbem/mof_compiler.py
Rolls back PR #2009 into 0.16.0.
> 0.16: Fixed that the MOFCompiler can be created with handle=None

- docs/changes.rst
- pywbem/mof_compiler.py
Rolls back PR #2011 into 0.16.0.
> 0.16: Fixed that MOF compiler did raise error when ModifyClass failed

- .travis.yml
- dev-requirements.txt
- minimum-constraints.txt
> 0.16: Enabled all Python 2.6 flavors on Travis for stable releases; fixed pkg versions

- docs/changes.rst
- docs/compiler.rst
- pywbem/mof_compiler.py
- pywbem_mock/_wbemconnection_mock.py
- tests/unittest/pywbem/test_mof_compiler.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
When reviewing, have a closer look at:
* Exception class structure (MOFCompileError and its derived classes)
* Disabling of error logging in compile methods of FakedWBEMConnection (see also issue #1997).
No rollback into 0.16 planned.
> Fixes #1235,#1997: Redesigned error handling in MOF compiler

- dev-requirements.txt
- docs/changes.rst
- minimum-constraints.txt
- tests/end2endtest/utils/server_definition_file.py
- tests/functiontest/conftest.py
Rolls back PR #2021 into 0.16.0.
> 0.16: Replaced yamlordereddictloader package with yamlloader

- docs/changes.rst
- pywbem/cim_http.py
- pywbem/cim_operations.py
Note that this PR does not need to be rolled forward into master. However, the clarification about the type of string that can be used for the `ca_certs` parameter of `WBEMConnection` has been applied to PR #2023.
> Fixes #2033: 0.16: Fixed handling of Unicode string in ca_certs parm of WBEMConnection on py2

- .travis.yml
- dev-requirements.txt
Rolls back PR #2045 into 0.16.0
> 0.16: Moved coveralls run back to Python 3.4

- docs/changes.rst
- docs/mocksupport.rst
- pywbem_mock/_resolvermixin.py
- pywbem_mock/_wbemconnection_mock.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
Completely removes the mode of operation called conn_lite,
the constructor attribute, tests that require conn_lite
and documentation from the code and documentation.
No other functional changes.
> Fixes #1959: Remove conn_lite mode from mocker

- pywbem/cim_xml.py
No rollback needed, as it only fixes the docstring.
> Fixes #2054: Added missing children in docstring of IRETURNVALUE() in cim_xml.py

- pywbem/cim_xml.py
No rollback needed, as it only fixes the docstring.
> Fixes #2055: Removed children in docstring of EXPPARAMVALUE() in cim_xml.py

- dev-requirements.txt
- requirements.txt
- rtd-requirements.txt
> Fixes #2071: Pinned PyYAML to <5.3 on py34; simplified rtd-requirements.txt

- dev-requirements.txt
- requirements.txt
- rtd-requirements.txt
Rolls back PR #2072 to 0.16.0.
> 0.16: Pinned PyYAML to <5.3 on py34; simplified rtd-requirements.txt

- README.rst
- README_PYPI.rst
- docs/changes.rst
- pywbem/_version.py
The fix for the removal of Python 3.4 support in PyYAML 5.3 should be released, otherwise pywbem users have a show stopper issue on Python 3.4.
This motivates the release of pywbem 0.16.0 which contains that fix.
> Release 0.16.0

- appveyor.yml
This PR removes the mitigation for installing the make package using chocolatey on Appveyor back to what it was before (i.e. using the default version of make).
> Finally Fixes #2094: Removed mitigation for installing make using choco

- dev-requirements.txt
- tests/unittest/pywbem/test_perf_equality.py
This is a first stage of addressing issue #2041, in which a unittest module for performance measurements of the equality test for CIM objects is added, so that the original performance can be determined.
> Added performance tests for CIM object equality test

- pywbem/_utils.py
- pywbem/cim_obj.py
- pywbem/cim_types.py
- tests/unittest/pywbem/test_cim_obj.py
- tests/unittest/pywbem/test_perf_equality.py
This is the second stage of addressing issue #2041, in which the actual performance improvement gets implemented.
Original equality performance:
* CIMInstanceName with two keybindings, last one different: 14.077 us (stddev 5.2% in 100 runs with 14 outliers)
* CIMClass with 10 properties, last one different: 197.023 us (stddev 3.0% in 100 runs with 11 outliers)
Improved equality performance:
* CIMInstanceName with two keybindings, last one different: 12.952 us (stddev 4.6% in 100 runs with 11 outliers)
* CIMClass with 10 properties, last one different: 173.040 us (stddev 3.5% in 100 runs with 7 outliers)
As a result, this change is not a significant performance improvement, but it did clean up the code and eliminated the old comparator-based logic.
**Update** related to Karl's suggestion …
> Fixes #2041: Improved performance of and cleaned up equality test for CIM objects

- docs/changes.rst
- pywbem/_listener.py
It would be good to test the listener using HTTPS.
> Fixes #2002: Switched to use SSLContext in WBEMListener

- .gitignore
- docs/changes.rst
- makefile
- pywbem/__init__.py
- pywbem/_cim_constants.py
- pywbem/_cim_http.py
- pywbem/_cim_obj.py
- pywbem/_cim_operations.py
- pywbem/_cim_types.py
- pywbem/_cim_xml.py
- pywbem/_exceptions.py
- pywbem/_listener.py
- pywbem/_mof_compiler.py
- pywbem/_recorder.py
- pywbem/_server.py
- pywbem/_subscription_manager.py
- pywbem/_tupleparse.py
- pywbem/_tupletree.py
- pywbem/_utils.py
- pywbem/_valuemapping.py
- pywbem/_warnings.py
Note this rollback of PR #2105 adds compatibility to the old sub-namespaces and therefore does not change any usages of the pywbem sub-modules e.g. in tests or in the docs.
> Made all pywbem sub-namespaces private, except config

- docs/mocksupport.rst
- minimum-constraints.txt
- pywbem_mock/__init__.py
- pywbem_mock/_baserepository.py
- pywbem_mock/_inmemoryrepository.py
- pywbem_mock/_mockmofwbemconnection.py
- pywbem_mock/_resolvermixin.py
- pywbem_mock/_utils.py
- pywbem_mock/_wbemconnection_mock.py
- requirements.txt
- tests/unittest/pywbem/test_mof_compiler.py
- tests/unittest/pywbem/test_wbemserverclass.py
- tests/unittest/pywbem_mock/test_inmemory_repository.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
- tests/unittest/utils/wbemserver_mock.py
See commit message for details:
1. Defines the abstract RepositoryInterface class as discussed in the presentation (by renaming and changing the current BaseRepositoryConnectionclass)
2. implements the in memory repository based on that RepositoryInterface class.
All communication with the repository is now through the InMemoryRepository interface.
NOTE: This PR, Part 2, leaves the code that was originally in MOFWBEMConnection temporarily in place except that it communicates with the inmemoryrepository.  I am in the process of moving the mof_compiler  interface to the repository code (similar to MOFWBEMconnection.py) but derived from the mof_compiler.BaseRepositoryConnection rather than MOFWBEMConnection.
It is 3 separate commits with the second two representing Andy's comments (Fixing …
> Part 2 of pywbem_mock refactor. This pr separates repository from _wbemconnection

- .travis.yml
- dev-requirements.txt
- makefile
- minimum-constraints.txt
- tests/leaktest/test_leaks_cim_obj.py
- tests/leaktest/test_leaks_cim_xml.py
- tests/leaktest/test_leaks_dict.py
- tests/leaktest/test_leaks_elementtree.py
- tests/leaktest/test_leaks_minidom.py
- tests/leaktest/test_leaks_statistics.py
- tests/utils.py
- tox.ini
See commit messages for details.
Invoke `make help` to understand how to run the memory leak tests, and look at the description of the new `leaktest` target and of the new `YAGOT*` env vars.
A complete `YAGOT=1 make test` runs for about 4h on my Mac, where without leak checking it takes about 4min. This seems to be caused by the many runs of the Python garbage collector that happen. Note that the `make leaktest` which runs just the specific leak tests is very fast.
Some tests that fail due to leaks have been excluded as XFAIL, and they can be run with: `TESTOPTS='--runxfail' make leaktest`.
**Discussion points (1): DONE**
* The implemented approach can be enabled for the pytest testcases, but the problem are the garbage objects pytest leaves in several situations (e.g. skipped testcase, …
> Fixes #805: Added support for garbage checking

- dev-requirements.txt
- makefile
- minimum-constraints.txt
- rtd-requirements.txt
Roll back of PR #2127 into 0.5.1, plus disabling flake8 on python 2.6
> 0.17: Updated minimum package versions for py34/py38

- docs/changes.rst
- pywbem_mock/_wbemconnection_mock.py
- tests/unittest/pywbem/test_recorder.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
Add a property to Fake_WBEMConnection to forbid_pull which when set to
False (either in the __init__ or a property setter) forces all call to
the Open... request operations to return CIM_ERR_NOT_SUPPORTED.
Adds a test to validate property is set correctly and the operations
react correctly.
I set rollback because I would like to make that test part of pywbemcli.
ANDY: Forget discussion of the forbid word.  Changed the __init__ option to disallow-pull-operations. In case the question comes up, I do not want to merge the use_pull and disable_pull_operations (one is the client, the other is the server) and I specifically want to have a client that uses pull with server mock that disallows it to test client ability to handle error response if server mock cannot handle pulls.
> Fixes #2126 Add option to disable pull operations to mocker

- dev-requirements.txt
- docs/changes.rst
Rolls back PR #2141 into 0.17.
> 0.17: Pinned dparse to <0.5.0 on Python 2.7 due to an issue

- dev-requirements.txt
- docs/changes.rst
> Fixes #2139: Pinned dparse to <0.5.0 on Python 2.7 due to an issue

- docs/changes.rst
- minimum-constraints.txt
Rolls back PR #2169 into 0.17.1.
> 0.17: Increased min version of setuptools on py37

- MANIFEST.in
- docs/changes.rst
- makefile
Note, this fixes the part of issue #2173 where the pywbem_os_setup.* scripts were missing from the source distribution archive. The failure with the openssl/err.h file could not be reproduced.
> Fixes #2173: Added the pywbem_os_setup.* scripts to the source dist archive

- docs/changes.rst
- pywbem/_server.py
- tests/unittest/pywbem/test_wbemserverclass.py
Rolls back PR #2189 into 0.17.2.
> 0.17: Fixed raise error for invalid reference_direction in WBEMServer.get_central_instances()

- docs/changes.rst
- pywbem/_listener.py
Rolls back PR #2191 into 0.17.2.
> 0.17: Fixed raise error for missing ports in WBEMListener.__init__()

- docs/changes.rst
- pywbem/_listener.py
- tests/unittest/pywbem/test_indicationlistener.py
**Note: This PR is on top of #2191 because it needs that fix.**
No rollback into 0.17 for the conversion to pytest.
> Fixes #2179: Converted listener tests from unittest to pytest; added tests

- pywbem/_utils.py
- tests/end2endtest/utils/pytest_extensions.py
- tests/end2endtest/utils/utils.py
- tests/unittest/pywbem/test_indicationlistener.py
This PR does not address Pylint issues in pywbem_mock because that is currently restructured.
Current Pylint results after this PR (with Pylint 2.4.4 on Python 3.8):
Note that most of them are related to pywbem_mock.
```
+--------------------------+------------+
|message id                |occurrences |
+==========================+============+
|fixme                     |182         |
+--------------------------+------------+
|redefined-builtin         |11          |
+--------------------------+------------+
|using-constant-test       |8           |
+--------------------------+------------+
|unused-argument           |7           |
+--------------------------+------------+
|try-except-raise          |3           |
+--------------------------+------------+
|protected-access          |3 …
```
> Fixed Pylint issues except for pywbem_mock

- pywbem_mock/__init__.py
- pywbem_mock/_baseprovider.py
- pywbem_mock/_defaultinstanceprovider.py
- pywbem_mock/_mainprovider.py
- pywbem_mock/_resolvermixin.py
- pywbem_mock/_wbemconnection_mock.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
WIP - separation complete and the provider registration defined.  Tests very limited.
1. Create a new class DefaultInstanceProvider and move CreateInstance
and DeleteInstance from MainProvider to this class.  The methods in this
class will be allowed to have user defined providers.  Also creats a class
ProviderDispatcher which provides request argument validation and routes the
request to the default provider unless a user provider is defined
2. Create the ProviderDispatcher class in DefaultInstanceProvider that
does the routing to the default provider for the method or to a user
defined provider and does standard parameter validation so that the default
or user provider do not have to do any input parameter validation.
3. Create BaseProvider which is the top level of the provider class …
> [WIP] Issue #2062: Create the DefaultInstanceProvider Class

- pywbem_mock/_baseprovider.py
- pywbem_mock/_defaultinstanceprovider.py
- pywbem_mock/_wbemconnection_mock.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
Note that this does not change the name of the file _defaultinstanceprovider.py.  That is for later.
Depends on pr # 2186
> Issue #2062 - Change name from DefaultInstanceProvider to InstanceWriteProvider

- pywbem_mock/_baseprovider.py
- pywbem_mock/_baserepository.py
- pywbem_mock/_defaultinstanceprovider.py
- pywbem_mock/_inmemoryrepository.py
- pywbem_mock/_mainprovider.py
- pywbem_mock/_mockmofwbemconnection.py
- pywbem_mock/_resolvermixin.py
- tests/unittest/pywbem_mock/test_inmemory_repository.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
Changes the method name in BaseObjectStore for exists(...) to
object_exists(...).  This was because we both confused the behavior to
mean that the object_store exists rather than the object itself.
Thus:
if not class_store.exists(classname)
becomes:
if not class_store.object_exists(classname)
> Modify mock code to change method name exists to object_exists

- docs/changes.rst
- pywbem/_mof_compiler.py
- tests/unittest/pywbem/test_mof_compiler.py
Modified the compiler CreateInstance path handling.
1. Theinstance alias is now created with the return from the
CreateInstance and not in the compiler p_instanceDeclaration.
2. The instance path is created in the MOFWBEMConnection CreateInstance
method rather than in the compiler instanceDeclaration method.  Implementations of BaseRepositoryConnection must create the instance path for newly created instances before they are installed in a cim repository.
3. Modified one of the mof_compiler tests to test that the path is
created.
> Fixes #1911: Instance alias use in compiler

- pywbem_mock/_defaultinstanceprovider.py
PR #2220 was merged by mistake (it still contained a temp commit, and it was on top of an old version of PR #2215). I undid that merge by manually setting back the master branch to before that PR.
This PR here contains the commit that PR #2220 was supposed to contain, and basically redoes what it was supposed to do.
> Fixed dictionary changed size during iteration on pypy (redo)

- pywbem/_mof_compiler.py
- pywbem_mock/_mainprovider.py
- pywbem_mock/_mockmofwbemconnection.py
- pywbem_mock/_wbemconnection_mock.py
- tests/unittest/pywbem/test_subscriptionmanager.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
Refactored the code in _MockMOFWBEMConnection to add things and get them from the cim repository through the WBEMConnection client interfaces (before we were communicating directly through the cim repository interface).
Waiting commit of pr #2215
> Fixes #2062: part4 compiler - refactor compiler interface in mocker

- pywbem_mock/_baseprovider.py
- pywbem_mock/_defaultinstanceprovider.py
- pywbem_mock/_inmemoryrepository.py
- pywbem_mock/_mockmofwbemconnection.py
- tests/unittest/pywbem_mock/test_inmemory_repository.py
Since the .copy method for CIMClass and CIMInstance does not do a deep
copy and we want to insure that we the objects in the dictionary are
truly different than the ones in the input and maintained in the
repository we changed to use deepcopy to copy all objects before they
are placed into the dictionary and for all objects that are extracted
from the dictionary with the copy property.
Note that we were doing extraneous copies in _baserepository and so
removed them.
Adds tests for cim repository to assure that the objects are copied
on create, modify, get with copy and iter_value with copy.
> Regularize use of deepcopy for objects xfrd to and from repository

- docs/changes.rst
- pywbem_mock/_dmtf_cim_schema.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
Fixes issue in the DMTFCIMSchema class where the schema builder method
was building the cim schema pragma in a different order than the
original cim schema pragma
Adds tests also
> Fixes issue #2223 - DMTFCIMSchema build order

- docs/changes.rst
- pywbem_mock/_dmtf_cim_schema.py
- pywbem_mock/_mainprovider.py
- pywbem_mock/_wbemconnection_mock.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
- tests/unittest/utils/wbemserver_mock.py
Currently in 3 commits, 1. original, 2. fixes to comments, 3. modify we use schema_mof_pragma_file 
as the input parameter to compile_schema_classes.
The original method for compiling parts of a DMTF schema was
compile_dmtf_schema() which compiled a specific set of classes from the
DMTF schema defined by a DMTF schema version number and the directory
where a local version of that DMTF was supposed to be located.
This change separates the compile of classes of the schema from the process
of downloading and installing the schema.
Thus, originally, the FakedWBEMConnection method to create a mock
repository with some classes from the schema was:
conn.compile_dmtf_schema(DMTF_TEST_SCHEMA_VER, TESTSUITE_SCHEMA_DIR,
class_names=[CIM_Namespace,'CIM_ObjectManager'],
verbose=True)
the separation …
> Partly fixes #2062: Implement new schema compile method

- docs/changes.rst
- docs/mocksupport.rst
- pywbem_mock/__init__.py
- pywbem_mock/_baseprovider.py
- pywbem_mock/_defaultinstanceprovider.py
- pywbem_mock/_dmtf_cim_schema.py
- pywbem_mock/_mainprovider.py
- pywbem_mock/_namespaceprovider.py
- pywbem_mock/_wbemconnection_mock.py
- pywbem_mock/config.py
- tests/unittest/pywbem/test_wbemserverclass.py
- tests/unittest/pywbem_mock/test_system_providers.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
- tests/unittest/utils/wbemserver_mock.py
Adds the first system provider, the namespace provider. This includes the implementation of the user defined provider, and  a method to FakedWBEMConnection, install_privileged_providers() that serves as the interface to install providers that are considered privileged to be installed.
TODO 
Figure out where we put the initialization code for user-defined providers to a) make insitialization simple, b) allow the different user providers to accomplish all if the initialization tasks in a common way.
Initialization tasks:
1.  Install user classes required by the provider
2. Install schema classes required by the provider (This and 1 may not be mutually exclusive)
3. Allow the provider to do any other setup (ex. Namespace provider would insure that there is an instance of CIM_Namespace for …
> Partly fixes #2062: add namespace provider

- pywbem_mock/__init__.py
- pywbem_mock/_defaultinstanceprovider.py
- pywbem_mock/_defaultmethodprovider.py
- pywbem_mock/_providerdispatcher.py
- pywbem_mock/_wbemconnection_mock.py
1. Create new _defaultmethodprovider.py
2. Create new file _providerdispatcher.py
3. Modify imports, etc. to use the new files.
I kept the name defaultinstanceprovider because I am uncomfortable
creating separate providers in the future for instancewrite and
instanceread.  DISCUSSION.
> Fixes #2231: Rename the provider files and separate classes

- tests/unittest/pywbem_mock/test_inmemory_repository.py
- tests/unittest/pywbem_mock/test_system_providers.py
Some of the mocker testcases did not use the concept of dynamically importing pywbem or pywbem_mock.
> Fixed pywbem,pywbem_mock imports into mocker testcases

- pywbem_mock/_instancewriteprovider.py
- pywbem_mock/_mainprovider.py
- pywbem_mock/_providerdispatcher.py
- tests/unittest/pywbem/test_mof_compiler.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
Fixes 3 issues found in testing with pywbemcli.
1. a code error in MainProvider  Open and pull processing.  We had some parameters out of order in a local function call.  Since this was changes made in Pywbem 1.0.0, no back port necessary.  
In the process, I found that we did not have a test for what caused this issue so added two new tests for Open/Pull
2. We were inserting extra properties in instances.  My coding error. Removed that code.
3. Restored use of CIM_ERR_NOT_FOUND in place of CIM_ERR_NOT_AVAILABLE when method not found.  This is correct since NOT_FOUND is higher priority than NOT_AVAILABLE. I misread the spec when review code during the refactor.
pywbemcli now passes tests (with a number of changes to its tests) against pywbem 1.0.0. I have not submitted that PR yet.
> Correct issues in pywbem_mock with Open/Pull

- pywbem_mock/_methodprovider.py
- pywbem_mock/_providerdispatcher.py
- pywbem_mock/_wbemconnection_mock.py
**NOTE: Expect manual changes before committing because PR #2251 moves the same code that we are changing here to a new module.**
This pr generates the following changes In response to the questions we made the following changes:
1. Move the definition of the default InstanceWriteProvider and
MethodProvider to the ProviderDispatcher. This is done with a property
for each that only constructs the default provider when the property is used.
2. Remove the constructor for the default providers from _wbemconnection
so the only parameter for the construction of ProviderDispatcher is the
CIM repository.
3. Change the default MethodProvider behavior to actually call the
MethodProvider where that provider generates the required exception.
This maintains the same pattern as the other operations in …
> Fixes #2244: Review Provider Manager

- docs/changes.rst
- pywbem_mock/_mainprovider.py
- pywbem_mock/config.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
Adds config variables to define if the instance request
IncludeQualifiers and IncludeClassOrigin are honored in the pywbem_mock
GetInstance and EnumerateInstance response generators since these
request parameters have been deprecated in DMTF 0200 with the proposed
solution being to not return either qualifiers or class origin.
> [WIP] Fixes #2065: Instance iq and ico variations

- pywbem_mock/_methodprovider.py
- pywbem_mock/_wbemconnection_mock.py
Corrects issue in pywbem_mock that was causing failures in tests with pywbemcli and pywbem version 1.0.0.
We were incorrectly processing the InvokeMethod response
> Correct issues with InvokeMethod response handling

- README.rst
- docs/appendix.rst
- docs/index.rst
- docs/intro.rst
- docs/mockwbemserver.rst
- pywbem_mock/_instancewriteprovider.py
- pywbem_mock/_methodprovider.py
- pywbem_mock/_wbemconnection_mock.py
Refactor the documentation section on Mock Support to define writing a
user provider and give examples.
> Fixes #2232: user-defined provider documentation

- docs/mockwbemserver.rst
- pywbem_mock/_inmemoryrepository.py
- pywbem_mock/_instancewriteprovider.py
- pywbem_mock/_providerdispatcher.py
- pywbem_mock/_providerregistry.py
- pywbem_mock/_wbemconnection_mock.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
Changes name of provider from 'instance" to "instance-write"
Based on pr #2232, mock documentation update because the name of the provider type changed in the documentation also
> Partly fixes #2261: provider type names

- pywbem_mock/_instancewriteprovider.py
- pywbem_mock/_methodprovider.py
- pywbem_mock/_providerregistry.py
Defines the post_register_setup method in the default providers
(MethodProvider and InstanceWriteProvider so that:
1. There is a model to work from when provider writers write their
providers subclassing MethodProvider and InstanceWriteProvider have a
defined API to override.
2. Any exception upon the execution of this method when the provider is
registered is considered an error whereas initially attribute error was
ignored because the method might not exist in the subclass.
> Partly fixes issue #2261, define post_register_setup in defaults

- docs/changes.rst
- pywbem/_cim_obj.py
- tests/unittest/pywbem/test_cim_obj.py
> Fixes #2264: Changed format 'standard' of CIMInstanceName.to_wbem_uri() to sort the   keys

- docs/changes.rst
- docs/mockwbemserver.rst
- pywbem_mock/_methodprovider.py
- pywbem_mock/_wbemconnection_mock.py
Broke into two sections, one for summary of the incompatibilities and
the second for details
Fixed issue in _methodprovider.py with misnamed doc label.
DISCUSSION: This set of changes is so big it might be better to add another layer of subsctions rather than just the bold headings
> Fixes #2267: Refactor changes.rst incompatibilities section

- appveyor.yml
- tox.ini
> Appveyor/tox: Fixed 32-bit CygWin envs; enabled py34 on native Windows

- appveyor.yml
- dev-requirements.txt
- minimum-constraints.txt
- tox.ini
> Appveyor: Cleaned up non-support of py34 on native Windows and 32-bit CygWin envs

- appveyor.yml
- dev-requirements.txt
- minimum-constraints.txt
- tox.ini
Rolls back PRs #2276 and #2280 into 0.17.
> 0.17: Appveyor: Cleaned up non-support of py34 on native Windows and 32-bit CygWin envs

- docs/mockwbemserver.rst
- pywbem_mock/_dmtf_cim_schema.py
- pywbem_mock/_wbemconnection_mock.py
- tests/unittest/pywbem/test_mof_compiler.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
This eliminates the use in pywbem code and pywbem tests of the property
`schema_mof_file` and the method `compile__dmtf_schema()` in favor of the
replacements.  
This pr DOES NOT remove the deprecated entities.
> Eliminate use of deprecated methods and properties in the mocker

- tests/unittest/pywbem/test_subscriptionmanager.py
This is one leftover that I did not catch when reviewing PR #2283.
> Replaced use of deprecated compile_dmtf_schema() in test_subscription_manager.py

- docs/changes.rst
NOTE: Since you took this issue, consider this what was the easiest way
document changes, etc. since it is formatted, complete and easy to
compare with original (sort of).  Feel free to use or just use as
input.
My proposed changes to changes.rst to remove some of the duplication and
extend explanations.
1. Shortened the summary section to one-liners essentially.
2. Added more explanation to the details section as to why,
alternativesm,  etc.
> Fixes #2294: Duplications in changes.rst incompatibilities

- docs/mockwbemserver.rst
- pywbem_mock/_baseprovider.py
- pywbem_mock/_instancewriteprovider.py
- pywbem_mock/_mainprovider.py
- pywbem_mock/_namespaceprovider.py
- pywbem_mock/_providerdispatcher.py
- pywbem_mock/_wbemconnection_mock.py
- tests/unittest/pywbem/test_mof_compiler.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
Refactor issues documented in issue # 2291 as follows:
* cimrepository attribute: Change to define as a property  in
BaseProvider with documentation
* find_instance() method: Changed method name to get_bare_instance()
* find_interop_namespace() method: No change.  See issue for comments.
* get_instance_store() method and get_qualifier_store method: Removed
them both and modified tests and examples to show difference.
> Fixes #2291: refactor base provider

- dev-requirements.txt
- docs/changes.rst
- minimum-constraints.txt
- pywbem/_valuemapping.py
- tests/unittest/pywbem/test_valuemapping.py
This rolls back PR #2304 into 0.17.3.
An additional commit was needed to address issues specific to Python 2.6.
Note that the exception indicating a non-integer type of the CIM element is still TypeError, consistent with pre-1.0.0. In 1.0.0, this gets changed to ModelError.
> 0.17: Improved support for array-typed elements in ValueMapping

- docs/changes.rst
- pywbem/_valuemapping.py
- tests/unittest/pywbem/test_valuemapping.py
Note that support for array-typed elements was already there, but the tovalues() method needed to be improved to accept a list/tuple of values.
> Fixes #2304: Improved support for array-typed elements in ValueMapping

- docs/changes.rst
- pywbem_mock/_mainprovider.py
Fixes issue where we were repeatedly copying from the repo rather than
just itering causing very large slowdown of enumerate classes mock
operation.
NOTE: This should have an entry in changes.rst for b2 but this commit is to master.
fixes issue #2314, mock enumerate classes --di very slow with large sets of classes.
Marked rollback for rollback to beta2
Marked priority because it makes it impossible to use the mocker with more than about 150 classes because of the speed of EnumerateClasses.
NOTE: I did not include a specific test. I will add one before the 1.0.0 release but that will take more time and the fix works with manual tests.
> Fixes #2314: slow performance for mock enumerate classes

- docs/changes.rst
- pywbem_mock/_dmtf_cim_schema.py
- pywbem_mock/_wbemconnection_mock.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
This removes the `compile_dmtf_schema()` method and `schema_mof_file` property that were deprecated in 1.0.0b1.
Please review for inclusion into 1.0.0 final (i.e. not into potential further beta versions).
If approved, the merging of this PR needs to wait until we are sure that there are no more beta versions before 1.0.0 final.
> Fixes #2284: Removed deprecated compile_dmtf_schema() and schema_mof_file

- docs/changes.rst
- pywbem_mock/_wbemconnection_mock.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
Fixes issue #1240 - cvt test_wbemconnection.py TODOS to issues, fixes some, and removes the obsolete ones
NOTE: This PR is not critical to beta b3
Created a new issue #2327 that documents the TODOs that are still
current in this test module as 18 items to be worked on to complete the
tests of pywbem_mock.
This removes a number of obsolete TODOs and converts the others to
references to Issue #2327.  From there I can work them off.
Fixes one issue in _wbemconnection.py and clarifies one other TODO
1. Cleaned up code section that was marked with TODO about compiling
multiple files to actually do this correctly by building the search_path
for each file in the input files.
2. Remove one TODO since I confirmed that we are doing all the correct
tests
> Fixes #1240: Clean TODOs in tests_wbemconnection.py and _wbemconnection.py

- docs/changes.rst
- docs/mockwbemserver.rst
- pywbem_mock/_inmemoryrepository.py
- pywbem_mock/_instancewriteprovider.py
- pywbem_mock/_methodprovider.py
- pywbem_mock/_wbemconnection_mock.py
See commit message. The provider examples are now consistent with PR #2329.
It is probably best to review this PR by building the documentation and looking at section "Mock WBEM server".
> Fixes #2290: Reworked docs on mock server, specifically user-defined providers

- .travis.yml
The Travis runs have been verified with py3 on macOS: https://travis-ci.org/github/pywbem/pywbem/builds/707445552
> Fixes #2333:  Fixed py38 upgrade issue on macOS on Travis 

- docs/changes.rst
- minimum-constraints.txt
- test-requirements.txt
Travis run with py38 on macos enabled: https://travis-ci.org/github/pywbem/pywbem/builds/707632980
> Fixes #2337: On Python 3.8, upgraded the minimum version of lxml

- docs/changes.rst
- pywbem/_mof_compiler.py
- pywbem_mock/_providerdispatcher.py
- tests/unittest/pywbem/test_mof_compiler.py
- tests/unittest/pywbem/testmofs/test_instance.mof
WARNING: This removes code in providerdispatcher that compares cls.embedded_object with instance.embedded_object.
LIMITATIONS;
1. Does not handle embedded class although that is only a few lines of code now.
2. Does not have test for recursive embedded.
Fixes #2277: MOF compiler ignores EmbeddedObject instance property.
The DMTF definition of the value of instance property MOF is one
or more strings containing the MOF that would be compiled into
CIM instances.
Originally the compiler simply passed the string through the compiler so
what went into a repository was simply a string for the value of the property.
The MOF compiler was extended to compile properties with the
EmbeddedInstance or EmbeddedObject qualifiers into CIMInstance
object(s).
The enhanced compiler creates CIMInstance …
> Fixes #2277:  MOF compiler ignores EmbeddedObject instance property

- tests/unittest/pywbem/test_mof_compiler.py
The illegal character reported was because when defined as a python string, the
\n character in the MOF must have either double  back-slash or be a python raw string.
Adds tests in test_mof_compiler for these characteristics and also adds
other tests for trying to compile embedded class and qualifier
declaration both of which are illegal.
> Fixes #2330: mof illegal char message in embedd mof Issue with test code

- docs/appendix.rst
- makefile
- minimum-constraints.txt
- pywbem_mock/_baseprovider.py
- pywbem_mock/_baserepository.py
- pywbem_mock/_inmemoryrepository.py
- pywbem_mock/_mainprovider.py
- pywbem_mock/_namespaceprovider.py
- pywbem_mock/_wbemconnection_mock.py
- requirements.txt
- setup.py
Ready to be reviewed and tried out. The test fails only because of Pylint enforcement that is now active.
Update: The pylint issue has been introduced by this PR and has been fixed in the latest update.
This PR fixes issue #2253 only partly, because it installs the new nocaselist package from a branch of its repo, and it had to disable the installtest which does not work with dependency links. This needs to be changed in a subsequent PR to be installed from Pypi, once released.
> Partly fixes #2253: Changed lists and dicts in mock support to use NocaseList

- docs/changes.rst
- pywbem/_cim_obj.py
Rolls back PR #2374 into 0.17.5.
> 0.17: Fixed docs of CIMInstanceName.keys(), values(), items() for py3

- dev-requirements.txt
Rolls back PR #2377 into 0.17.5.
> 0.17: Excluded pytest 6.0.0 from test dependencies to fix not-callable issue

- test-requirements.txt
> Pinned pytest to <6.0 on py35/36/37 to avoid pylint issue 'abstract-method'

- docs/changes.rst
- pywbem/_cim_obj.py
**DISCUSSION**:
* It is quite unsatisfactory to have CIMInstance.values/items() return lists. This is inconsistent, prevents deprecation of its iter..() methods, and does not provide a good path forward.
* It is equally unsatisfactory that NocaseDict.keys/values/items() returns lists on py2, even though it has dict view classes it could return also on py2.
Both could be addressed by having these methods return dict view objects on all Python versions. For NocaseDict, the price would be incompatibility with the built-in dict on py2 e.g. in cases where a dict is modified while iterating over it.
> Deprecated the iter..() methods of CIMInstanceName

- docs/changes.rst
- pywbem/_cim_obj.py
> CIMInstance: values/items() returns dict view on py3 and deprecated iter..()

- docs/changes.rst
- pywbem_os_setup.sh
Rolls back PR #2395 into 0.17.5.
> 0.17: Fixed test install issue on CygWin due to missing libffi-devel

- docs/changes.rst
- pywbem/_version.py
Please approve the release of pywbem 1.0.0 (final).
One consideration might be whether we want to release nocasedict 1.0.0 before, but that is not a hard requirement.
> Release 1.0.0

- docs/changes.rst
- pywbem/_version.py
Please approve the release of pywbem 0.17.5, and that this is the last 0.17 version, which means that I suggest not fixing issue #2383 on 0.17 anymore.
> Release 0.17.5 as the last 0.17.x release

- docs/changes.rst
- pywbem/_statistics.py
- pywbem_mock/_wbemconnection_mock.py
- tests/unittest/pywbem/test_statistics.py
This is a first step to address the "make mock faster" issue #2365. It provides time statistics for the mock support, in order to find out where the time is spent.
There are no testcases for it yet, but it is ready to be tried out.
Usage:
```
conn.statistics.enabled = True  # or stats_enabled=True in ctor
conn.compile_schema_classes(...)
conn.compile_mof_string(...)
conn.compile_mof_file(...)
conn.add_cimobjects(...)
conn.EnumerateInstances(...) # and all other operations
print(conn.statistics.formatted())  # print formatted time statistics
stats = conn.statistics.snapshot()  # get a snapshot of the time statistics as a list of tuple(name, stats)
```
> Added time statistics support to pywbem_mock

- docs/changes.rst
- minimum-constraints.txt
- pywbem_mock/_baserepository.py
- pywbem_mock/_inmemoryrepository.py
- requirements.txt
Removes the use of and install of thePython custom-inherit package in pywbem since it is causing problems for at least one of the OS developer/packaging organizations that use pywbem and  and which must build their own versions of packages into their releases for all dependencies used by apps such as pywbem that they package into OS  releases.
> Fixes issue #2436, Remove package custom-inherit from pywbem

- pywbem/_cim_operations.py
- tests/unittest/pywbem/test_cim_operations.py
- tests/unittest/pywbem/test_logging.py
Adds tests to:
1. test cim operation request failures. This should now test
about all of the request validation failures we can test.
2. extend some of the other tests in test_cim_operations.py
3. Removes an orphan function from _cim_operations.py
> Add tests to increase test coverage for WBEMConnection class

- docs/changes.rst
- pywbem_mock/_mainprovider.py
- pywbem_mock/_resolvermixin.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
Added and extended tests for pywbem_mock documented in issue #2327 and
where the coverage report showed untested code.
Remove unused method _make_tuple in _mainprovider.py
NOTE: This leaves 3 of the items from issue # 2327 in the code open and two other tests (the original namespace tests) marked skipped for the moment.  Otherwise all tests extended per iseu # 2327 and the comments removed .
> Fixes #2327-incomplete mock tests

- pywbem_mock/_mainprovider.py
- pywbem_mock/_providerdispatcher.py
- pywbem_mock/_resolvermixin.py
- pywbem_mock/_wbemconnection_mock.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
Adds a number of tests to test_wbemconnection.py, removes some orphan methods, and fixes one issue in a test in _resolvermixin where a test for error in qualifier decl scope incorrect on CreateClass was not accomplishing anything.
Sadly this is still at 90% coverage.
This is partial response to issue #2353 but by itself should not close that issue
> Add tests to pywbem_mock; remove orphan code

- docs/changes.rst
- pywbem_mock/_resolvermixin.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
The test in the class resolver was extended to correctly catch errors
where the qualifier on a class creating has a scope that does not match
the qualifier declaration.
Also added tests for some other cases where the coverage showed we were
not executing code.
> Fixes issue #2451- Mock CreateClass incomplete test for qualifiers

- pywbem_mock/_mainprovider.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
This pr adds a more detailed test of the internal _get_instance to test
for local_only, (calling from the request operations forces this to a
default) and extends other verifications in this test.
It also modifies the instance naming on the tst_instances and
tst_instances_mof fixture to produce the same instances so that either
can be used in tests with the same result.
NOTE: It corrects one issue in that we were deleting from the property
list without making the input a list.
> Add more tests for pywbem_mock

- docs/changes.rst
- pywbem/_mof_compiler.py
- pywbem_mock/_mainprovider.py
- pywbem_mock/_mockmofwbemconnection.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
The CreateClass _mockmofwbemconnection is used by the compiler .py for
existence of class dependencies (reference classes and embeddedobject
classes). However, the CreateClass in _mainprovider (direct user
call to create class does not validate dependent classes existence.
We might have pulled these together into a single function except that
there is a core difference between the two in that a direct user does
not have to maintain the local class cach used by other methods in
_mockmofwbemconnection.
This pr adds these validity tests to MainProvider.CreateClass for existence of
dependent classes.
At the same time we noted in the DMTF specification that it is allowed
for the EmbeddedObject value to be None which the code in the MOF
compiler does not do.  That test was added.
Finally, we …
> Fixes issue #2455 Add validity test to pywbem_mock CreateClass

- tests/unittest/pywbem_mock/test_complexassoc.py
This covers issue where if pdb++ which is supposed to be call compatible
with pdb is installed, a pylint error occurs on every use of set_trace()
because pdb++ dynamically builds this method
> Add pylint comment to lines with pdb.set_trace()

- docs/changes.rst
- pywbem/_mof_compiler.py
- pywbem_mock/_resolvermixin.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
The mof compiler failed with an assert if a class compile had
dependencies that were not in the repository or were invalid so the
dependency resolution failed.   While this might be logical for a local
compile, it is an issue when the compiler is part of another application.
Changed to use MOFDependencyError and also show the originating
exception since that may present more information about the failure.
Added tests for this issue to:
tests/unittest/pywbem_mock/test_wbemconnection.py
Note: We also modified one of the Exception messages in
pywbem_mock/_resolver to clarify it.
> Fixes #2458: Assert from mof_compiler in dependency compile

- dev-requirements.txt
- docs/changes.rst
- minimum-constraints.txt
- tests/functiontest/conftest.py
This PR rolls back into 0.17.6:
* PR #2441: Fixed dependency issues with 'pyrsistent' package on py27 and py34
* PR #2444: Test: Changed collection of .yaml files to address pytest DeprecationWarning
> 0.17: Roll back fixes: pyrsistent install; pytest collection of .yaml files

- docs/changes.rst
- tests/functiontest/conftest.py
Rolls back PR #2430 into 1.0.3.
> 1.0: Test: Changed collection of .yaml files to address pytest DeprecationWarning

- docs/changes.rst
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
Added a test that resets the path to the original test since the act of
changing a key property in an instance also changes the property in the
path
> Fixes #2449: Test that catches ModifyInstance key property change

- docs/changes.rst
- tests/unittest/pywbem/test_mof_compiler.py
> Test: Fixed ResourceWarning for not closing MOF compiler log file

- docs/changes.rst
- pywbem/_version.py
Please approve the release of pywbem 1.0.3
**Open:** Do we need to upgrade the minimum versions of nocasedict/nocaselist here as well? Wait for CI runs.
> Release 1.0.3

- makefile
You can now see the OpenSSL version that is used by Python's ssl module in each test.
Result as shown by the tests of this PR:
| CI | OS       | Python | OpenSSL | 
|:--- |:------ |:------ |:------ |
| Appveyor | Windows | 2.7.17 |1.0.2t |
| Appveyor | CygWin | 3.8.3 | 1.1.1f |
| Travis | Ubuntu 16.04.6 | 2.7.15 | 1.0.2g |
| Travis | Ubuntu 16.04.6 | 3.4.8 | 1.0.2g |
| Travis | Ubuntu 16.04.6 | 3.8.0 | 1.0.2g |
> Added Python's OpenSSL version to 'make platform'

- docs/changes.rst
- tests/unittest/pywbem/test_mof_compiler.py
> Partly fixes #86: Test: Fixed ResourceWarning issued in test_mof_compiler.py

- docs/changes.rst
- makefile
- pywbem/_cim_operations.py
- pywbem/_logging.py
- tests/unittest/pywbem/test_logging.py
**Note:** This PR is on top of PR #2496 - review only the last commit.
Together, these PRs remove all remaining ResourceWarnings during test.
> Added ability to disable logging; Fixed ResourceWarnings in test_logging.py

- pywbem/_mof_compiler.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
The MOF compiler cannot install a DMTF schema in a second namespace
because it tries to get the qualifiers from an incorrect remote
namespace.  This is a one line fix to the   compiler.
Adds test for pywbem_mock compiling into multiple namespaces.
Marked as priority because while this is a mof compiler issue it directly affects the last pywbem 0.8.0. This is blocking pywbemtools 0.8.0 release.
NOTE: I did not add comment to change log because it still reflects 1.1.0-dev.
> Fixes issue #2502 pywbem compiler issue building in second namespace

- docs/changes.rst
- pywbem/_cim_obj.py
- pywbem/_cim_types.py
- pywbem/_tupleparse.py
- pywbem/_warnings.py
- tests/unittest/pywbem/test_cim_http.py
- tests/unittest/pywbem/test_cim_obj.py
- tests/unittest/pywbem/test_tupleparse.py
**Note: Other than discussed in the meeting, I did not raise ValueError when creating a WBEM URI, but issued the new warning as well. This was because WBEM URIs are often created to report issues with instances, for example instances without keys, and so we should be as tolerant as before.**
> New MissingKeybindingsWarning warning for instance paths without keys

- docs/changes.rst
- pywbem/_cim_obj.py
- pywbem/_cim_types.py
- pywbem_mock/_resolvermixin.py
- tests/unittest/pywbem/test_cim_obj.py
- tests/unittest/pywbem/test_cim_types.py
**Note: This PR is on top of PR #2501 - review only the delta.**
For seeing the resource savings by this change, compare the output of `make resourcetest` between this PR and PR #2501. Results have been posted to issue #2511.
> Reduced memory consumption of CIM objects by using lazy initialization

- docs/changes.rst
- pywbem/_cim_obj.py
- pywbem/_cim_types.py
- pywbem/_tupleparse.py
- pywbem/_warnings.py
- tests/functiontest/references_instances.yaml
- tests/unittest/pywbem/test_cim_http.py
- tests/unittest/pywbem/test_cim_obj.py
- tests/unittest/pywbem/test_indicationlistener.py
- tests/unittest/pywbem/test_tupleparse.py
This PR rolls back PR #2515 and #2516 into 1.1.2.
> 1.1: Improvements in CIM-XML parsing and instance paths without keybindings

- .travis.yml
- dev-requirements.txt
- docs/changes.rst
- minimum-constraints.txt
- pywbem_os_setup.sh
- tests/functiontest/conftest.py
- tests/unittest/pywbem/test_utils.py
- tests/unittest/utils/validate.py
This PR rolls back PR #2520 (except for resourcetest changes which does not exist yet) into 1.1.3.
> 1.1: Enabled pypy3, py39; Various fixes for that and for pypy2

- dev-requirements.txt
- minimum-constraints.txt
Another fix that was needed to get the manual-ci-run to succeed again.
> Increased min version of psutil to fix install error on Windows with py>=36

- dev-requirements.txt
- minimum-constraints.txt
Rolls back PR #2526 into 1.1.3.
> 1.1: Increased min version of psutil to fix install error on Windows with py>=36

- docs/changes.rst
- pywbem/_cim_operations.py
Since we are now enforcing expected warnings in tests, the unexpected DeprecationWarning causes tests to fail. This PR fixes that.
> Fixed DeprecationWarning issued by urllib3

- dev-requirements.txt
- docs/changes.rst
- makefile
- minimum-constraints.txt
- pylintrc
- requirements.txt
- setup.py
- test-requirements.txt
Rollback not intended because it would restrict the applicability of these pywbem versions.
> Increased minimum versions of several packages; enforcing safety reports no issues

- docs/changes.rst
- makefile
- minimum-constraints.txt
- test-requirements.txt
No rollback into pywbem 1.1 needed, because safety checks were enforced only starting with pywbem 1.2.
> Fixed safety issue by increasing lxml to 4.6.2

- minimum-constraints.txt
Rolls back commit 3a9babc (no PR) into 1.1.3.
> 1.1: Fixed issue with github version of coveralls in constraints file

- .github/workflows/test.yml
- pywbem_os_setup.bat
> Fixed WinOpenSSL version on Windows with py27; added py27 to normal tests

- minimum-constraints.txt
Rolls back PR #2555 into 1.1.3.
> 1.1: Fixed safety issue 39253 with py

- docs/changes.rst
- pywbem_mock/_methodprovider.py
Rolls back PR #2565 into 1.1.4.
> 1.1: Docs: Fixed incorrect attr 'provider_classnames' in method provider example

- docs/changes.rst
- docs/mof_compiler.help.txt
- pywbem/_mof_compiler.py
- pywbem_mock/_wbemconnection_mock.py
- tests/unittest/pywbem/test_mof_compiler.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
This pr fixes issue #2256 as follows:
1. Adds tests to mof compiler for no  name on the namespace pragma
just to be sure we have that covered
2. Adds tests in pywbem_mock for use of the namespace pragma.
3. Adds fix to the mof compiler for case where pybwbem_mock
compile_mof_string and compile_mof_file fail if the MOF contains a
namespace pragma that has a different namespace name than the namespace
parameter on the methods.  Note that it is just that one of the
MOFWBEMConnection lists does not get created for the namespace defined
in the pragma.
4. Extends documentation on the namespace parameter for the
compile_mof_string and compile_mof_file() methods to clarify the
behavior with the namespace pragma in the MOF.
5. Add note on limitation of name in namespace pragma to just the name and …
> Fixes and tests for use of compiler namespace pragma

- docs/changes.rst
- docs/mockwbemserver.rst
- pywbem/_server.py
- pywbem_mock/_baseprovider.py
- pywbem_mock/_namespaceprovider.py
- pywbem_mock/_wbemconnection_mock.py
- tests/unittest/pywbem/test_wbemserverclass.py
I believe this also fixes Karl's issue #2575 . Please verify.
>  Fixed, improved, clarified support for Interop namespace in mock+WBEMServer

- pywbem_mock/_wbemconnection_mock.py
> Fixed printing of MOF compiler error messages in mock compile

- minimum-constraints.txt
- pywbem_mock/_wbemconnection_mock.py
- requirements.txt
- tests/unittest/pywbem/test_cim_obj.py
- tests/unittest/pywbem/test_itermethods.py
- tests/unittest/pywbem/test_valuemapping.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
This includes the change from PR #2590 plus a fix in the minimum constraints file.
> Migrate to using unittest.mock (2)

- docs/changes.rst
- docs/genindex.rst
- docs/index.rst
This pr adds a new section to the end of the pywbem documentation, an
index.  Note that there are probably no hand created index entries but
the index gathers a number of entries from API information, etc.
This is parallel to what we did for pywbemcli and only adds a new rst
file (genindex.rst) and a reference to that file in index.rst.
> Adds index section to generated documentation

- dev-requirements.txt
- docs/changes.rst
- pylintrc
- pywbem/_listener.py
- pywbem/_mof_compiler.py
- tests/end2endtest/utils/utils.py
**DISCUSSION:**  The unpinning causes pylint 2.7.0 to be used, which increases its run time significantly (from 2 min to 22 min). See for example the test run for py39 with latest package levels. Should we exclude pylint 2.7.0?
> Fixed new pylint issues raised by pylint 2.7.0

- docs/changes.rst
- docs/mockwbemserver.rst
- pywbem_mock/_mainprovider.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
Extends pywbem_mock ModifyClass to test for a number of possible errors including:
1. Instances exist
2. Subclasses exist
3. Invalid superclass
4. Invalid prerequisite classes
Adds a test_modifyclass test to pywbem_mock/test_wbemconnection.py for
most of these errors and for correct handling of simple modifications.  The test covers 10% of the ModifyClass method
NOTE: ModifiedClass is still probably missing tests for some particular conditions when a superclass exists (i.e validation of the sutibility of all inherited elements) but does all the tests that CreateClass does.
> Fixes issue ##2447. Extends pywbem_mock ModifyClass and tests

- dev-requirements.txt
- makefile
- minimum-constraints.txt
> Circumvented an install failure of lazy-object-proxy on py35/minimum

- Makefile
- docs/changes.rst
- test-requirements.txt
Added the safety id 40072 (lxml) to the Makefile safety ignore list
and comment in test_requirements.txt
> Fix issue #2645 & #2647, Safety failure in make check with lxml & decorator pkg version

- pywbem_mock/_mainprovider.py
- pywbem_mock/_namespaceprovider.py
- pywbem_mock/_providerdispatcher.py
- tests/unittest/pywbem_mock/conftest.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
Waiting on pr  #2643.
1. Add test for pywbem_mock create class with existing class.
2. Cleanup some TODOs in pywbem_mock and test of pywbem mock to
remove TODOS no longer valid or make issue for know issues.
This leaves a number of TODOS in the tests for pywbem_mock but
only a single TODO without an issue in pywbem_mock (General comment
about a algorithm being to wide so it wastes time)
> Modifications to pywbem_mock and tests, miscellaneous

- docs/changes.rst
- pywbem_mock/_mainprovider.py
- pywbem_mock/_wbemconnection_mock.py
Based on PR #2644
Waiting on PR #2646 - Andy: meanwhile merged.
Fixes issue where DeleteClass was calling the cim reopository directly to delete instances rather than calling the 
providerdispatcher to allow any instance providers that delete instances to  correctly handle the delete.
> Fixes issue #2643 mock delete instance

- pywbem/_cim_operations.py
- tests/functiontest/associatornames_classes.yaml
- tests/functiontest/associatornames_instances.yaml
- tests/functiontest/associators_classes.yaml
- tests/functiontest/deleteinstance.yaml
- tests/functiontest/deletequalifier.yaml
- tests/functiontest/invokemethod.yaml
- tests/functiontest/openenumerateinstancepaths.yaml
- tests/unittest/pywbem/test_cim_operations.py
1. Refactor the code for the open... methods that duplicate some of the test code (test for object types returned) to create common functions.
2. Add tests for this code and other pieces of _cimoperations.py that are not covered.  This reduces the uncovered code in _cim_operaitons.py to about 130 lines of which about 100 are the recorder calls and several are code that apparently duplicates tests in the xml parser and so may never be called.
> Add more tests to increase coverage for _cim_operations.py and refactor one piece of code

- .github/workflows/test.yml
- .gitignore
- Makefile
- dev-requirements.txt
- docs/intro.rst
- minimum-constraints.txt
- pywbem/_cim_types.py
- pywbem/_mof_compiler.py
- setup.py
- tests/utils.py
This adds support so that users can build a cythonized version of the wheel distribution archive for pywbem, by using **either one** of these commands:
`$ make buildc`
or
`$ ./setup.py bdist_wheel --cythonized`
Note that `./setup.py bdist_wheel --help` displays help text that covers the `--cythonized` option.
The cythonized version can be successfully built on macOs and Ubuntu on Python 3.5 and higher, but not on Windows.
The failing tests should only be the occasional ConnectionError failures when sending indications.
See the commit message for details.
> Support for building cythonized distribution archive

- .github/workflows/test.yml
- Makefile
- README_PYPI.rst
- dev-requirements.txt
- docs/changes.rst
- minimum-constraints.txt
- pywbem/_version.py
Please approve the release of pywbem 1.2.0.
The one extra commit solves an issue that only shows up in the full set of tests, but nt in the normal set of tests. That's why it is part of the release PR.
> Release 1.2.0

- docs/changes.rst
- pywbem/_mof_compiler.py
Add test for p.parser.lverbose test around p.parser.log output if ModifyClass within createclass production fails.  This was causing a log output whether the verbose flag was set or not.
This resolves part of the issue defined by pywbemtools issue https://github.com/pywbem/pywbemtools/issues/935  (ModifyClass exception produces multiple output).
NOTE: There is still an issue documented in the original pywbemtools issue in that the exception is displayed twice and I have not yet concluded whether that is a pywbem or pywbemtools issue.
> Fix mof_compiler unwanted output of trace log information.

- docs/changes.rst
- docs/indication.rst
- examples/listen.py
- pywbem/_exceptions.py
- pywbem/_listener.py
- tests/unittest/pywbem/test_exceptions.py
- tests/unittest/pywbem/test_indicationlistener.py
This came up when implementing listener support in pywbemtools. It started out as only an improvement with no required functionality for the listener support in pywbemtools, but it ended up with new exception classes pywbemtools now has a dependency on.
> Improved the running of indication listeners when using HTTPS

- Makefile
- docs/changes.rst
This PR circumvents the issue by ignoring the safety issues, which allows using notebook on py27. Fixing the safety issues would require using notebook 6.1.5 as a minimum version which would require us to drop support for using Jupyter Notebook on Python 2.7. There is an according discussion point in issue #2703.
> Circumvented safety issues 40380..40386 with the notebook package

- docs/changes.rst
- pywbem_mock/_wbemconnection_mock.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
Adds one more parameter to the __init__ method of FakedWBEMConnection
(url) to allow the user to define a different url that will be passed to
the superclass in place of http://FakedURL:5988.
This will be useful in testing, particularly subscription testing where
we want to establish multiple server_ids in the tests.
> Allow initalization defined url for FakedWBEMConnection class

- docs/changes.rst
- pywbem/_subscription_manager.py
- tests/unittest/pywbem/test_subscriptionmanager.py
1. Fixes an issue where the build of owned CIM Listener destination and CIM
indication filter objects and the regex to find the objects when
restoring these objects from a server did not have a common
understanding of the exact format of the Name property. The host_name
element was part of the regex but not of the string in the Name
property. This pr simply adds the host_name to the Name property.
Resolved: We send them
2. Fixes an issue where the add_subscription() comparison of the new instance path with paths from the list of owned instances is working with an incomplete path on the new instance (the keybindings have not been added).
Resolved: We don't do the modify so that code removed.
It also adds tests to confirm that when a SubscriptionManager is created, the owned subscriptions, …
> Fixes issue #2701, SubscriptionManager code issues 

- docs/changes.rst
- examples/send_indications.py
- tests/unittest/pywbem/test_indicationlistener.py
For windows the host name was changed from localhost to 127.0.0.1 in test_indicationlistener.py to eliminate the delay
Also added note to examples/sendindications.py and fixed a number of flake8 issues in that code.
> Fix issue with slow indications with Windows OS in tests

- docs/changes.rst
- pywbem/_subscription_manager.py
- tests/unittest/pywbem/test_subscriptionmanager.py
The subscription manager does not pass the owned parameter to recalls of
itself if there are multiple urls provided in the call.
Extends test_suscriptions slightly adds capability to remove destinations, filters, subscriptions and test result in addition to new test for creating multiple destinations. Subscription manager now up to 94% with only 15 untested lines of code.
> Fix issue #2715, SubscriptionManager loses owned parameter

- docs/changes.rst
- pywbem/_subscription_manager.py
Fixes issue defined in issue #2719 with instance returned from
add_subacriptions()
This pr does not add a test for this change.  That is accomplished in
other PRs.
NOTE: I did not mark this one for rollback because it is in the new code. The old code tried to modify the instances.
> Fix issue in add_subscriptions()

- Makefile
- docs/changes.rst
Rolls back PR #2717 into 1.2.1.
> 1.2: Windows: Removed dependency on bash command in pip upgrade in Makefile

- docs/changes.rst
- pywbem/_cim_operations.py
Rolls back PR #2739 into 1.2.1.
> 1.2: Tolerated servers returning CIM_ERR_FAILED when not supporting pull ops

- docs/changes.rst
- minimum-constraints.txt
- requirements.txt
Rolls back PR #2746 into 1.2.1.
> 1.2: Fixed yamlloader error during setup.py install on Ubuntu with py27/34/35

- docs/changes.rst
- minimum-constraints.txt
- pywbem/_cim_operations.py
- requirements.txt
- tests/unittest/pywbem/test_itermethods.py
Has priority since pywbemtools PRs fail due to this.
> Fixed error in tolerating CIM_ERR_FAILED when not supporting pull ops

- Makefile
> Suppressed confusing error messages when make determines package_version

- docs/changes.rst
- pywbem/_mof_compiler.py
- pywbem_mock/_instancewriteprovider.py
- pywbem_mock/_providerdispatcher.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
Adds validation on pywbem_mock and mof_compiler for attempts to create
an instance where the creation class has the Abstract qualifier.  Adds the validation, documents the new validation, and adds tests for both CreateInstance and compile of the instance into pywbem_mock.
This fails with CIMError CIM_ERR_FAILED.
> Issue #2742 - Add tests for instance create of abstract class

- docs/changes.rst
- pywbem_mock/_wbemconnection_mock.py
Change use of unittest.MOCK to duck typing mocked methods in FakedWBEMConnection
The use of Mock was causing issues with pywbemcli pickle and restore of
connection information when the connections were mocked.  Replacing the
Mock with simply duck typing the methods removed the problem
See pywbemtools issueL https://github.com/pywbem/pywbemtools/issues/1038
for a detailed description of the problem.
Note that there is no test for this since pywbem does not use pickle.
> Remove use of unittest.Mock from FakedWBEMConnection

- pywbem_mock/_mainprovider.py
> Disabled Pylint issue on using deprecated time.clock()

- docs/changes.rst
- pywbem_mock/_mainprovider.py
- tests/end2endtest/test_profile_generic.py
- tests/end2endtest/test_profile_snia_server.py
- tests/end2endtest/test_server.py
Rolls back PR #2769 into 1.2.1.
> 1.2: Mitigated Pylint issues 'deprecated-method' and 'not-an-iterable'

- docs/changes.rst
- pywbem/_subscription_manager.py
- pywbem/_warnings.py
- tests/unittest/pywbem/test_subscriptionmanager.py
- tests/unittest/pywbem/test_warnings.py
Note that this PR only addresses this for filter names (see issue #2765).
A separate PR will be made for destination names (see issue #2766).
> Simplified auto-generated Name of owned filter instances

- docs/changes.rst
- pywbem/_warnings.py
- tests/unittest/pywbem/test_warnings.py
Adds a new warnings class to pywbem and adds that class to the unit
test.  This is expected to be used in the future in the MOF compiler and
by pywbem tools to warn the user about issues in the schema that are
either repaired or which do not warrent a failure.
> Add Warning class for TolerateSchemaIssuesWarning

- pylintrc
> Ignored Pylint issue 'consider-using-f-string' in new Pylint 2.11

- docs/changes.rst
- pylintrc
Rolls back PR #2774 into 1.2.1.
> 1.2: Ignored Pylint issue 'consider-using-f-string' in new Pylint 2.11

- docs/changes.rst
- pywbem/_subscription_manager.py
- pywbem/_warnings.py
- tests/manualtest/run_cim_operations.py
- tests/unittest/pywbem/test_subscriptionmanager.py
- tests/unittest/pywbem/test_warnings.py
Particular review points might be:
* I left the `owned` parameter in the new `add_destination()` method, because I found it too implicit that the ownership type is determined just by the choice of `name` vs `destination_id` parameter, and for consistency with `add_filter()`.
**COMMENT/KS:** I agreed with you until I went through the code and API.  Now I begin to think that the owned parameter is redundant because it offers the user an option that does not really exist (mixing ownership and xxxx_id vs name)  By definition owned must be True if xxxx_id parameter exists and False if name parameter exists.  Having the owned parameter implies that the user could do owned=True/name=fred or owned=False/destination_id=fred so we have to add tests to disallow it..  I made …
> Changes for creating listener destinations in WBEMSubscriptionManager

- dev-requirements.txt
- docs/changes.rst
- minimum-constraints.txt
- requirements.txt
- test-requirements.txt
Rolls back PR #2776 into 1.2.1.
> 1.2: Fixed install errors of PyYAML,wrapt,jsonschema on older Python versions

- Makefile
- dev-requirements.txt
- docs/changes.rst
- minimum-constraints.txt
- rtd-requirements.txt
Includes commit for pr #2791,  update to safety checks.
Docutils created incompatible change with version 0.18. Sphinx fixing
this for Sphinx V 4,3.0 but not for older versions. Since we use Sphinx 1.8.5 for python < 3.5 we need to use docutils < 0.18
for these tests.
> Issue between Sphinx 1.85 and docutils 0.18

- docs/changes.rst
- pywbem/_mof_compiler.py
Waiting on prs #2790 and #2791
The MOF compiler ignores issues of mismatch between the class definition of properties arrayness and the corresponding values in instances of the class. Thus, the compiler where a class with an array property is defined will accept a single value property value (and output it as a single value property value) and will accept an array value defintion for an instance and produce an array value in the CIMProperty.  This fix tests for this mismatch in the compiler and generates an error if found.
I chose the approach of adding a specific test for the issue to the compiler rather than fixing issue #2789 (which adds the test code to CIMProperty) because this isolates the change and I am not sure what all might break with the more complete change define in issue …
> Issue #2786, Compiler ignores arrayness mismatches

- dev-requirements.txt
- docs/changes.rst
- minimum-constraints.txt
Fix issue #2796 that does not limit the version of more-itertools which causes test failures and fix an issue with use of >= in minimum-constraints.
This limits the version of more-itertools version 8.11.0 to python > 3.6
NOTE: I assume that the developers will correct the issue and either rerelease 8.11.0 or release an 8.11.1 since there is already a PR defined.
Priority because issue # 2796 it breaks tests.
Also fixes issue # 2792 where there is a invalid comparison error in minimum-constraints.txt.  That, however, was not a test breaking issue.
NOTE: more-tools has a PR up to fix this problem (https://github.com/more-itertools/more-itertools/pull/579) but if we assume that the fix in by creating a new version (several users have requested that they reissue 8.11.0) we will have another …
> Set version limit on more-itertools in dev-requirements.txt

- pywbem_mock/_subscriptionproviders.py
- tests/unittest/pywbem/test_subscriptionmanager.py
First commit:
1. Added description property to each of the providers just to clarify
that these are from the Mock
2. Add a couple of Null properties just to expand the pywbemcli test.
3. Extended one property in subscription to add it NULL even if not
provided by client as a logical server based property.
These are all minor changes to the mock providers and have been tested
against pywbemcli.
The second commit:
Corrects an issue where the replacement of key properties fails if the property being tested has None as a value.  This only occurs if an instance is installed outside of the subscription manager (ex. directly compiled into the the mock environment)
> Add some properties to Subscription provider instances

- docs/changes.rst
- pywbem/_subscription_manager.py
- tests/unittest/pywbem/test_subscriptionmanager.py
Wating on priority prs #2795
Moves the test for duplicated name property to before the test for
duplicated URL and adds PersistenceType as test for equality between new
and existing owned destination instances.
Fixed test_subscriptionmanager.py to account for possible multiple
destination definitions in test since the code has been changed to now
allow only a single destination for each call.
NOTE: It would not bother me if we changed the code to return ValueError if the URL matched or even just to
remove the test for URL code.  I chose returning the existing instance as one of 3 generally almost equal
choices.
Added tests specifically for duplicated destination destination_id and
for returning instance if url and persistence type match.
> Fixes issue # 2782, handling of add_destination duplicates.

- docs/changes.rst
- minimum-constraints.txt
- test-requirements.txt
Rolls back PR #2811 into 1.2.1.
> 1.2: Fixed error when installing virtualenv in install test on Python 2.7

- docs/changes.rst
- pywbem/_mof_compiler.py
- pywbem/_server.py
- pywbem_mock/_baseprovider.py
- pywbem_mock/_wbemconnection_mock.py
This is needed for the namespace creation tests in pywbemtools (PR https://github.com/pywbem/pywbemtools/pull/1114)
**DISCUSSION:**
There are two options on how to deal with this PR:
* Release pywbem 1.4.0 with this change quickly and have the namespace creation tests in pywbemtools 1.0.0
* Defer this change until after pywbem 1.4.0 and defer the namespace creation tests in pywbemtools until after pywbemtools 1.0.0
* Then we need to decide what we do with the changes in the mock scripts in pywbemtools
> Improved verbosity of namespace creation/deletion

- Makefile
Rolls back PR #2832 into 1.4.1.
> 1.4: Ignored safety issue 43366 (lxml, code not used)

- docs/changes.rst
- pywbem_mock/_wbemconnection_mock.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
Rolls back PR #2840 into 1.4.1.
> 1.4: Ks/#2839 deep inheritance open enumerate instances parm missing

- docs/changes.rst
- pywbem/_mof_compiler.py
- pywbem_mock/_providerdispatcher.py
- tests/unittest/pywbem/test_mof_compiler.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
Change code to allow the CreateInstance of an abstract class but issue a warning.  Note that
there are two places this occurs:
1. The create instance from the compiler
2. Pywbem_mock CreateInstance
Add tests to mof_compiler for this change.
> Fix issue with create instance of abstract class

- Makefile
- minimum-constraints.txt
Rolls back PR #2880 into 1.4.2
> 1.4: Fixed missing new dependency 'rich' for 'twine' package; Fixed new safety issues

- docs/changes.rst
- tests/manualtest/run_cim_operations.py
Fixed a number of issues that was causing this manual test of pywbem against local OpenPegasus server to fail tests.  This is in preperation for adding general request tests to the end2end tests.
> Fix issues in manual test run_cimoperation.py

- Makefile
- docs/changes.rst
- minimum-constraints.txt
- requirements.txt
Rolls back PR #2889 (with both commits) into 1.4.2.
> 1.4: Fixed installtest error by pinning certifi; fixed safety issues

- docs/changes.rst
> Reflected previous two commits in the change history

- docs/changes.rst
Rolls back PR #2899 into 1.4.2.
> 1.4: Reflected previous two commits in the change history

- tests/unittest/pywbem_mock/test_complexassoc.py
Rolls back PR #2897 into 1.4.2.
> 1.4: Resolved pylint issue on arg name in test_complexref_classnames

- Makefile
- dev-requirements.txt
- docs/changes.rst
- minimum-constraints.txt
- test-requirements.txt
No rollback needed, since that would require support for Python 3.4 (and build 0.5.1 requires py27 or py>=35)
> Transitioned build of dist archive to use 'build'  package

- Makefile
New security issues on dparse, ipwidgets, nbconvert.  Marked all to be
ignored for now.
I just marked them  for ignore for the moment since they are all packages
that are part of test environment and not pywbem pip package.  I took this as the fastest approach to getting
CI running with number of outstanding Open PRs
===================
I tried to use dparse rather than just ignore it.  It would appear that this is not possible with
python 2.7 however. I changed the limits in dev-requirements and minimum-constraints for dparse dparse I enabled min version 0.5.2 for all but python 2.7 and put entry into ignore list (in the Makefile) for python 2.7.
However, that is not working correctly as of Friday afternoon.   
For example fails with python 3.10, ubuntu, minimum test but results show …
> Mark new security(safety) issues for ignore

- docs/changes.rst
- pywbem_mock/_instancewriteprovider.py
- pywbem_mock/_mainprovider.py
- pywbem_mock/_mockmofwbemconnection.py
- pywbem_mock/_providerdispatcher.py
- pywbem_mock/_wbemconnection_mock.py
- tests/unittest/pywbem/test_subscriptionmanager.py
- tests/unittest/pywbem_mock/test_multi_ns_assoc.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
Waiting pr #2916, the latest security issues so should fail if resubmitted before that issue is fixed
Extends creation, modification, and deletion of association instances in
pywbem_mock where the instance reference defines cross namespace
associations to build a corresponding instance of the association in
each namespace.
See Commit message for details
NOTE: This pr also fixed some pylint issues that apparently popped up with new version of pylint and added test for existence of association endpoints when creating/modifying new instances in pywbem_mock
Prviously it would pass end points path definitions that were invalid.
> Extend inter-namespace  mock associations to be bidirectional

- tests/unittest/utils/wbemserver_mock.py
Removed obsolete bypass code and comments in wbemserver_mock.py and
restored the call to function that was commented out for a now
corrected issue.
> Remove obsolete bypass code in test

- docs/changes.rst
- pywbem/_cim_operations.py
Documents the fact that when pull operations are used this method only
delivers instances after the request to the server is complete rather
than after each of the Open and Pull operations and that the Query parameter
will generate an exception if the server does not have pull operations
so that it  is best to set UsePullOperation=True if the Query parameter
is set.
No code or test changes
> issue # 1801, documentation limitations to IterQueryInstances

- .github/workflows/test.yml
- dev-requirements.txt
- docs/changes.rst
- minimum-constraints.txt
- test-requirements.txt
This PR includes the change from PR #2925 in order to test on the Python 3.7 version where it previously failed.
> Fixed flake8 RecursionError on Python 3.6+3.7; Added Python 3.7 to general tests

- .github/workflows/test.yml
- dev-requirements.txt
- docs/changes.rst
- minimum-constraints.txt
- test-requirements.txt
Rolls back PR #2921 into 1.4.2.
> 1.4: Fixed flake8 RecursionError on Python 3.6+3.7; Added Python 3.7 to general tests

- Makefile
- dev-requirements.txt
- docs/changes.rst
- minimum-constraints.txt
- test-requirements.txt
2 separate commits.
* Modifies versions of importlib-metadata package because of failure with python 3.7 in flak8.  Issue #2931
* Set safety ignore for pygments.  Set to same values in pywbemtools  dev-requirements.txt and minimum-constraints.txt.
Packaged them into two commits but in the same pr because both cause github CI failure so we need both to get tests running.
Set rollback needed because they cause CI failure that would apply to previous versions of pywbem
> Ignore security  issues and fix new issue with flake8 2022

- Makefile
- dev-requirements.txt
- docs/changes.rst
- minimum-constraints.txt
- test-requirements.txt
Rolls back PR #2929 into 1.4.2.
> 1.4: Ignore security issues and fix new issue with flake8 2022

- docs/changes.rst
- pywbem_mock/_baseprovider.py
- pywbem_mock/_namespaceprovider.py
- tests/unittest/pywbem/test_subscriptionmanager.py
- tests/unittest/pywbem_mock/test_system_providers.py
This fixes two issues:
1. Error caused by bad edit in pr# 2913
2. Fix issue #2918 - limitation where duplicate namespaces could be created.
The fix consists of modifying the test for existence of the namespace being created in the namespaceprovider rather than just the instance path of the new instance.  A method was added to baseprovider to accomplish this change and used in the namespace provider.
The test modifies and extends some of the tests for namespace provider installation
See commit for more details
> Fix issues with namespace provider.

- docs/changes.rst
- pywbem_mock/_instancewriteprovider.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
Fix issue #2920 in pywbem_mock where CreateInstance or ModifyInstance on an association instance fails if a reference property CIMInstanceName property includes host name in the path.
Modified to fail with correct message if any reference property of an association includes the host element in the CIMInstanceName
This seemed logical since otherwise, the user would have an instance that they created which differed from the path we create in CreateInstance.
Added test for this failure for CreateInstance
> Fix mocker issue with create association instance.

- Makefile
- dev-requirements.txt
- docs/changes.rst
- minimum-constraints.txt
- test-requirements.txt
Fixes safety issues for py, safety, and wheel from November 2022 safety report.
This PR will not complete tests successfully because of issues fixed by pro #2954. It was rebased into that PR to test together.
This generate a conflict in version requirements between safety (>=8.0.2) and easy-vault
(>=7.1.1) on click minimum version causes failure with 2.10 minimum because
we specify  click==7.1.1 in minimum. Moved to specify click min = 8.0.2
It generates a second conflict because safety 2.2.0 requires packaging 21.0 and the definition in minimum-constrants is 19.0. Fix
NOTE: These are the same fixes made for pywbemtools in November except for the issues with easy-vault and packaging
> Fix several security issues.

- .github/workflows/test.yml
- docs/changes.rst
This PR is rebased on PR # 2953, that fixes new security issues and changes only the requirements files (i.e. minimum-constrains.txt).  The changes to fix the issues CI testing with the ubuntu version are in the file test.yaml.  Did this so we could get a running version with these two separate issues since each of them breaks the CI tests.
CI tests fail because github moved to use ubuntu-22.04 as ubuntu-latest and the setup_python github action does not support versions of python older than version 3.7 with this ubuntu version.  This means that the github actions matrix had to be updated to reflect the use of ubuntu-20.04 for tests with the older versions of ubuntu.  This is documented in pywbemtools issue #1245
Modified github actions matrix to use ubuntu 20.04 in whereever python <= …
> Fixed issue with Python 3.5+3.6 no longer supported in ubuntu_latest; Updated the version of setup-python

- .github/workflows/test.yml
- docs/changes.rst
Rolls back PR #2954 into 1.5.1.
> 1.5: Fixed issue with Python 3.5+3.6 no longer supported in ubuntu_latest; Updated the version of setup-python

- dev-requirements.txt
- minimum-constraints.txt
> pip-check-reqs 2.4.3 fixes a speed issue on Python 3.11

- Makefile
- dev-requirements.txt
- minimum-constraints.txt
- rtd-requirements.txt
There are 3 new safety issues:
1.  setuptools - new minimum 65.5.1 issue id 52495, added to ignore
because different minimum with python 3.9
2. certifi - new minimum 2022.12.07 issue  id 52365, added to ignore
because different min version for python 2.7
3. gitpython - new minimum 3.1.27 issue id 52518, added to ignore
because diff min version for python 2.7.
Safety report:
```
-> setuptools, installed 41.5.1, affected <65.5.1, id 52495
Python Packaging Authority (PyPA) setuptools before 65.5.1 allows remote attackers to cause a denial of service via HTML in a crafted package or custom PackageIndex page. There is a Regular Expression Denial of Service (ReDoS) in package_index.py.
--
-> setuptools, installed 49.0.0, affected <65.5.1, id 52495
Python Packaging Authority (PyPA) setuptools …
```
> Fix security (safety) issues that appeared 1 Jan. 2023.

- docs/changes.rst
- tests/end2endtest/es_server.yml
Updates the docker image to use the image kschopmeyer/openpegasus-server:0.1.2 which was created using the OpenPegasus 3.14.3 release located in the github repository https://github.com/OpenPegasus/OpenPegasus, built with the Docker files in https://github.com/OpenPegasus/OpenPegasusDocker.
This docker file uses the same CIM model and providers as the previous image.  However it is several hundred megabytes smaller (now ~ 100 mb).
> Use a new docker image in tests.

- docs/changes.rst
- pywbem/_cim_operations.py
Fixes an issue in the parameters for  HTTP POST retries within urllib3 where the retry values defined in CIM_operations  allowed the retry of a CIM/XML request that such as
invokemethod, update, etc. where it is critical that the operation only be issued once.  This is because all CIM/XML operations use POST.
Changes the retry to not allow retries on POST operations.
Issue documented in #2951
> Fix issue with HTTP retries of cim-xml operations.

- Makefile
- docs/changes.rst
This is the first step in correcting the issue where we have test failures each month as new security issues are defined.
This simply ignores the failure status return from the safety check target in the Makefile.
See Issue #2970 for more information. This does not close issue # 2970 since there is a second step.
> Disable CI test failure upon safety check failure

- .github/workflows/test.yml
- dev-requirements.txt
- docs/changes.rst
- minimum-constraints.txt
Rolls back PR #2998 into 1.6.2
> 1.6: Fixed coveralls issues with KeyError and HTTP 422 Unprocessable Entity

- minimum-constraints.txt
- requirements.txt
Rolls back PR #3003 into 1.6.2.
> 1.6: Limit max version of urllib3 to lt 2.0.0

- minimum-constraints.txt
- requirements.txt
Limit the max version of urllib3 to lt 2.0 since there are a number of issues in this change that will cause our tests to fail including
1. no longer supports python 2.7, 3.5, 3.6
2. pool module removed
as a minimum  
For the time being we will limit the versions we use to < 2.0 but have filed issue #3006 to determine the overall impact of the new version and changes we will make to support it.
Note: This will only pass the tests when run with pr # 3005, the update to safety (with the policy file)
> Limit max version of urllib3 to lt 2.0.0

- .safety-policy.yml
- Makefile
- dev-requirements.txt
- docs/changes.rst
- minimum-constraints.txt
- test-requirements.txt
Rolls back PR #3005 into 1.6.2.
> 1.6: Modify use of the safety utility to use their .safety_policy_file

- .safety-policy.yml
- Makefile
- dev-requirements.txt
- docs/changes.rst
- minimum-constraints.txt
- test-requirements.txt
NOTE: Rebased with PR #3003 (urllib fix) to avoid test failure. Waiting on commit of that pr.
1. Created new .policy_safety_file in root directory. This was based on the file in zhmcclient but with a number of new entries since there are significantly more dependencies here than in zhmcclient  
2. Modify Makefile to use this file and ignore the list of safety issues in the Makefile.
3. Remove the set of issues in the Makefile.
4. Review the set of issues in the Makefile to confirm differences with the .safety_policy_file.
5. Added a number of new safety issues that appeared on May 1
This PR superceedes PR #3002 which I closed because this replaces the old form of keeping a safety issue ignore list
This PR involved a significant number of version changes in minimum-constraints, largely …
> Modify use of the safety utility to use the .safety_policy_file

- .github/workflows/test.yml
Rolls back PR #3011 into 1.6.2.
> 1.6: Added Python 3.6 to normal test envs

- .github/workflows/test.yml
- dev-requirements.txt
- minimum-constraints.txt
Rolls back PR #3015 into 1.6.2.
> 1.6: Fixed Jupyter Notebook dependencies for Python 3.6

- pywbem/_listener.py
This change clarifies the definition of the host parameter on the WBEMListener class to include the definition of how to define a listener that listens on multiple network addresses.
Note that there is still some ambiguity in that a. this does not discusss IPV6 and b) only briefly mentions that the actual behavior of a listener with a specific address may be OS or network dependent in that in some cases the test is limited to only pass requests with the specific address and in other cases, it will pass any address that is part of the specific network interface defined by the host parameter.
> Expand documentation on the WBEMListener host parameter

- docs/changes.rst
- tests/end2endtest/test_indications.py
- tests/end2endtest/utils/pytest_extensions.py
Adds a new end-end test for:
1. Managing indication subscriptions.
2. Receiving indications from the WBEM Server
This test is based on the OpenPegasus docker image defined for the other end-end tests.
See commit mesage for details
NOTE: This commit includes changes for the example pegasusindicaitonstest.py since basically the same code is in both the end to end test and the example and this made the two almost the same.
In order to get a consinstent pass of this test, I disabled python 2.7 and reduced python 3.7 to minimum.  We could have passed on the PACKAGE_LEVEL variable from Makefile but this establishes that the issues with quitting early are at least probably tied to python 2.7 and 3.7 We also know from earlier tests that it is probably tied to the minimum config.
I suggest we …
> Adds end-end test for indications

- dev-requirements.txt
- docs/changes.rst
- minimum-constraints.txt
- requirements.txt
- test-requirements.txt
Rolls back PR #3027 into 1.6.2.
> 1.6: Fixed missing dependencies in minimum-constraints.txt

- minimum-constraints.txt
- test-requirements.txt
> Fixed dependency issue with importlib-metadata on py38+39

- minimum-constraints.txt
- test-requirements.txt
Rolls back PR #3033 into 1.6.2.
> 1.6: Fixed dependency issue with importlib-metadata on py38+39

- dev-requirements.txt
Rolls back PR #3039 into 1.6.2.
> 1.6: Fixed install of ipywidget on Python 2.7

- dev-requirements.txt
- docs/changes.rst
- minimum-constraints.txt
> Test: Circumvented a pip-check-reqs issue by excluding its version 2.5.0

- dev-requirements.txt
- docs/changes.rst
- minimum-constraints.txt
Rolls back PR #3055 into 1.6.3
> 1.6: Test: Circumvented a pip-check-reqs issue by excluding its version 2.5.0

- examples/listen.py
- pywbem/_listener.py
Update documentation on listener host parameter.  No code changes in this PR.
Clarify the possible values for the host (i.e. the bind address)
NOTE: Fails without PR #3060 and PR#3059
Modify the example since getfqdn() may well return localhost which is only useful if the indication sender is in the same system as the listener and also show example of wildcard bind address.
> Update documentation on listener host parameter.

- .safety-policy.yml
- dev-requirements.txt
- docs/changes.rst
- minimum-constraints.txt
Rolls back PR #3058 into 1.6.3
> 1.6: Update .safety_policy, dev-ramts, minimum_constraints.txt files.

- docs/changes.rst
- pylintrc
- tests/manualtest/run_operationtimeouts.py
Disable cyclic-import issue.
NOTE: Fails without PR #3059
A new issue popped up, cyclic-import with a number of warnings issued,
apparently when the new version of pylint (3.00) was released.
The following messages were produced by make pylint today:
```
mof_compiler:1:0: R0401: Cyclic import (pywbem._cim_obj ->
pywbem._cim_types) (cyclic-import)
mof_compiler:1:0: R0401: Cyclic import (pywbem -> pywbem._server ->
pywbem._cim_operations -> pywbem._recorder -> pywbem._logging)
(cyclic-import)
mof_compiler:1:0: R0401: Cyclic import (pywbem -> pywbem._mof_compiler
-> pywbem._cim_operations -> pywbem._recorder -> pywbem._logging)
(cyclic-import)
mof_compiler:1:0: R0401: Cyclic import (pywbem -> pywbem._logging)
(cyclic-import)
mof_compiler:1:0: R0401: Cyclic import (pywbem -> pywbem._recorder …
```
> pylint cyclic import issue.

- docs/changes.rst
- examples/pegasusindicationtest.py
Fixed python syntax error in examples/pegasus_indication_test.py code and issue with logging.
In addition this PR:
1. Cleans up use of logs both for logging the client api calls and for logging the reception of indications.
2. Restructures some of the code be more readable.
3. Modifies some of the argument help to clarify usage.
4. Error exit if test fails.
I have tested this significantly since it is the basis for trying to figure out why there is a communication issue with OpenPegasus where we do not receive all requested indications.  
There are no real functional changes. 
You do not have to review this code if you do not want to since there are a lot of minor changes and moving code around.  After-all to everybody else it is just an example of creating subscriptions and getting …
> Fix python syntax error in example and refactor example.

- docs/changes.rst
- pywbem/_cim_http.py
- requirements.txt
- tests/unittest/pywbem/test_cim_http.py
- tests/unittest/pywbem/test_cim_operations.py
This pr includes:
1. Update of requirements to allow use of  urllib3 version 2 but modify the code for continued use of urllib3 < 20
2. Update of tests and code to account for interface difference in the utllib3 NewConnectionError class.
3. Adds a single test for failure of a connection to  test_cim_operations.py
4. Modify test_http.py to provided for modified interface of the urllib3 NewConnection exception.
This is only part of the changes for issue #3006, the complete integration of urllib3 version 2.0
It does not close that Issue.  The remaining issues involve any changes
because with urllib3, OpenSSL version 1.1.1 (released 2018) is required.
> Update requirements to use urllib3 version 2 (Part 1).

- docs/appendix.rst
- docs/changes.rst
- docs/client/objects.rst
- docs/client/operations.rst
- docs/client/types.rst
- docs/client/valuemappings.rst
- docs/indication.rst
- docs/intro.rst
- docs/mockwbemserver.rst
- docs/notebooks/pywbemmock.ipynb
- docs/server.rst
- docs/tutorial.rst
- docs/utilities.rst
The inclusion of urllib3 verson 2.0+ can cause SSL incompatibility issue because it sets the minimum TLS version to 1.2 where it was previously TLS 1.1 or less and also limits the allowable SSL libraries to OpenSSL and possibly libreSSL.
This change updates the changes.rst document to describe the possible issues and also updates the troubleshooting section to provide details on the possible issues and corrections.
Adds index entries for SSL and OpenSSL.
> Add documentation in the update of urllib3 (part 2)

- .safety-policy.yml
- docs/changes.rst
- minimum-constraints.txt
- requirements.txt
- tests/end2endtest/test_operation_timeouts.py
Adds a test that uses a provider in OpenPegasus to delay the response to an invoke method to test for operation timeout in the end2end tests.
> Add end2end test for operation timeout.

- .github/workflows/test.yml
- .safety-policy.yml
- dev-requirements.txt
- docs/changes.rst
- minimum-constraints.txt
- test-requirements.txt
Rolls back PR #3090 into 1.6.3.
In addition, pins lxml to <4.9.4 to mitigate install failure on Python 3.5 on Windows. For the lxml install failure, created issue https://bugs.launchpad.net/lxml/+bug/2047927
In addition, added Python 3.6 / Windows / latest to normal tests to ensure the lxml install failure does not show up there.
> 1.6: Safety issues; Pinned lxml<4.9.4 on py35/win/latest; Added py36/win/latest to normal tests

- dev-requirements.txt
- docs/changes.rst
Rolls back PR #3103 into 1.6.3.
> 1.6: Fixed dependency issue with safety 3.0.0 by pinning it

- .github/workflows/test.yml
- docs/changes.rst
Rolls back PR #3105 into 1.6.3.
> 1.6: Test: Upgraded GitHub Actions plugins to use node.js 20

- docs/changes.rst
- tests/functiontest/conftest.py
This PR fixes only the error reported in issue #3113, but not the warning.
> Fixed new Pylint issue for unused variable 'exp_result'

- .github/workflows/test.yml
- dev-requirements.txt
- docs/changes.rst
- minimum-constraints.txt
- pywbem/_cim_types.py
- setup.py
- test-requirements.txt
- tests/functiontest/conftest.py
- tests/unittest/pywbem/test_recorder.py
Changes to integrate python 3.12 include:
1. Modify the CI test definition to include python 3.12
2. Modify dev-requirements and minimum-requirements for changes to package versions.
3. Modify setup.py to define python 3.12 support
4. Fix issue #3097, issue with OrderedDic. that causes test_recorder.py to fail
5. Set max version of build package to < 1.0 per issue #3112
6.  etc.
See commits message for details
> Integrate python version 3.12.

- .safety-policy.yml
- dev-requirements.txt
- docs/changes.rst
- minimum-constraints.txt
- test-requirements.txt
Modified safety policy dev-requirements, and minimum constraints for new issues with:
1. cryptograpy - New minimum 42.0.2 for python > 3.7
2. Jupyter Notebook - New Minimum 7.07 Python > 3.8
3. jupyter-server - recommendation of minim version from Notebook safety issue.
The new safety issues are as follows:
-> Vulnerability ID: 65183 Affected spec: >=7.0.0,<=7.0.6 ADVISORY: CVE-2024-22420 describes a vulnerability in Jupyter Notebook, where user interaction with a malicious notebook or Markdown file
enables an attacker to access and act with the same permissions as the user.
The flaw lies in the table of contents plugin. Jupyter Notebook v7.0.7
includes a patch for this issue. Users can manually disable the plugin as a
workaround. …
> Add fixes for new safety issues, 17 Mar 24.

- .flake8
- .github/workflows/test.yml
- Makefile
- dev-requirements.txt
- minimum-constraints.txt
- tests/end2endtest/test_indications.py
- tests/end2endtest/test_operation_timeouts.py
- tests/end2endtest/utils/pytest_extensions.py
- tests/unittest/pywbem/test_recorder.py
- tests/unittest/pywbem_mock/test_complexassoc.py
The Python "ruff" package is used, and is run on Python >=3.7.
For details, see the commit message and issue #3144.
> Added support for running ruff

- pywbem/_cim_obj.py
- pywbem/_recorder.py
Running coverity on version 0.15.0 which is the latest packaged version for fedora is reporting some errors.  I believe this PR addresses some potential issues that should be considered for inclusion.
> Coverity corrections

- docs/changes.rst
- pywbem/_listener.py
see commit message for description.
This fixes issue #3157 where the failure of the http server in pywbemcli startup causes the subprocess to hang because the callback thread was already created and was not shutdown .
rollback to 1.7.1 required.
NOTE: I assume that this also means that we should pull pywbem 1.7.0 in favor of 1.7.1.
> Fix issue where listener startup failure can cause extra exceptions.

- .github/workflows/test.yml
- docs/changes.rst
- test-requirements.txt
Rolls back PR #3171 into 1.7.3.
> 1.7: Fixed Python 3.6/3.7 on macos

- docs/changes.rst
- setup.py
> Eliminate build warning about ambiguous package list

- docs/mof_compiler.help.txt
- pywbem/_cim_http.py
- pywbem/_cim_obj.py
- pywbem/_cim_types.py
- pywbem/_recorder.py
- pywbem_mock/_baserepository.py
- tests/functiontest/README.md
- tests/unittest/pywbem/test_cim_obj.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
- tests/unittest/utils/pytest_extensions.py
Fix a number of issues documented as TODO-OLD-PYTHON.
**DISCUSSION:** There is one TODO-PYTHON still in the code, the use of x key in dictionary in the CIMInt code and used in functiontests to supply Uint32 data to the InvokeMethod function tests.  I would like the change for that issue to be considered separately, I want to think that one out more but the others are ready for review.
> Fix TODO-OLD-PYTHON flagged changes for python 3.8.

- docs/changes.rst
- pywbem/_cim_types.py
- pywbem/_tupleparse.py
This pr proposed to keep the x parameter and document it rather than modify the tests.  This covers anybody who might have been using x in the past also.  As far as I can tell, the position-only argument appears to be driven generally by implementations in C.
Modify the documentation on the CIMInt type definition to publicly support both the positional and  keyword definition of the input argument 'x' that defines the value of the CIMInt.
This differs from the definition of int() where the definition of the value argument is only positional for Python >= 3.7.  This provides compatibility for pre python 3.7 apps that use the CIM integer types Uint*, Sint*.
One other minor fix where there were still several uses of long in the documentation in pywbem. These were removed since effective with …
> Modify documentation on cim types for CIMInt.

- docs/changes.rst
- test-requirements.txt
This is a circumvention for the issue.
Issue https://github.com/pywbem/pywbem/issues/3198 is for the final solution and links to the details of the issue.
> Test: Excluded testfixtures 8.3.0 to circumvent a new AssertionError

- docs/changes.rst
- minimum-constraints.txt
- test-requirements.txt
Rolls back PR #3199 into 1.7.3.
> 1.7: Test: Excluded testfixtures 8.3.0 to circumvent a new AssertionError

- docs/changes.rst
- pywbem/_exceptions.py
- pywbem/_listener.py
- tests/unittest/pywbem/test_indicationlistener.py
Defines a new exception and exception handling so that user can define a queue full argument on listener initialization and the listener will create the exception and pass it to main thread  if the received indication queue reaches this limit.  If this condition occurs, the whole listener is effectively stopped and must be recreated because we have stopped receiving indications from the wbem server
* Defines an argument on the indication listener init  (max_ind_queue_size) that will define the QUEUE_FULL condition if the number of indications in the listener  indication queue exceeds that limit. This is an optional exception and is only enabled when a listener init argument defines a integer that represents the maximum number of integers allowed in the queue.
* Adds an exception …
> Add capability for listener to define a case where the received indication queue is full.

- .github/workflows/test.yml
- docs/changes.rst
For the attempt to debug this, see PR https://github.com/zhmcclient/python-zhmcclient/pull/1663.
I opened an issue against the actions/setup-python repo: https://github.com/actions/setup-python/issues/942
This PR fixes the issue permanently (without dependency on a resolution of the issue above).
If you have an idea why the login shell was specified for invoking coveralls, please comment on that during your review.
> Fixed coveralls not found on MacOS with py39-311

- .github/workflows/test.yml
- docs/changes.rst
Rolls back PR #3219 into 1.7.3.
> 1.7: Fixed coveralls not found on MacOS with py39-311

- docs/changes.rst
- test-requirements.txt
- tests/unittest/pywbem/test_recorder.py
Rolls back PR #3198 into 1.7.3.
No additional review needed.
> 1.7: Test: In test_recorder.py avoid a new AssertionError by testfixtures 8.3.0

- .github/workflows/test.yml
- base-requirements.txt
- dev-requirements.txt
- docs/changes.rst
- minimum-constraints-develop.txt
- minimum-constraints-install.txt
- pyproject.toml
- requirements.txt
- test-requirements.txt
- tox.ini
Specific review points:
* Workaround for FormEncode installation issue (see commit message)
* Workaround for pywin32 installation issue (see commit message)
Note, this PR uses RC1 of Python 3.13.0. Issue #3228 will upgrade this to the GA version of 3.13.0.
> Added tests for Python 3.13.0-rc.1

- .github/workflows/test.yml
- dev-requirements.txt
- docs/changes.rst
- minimum-constraints.txt
- requirements.txt
Rolls back PR #3245 into 1.7.3, plus the following fixes specific to the stable branch and its older set of supported Python versions:
* Changed Ubuntu image for Python 3.7 tests on Ubuntu.
* Removed Python 3.6/3.7 tests on MacOS.
* Circumvented issue with yamlloader on Python 3.6.
> 1.7: Circumvented issue with installing pywinpty

- Makefile
- docs/changes.rst
- minimum-constraints.txt
Rolls back PR #3247 into 1.7.3, but with a different solution.
> 1.7: Added twine deps; Replaced jupyter in check_reqs

- .safety-policy-all.yml
- .safety-policy-install.yml
- dev-requirements.txt
- docs/changes.rst
- minimum-constraints-install.txt
- minimum-constraints.txt
Rolls back PRs #3253 and #3256 into 1.7.
> 1.7: Fixed safety issued and missing dependencies

- changes/noissue.4.cleanup.rst
- tests/end2endtest/es_server.yml
Update the version of the OpenPegasus Docker file to match pywbemtool repo.  This version of the Docker file make several changes to the container to:
1. Clean up documentation
2. Add more tools to the build image to enhance testing of this image.
3. Standardize the names of the various makefiles
Note that the pywbemtools repo was updated to this version some time ago.
> Update version of OpenPegasus Docker file from 

- dev-requirements.txt
- minimum-constraints-develop.txt
Note: The actual safety issue fixes were pushed directly to master in commit 228b921
> Safety issues (2)

- .coveragerc
- .gitignore
- changes/noissue.vendorcov.cleanup.rst
- changes/noissue.vendorcov.fix.rst
> Omitted pywbem/_vendor subtree from coverage

- changes/noissue.111.fix.rst
- dev-requirements.txt
- minimum-constraints-develop.txt
> Increased version of safety to 3.6.2 to simplify its dependencies

- Makefile
- changes/noissue.75.fix.rst
> Fixed error detection when preparing LICENSE files for vendorized packages
