pywbem/pywbem

pywbem/cim_obj.py

Fixes #1985: Improved exception and description for NULL keybinding

---

docs/changes.rst
pywbem/mof_compiler.py
tests/unittest/pywbem/test_mof_compiler.py
tests/unittest/pywbem_mock/test_wbemconnection_mock.py
tests/utils.py

Fixes #2004: Silenced MOFCompiler for verbose=False; Fixed moftab version check

---

docs/changes.rst
pywbem/mof_compiler.py

Fixes #1996: Fixed that MOF compiler did raise error when ModifyClass failed

---

tests/unittest/pywbem_mock/test_wbemconnection_mock.py

Fixes #2016: Fixed mock delay test that sometimes failed

---

tests/unittest/pywbem_mock/test_wbemconnection_mock.py

Rolls back PR #2017 into 0.16.0.

0.16: Fixed mock delay test that sometimes failed

---

docs/changes.rst
docs/compiler.rst
pywbem/mof_compiler.py
pywbem_mock/_mockmofwbemconnection.py

Fixes #2001: Made the MOFWBEMConnection class internal and undocumented

---

pywbem/mof_compiler.py

Fixes #2014: Improved CIMError status descriptions in MOF compiler

---

pywbem/mof_compiler.py

Rolls back PR #2019 into 0.16.0.

0.16: Improved CIMError status descriptions in MOF compiler

---

dev-requirements.txt
docs/changes.rst
minimum-constraints.txt
tests/end2endtest/utils/server_definition_file.py
tests/functiontest/conftest.py

Fixes #2008: Replaced yamlordereddictloader package with yamlloader

---

docs/changes.rst
pywbem/_recorder.py
tests/unittest/pywbem/test_logging.py
tests/unittest/pywbem/test_recorder.py

Rolls back PR #2024 into 0.16.0

0.16: Ensured that log entries are single-lined, and fixed logger test

---

docs/changes.rst
pywbem/_recorder.py
tests/unittest/pywbem/test_logging.py
tests/unittest/pywbem/test_recorder.py

needed for migrating to requests (PR #2023).

Ensured that log entries are single-lined, and fixed logger test

---

docs/changes.rst
tests/unittest/pywbem/test_utils.py

Fixes #2027: Test: Fixed error in test_format_random() for backslash

---

docs/changes.rst
tests/unittest/pywbem/test_utils.py

Rolls back PR #2028 into 0.16.0.

0.16: Test: Fixed error in test_format_random() for backslash

---

docs/changes.rst
pywbem/cim_operations.py
tests/unittest/pywbem/test_cim_operations.py

Rolls back PR #2031 into 0.16.0.

0.16: Clarified x509 parm of WBEMConnection; added checks and tests

---

docs/changes.rst
pywbem/cim_operations.py
tests/unittest/pywbem/test_cim_operations.py

Fixes #2030: Clarified x509 parm of WBEMConnection; added checks and tests

---

.travis.yml
dev-requirements.txt

Moved coveralls run back to Python 3.4

---

pywbem/_subscription_manager.py
pywbem/cim_constants.py
pywbem/cim_http.py
pywbem/cim_operations.py
pywbem_mock/_wbemconnection_mock.py
tests/unittest/pywbem/test_cim_http.py
tests/unittest/pywbem/test_cim_operations.py
tests/unittest/pywbem/test_logging.py
tests/unittest/pywbem/test_recorder.py
tests/unittest/pywbem/test_wbemserverclass.py
tests/unittest/pywbem_mock/test_wbemconnection_mock.py

**Note: This PR is on top of PR #2023. Review only the last commit.**
This PR resulted from comments on PR #2023.
Ready for review and merge. For details, see the commit message.

Changed url,scheme,host in WBEMConnection to be normalized

---

docs/changes.rst
pywbem/cim_xml.py
tests/unittest/pywbem/test_cim_xml.py
tests/unittest/utils/validate.py

Fixes #2051: Test: Converted test_cim_xml.py to pytest; Fixed errors in cim_xml response elements

---

tests/unittest/pywbem/test_cim_obj.py

Test: Added tests for less/larger-than comparison of CIM objects

---

pywbem/cim_xml.py

Fixes #2050: Removed elements from prelim DTD 2.2 from cim_xml.py

---

docs/changes.rst
docs/intro.rst

No rollback planned, but please think about that.

Documented limitation that CORRELATOR is not supported

---

pywbem_mock/_mockmofwbemconnection.py
pywbem_mock/_resolvermixin.py
pywbem_mock/_wbemconnection_mock.py

See commit for details
Note that this primarily just changes documentation but actually just removes a few TODOS by implementing the change proposed.
It leaves 3 TODOs in pywbem_mock that I have not reached a conclusion on.

Fixes issue #1240 Convert TODOs in pywbem_mock code into issues

---

docs/changes.rst
pywbem_mock/_wbemconnection_mock.py
tests/unittest/pywbem_mock/test_wbemconnection_mock.py

This is one part of a multipart set of PRs that will refactor pywbem mock.

Partly fixes #2062: Part 1 of refactor of pywbem_mock

---

docs/appendix.rst
docs/changes.rst
docs/client/types.rst
pywbem/cim_obj.py
pywbem/cim_types.py
tests/unittest/pywbem/test_cim_obj.py
tests/unittest/pywbem/test_cim_types.py

Fixes #2052: Second stage of setting KEYVALUE TYPE attribute

---

docs/changes.rst
tests/README
tests/manualtest/run_cim_operations.py
tests/manualtest/run_enum_performance.py
tests/manualtest/run_enum_performancesimple.py
tests/manualtest/run_operationtimeouts.py
tests/manualtest/run_response_performance.py
tests/manualtest/run_uprint.py

Fixes #2039: Fixed imports in manual test scripts

---

docs/changes.rst
tests/README
tests/manualtest/run_cim_operations.py
tests/manualtest/run_enum_performance.py
tests/manualtest/run_operationtimeouts.py
tests/manualtest/run_response_performance.py
tests/manualtest/run_uprint.py

Rolls back PR #2083 into 0.17.0.

0.17: Fixed imports in manual test scripts

---

docs/changes.rst

Cleaned up list of incompatible changes in change log

---

appveyor.yml

Rolls back PR #2095 to 0.17.0.

0.17: Mitigated installation of make on Appveyor

---

appveyor.yml

Rolls back PR #2098 into 0.17.0.

0.17: Removed mitigation for installing make using choco

---

appveyor.yml

Rolls back PR #2035 into 0.17.0.

0.17: Reduced Appveyor tests from 4 to 3

---

appveyor.yml
makefile
tox.ini

Rolls back PR #2101 into 0.17.0.

0.17: Added locale settings ti fix issue with 'safety' command on CygWin

---

appveyor.yml
makefile
tox.ini

Fixes #2097: Added locale settings ti fix issue with 'safety' command on CygWin

---

tests/functiontest/conftest.py

Rolls back PR #2107 to 0.17.0.

0.17: Fixed incorrect exception class name in assertion message in function test

---

docs/changes.rst
docs/client/exceptions.rst
pywbem/_server.py
pywbem/cim_http.py
pywbem/cim_operations.py
pywbem/exceptions.py
tests/unittest/pywbem/test_exceptions.py

See the discussion point in issue #1423. Will be done in a separate PR.

Fixes #1423: Fixes and context for HTTPError and CIMError exceptions and change to use ModelError

---

makefile

Make clean removes temp vim files

---

makefile

Rolls back PR #2111 into 0.17.0.

0.17: Make clean removes temp vim files

---

tests/unittest/pywbem/test_statistics.py

Partly fixes #1414: Converted test_statistics.py from unittest to pytest

---

pywbem/_utils.py
pywbem/cim_http.py
pywbem/cim_obj.py
tests/end2endtest/utils/pytest_extensions.py
tests/unittest/pywbem/test_cim_operations.py
tests/unittest/pywbem/test_cim_xml.py
tests/unittest/pywbem/test_perf_equality.py

Changes:
| message id                         | occurrences (previously) | occurrences (now) |
|--------------------------|-----------|-----------|
| fixme                              |162         | 163 |
|using-constant-test                |8           | 8 |
|no-else-return                     |5           | 0 |
|no-member                          |4           | 4 |
|anomalous-unicode-escape-in-string |4           | 0 |
|unused-variable                    |3           | 0 |
|unused-argument                    |2           | 0 |
|too-few-public-methods             |2           | 2 |
|redefined-builtin                  |2           | 0 |
|no-value-for-parameter             |2           | 2 |
|wrong-import-order                 |1           | 0 |
|ungrouped-imports                  |1 …

Partly fixes #1413: Fixed Pylint issues

---

docs/changes.rst
docs/client/exceptions.rst
pywbem/cim_http.py
pywbem/exceptions.py
tests/unittest/pywbem/test_exceptions.py

Fixes #2110: Changed exception reporting HTTP header issues to new HeaderParseError

---

docs/changes.rst
docs/client.rst
docs/client/proxy.rst
pywbem/cim_operations.py
tests/unittest/pywbem/test_cim_operations.py

Ready for test and review. Please also review the new "Proxy support" section.

Fixes #2040: Added support for HTTP and SOCKS proxies

---

docs/changes.rst
pywbem/_listener.py

Rolls back PR #2103 into 0.17.0.

0.17: Switched to use SSLContext in WBEMListener

---

dev-requirements.txt
minimum-constraints.txt
rtd-requirements.txt

Updated minimum package versions for py34/py38

---

appveyor.yml
dev-requirements.txt
makefile
minimum-constraints.txt
rtd-requirements.txt
tox.ini

0.17: Fixed CygWin in Appveyor; Reduced Appveyor to 2 envs

---

appveyor.yml
dev-requirements.txt
minimum-constraints.txt
rtd-requirements.txt
tox.ini

Fixed CygWin in Appveyor; Reduced Appveyor to 2 envs

---

dev-requirements.txt
docs/changes.rst
minimum-constraints.txt

This change was rolled over from pywbemtools PR https://github.com/pywbem/pywbemtools/pull/550.

Fixed incorrect coverage reported after pytest

---

makefile

Minor cleanup in makefile: tabs/blanks & SHELL

---

dev-requirements.txt
docs/changes.rst
minimum-constraints.txt

Fixes #2135: Fixed installation of Jupyter Notebook on Python 3.4

---

dev-requirements.txt
docs/changes.rst
minimum-constraints.txt

Rolls back PR #2137 into 0.17.0

0.17: Fixed installation of Jupyter Notebook on Python 3.4

---

docs/changes.rst
pywbem/_version.py

Start 0.17.1

---

pywbem/_recorder.py
requirements.txt
tests/unittest/pywbem/test_recorder.py
tests/utils.py

Note: Issue #2118 has been created for the missing attributes this PR marks as TODOs. They will be addressed in a separate PR.

Partly fixes #1414: Changed test_recorder.py from unittest to pytest, and cleanups in _recorder.py

---

README.rst

Changed badges on README page

---

pylintrc
pywbem/_exceptions.py
pywbem_mock/_baserepository.py
pywbem_mock/_cimrepository.py
pywbem_mock/_mockmofwbemconnection.py
pywbem_mock/_resolvermixin.py
pywbem_mock/_wbemconnection_mock.py
tests/functiontest/conftest.py
tests/leaktest/test_leaks_cim_obj.py
tests/unittest/pywbem/test_statistics.py
tests/unittest/pywbem_mock/test_inmemory_repository.py
tests/unittest/pywbem_mock/test_wbemconnection_mock.py

Fixed pylint issues; fixed issue in exc message

---

dev-requirements.txt

0.17: Pinned requests for py26

---

dev-requirements.txt
docs/changes.rst
minimum-constraints.txt

Fixes #2153: Fixed version conflicts reported by pip for dev packages

---

dev-requirements.txt
docs/changes.rst
minimum-constraints.txt

Rolls back PR #2158 back into 0.17.1.

0.17: Fixed version conflicts reported by pip for dev packages

---

dev-requirements.txt
docs/changes.rst
minimum-constraints.txt
pywbem/_cim_types.py
tests/unittest/pywbem/test_cim_types.py

Fixes #2160: Fixed missing MinutesFromUTC.tzname(); added tests

---

dev-requirements.txt
docs/changes.rst
minimum-constraints.txt
pywbem/_cim_types.py
tests/unittest/pywbem/test_cim_types.py

Rolls back PR #2161 to 0.17.1.

0.17: Fixed missing MinutesFromUTC.tzname(); added tests

---

.travis.yml

Added empty lines to .travis.yml for consistency with master

---

docs/changes.rst
minimum-constraints.txt

Fixes #2167: Increased min version of setuptools on py37

---

.travis.yml
DEVELOP.md
appveyor.yml

0.17: Enabled manual CI run for stable branch; other cleanup in CI files

---

.travis.yml
DEVELOP.md
appveyor.yml

Rolls forward PR #2170 into master.

Enabled manual CI run for stable branch; other cleanup in CI files

---

docs/changes.rst
pywbem/_version.py

Do you approve releasing 0.17.1?

Release 0.17.1

---

dev-requirements.txt
docs/changes.rst
makefile
minimum-constraints.txt
tests/installtest/test_install.sh

Rolls back PR #2175 into 0.17.2.

0.17: Fixed a virtualenv creation failure during install test

---

dev-requirements.txt
docs/changes.rst
makefile
minimum-constraints.txt
tests/installtest/test_install.sh

Fixes #2174: Fixed a virtualenv creation failure during install test

---

docs/changes.rst
makefile
minimum-constraints.txt
requirements.txt
tools/python_unicodesize.py

[WIP] Fixes #2182: Test_recorder test complains about D800 character

---

docs/changes.rst
makefile
minimum-constraints.txt
requirements.txt
tools/python_unicodesize.py

Rolls back PR #2183 into 0.17.2.

0.17: Test_recorder test complains about D800 character

---

docs/changes.rst
pywbem/_server.py
tests/unittest/pywbem/test_wbemserverclass.py

Fixes #2187: Fixed raise error for invalid reference_direction in WBEMServer.get_central_instances()

---

docs/changes.rst
pywbem/_listener.py

Fixes #2188: Fixed raise error for missing ports in WBEMListener.__init__()

---

docs/changes.rst
pywbem/_version.py

Start 0.17.3

---

dev-requirements.txt
minimum-constraints.txt

A regular update to sync with python-cookiecutter. Not really driven by issues.

Updated dependencies for development

---

README.rst

Readme: Changed doc links to latest/master version

---

docs/mocksupport.rst
pywbem_mock/_baseprovider.py
pywbem_mock/_defaultinstanceprovider.py
pywbem_mock/_wbemconnection_mock.py
tests/unittest/pywbem_mock/test_wbemconnection_mock.py

Issue #2062 part 3c - Create method provider

---

docs/mocksupport.rst
makefile
pywbem_mock/_baseprovider.py
pywbem_mock/_baserepository.py
pywbem_mock/_defaultinstanceprovider.py
pywbem_mock/_wbemconnection_mock.py

Docs: Fixed formal aspects of mock docs

---

.travis.yml
dev-requirements.txt
minimum-constraints.txt
pywbem_mock/_defaultinstanceprovider.py
tests/installtest/test_install.sh

**Note: This PR is on top of PR #2215 - review only the delta (last commit)**

Fixes #2219: Fixed 'dictionary changed size during iteration' on pypy

---

dev-requirements.txt
minimum-constraints.txt
tests/installtest/test_install.sh

See commits. Ready for review.

Fixes #2214: Fixed Travis errors with use of implementation_name marker, and pip not installed

---

dev-requirements.txt
pywbem_mock/_baseprovider.py
pywbem_mock/_defaultinstanceprovider.py
pywbem_mock/_mainprovider.py
pywbem_mock/_wbemconnection_mock.py
tests/functiontest/conftest.py
tests/unittest/pywbem/test_logging.py
tests/unittest/pywbem_mock/test_wbemconnection_mock.py

Note, this fixes some real errors.

Resolved Pylint issues; Pinned Pylint to <2.5.0

---

pywbem_mock/_baseprovider.py
pywbem_mock/_namespaceprovider.py
pywbem_mock/_wbemconnection_mock.py

Marked WIP for the moment but it passes tests.
**DISCUSSION:** In this code I ignore  attribute error in call to post_register_setup(conn).  Not sure whether we should ignore (they supply if they want to) or error(they must supply at least a dummy). Since this is server side code, I figured that they will figure it out.

Partly fixes #2062: part5b refactor register provider

---

pywbem_mock/_baseprovider.py
pywbem_mock/_baserepository.py
pywbem_mock/_defaultinstanceprovider.py
pywbem_mock/_defaultmethodprovider.py
pywbem_mock/_dmtf_cim_schema.py
pywbem_mock/_mainprovider.py
pywbem_mock/_namespaceprovider.py
pywbem_mock/_wbemconnection_mock.py

Formal and light content improvements of mock docs

---

docs/mocksupport.rst
pywbem_mock/__init__.py
pywbem_mock/_instancewriteprovider.py
pywbem_mock/_methodprovider.py
pywbem_mock/_namespaceprovider.py
pywbem_mock/_providerdispatcher.py
pywbem_mock/_wbemconnection_mock.py

WIP because I need to add test.
Changes to complete the basic user-defined provider code including:
1. Change the names of the provider files to methodprovider,
instancewriteprovider.
2. Add try block for the call to provider CreateInstance,
ModifyInstance, CreateInstance to execute the default method as
a fallback.
3. Add some documentation.

WIP Changes to close out some issues with issue#2062

---

pywbem_mock/_baseprovider.py
pywbem_mock/_mainprovider.py
pywbem_mock/_namespaceprovider.py
pywbem_mock/_resolvermixin.py
pywbem_mock/_wbemconnection_mock.py
tests/unittest/pywbem_mock/test_system_providers.py
tests/unittest/pywbem_mock/test_wbemconnection_mock.py

Fixes #2229: clean up convience functions

---

tests/unittest/pywbem/test_mof_compiler.py

Fixes #369: Cleaned up direct access of MOFWBEMConnection instance attrs

---

pywbem_mock/_baseprovider.py
pywbem_mock/_namespaceprovider.py
pywbem_mock/_wbemconnection_mock.py
tests/unittest/pywbem_mock/test_wbemconnection_mock.py

Complete.  Adds display of registered provider and tests.
In latest revision I made the _provider_namespace, etc. public methods.

Fixes #2233: display registered providers

---

docs/changes.rst
pywbem/_mof_compiler.py
pywbem_mock/_mockmofwbemconnection.py
tests/unittest/pywbem/test_mof_compiler.py
tests/unittest/pywbem_mock/test_wbemconnection_mock.py

Fixes #2247: MOF compiler changes default_namespace

---

README.rst

Fixed broken link in README

---

docs/changes.rst
docs/client/conversion.rst
pywbem/_cim_obj.py
pywbem/_cim_operations.py
pywbem/_nocasedict.py
pywbem_mock/_dmtf_cim_schema.py
pywbem_mock/_wbemconnection_mock.py
tests/unittest/pywbem/test_cim_obj.py
tests/unittest/pywbem/test_cim_operations.py

Fixes #2263: Removed deprecated functionality

---

docs/changes.rst

See the open items in the next comment.

Change log: Prepared for beta version and general improvements

---

docs/intro.rst
pywbem/_cim_operations.py

Fixed and improved Intro chapter of docs

---

docs/mockwbemserver.rst

Improved mock documentation

---

pywbem/_cim_obj.py

Fixed docs and sorting of CIMInstanceName.to_wbem_uri()

---

docs/mockwbemserver.rst
pywbem_mock/_baseprovider.py
pywbem_mock/_instancewriteprovider.py
pywbem_mock/_mainprovider.py
pywbem_mock/_providerdispatcher.py
pywbem_mock/_wbemconnection_mock.py
tests/unittest/pywbem_mock/test_wbemconnection_mock.py

Fixes #2298: Make BaseProvider.get_bare_instance() private

---

.travis.yml
README_PYPI.rst
appveyor.yml
docs/changes.rst
pywbem/_version.py

Release 1.0.0b1

---

docs/changes.rst
pywbem/_version.py

Start 1.0.0b2

---

docs/changes.rst

Fixes #2303: Split change log of 1.0.0b1

---

docs/changes.rst
pywbem/_version.py

Release 1.0.0b2

---

docs/changes.rst
pywbem/_version.py

Release 0.17.3

---

docs/changes.rst
pywbem/_version.py

Start 0.17.4.dev1

---

docs/changes.rst
pywbem/_version.py

Changed version 1.0.0 to 1.0.0b3

---

pywbem/_cim_operations.py
pywbem_mock/_mainprovider.py

Minor doc fixes and renames in mock support

---

docs/changes.rst
pywbem/_cim_operations.py
pywbem_mock/_instancewriteprovider.py
pywbem_mock/_mainprovider.py
tests/functiontest/pullinstances.yaml
tests/functiontest/pullinstanceswithpath.yaml
tests/unittest/pywbem/test_itermethods.py
tests/unittest/pywbem_mock/test_wbemconnection_mock.py

For details, see commit messages.
The commits are intentionally separated to break this large PR down into some reasonable steps. Each commit can be reviewed independently.

Fixes #2313: Fixed validation in main provider and instance write provider

---

tests/unittest/pywbem_mock/test_wbemconnection_mock.py

Reworked mocker testcase test_associator_instances() as a proposal on
how all mocker testcases ultimately should be reworked. The rework
solves these issues:
- No special cases anymore in the test function code
- The testcase definition is moved into a variable to shorten the
display by pytest.
- A testcase description has been added to identify the testcase in
pytest display, and to point out to a reader what is the point of
the testcase.
- Added all input parameters of the function to be tested, to the
testcase definition.

Reworked mocker testcase test_associator_instances()

---

docs/changes.rst
pywbem/_cim_operations.py
pywbem_mock/_baseprovider.py
pywbem_mock/_dmtf_cim_schema.py
pywbem_mock/_instancewriteprovider.py
pywbem_mock/_mainprovider.py
pywbem_mock/_methodprovider.py
pywbem_mock/_namespaceprovider.py
pywbem_mock/_providerdispatcher.py
pywbem_mock/_resolvermixin.py
pywbem_mock/_wbemconnection_mock.py
pywbem_mock/config.py
tests/unittest/pywbem_mock/conftest.py
tests/unittest/pywbem_mock/test_wbemconnection_mock.py

This PR is now complete from my perspective and should get a final review.
There is still this an open discussion item, see review comments below.

Fixes #2326: Simplified providers by moving checks to caller and improved docs

---

docs/mockwbemserver.rst
pywbem_mock/_instancewriteprovider.py
pywbem_mock/_mainprovider.py
pywbem_mock/_methodprovider.py
pywbem_mock/_wbemconnection_mock.py
tests/unittest/pywbem/test_mof_compiler.py
tests/unittest/pywbem/test_recorder.py
tests/unittest/pywbem/test_wbemserverclass.py
tests/unittest/pywbem_mock/test_complexassoc.py
tests/unittest/pywbem_mock/test_wbemconnection_mock.py
tests/unittest/utils/wbemserver_mock.py

Docs fixes: Syntax errors; remaining term mock repo in tests

---

.travis.yml

Rolls back PR #2335 into 0.17.4

0.17: Fixed py38 upgrade issue on macOS on Travis

---

docs/changes.rst
pywbem_mock/_baseprovider.py
pywbem_mock/_providerdispatcher.py
tests/unittest/pywbem_mock/test_wbemconnection_mock.py

**Note:** This PR is on top of the (rebased) PR #2331 .

Fixed embedded_object check in CreateInstance dispatcher method

---

docs/changes.rst
pywbem/_version.py

Requesting approval for release of 1.0.0b3.
See PR #791 for a run with this code level on all environments.
See https://pywbem.readthedocs.io/en/latest/changes.html for the change log of 1.0.0b3.

Release 1.0.0b3

---

pywbem/_cim_operations.py
pywbem/_exceptions.py
pywbem_mock/_mainprovider.py
pywbem_mock/_namespaceprovider.py
pywbem_mock/_providerdispatcher.py
pywbem_mock/_wbemconnection_mock.py
setup.py
tests/end2endtest/test_profile_snia_server.py
tests/end2endtest/utils/pytest_extensions.py
tests/manualtest/run_operationtimeouts.py
tests/unittest/pywbem/test_exceptions.py
tests/unittest/pywbem/test_logging.py
tests/unittest/pywbem/test_mof_compiler.py
tests/unittest/pywbem/test_valuemapping.py
tests/unittest/pywbem_mock/test_wbemconnection_mock.py

New Pylint result with this PR:
```
+--------------------+------------+
|message id          |occurrences |
+====================+============+
|fixme               |131         |
+--------------------+------------+
|using-constant-test |8           |
+--------------------+------------+
|redefined-builtin   |2           |
+--------------------+------------+
```

Addressed Pylint issues

---

docs/changes.rst
docs/client/objects.rst
pywbem/__init__.py
pywbem/_nocaselist.py
tests/unittest/pywbem/test_nocaselist.py

This PR adds a `NocaseList` class, but does not use it yet for anything other than testing.
The implementation and test cases are complete now.

Partly fixes #2253: Added NocaseList and corresponding tests

---

makefile
pywbem/__init__.py
tests/unittest/pywbem/test_cim_obj.py
tests/unittest/pywbem/test_mof_compiler.py

Fixes #1413: Addressed Pylint issues and enforced clean Pylint results

---

makefile
minimum-constraints.txt
requirements.txt

Fixes #2253: Using released nocaselist 1.0.0

---

docs/changes.rst
pywbem_os_setup.bat

0.17: Fixed swig issue on Appveyor

---

docs/changes.rst
pywbem/_version.py

Release 0.17.4

---

docs/changes.rst
pywbem_os_setup.bat

Fixed swig issue on Appveyor

---

docs/changes.rst
pywbem/_version.py

Start 0.17.5

---

docs/changes.rst
pywbem/_cim_types.py
pywbem_mock/_mainprovider.py
pywbem_mock/_mockmofwbemconnection.py
tests/manualtest/run_cim_operations.py
tests/unittest/pywbem/test_mof_compiler.py

Changed the order of inheriting from mixin classes

---

docs/changes.rst
pywbem/_cim_obj.py

Fixed docs of CIMInstanceName.keys(), values(), items() for py3

---

docs/changes.rst
minimum-constraints.txt
requirements.txt

Fixed inconsistent dependency to six package

---

docs/changes.rst
minimum-constraints.txt
pywbem_mock/_resolvermixin.py
requirements.txt

Renamed loop variables for names and CIM objects for consistency

---

.travis.yml
docs/changes.rst

Enabled coveralls to run on all Python versions in the Travis CI

---

tests/unittest/pywbem/test_cim_obj.py

Made iter..() tests on CIMInstance/Name run on all Python versions

---

docs/changes.rst
pywbem_os_setup.sh

Fixed test install issue on CygWin due to missing libffi-devel

---

docs/changes.rst
pywbem/_version.py

Already agreed upon - no review needed.

Downgraded version to 1.0.0b4 (.dev1)

---

docs/changes.rst
pywbem/_version.py

Please approve the release of 1.0.0b4.
Note: This PR is on top of PR #2392.

Release 1.0.0b4

---

tests/unittest/pywbem/test_indicationlistener.py

This PR is in preparation of fixing issue #2383, but it stands on its own and provides value independent of that fix.
Please review.

0.17: Improved diagnostics for failures in indication testing

---

docs/changes.rst
pywbem/_version.py

Start 1.1.0

---

docs/changes.rst
pywbem/_listener.py
tests/unittest/pywbem/test_indicationlistener.py

Rolls back PR #2405 / #2407 into 0.17.5.

0.17: Improved logging in WBEM listener and its test module

---

docs/changes.rst
pywbem/_listener.py
tests/unittest/pywbem/test_indicationlistener.py

Same content as PR #2405 (which was approved and targeted 1.1), just targeting 1.0.0 final now.

Improved logging in WBEM listener and its test module

---

docs/changes.rst
pywbem/_cim_operations.py
pywbem_mock/_mainprovider.py
pywbem_mock/_wbemconnection_mock.py
tests/unittest/pywbem_mock/test_wbemconnection_mock.py

Multiple fixes for OpenQueryInstances() in WBEMConnection, mock, testcases

---

docs/changes.rst
pywbem/_cim_operations.py
pywbem_mock/_mainprovider.py
pywbem_mock/_wbemconnection_mock.py
tests/unittest/pywbem_mock/test_wbemconnection_mock.py

Rolls back PR #2413 into 1.0.1.

1.0: Multiple fixes for OpenQueryInstances() in WBEMConnection, mock, testcases

---

docs/changes.rst
pywbem_mock/_methodprovider.py
pywbem_mock/_providerdispatcher.py
tests/unittest/pywbem_mock/test_wbemconnection_mock.py

Added support for NocaseDict as output parameters type in method providers

---

docs/changes.rst
pywbem_mock/_methodprovider.py
pywbem_mock/_providerdispatcher.py
tests/unittest/pywbem_mock/test_wbemconnection_mock.py

Rolls back PR #2416 into 1.0.1.

1.0: Added support for NocaseDict as output parameters type in method providers

---

docs/changes.rst
pywbem/_version.py

Please approve the release of pywbem 1.0.1.

Release 1.0.1

---

docs/changes.rst
pywbem/_version.py

Start 1.0.2

---

docs/changes.rst
pywbem/_cim_http.py
tests/functiontest/headers.yaml

Fixed erronously raised HeaderParseError for Content-type text/xml

---

docs/changes.rst
pywbem/_cim_http.py
tests/functiontest/headers.yaml

Rolls back PR #2421 into 1.0.2.

1.0: Fixed erronously raised HeaderParseError for Content-type text/xml

---

docs/changes.rst
pywbem/_version.py

Please approve the release of pywbem 1.0.2.

Release 1.0.2

---

docs/changes.rst
pywbem/_version.py

Start 1.0.3

---

docs/changes.rst
pywbem/_cim_operations.py
tests/unittest/pywbem/test_cim_operations.py

This change is used by the pywbemtools support for displaying units in instance table output.

Added a new method is_subclass() to WBEMConnection

---

docs/changes.rst
docs/client.rst
docs/client/units.rst
pywbem/__init__.py
pywbem/_units.py
tests/unittest/pywbem/test_units.py

**Note: If this PR is merged, PR https://github.com/pywbem/pywbemtools/pull/731 needs to be updated to get pywbem from master.**

Added support for translating PUnit and Units qualifiers to SI units

---

docs/changes.rst
minimum-constraints.txt
pywbem_mock/__init__.py
pywbem_mock/_inmemoryrepository.py
pywbem_mock/_providerregistry.py
requirements.txt
tests/unittest/pywbem_mock/test_inmemory_repository.py
tests/unittest/pywbem_mock/test_providerregistry.py

The second commit added testcases for the new methods.

Support for caching mock environments

---

test-requirements.txt
tests/unittest/pywbem/test_mof_compiler.py

Fixed PytestCollectionWarning in test_mof_compiler.py; added hint to Pytest issue in reqs

---

docs/changes.rst
minimum-constraints.txt
pywbem_mock/_baserepository.py
pywbem_mock/_inmemoryrepository.py
requirements.txt

Rolls back PR #2437 into 1.0.3

Fixes issue # 2436, Remove package custom-inherit from pywbem

---

dev-requirements.txt
docs/changes.rst
minimum-constraints.txt
requirements.txt

1.0: Fixed dependency issues with 'pyrsistent' package on py27 and py34

---

dev-requirements.txt
docs/changes.rst
minimum-constraints.txt
requirements.txt

Fixed dependency issues with 'pyrsistent' package on py27 and py34

---

docs/changes.rst
docs/mockwbemserver.rst
pywbem_mock/__init__.py
pywbem_mock/_providerdependentregistry.py
pywbem_mock/_wbemconnection_mock.py
tests/unittest/pywbem_mock/test_providerdependentregistry.py

This is in support of https://github.com/pywbem/pywbemtools/issues/748.

Mock: Added a registry of provider dependent files

---

pywbem_mock/_providerdependentregistry.py
tests/unittest/pywbem_mock/test_providerdependentregistry.py

Changed iter_dependents() to return accessible path names

---

docs/changes.rst
tests/functiontest/conftest.py

Test: Changed collection of .yaml files to address pytest DeprecationWarning

---

pywbem/_cim_operations.py
tests/unittest/pywbem/test_itermethods.py

Added tests for Iter operations

---

examples/enumerator_generator.py
examples/send_indications.py
mof_compiler
tests/manualtest/run_enum_performance.py
tests/manualtest/run_enum_performancesimple.py
tests/manualtest/run_response_performance.py
try/run_central_instances.py

Cleaned up the help formatting of mof_compiler and other scripts

---

docs/changes.rst
pywbem_os_setup.bat

Upgraded WinOpenSSL to 1.1.1h

---

docs/changes.rst
pywbem_os_setup.bat

Rolls back PR #2459 into 1.0.3.

1.0: Upgraded WinOpenSSL to 1.1.1h

---

docs/changes.rst
pywbem/_version.py

Start 0.17.6

---

docs/changes.rst
pywbem_os_setup.bat

Rolls back PR #2459 into 0.17.6.

0.17: Upgraded WinOpenSSL to 1.1.1h

---

appveyor.yml
makefile

Rolls back PR #2467 into 1.0.3

1.0: Added pip environment info; Mitigated virtualenv creation issue

---

appveyor.yml
makefile

Added pip environment info; Mitigated virtualenv creation issue

---

appveyor.yml
makefile

Rolls back PR #2467 into 0.17.6

0.17: Added pip environment info; Mitigated virtualenv creation issue

---

dev-requirements.txt

0.17: Fixed installtest failure on cygwin by excluding virtualenv 20.0.32

---

docs/changes.rst
tests/unittest/pywbem/test_mof_compiler.py
tests/unittest/pywbem/testmofs/test_instance.mof

Defined the two missing embedded... properties with values and added tests for those values.

Fixes #464: Finished incomplete embedded instance test

---

docs/changes.rst
pywbem/_cim_obj.py
pywbem_mock/_mockmofwbemconnection.py
tests/unittest/pywbem/test_cim_obj.py
tests/unittest/utils/pytest_extensions.py
tests/unittest/utils/validate.py

This one came up during PR #2475.

Test: Added checking for no expected warning

---

docs/changes.rst
pywbem/_cim_obj.py
tests/unittest/pywbem/test_cim_obj.py

Deprecated propagation of key properties to path in CIMInstance

---

docs/changes.rst
minimum-constraints.txt
requirements.txt

Upgraded nocasedict and nocaselist to pick up fixes

---

docs/changes.rst
minimum-constraints.txt
requirements.txt

Rolls back PR #2480 into 1.0.3.

1.0: Upgraded nocasedict and nocaselist to pick up fixes

---

docs/changes.rst
makefile
test-requirements.txt

Test: Ensuring indirect dependencies are at latest versions

---

docs/changes.rst
pywbem/_version.py

Please approve the release of pywbem 0.17.6

Release 0.17.6

---

.travis.yml
README_PYPI.rst
appveyor.yml
docs/changes.rst
pywbem/_version.py

Please approve the release of pywbem 1.1.0

Release 1.1.0

---

docs/changes.rst
pywbem/_version.py

Start 1.1.1

---

makefile

Added make todo

---

docs/changes.rst
pywbem/_version.py

Start 1.2.0

---

docs/changes.rst
tests/functiontest/conftest.py
tests/unittest/pywbem_mock/test_wbemconnection_mock.py

Cleaned up DeprecationWarning for the propagation of key property values

---

pywbem/_mof_compiler.py
tests/unittest/pywbem_mock/test_wbemconnection_mock.py

Rolls back PR #2503 into 1.1.1.

1.1: Fixes issue #2502 pywbem compiler issue building in second namespace

---

docs/changes.rst

1.1: Fixed changelog for issue 2502

---

docs/changes.rst

Fixed changelog for issue 2502

---

docs/changes.rst
pywbem/_version.py

Please approve the release of pywbem 1.1.1.
For changes since 1.1.0, see the change log (in this PR)

Release 1.1.1

---

docs/changes.rst
pywbem/_version.py

Start 1.1.2

---

docs/changes.rst
pywbem/_tupleparse.py
tests/functiontest/references_instances.yaml
tests/unittest/pywbem/test_indicationlistener.py

I don't think this PR needs to be rolled back into pywbem 1.1.

Improved exception handling for received CIM-XML in tuple parser

---

.travis.yml
dev-requirements.txt
makefile
minimum-constraints.txt
tests/resourcetest/memory_utils.py
tests/resourcetest/random_objects.py
tests/resourcetest/resource_measurement.py
tests/resourcetest/test_enuminst.py
tests/resourcetest/timers.py
tests/unittest/resourcetest/test_memory_utils.py
tox.ini

Notes:
* There is no measurement of CIM-XML based resource consumption at this point. It would require adding server-side CIM-XML support to the mock environment, and that seemed too big of a task right now.
Output of `make resourcetest`:
```
tests/resourcetest/test_enuminst.py 
Resource consumption test: EnumerateInstances with num_props=1, num_insts=1:
Elapsed time:        2.395 ms
CPU time:            2.285 ms
Peak usage:          38895 B
Result size:          3960 B
.
Resource consumption test: EnumerateInstances with num_props=10, num_insts=100:
Elapsed time:      230.473 ms
CPU time:          229.457 ms
Peak usage:         842896 B
Result size:       1108848 B
.
Resource consumption test: EnumerateInstanceNames with num_props=1, …
```

Resource consumption tests

---

docs/changes.rst
pywbem/_version.py

Please approve the release of pywbem 1.1.2

Release 1.1.2

---

docs/changes.rst
pywbem/_version.py

Start 1.1.3

---

tests/unittest/resourcetest/test_memory_utils.py

Fixed calculation of expected object sizes in unit test of total_sizeof()

---

.travis.yml
dev-requirements.txt
docs/changes.rst
minimum-constraints.txt
pywbem_os_setup.sh
setup.py
tests/functiontest/conftest.py
tests/resourcetest/resource_measurement.py
tests/unittest/pywbem/test_utils.py
tests/unittest/resourcetest/test_memory_utils.py
tests/unittest/utils/validate.py

See commit messages for details.

Enabled pypy3, py39; Various fixes for that and for pypy2

---

docs/changes.rst
pywbem/_cim_obj.py
pywbem/_exceptions.py
pywbem/_listener.py
pywbem/_tupleparse.py
tests/unittest/pywbem/test_cim_obj.py
tests/unittest/pywbem/test_indicationlistener.py
tests/unittest/pywbem/test_tupleparse.py

See commit messages for details.
Each commit is a logical step in this PR, and the commit messages are rather detailed.
Test coverage in the tuple parser is now at 100% :-)

Fixes, cleanup and coverage improvements in tuple parser

---

docs/changes.rst
pywbem/_cim_operations.py

Rolls back PR #2532 into 1.1.3.
No separate review needed.

1.1: Fixed DeprecationWarning issued by urllib3

---

pywbem_mock/_providerdependentregistry.py
tests/unittest/pywbem_mock/test_providerdependentregistry.py

Fixed handling of path names in ProviderDependentRegistry

---

.github/workflows/test.yml
DEVELOP.md

This migrates from using the manual-ci-run branch to running the full envs on master.

Fixed scheduled test runs; Fixed releasing/starting a version docs

---

docs/changes.rst
pywbem_os_setup.sh

Fixed issue on GitHub Actions with macos

---

docs/changes.rst
pywbem_os_setup.sh

Rolls back PR #2548 into 1.1.3

1.1: Fixed issue on GitHub Actions with macos

---

.github/workflows/test.yml
pywbem_os_setup.bat

Rolls back PR #2550 into 1.1.3

1.1: Fixed WinOpenSSL version on Windows with py27; added py27 to normal tests

---

minimum-constraints.txt

Fixed safety issue 39253 with py

---

.github/workflows/test.yml

Removed minimum levels from normal test envs

---

.github/workflows/test.yml

Rolls back PR #2557 into 1.1.3.

1.1: Removed minimum levels from normal test envs

---

pywbem_mock/_providerdependentregistry.py
tests/unittest/pywbem_mock/test_providerdependentregistry.py

Rolls back PR #2536 into 1.1.3.

1.1: Fixed handling of path names in ProviderDependentRegistry

---

docs/changes.rst
pywbem/_version.py

Please approve the release of pywbem 1.1.3.
This will be the minimum release for the upcoming pywbemtools 0.8.1.
Change log: https://github.com/pywbem/pywbem/blob/release_1.1.3/docs/changes.rst#pywbem-113

Release 1.1.3

---

docs/changes.rst
pywbem/_version.py

Start 1.1.4

---

docs/changes.rst
pywbem_mock/_methodprovider.py

Docs: Fixed incorrect attr 'provider_classnames' in method provider example

---

dev-requirements.txt
docs/changes.rst

Mitigated the coveralls HTTP status 422

---

dev-requirements.txt
docs/changes.rst

Rolls back PR #2573 into 1.1.4

1.1: Mitigated the coveralls HTTP status 422

---

docs/changes.rst
pywbem/_units.py
tests/unittest/pywbem/test_units.py

Extended siunit() to support more flexible PUnit format

---

docs/changes.rst
pywbem/_mof_compiler.py
pywbem_mock/_wbemconnection_mock.py

Improved MOF compiler messages

---

tests/unittest/pywbem_mock/test_wbemconnection_mock.py

Removed MOF compiler messages during test

---

pywbem_mock/_wbemconnection_mock.py

Reverted change to log_func parm of MOFCompiler

---

docs/changes.rst
pywbem/_mof_compiler.py

Set to priority because the new compile commands in pywbemtools need this fix.

Fixed issue with ModifyInstance path in MOF compiler

---

makefile

Ignoring safety issue 39462 for tornado

---

dev-requirements.txt
minimum-constraints.txt

Increased bleach package to 3.3.0 where possible

---

docs/changes.rst
pywbem_mock/_mainprovider.py
tests/unittest/pywbem_mock/test_wbemconnection_mock.py

Fixes #2585 - add test to DeleteQualifier in pywbem_mock

---

docs/changes.rst
pywbem/_cim_operations.py
tests/unittest/pywbem/test_cim_operations.py

Added close() method to WBEMConnection and context manager

---

dev-requirements.txt
docs/changes.rst
pylintrc
pywbem/_listener.py
pywbem/_mof_compiler.py
pywbem/_statistics.py
tests/end2endtest/utils/utils.py

Fixed incorrect statistics min/max of server time

---

docs/changes.rst
pywbem/_statistics.py
tests/unittest/pywbem/test_statistics.py

Suspended statistics counting for partial server response time

---

makefile

Fixed safety issues

---

makefile

Reliable order in pylint output for make todo

---

dev-requirements.txt
minimum-constraints.txt

Fixed flake8 and lazy-object-proxy install issues via dependencies

---

.github/workflows/notify.yml

More debug in notify workflow

---

.github/workflows/notify.yml

More debug in notify workflow; restructured condition

---

.github/workflows/notify.yml

notify: run always for debug

---

.github/workflows/notify.yml

Notify workflow runs only on scheduled tests

---

.github/workflows/test.yml

Temporary change of scheduled test to SUN 12:00 UTC

---

.github/workflows/notify.yml

Simplified notify workflow and added setup instructions

---

dev-requirements.txt
docs/appendix.rst
docs/changes.rst
docs/client/exceptions.rst
docs/client/logging.rst
docs/client/objects.rst
docs/client/operations.rst
docs/client/statistics.rst
docs/client/types.rst
docs/client/valuemappings.rst
docs/client/warnings.rst
docs/compiler.rst
docs/conf.py
docs/indication.rst
docs/mockwbemserver.rst
docs/server.rst
docs/subscription.rst
minimum-constraints.txt
pywbem/_cim_obj.py
pywbem/_cim_types.py
pywbem/_exceptions.py
pywbem/_nocasedict.py

Used 'autodocsumm' Sphinx extension; moved base classes to appendix; other fixes

---

rtd-requirements.txt

Fixed RTD docs build with autodocsumm

---

docs/changes.rst
mof_compiler
pywbem/_mof_compiler.py
tests/unittest/pywbem/test_mof_compiler.py

Removed ResourceWarning about unclosed sockets in mof_compiler

---

issues/badstatusline/badstatusline.py

I think we should keep such issue reproduction scripts in the repo. This is the first one.

Added issues subtree with badstatusline script

---

docs/changes.rst
docs/concepts.rst
pywbem/_cim_operations.py
pywbem/_mof_compiler.py
pywbem/_server.py
pywbem_mock/_mainprovider.py
pywbem_mock/_namespaceprovider.py
tests/functiontest/execquery.yaml
tests/unittest/pywbem/test_mof_compiler.py

Removes some TODOs by fixing code, creating an issue, or changing the to
do to a Note.  NBote that this only fixes issued in pywbem and pywbemtools:
See commit for more details.
Reduces total number of TODOs in pywbem code to about 6.
DISCUSSION:
I would like to discuss the following TODOs
```
pywbem/_recorder.py:577:            # TODO: future bypassed code to only ouput name and method if the
pywbem/_listener.py:988:        # TODO: Describe how the processing threads terminate.
pywbem/_cim_operations.py:1631:                # TODO execute stage of wbem connection if not already executed.
```
NOTE: This does not fix all TODOs so I did not mark issue #1491 for close
All the TODOS with changes and DISCUSSION items marked:
```
pywbem/_recorder.py:577:            # TODO: future bypassed code …
```

Fixes for issue #2491 - Remove TODOS

---

docs/changes.rst
tests/unittest/pywbem/test_indicationlistener.py

Workaround for BadStatusLine issue

---

dev-requirements.txt
docs/conf.py
minimum-constraints.txt
pylintrc

Addressed remaining TODOs in requirement files, pylintrc, and conf.py

---

.github/workflows/test.yml

Reduced perftest to run only on scheduled and release runs; cleanup

---

dev-requirements.txt
docs/changes.rst
minimum-constraints.txt

Fixed installation of pywinpty

---

.github/workflows/test.yml
docs/changes.rst

Split commands into separate steps in test workflow

---

tests/perftest/test_indications.py
tests/unittest/pywbem/test_indicationlistener.py
tests/utils.py

Extended BadStatusLine retry to perftest code

---

Makefile
minimum-constraints.txt

Fixed safety issue 40291

---

Makefile
minimum-constraints.txt

Rolls back PR #2690 into 1.2.1.

1.2: Fixed safety issue 40291

---

docs/changes.rst
pywbem/_mof_compiler.py

Rolls back PR #2693 into 1.2.1.

1.2: Fix mof_compiler unwanted output of log data

---

dev-requirements.txt
docs/changes.rst
rtd-requirements.txt

Docs: Fixed an error with the autodocsumm and Sphinx 4.0.0

---

dev-requirements.txt
docs/changes.rst
rtd-requirements.txt

Rolls back PR #2698 into 1.2.1.

1.2: Docs: Fixed an error with the autodocsumm and Sphinx 4.0.0

---

Makefile
docs/changes.rst
minimum-constraints.txt
test-requirements.txt
tests/end2endtest/es_schema.yml
tests/end2endtest/es_vault.yml
tests/end2endtest/utils/pytest_extensions.py

Test: Added support for validating user-defined properties in easy-server files

---

Makefile
docs/changes.rst

Rolls back PR #2706 into 1.2.1

1.2: Circumvented safety issues 40380..40386 with the notebook package

---

.github/workflows/test.yml

Moved scheduled run to 01:00 UTC

---

docs/changes.rst
pywbem/_units.py

Finalized support for SI units

---

docs/changes.rst
pywbem/_listener.py
tests/unittest/pywbem/test_indicationlistener.py

Fixed errors in header values in WBEM listener

---

docs/changes.rst
pywbem/_listener.py
tests/unittest/pywbem/test_indicationlistener.py

Rolls back PR #2733 into 1.2.1.

1.2: Fixed errors in header values in WBEM listener

---

docs/changes.rst

Fixed Sphinx warnings in change log

---

docs/changes.rst
pywbem/_cim_http.py
pywbem/_cim_operations.py
pywbem/_tupleparse.py
tests/functiontest/exportindication.yaml
tests/functiontest/invalidexpresponseerror.yaml
tests/unittest/pywbem/test_cim_operations.py
tests/unittest/pywbem/test_recorder.py

Added support for ExportIndication export operation

---

docs/changes.rst
tests/unittest/pywbem/test_recorder.py

Test: Improved diff display when assertion in test_recorder.py fails

---

docs/changes.rst
pywbem/_cim_operations.py

Tolerated servers returning CIM_ERR_FAILED when not supporting pull ops

---

docs/changes.rst
pywbem/_cim_operations.py
pywbem/_recorder.py
pywbem_mock/_wbemconnection_mock.py
tests/unittest/pywbem/test_cim_operations.py
tests/unittest/pywbem/test_recorder.py
tests/unittest/pywbem_mock/test_wbemconnection_mock.py
tests/unittest/utils/unittest_extensions.py

Added copy() to Faked/WBEMConnection and recorder classes

---

docs/changes.rst
pywbem/_cim_operations.py
tests/unittest/pywbem/test_cim_operations.py

Made WBEMConnection.timeout property settable

---

dev-requirements.txt
docs/changes.rst
pylintrc
pywbem/_cim_obj.py
pywbem/_mof_compiler.py
pywbem/_recorder.py
pywbem/_statistics.py
pywbem/_units.py
pywbem/_utils.py
pywbem_mock/_dmtf_cim_schema.py
pywbem_mock/_providerdispatcher.py
pywbem_mock/_wbemconnection_mock.py
tests/end2endtest/utils/utils.py
tests/functiontest/conftest.py
tests/manualtest/run_cim_operations.py
tests/resourcetest/memory_utils.py
tests/unittest/pywbem/test_cim_operations.py
tests/unittest/pywbem/test_cim_xml.py
tests/unittest/pywbem/test_mof_compiler.py
tests/unittest/pywbem/test_recorder.py
tests/unittest/pywbem_mock/test_inmemory_repository.py
tests/unittest/resourcetest/test_memory_utils.py
tests/unittest/utils/validate.py

Removed Pylint pinning to 2.7.0 and addressed Pylint issues

---

docs/changes.rst
pywbem/_subscription_manager.py
tests/unittest/pywbem/test_subscriptionmanager.py

Fixed name/filter_id issue in SubscriptionManager.add_filter()

---

docs/changes.rst
pywbem_mock/_mainprovider.py
tests/end2endtest/test_profile_generic.py
tests/end2endtest/test_profile_snia_server.py
tests/end2endtest/test_server.py

Mitigated Pylint issues 'deprecated-method' and 'not-an-iterable'

---

dev-requirements.txt
docs/changes.rst
minimum-constraints.txt

Rolls back PR #2794 into 1.2.1

1.2: Fix issue #2796 and also hange Sphinx target in minimum-constraints.txt

---

Makefile
docs/changes.rst

Rolls back the second commit of PR #2790 into 1.2.1.

1.2: Added several new safety issues to ignore list

---

dev-requirements.txt
docs/changes.rst
minimum-constraints.txt
rtd-requirements.txt

Rolls back PR #2790 into 1.2.1.

1.2: Issue between Sphinx 1.85 and docutils 0.18

---

dev-requirements.txt
minimum-constraints.txt
rtd-requirements.txt

Second fix for Sphinx/docutils issue

---

dev-requirements.txt
minimum-constraints.txt
rtd-requirements.txt

Rolls back PR #2803 into 1.2.1

1.2: Second fix for Sphinx/docutils issue

---

docs/changes.rst
pywbem/_cliutils.py
pywbem/_tupletree.py

Fixed new issues raised by Pylint 2.12.1

---

docs/changes.rst
pywbem/_cliutils.py
pywbem/_tupletree.py

Rolls back PR #2805 into 1.2.1

1.2: Fixed new issues raised by Pylint 2.12.1

---

DEVELOP.md

Editorial changes in DEVELOP.md

---

docs/changes.rst
minimum-constraints.txt
test-requirements.txt

Fixed error when installing virtualenv in install test on Python 2.7

---

Makefile

Ignored safety issue 42559 (pip)

---

Makefile

Rolls back PR #2813 into 1.2.1.

1.2: Ignored safety issue 42559 (pip)

---

docs/changes.rst
pywbem/_version.py

Please approve the release of pywbem 1.2.1.

Release 1.2.1

---

tests/unittest/pywbem/test_statistics.py

Adjusted allowable delta in test_Statistics_measure_avg()

---

DEVELOP.md

Fixed RTD treatment in DEVELOP.md

---

.github/workflows/test.yml
README_PYPI.rst
dev-requirements.txt
docs/changes.rst
minimum-constraints.txt
pywbem/_version.py
requirements.txt

Please approve the release of pywbem 1.3.0.

Release 1.3.0

---

docs/changes.rst
pywbem/_version.py

1.3: Start 1.3.1

---

docs/changes.rst
pywbem/_version.py

Start 1.4.0

---

.github/workflows/test.yml
minimum-constraints.txt

Fixed minimum versions of pip; Added py35/min/macos to tests

---

pywbem/_server.py
pywbem/_subscription_manager.py
pywbem_mock/_inmemoryrepository.py

Separated code that determines the Interop namespace from its use

---

docs/changes.rst

Added missing change log entry for pip version fix

---

.github/workflows/test.yml
README_PYPI.rst
docs/changes.rst
pywbem/_version.py

Please approve the release of pywbem 1.4.0.

Release 1.4.0

---

docs/changes.rst
pywbem/_version.py

Start 1.5.0

---

docs/changes.rst
pywbem/_version.py

Start 1.4.1

---

Makefile

Ignored safety issue 43366 (lxml, code not used)

---

docs/conf.py

Docs: Added debug info for current directory

---

tests/unittest/pywbem/test_statistics.py

This hopefully addresses the re-occurring test failures in the statistics tests that were caused by CI environments simply sometimes running more slowly.

Test: Improved time checking in statistics tests

---

docs/changes.rst
pywbem/_mof_compiler.py
pywbem_mock/_providerdispatcher.py
tests/unittest/pywbem/test_mof_compiler.py
tests/unittest/pywbem_mock/test_wbemconnection_mock.py

Rolls back PR #2825 into 1.4.1

1.4: Fix issue with create instance of abstract class

---

docs/changes.rst
pywbem/_version.py

Please approve the release of pywbem 1.4.1.

Release 1.4.1

---

docs/changes.rst
pywbem/_version.py

Start 1.4.2

---

Makefile
dev-requirements.txt
minimum-constraints.txt

Fixed safety issues with urllib3, ipython

---

docs/changes.rst
pywbem/_server.py

Added support for CIM_WBEMServerNamespace namespace class

---

attic/jobs_manager/pywbem/_jobs_manager.py

This PR has been created to not forget about this old branch.

Issue #810: Prototype for jobs manager -> moved to attic

---

attic/cim_xml_parser/pywbem/_cim_xml_parser.py
attic/cim_xml_parser/tests/unittest/pywbem/test_cim_xml_parser.py

WIP, with these ToDos:
* Double check new implementation with tupleparse.py to make sure any special cases are covered and have testcases.
Left for future work, beyond this PR:
* Usage of the new CIM-XML parser in pywbem (configurable between new parser and tupleparser)
* Implementation and use of listener support in new parser (indication delivery requests)

Issue #1679: Redesigned CIM-XML parser for better performance -> moved to attic

---

docs/changes.rst
docs/intro.rst

Documented that the MOF compiler does not support EmbeddedObject with class

---

dev-requirements.txt
docs/changes.rst
minimum-constraints.txt
rtd-requirements.txt

Docs: Changes in autodocsumm and Sphinx versions for final fix for issue #2697

---

Makefile
dev-requirements.txt
docs/changes.rst
minimum-constraints.txt

Re-enabled pylint on py35

---

Makefile
dev-requirements.txt
docs/changes.rst
minimum-constraints.txt
pylintrc

Increased pylint to >=2.10 on Python >=3.6 to pick up fixes

---

.github/workflows/test.yml

Expected to fail on win/py35/minimum.

Added py35/py310 with minimum versions on Windows

---

.github/workflows/test.yml
Makefile
dev-requirements.txt
docs/changes.rst
minimum-constraints.txt
requirements.txt
rtd-requirements.txt
tests/installtest/test_install.sh

Added package dep tools; Fixed dep versions; Fixed setuptools 61.0.0 issue

---

.github/workflows/test.yml
Makefile
dev-requirements.txt
docs/changes.rst
minimum-constraints.txt
requirements.txt
rtd-requirements.txt
tests/installtest/test_install.sh

Rolls back the setup.py install fix from PR #2863 into 1.4.2.

1.4: Added package dep tools; Fixed dep versions; Fixed setuptools 61.0.0 issue

---

Makefile
dev-requirements.txt
docs/changes.rst
pywbem/_cim_operations.py
pywbem/_mof_compiler.py
setup.py
tests/functiontest/conftest.py
tests/manualtest/run_cim_operations.py

Note: This PR is on top of PR #2863. Needs to wait until it is approved.

Resolved Pylint 2.13 issues; Fixed setup.py command display

---

dev-requirements.txt
docs/changes.rst
pywbem/_cim_operations.py
pywbem/_mof_compiler.py
setup.py
tests/functiontest/conftest.py
tests/manualtest/run_cim_operations.py

Rolls back PR #2873 into 1.4.2.
Note: This PR is on top of PR #2872. Needs to wait until that one is approved.

1.4: Resolved Pylint 2.13 issues; Fixed setup.py command display

---

Makefile
minimum-constraints.txt

Fixed missing new dependency 'rich' for 'twine' package; Fixed new safety issues

---

pywbem/_cim_operations.py
tests/unittest/pywbem/test_logging.py

Added validation that the result is correct at the point
where the issue/question was documented.

Fixes issue #2667 question about logger setup paths.

---

design/connection_errors.md
docs/changes.rst
pywbem/_cim_constants.py
pywbem/_cim_http.py
pywbem/_cim_operations.py
pywbem/_exceptions.py
pywbem/_warnings.py
pywbem_mock/_wbemconnection_mock.py
tests/unittest/pywbem/test_cim_http.py
tests/unittest/pywbem/test_cim_operations.py
tests/unittest/pywbem/test_recorder.py

This PR requires thorough review and testing in situations with broken connections.

Fixed and improved handling of requests/urllib3 exceptions and retries

---

tests/unittest/pywbem_mock/test_complexassoc.py

Resolved pylint issue on arg name in test_complexref_classnames

---

.github/workflows/test.yml
Makefile
docs/changes.rst
minimum-constraints.txt
test-requirements.txt

Fixed several issues for cythonized archive

---

tests/manualtest/run_operationtimeouts.py

NOTE: This just adds parameter so we can set port for test.  I would not worry about reviewing since the timeout end2end will superceed this.  However, this might prove useful in future since it runs a wide range of timeouts but takes about 30 minutes to do it so I just want to keep it running

Ks/fixes to manual test run_operationtimeouts.py

---

docs/changes.rst
pywbem_mock/_inmemoryrepository.py
tests/unittest/pywbem/test_mof_compiler.py
tests/unittest/pywbem_mock/test_wbemconnection_mock.py

Fixed new formatting issues raised by flake8 5.0

---

docs/changes.rst
pywbem_mock/_inmemoryrepository.py
tests/unittest/pywbem/test_mof_compiler.py
tests/unittest/pywbem_mock/test_wbemconnection_mock.py

Rolls back PR #2911 into 1.4.2

1.4: Fixed new formatting issues raised by flake8 5.0

---

docs/changes.rst
pywbem_mock/_wbemconnection_mock.py
tests/unittest/pywbem_mock/test_system_providers.py

See commit message for information on this pr.

Fix issue # 2865 where mocker.add_namespace fails

---

Makefile
minimum-constraints.txt
test-requirements.txt

Rolls back PR #2916 into 1.4.2.

1.4: Mark new security issues for ignore

---

Makefile

No longer ignoring Python warnings in pytest

---

minimum-constraints.txt

Added dataclasses to min constraints to fix safety dependency

---

.github/workflows/test.yml

Changed macos test run on py35/min to ubuntu

---

.github/workflows/test.yml

Rolls back PR #2942 into 1.4.2.

1.4: Changed macos test run on py35/min to ubuntu

---

docs/changes.rst
pywbem/_version.py

Please approve the release of pywbem 1.4.2.

Release 1.4.2

---

.github/workflows/test.yml
README_PYPI.rst
docs/changes.rst
pywbem/_version.py

Please approve the release of pywbem 1.5.0.

Release 1.5.0

---

docs/changes.rst
pywbem/_version.py

Start 1.6.0

---

docs/changes.rst
pywbem/_version.py

Start 1.5.1

---

minimum-constraints.txt

Fixed make check_reqs issue with notebook package

---

minimum-constraints.txt

Rolls back PR #2949 into 1.5.1.

1.5: Fixed make check_reqs issue with notebook package

---

Makefile
dev-requirements.txt
docs/changes.rst
minimum-constraints.txt
test-requirements.txt

Rolls back PR #2953 into 1.5.1

1.5: Fix several security issues.

---

.github/workflows/test.yml

Migrated Actions workflows to use environment files

---

setup.py

For details. see the commit message.

Addressed import error for wheel

---

.github/workflows/test.yml
Makefile

Disabled pip version checks

---

.github/workflows/test.yml

Updated Github Actions module versions to address warnings

---

Makefile

Renamed make variable for consistency with pywbemtools

---

minimum-constraints.txt

Fixed version conflict between packaging and safety on Pythpn 3.6

---

dev-requirements.txt

Fixed that tornado is not installed on Python 3.10

---

.github/workflows/test.yml
Makefile
minimum-constraints.txt

Fixed the silencing of pip checks for pip and Python versions

---

.github/workflows/test.yml
dev-requirements.txt
docs/changes.rst
minimum-constraints.txt
pywbem_os_setup.sh
setup.py
test-requirements.txt

Support for Python 3.11

---

.github/workflows/test.yml

Added Python 3.7+3.10 with minimum versions to normal tests

---

.github/workflows/test.yml
dev-requirements.txt
minimum-constraints.txt

Increased min version of Cython/pyzmq; Added py310 on win/minimum

---

.github/workflows/test.yml
README_PYPI.rst
docs/changes.rst
pywbem/_version.py

Please approve the release of pywbem 1.6.0

Release 1.6.0

---

.github/workflows/test.yml
DEVELOP.md

Test workflow: Added py39, generalized stable_.. branch; changed weekly time

---

.github/workflows/test.yml
DEVELOP.md

Rolls back PR #2985 into 1.6.1.

1.6: Test workflow: Added py39, generalized stable_.. branch; changed weekly time

---

docs/changes.rst
pywbem/_version.py

Release 1.6.1

---

.github/workflows/test.yml

Added Python 3.6 to normal test envs

---

Makefile

Made filename of .done files unique w.r.t. package level

---

Makefile

Rolls back PR #3013 into 1.6.2

1.6: Made filename of .done files unique w.r.t. package level

---

docs/changes.rst
pywbem/_valuemapping.py
tests/unittest/pywbem/test_valuemapping.py

Improved handling of missing/extra Values items in ValueMapping

---

docs/changes.rst
pywbem/_valuemapping.py
tests/unittest/pywbem/test_valuemapping.py

Rolls back PR #3000 into 1.6.2.
Needs to wait for its approval.

1.6: Improved handling of missing/extra Values items in ValueMapping

---

.github/workflows/test.yml
docs/changes.rst
pywbem_os_setup.sh

Circumvented the removal of Python 2.7 from setup-python plugin

---

.github/workflows/test.yml
docs/changes.rst
pywbem_os_setup.sh

Rolls back PR #3025 into 1.6.2.

1.6: Circumvented the removal of Python 2.7 from setup-python plugin

---

.github/workflows/test.yml

Removed duplicate py36/ubuntu test env

---

dev-requirements.txt
docs/changes.rst
minimum-constraints.txt
requirements.txt
test-requirements.txt

Fixed missing dependencies in minimum-constraints.txt

---

.safety-policy.yml
dev-requirements.txt
minimum-constraints.txt
requirements.txt
test-requirements.txt

Fixed safety issues from 2023-07-24

---

.safety-policy.yml
dev-requirements.txt
minimum-constraints.txt
requirements.txt
test-requirements.txt

Rolls back PR #3023 into 1.6.2

1.6: Fixed safety issues from 2023-07-24

---

.github/workflows/test.yml

Disabled Github Actions tests on Python 2.7

---

.github/workflows/test.yml

Rolled back PR #3030 into 1.6.2.

1.6: Disabled Github Actions tests on Python 2.7

---

pywbem/_tupleparse.py
tests/unittest/pywbem/test_cim_http.py

No review needed. Remaining safety failure will be fixed in separate PR.

Fixed issues reportd by new flake8 version 6.1.0

---

pywbem/_tupleparse.py
tests/unittest/pywbem/test_cim_http.py

Rolls back PR #3037 into 1.6.2.

1.6: Fixed issues reportd by new flake8 version 6.1.0

---

dev-requirements.txt

Fixed install of ipywidget on Python 2.7

---

.safety-policy.yml
dev-requirements.txt
docs/changes.rst
minimum-constraints.txt

Rolls back PR #3041 into 1.6.2.

1.6: Fixed safety issues as of 8/21

---

.safety-policy.yml
dev-requirements.txt
docs/changes.rst
minimum-constraints.txt

Fixed safety issues as of 8/21

---

tests/unittest/pywbem/test_cim_http.py

Fixed flake8 issue part 2

---

tests/unittest/pywbem/test_cim_http.py

Rolls back PR #3043 into 1.6.2.

1.6: Fixed flake8 issue part 2

---

pywbem/_tupleparse.py

Fixed flake8 issue, part 3

---

pywbem/_tupleparse.py

Rolls back PR #3045 into 1.6.2.

1.6: Fixed flake8 issue, part 3

---

docs/changes.rst
pywbem/_version.py

Please approve the release of pywbem 1.6.2.

Release 1.6.2

---

.safety-policy.yml
docs/changes.rst

Fixed safety issues as of 2023-09-10

---

.safety-policy.yml
docs/changes.rst

Rolls back PR #3053 into 1.6.3.

1.6: Fixed safety issues as of 2023-09-10

---

docs/changes.rst
pylintrc
tests/manualtest/run_operationtimeouts.py

Rolls back PR #3060 into 1.6.3.

1.6: Fix one pylint issue in manual tests

---

docs/changes.rst
pywbem_mock/_baseprovider.py

Remove reference to invalid parameter and add value for cimrepository

Fix pywbem_mock/_baseprovider.py

---

docs/appendix.rst
docs/client/objects.rst
docs/client/operations.rst
docs/client/types.rst
docs/client/valuemappings.rst
docs/indication.rst
docs/intro.rst
docs/mockwbemserver.rst
docs/notebooks/pywbemmock.ipynb
docs/server.rst
docs/tutorial.rst
docs/utilities.rst

Adds paragraphs in intro to note that there are examples in the document, in the tutorial, and in an examples section of the github repository.
Adds index entries in a number of places.

Add more info on examples to documentation.

---

.safety-policy.yml
docs/changes.rst
minimum-constraints.txt
requirements.txt

Addressed safety issues up to 2023-11-05

---

.safety-policy.yml
docs/changes.rst
minimum-constraints.txt
requirements.txt

Rolls back PR #3077 into 1.6.3.

1.6: Addressed safety issues up to 2023-11-05

---

tests/end2endtest/test_indications.py

Corrected code issue where the last indication time was not always
captured before testing for elapsed time.
Also modified the code testing for next sequence number to assert if it
is not correct since that is actually an error.

Fixes issue #3071 end end test fail.

---

examples/pegasusindicationtest.py

Fix issue similar to issue #3071 where we were getting an exception sometimes because variable not initialized.
Also expanded the sequence number test and display.

Fix issue with example/pegasusindicationtest.py.

---

.safety-policy.yml
dev-requirements.txt
docs/changes.rst
minimum-constraints.txt

Addressed safety issues up to 2023-11-26

---

.safety-policy.yml
dev-requirements.txt
docs/changes.rst
minimum-constraints.txt

Rolls back PR #3085 into 1.6.3.

1.6: Addressed safety issues up to 2023-11-26

---

INSTALL.md
README.rst
docs/appendix.rst
docs/client/operations.rst
docs/indication.rst
docs/intro.rst
docs/mockwbemserver.rst
docs/server.rst

This pr documents the issues and possible fixes if the Externally-managed-environment error occurs.
There are no code changes for this issue

Document issue with install failing with Externally-managed-environment error.

---

.safety-policy.yml
dev-requirements.txt
docs/changes.rst
minimum-constraints.txt

Safety issues

---

.safety-policy.yml
dev-requirements.txt
docs/changes.rst
minimum-constraints.txt

Safety issues up to 2024-01-15

---

.safety-policy.yml
dev-requirements.txt
docs/changes.rst
minimum-constraints.txt

Rolls back PR #3092 into 1.6.3.

1.6: Safety issues up to 2024-01-15

---

.github/workflows/test.yml

Fixed call to pipdeptree

---

.github/workflows/test.yml

Rolls back PR #3095 into 1.6.3.

1.6: Fixed call to pipdeptree

---

dev-requirements.txt
docs/changes.rst

Fixed dependency issue with safety 3.0.0 by pinning it

---

.github/workflows/test.yml
docs/changes.rst

Test: Upgraded GitHub Actions plugins to use node.js 20

---

minimum-constraints.txt
test-requirements.txt

Fixed pkgutil install issue on Python 3.12

---

minimum-constraints.txt
test-requirements.txt

Rolls back PR #3107 into 1.6.3.

1.6: Fixed pkgutil install issue on Python 3.12

---

.safety-policy.yml
Makefile
dev-requirements.txt
docs/changes.rst
minimum-constraints.txt
pylintrc
pywbem/_statistics.py
tests/functiontest/conftest.py

Adds new entries in safety for
- GitPython
- jinga2
- Jupyterlab
- new version for send to trash
Added fixes for new pylint issues so that the commit would complete.

Add new safety issues to safety policy file feb 2024

---

docs/changes.rst
tests/functiontest/conftest.py
tests/unittest/pywbem_mock/test_wbemconnection_mock.py
tests/unittest/utils/pytest_extensions.py

Fixed use of pytest.warns(None)

---

.safety-policy.yml
Makefile
dev-requirements.txt
docs/changes.rst
minimum-constraints.txt
pylintrc
pywbem/_statistics.py
tests/functiontest/conftest.py
tests/unittest/pywbem_mock/test_wbemconnection_mock.py
tests/unittest/utils/pytest_extensions.py

Rolls back PRs #3114 and #3111 into 1.6.3.

1.6: Safety issues feb 2024; Fixed use of pytest.warns(None)

---

.safety-policy.yml
dev-requirements.txt
docs/changes.rst
minimum-constraints.txt
test-requirements.txt

Rolls back PR #3121 into 1.6.3.

1.6: Add fixes for new safety issues, 17 Mar 2024.

---

.safety-policy.yml
docs/changes.rst

Safety issues up to 3/25

---

.safety-policy.yml
docs/changes.rst

Rolls back PR #3126 into 1.6.3.

1.6: Safety issues up to 3/25

---

.github/workflows/test.yml
.safety-policy-all.yml
.safety-policy-install.yml
DEVELOP.md
Makefile
dev-requirements.txt
docs/changes.rst
minimum-constraints-install.txt
minimum-constraints.txt
requirements.txt
test-requirements.txt

Split safety runs into install and all; Dependencies cleanup

---

dev-requirements.txt
minimum-constraints.txt

Fixed Cython build error

---

.safety-policy-all.yml
.safety-policy-install.yml

Reduced safety ignores to the minimum needed

---

.github/workflows/test.yml

Increased actions/github-script to v7 to run with node 20

---

.github/workflows/test.yml
dev-requirements.txt
minimum-constraints.txt

For details, see the 2 commit messages.

Fixed install and test issues on py312-minimum on Windows

---

docs/appendix.rst
docs/changes.rst

This change does not modify any code. It extends the description of the issues around the move to urllib3 and the corresponding incompatibilities.

Documentation changes for urllib3 ver 2 support.

---

docs/appendix.rst
docs/changes.rst
examples/listen.py
examples/pegasusindicationtest.py
examples/send_indication.sh
pywbem/_listener.py
tests/unittest/pywbem/test_indicationlistener.py

Replaces pr #3084. Same code changes but fixes a merge conflict introduced in last update of that pr.

Fix issue with losing indications sent by OpenPegasus (new PR)

---

setup.py

Fixed MIME type of markdown README

---

.gitignore

git-ignore temporary coverage files

---

docs/changes.rst
pywbem/_listener.py

Rolls back PR #3158 into 1.7.1.

1.7: Fix issue where listener startup failure can cause extra exceptions.

---

dev-requirements.txt
docs/changes.rst

1.7: Speed up install of dev. env. by pinning coverage

---

docs/changes.rst
pywbem/_version.py

Release 1.7.1

---

docs/changes.rst
pywbem/_version.py

Start 1.7.2

---

MANIFEST.in
Makefile
docs/changes.rst
tests/installtest/test_install.sh

Fixed pywbem install error with ImportError on Python 2.7

---

MANIFEST.in
Makefile
docs/changes.rst
tests/installtest/test_install.sh

Rolls back PR #3164 into 1.7.2.

1.7: Fixed pywbem install error with ImportError on Python 2.7

---

docs/changes.rst
pywbem/_version.py

Release 1.7.2

---

docs/changes.rst
pywbem/_version.py

Start 1.7.3

---

.github/workflows/test.yml
docs/changes.rst
test-requirements.txt

Fixed Python 3.6/3.7 on macos

---

Makefile
docs/changes.rst

Added .pytest_cache and .ruff_cache to be removed in 'make clean'

---

.safety-policy-install.yml
docs/changes.rst

Fixed safety issues up to 2024-05-13

---

.safety-policy-install.yml
docs/changes.rst

Rolls back PR #3183 into 1.7.3.

1.7: Fixed safety issues up to 2024-05-13

---

.github/workflows/test.yml
.safety-policy-install.yml
base-requirements.txt
docs/changes.rst
minimum-constraints-install.txt
pyproject.toml
pywbem/_mof_compiler.py
requirements.txt
tests/manualtest/run_enum_performance.py
tests/manualtest/run_enum_performancesimple.py
tests/manualtest/run_operationtimeouts.py
tests/unittest/pywbem/test_subscriptionmanager.py
tests/unittest/pywbem_mock/test_inmemory_repository.py
tests/unittest/pywbem_mock/test_wbemconnection_mock.py

Fixed new issues reported by Pylint 3.2

---

.safety-policy-install.yml
docs/changes.rst
minimum-constraints-install.txt
pywbem/_cim_types.py
pywbem/_mof_compiler.py
requirements.txt
tests/end2endtest/test_indications.py
tests/manualtest/run_enum_performance.py
tests/manualtest/run_enum_performancesimple.py
tests/manualtest/run_operationtimeouts.py
tests/unittest/pywbem/test_subscriptionmanager.py
tests/unittest/pywbem_mock/test_inmemory_repository.py
tests/unittest/pywbem_mock/test_wbemconnection_mock.py

Rolls back PR #3189 into 1.7.3.

1.7: Fixed new issues reported by Pylint 3.2

---

minimum-constraints-develop.txt
requirements.txt

Removed remaining dependencies for Python<3.8

---

minimum-constraints-install.txt
requirements.txt
tests/functiontest/conftest.py
tests/unittest/pywbem/test_mof_compiler.py
tests/unittest/pywbem_mock/test_wbemconnection_mock.py

See commit message for changes.

Fix issues with safety, check. & ruff fixes, July 2024

---

.safety-policy-install.yml
docs/changes.rst
minimum-constraints-install.txt
requirements.txt
setup.py
tests/functiontest/conftest.py
tests/unittest/pywbem/test_mof_compiler.py
tests/unittest/pywbem_mock/test_wbemconnection_mock.py

Rolls back the safety part of PR #3201 into 1.7.3.

1.7. Fixed safety issues up to 2024-07-08

---

docs/conf.py

Fixed RTD build issue (2)

---

dev-requirements.txt
minimum-constraints-develop.txt

Remove max version limit on build package.

---

.safety-policy-develop.yml
dev-requirements.txt
docs/changes.rst
minimum-constraints-develop.txt
minimum-constraints-install.txt
requirements.txt

Addressed safety issues up to 2024-07-21

---

.gitignore
.safety-policy-all.yml
Makefile
dev-requirements.txt
docs/changes.rst
minimum-constraints-install.txt
minimum-constraints.txt
requirements.txt
test-requirements.txt

Rolls back PR #3206 into 1.7.3.

1.7: Addressed safety issues up to 2024-07-21

---

DEVELOP.md

See also PR https://github.com/pywbem/pywbem.github.io/pull/15 both of which need to be reviewed.

Removed updating of pywbem.github.io from release instructions

---

dev-requirements.txt
docs/changes.rst
minimum-constraints-develop.txt
minimum-constraints-install.txt
requirements.txt
test-requirements.txt

Safety issues up to 2024-08-13

---

.safety-policy-all.yml
dev-requirements.txt
docs/changes.rst
minimum-constraints-install.txt
minimum-constraints.txt
requirements.txt
test-requirements.txt

Rolls back PR #3210 into 1.7.3.

1.7: Safety issues up to 2024-08-13

---

base-requirements.txt
docs/changes.rst
minimum-constraints-install.txt
pyproject.toml

Addressed safety issues

---

.safety-policy-install.yml
docs/changes.rst
minimum-constraints-install.txt

Rolls back PR #3212 into 1.7.3.

1.7: Addressed safety issues

---

Makefile
docs/changes.rst
pywbem/_version.py

Fixed RTD build issue

---

DEVELOP.md
pywbem/_version.py

Fixed steps to start new version; removed types from _version.py

---

dev-requirements.txt
docs/changes.rst
pylintrc

Fixed new issues reported by Pylint 3.3

---

dev-requirements.txt
docs/changes.rst
pylintrc

Rolls back PR #3222 into 1.7.3.

1.7: Fixed new issues reported by Pylint 3.3

---

tox.ini

Updated tox.ini to add Python 3.10-3.12

---

dev-requirements.txt
docs/changes.rst
minimum-constraints-develop.txt
test-requirements.txt

Safety issues up to 2024-11-30

---

.safety-policy-all.yml
dev-requirements.txt
docs/changes.rst
minimum-constraints-install.txt
minimum-constraints.txt
requirements.txt
test-requirements.txt

Rolls back PR #3239 into 1.7.3.

1.7: Safety issues up to 2024-11-30

---

changes/noissue.9.fix.rst
dev-requirements.txt
minimum-constraints-develop.txt

See https://github.com/andfoy/pywinpty/issues/486

Circumvented issue with installing pywinpty

---

Makefile
changes/noissue.10.fix.rst
changes/noissue.11.fix.rst
dev-requirements.txt
minimum-constraints-develop.txt
requirements.txt

Removed twine from deps; Replaced jupyter in check_reqs

---

.github/workflows/test.yml

1.7: Added Python 3.6+3.7 for macOS in full test

---

Makefile
changes/noissue.11.fix.rst

Reverted replacement of jupyter in check_reqs

---

Makefile
docs/changes.rst

1.7: Reverted replacement of jupyter in check_reqs

---

base-requirements.txt
changes/noissue.safety.fix.rst
dev-requirements.txt
minimum-constraints-develop.txt
minimum-constraints-install.txt

Fixed safety issued and missing dependencies

---

Makefile
docs/development.rst

Has not been tested yet. A test can only be performed after this PR has been merged.
The necessary start tags have been created for versions 1.8.0 and 1.7.3.

Simplified releasing and starting a version

---

changes/3258.feature.rst

Resolution of a review comment on PR #3261 that was forgotten to commit.

Fixed change entry for PR 3258

---

.github/workflows/test.yml
Makefile
changes/3265.fix.rst
docs/development.rst
tests/README

Fixed testing of installed version of pywbem

---

.github/workflows/test.yml
Makefile
base-requirements.txt
docs/changes.rst
docs/development.rst
minimum-constraints.txt
test-requirements.txt
tests/README

Rolls back PR #3269  into 1.7.

1.7: Fixed testing of installed version of pywbem; Fixex lxml for py313

---

.github/workflows/test.yml
changes/noissue.13.fix.rst
dev-requirements.txt
minimum-constraints-develop.txt
minimum-constraints-install.txt
requirements.txt
test-requirements.txt

Optimized versions for testing; Moved to latest 3.13 fix version; Fixed min versions

---

changes/noissue.flake8.fix.rst
tests/manualtest/run_operationtimeouts.py

1.7: Fixed new flake8 issue

---

changes/noissue.safety.fix.rst
dev-requirements.txt
minimum-constraints-develop.txt

Upgraded safety; Fixed safety issues & dependencies

---

.github/workflows/test.yml
dev-requirements.txt
minimum-constraints.txt

Rolls back PR #3279 (partially) into 1.7.

1.7: Removed Ubuntu 20.04; Fixed safety issues & dependencies

---

.safety-policy-install.yml
dev-requirements.txt
minimum-constraints.txt

1.7: Safety issues

---

pywbem/_recorder.py

1.7: Fixed use of long in Python 2 for Cython - part 2

---

dev-requirements.txt
docs/changes.rst
minimum-constraints.txt

1.7: Cython support for Python 3.13

---

.github/workflows/publish.yml

Fixed publish workflow

---

docs/conf.py

Suppressed Sphinx warning on ListenerQueueFullError

---

changes/noissue.83.fix.rst
pywbem/_listener.py
tests/unittest/pywbem/test_indicationlistener.py

Fixed and improved log/exception messages related to indications
