- pylint.rc
> Fix for issue 28: Removed deprecated options from pylint.rc

- makefile
This addresses issue #41 and some other issues.
Details, from the commit message:
- Added dependents for Lex/Yacc table files (mofparsetab.py/moflextab.py).
- Made sure that mofparsetab.py and moflextab.py are generated in the right
directory (pywbem package directory) even when mof_compiler.py is invoked
standalone.
- Bad return codes from py.test and epydoc are now surfaced as make errors
(solves issue #41).
- Changed meaning of 'clean' target to be cleanup before other make targets.
- As a result, 'clean' target now removes anyhting that is dependent on
Python version but has same file name.
- test.log now has a Python version dependent name (e.g. test_27.log).
- Made 'all' target consistent with tox and Travis invocations (i.e. removed
build+install, because that is done by the …
> Fixes and improvements in makefile

- pywbem/wbemcli.py
> Added missing LocalOnly parameter to EnumerateInstances() of wbemcli.

- pywbem/cim_operations.py
This PR fixes a part of issue #91.
> Fixes in descriptions of class and qualifier operations.

- pywbem/NEWS
- pywbem/cim_constants.py
- pywbem/cim_operations.py
- testsuite/run_cim_operations.py
> Fixes #84: Moved DEFAULT_NAMESPACE from cim_operations to cim_constants module.

- os_setup.py
- pywbem/cim_http.py
- pywbem/cim_obj.py
- pywbem/cim_types.py
- pywbem/cim_xml.py
- pywbem/cimxml_parse.py
- pywbem/mof_compiler.py
- pywbem/tupleparse.py
- setup.py
- testsuite/test_cim_obj.py
- testsuite/test_client.py
- testsuite/test_tupleparse.py
- testsuite/validate.py
+1. This is mostly clean cleanup code.  There are a couple more pylints to do after we sort out questons but this is the majority without more real work
> Changes for pylint.  Reduces pylints from 490 to 340.

- pywbem/NEWS
- pywbem/__init__.py
- setup.py
Updated the versions to `0.8.2dev`.
> Started develoment of version 0.8.2

- pywbem/NEWS
- pywbem/__init__.py
- setup.py
This PR starts development of 0.8.3 based upon the fix branch stable_0.8.
> Started development of 0.8.3.

- pywbem/NEWS
- pywbem/__init__.py
- setup.py
> Start 0.8.3 - redo merge correctly

- pywbem/cim_obj.py
Changed variable name that was causing pylint undefined variable error
> Fix issue with bad variable elf -> self

- DEVELOP.md
This file describes things that are important for PyWBEM Client developers.
Please review.
> Fixes #16: Added initial DEVELOP.md readme file for developers.

- pywbem/_cliutils.py
- pywbem/mof_compiler.py
- pywbem/wbemcli.py
We talked about this in one of the calls. Ready for review.
Details from the commit message:
- Created `_cliutils.py`. It will be picked up automatically by build.
- Moved the SmartFormatter class from `wbemcli.py` and `mof_compiler.py` into `_cliutils.py`.
- Changed `import pywbem` in wbemcli.py to `from . import WBEMConnection` because wbemcli is a pywbem module.
> Created _cliutils module with utility stuff for CLI scripts.

- pywbem/_version.py
- pywbem/mof_compiler.py
- pywbem/tupleparse.py
- pywbem/wbemcli.py
- setup.py
- testsuite/test_cim_obj.py
- testsuite/test_nocasedict.py
These should be trivial. Please review.
> A few more trivial pylint fixes.

- setup.py
This PR contains the same change as PR #157, but targets the master branch, instead.
> Fixes #157: Changed os-level dependency 'zip' and 'unzip' to 'tar' (master)

- docs/index.rst
- docs/mof_compiler.help.txt
- docs/wbemcli.help.txt
- makefile
> Added help messages for utilities to documentation.

- DEVELOP.md
- testsuite/test_install.sh
This PR adds a shell script `testsuite/test_install.sh` that performs installation testing.
Also, it updates the DEVELOP.md file to document that it should be run during the final release tests.
Please review, and try out the shell script.
> Fixes #165: Added shell script for install testing (testsuite/test_install.sh).

- docs/changes.rst
- pywbem/cim_constants.py
This PR adds the CIM status codes 20 to 28.
It also updates the descriptions of all CIM status codes to match those from DSP0200.
Please review.
> Fixes #187: Added CIM status codes 20 to 28 and updated their descriptions to match DSP0200.

- docs/changes.rst
- docs/client.rst
- makefile
- pywbem/__init__.py
- pywbem/cim_http.py
- pywbem/cim_operations.py
- pywbem/exceptions.py
- pywbem/tupleparse.py
Ready for merge; please review.
> Fixes #178: Moved exceptions into new module 'exceptions' and derived all from 'Error'

- DEVELOP.md
- docs/conf.py
Details:
- Automated determination of package version in `docs/conf.py`.
- Updated DEVELOP.md to match v0.9.0 changes.
> WIP (incomplete): Automated the package release somewhat better.

- pywbem/NEWS
- pywbem/__init__.py
- setup.py
Bumped versions to 0.8.4.dev0.
> Started development of v0.8.4

- testsuite/unittest_extensions.py
> Fixes #232: Fixed copy&paste error in assertRegexpMatches().

- DEVELOP.md
Adjusted to current state of 0.8.x release.
> Fixed DEVELOP.md readme file for v0.8.x.

- DEVELOP.md
Ready for merge. Please review.
Basically the v0.8.0 version,
* plus steps for creating new dist subdirectory for new M.N release
* minus the manual handling of doc updates because that is automated now with Sphinx and RTD.
> Updated DEVELOP.md to integrate changes from recent 0.8 update.

- docs/changes.rst
- docs/intro.rst
- makefile
Ready for merge.
Please review.
* Added section 'Deprecation policy' that describes the rules.
* Changed makefile to enable `DeprecationWarning` messages during test.
* Added entry `DeprecationWarning` to section "Special types", for easier reference by description of deprecated functionality.
>  Described a deprecation policy.

- DEVELOP.md
Please review, this is just an initial stab but reflects the discussion on issue #188.
> Fixes #188: Added section to DEVELOP.md about use of Python namespaces in the project

- pywbem/cim_obj.py
In addition, this PR fixes issue #254.
Please review.
> Fixed Sphinx markup and formatting of docstrings in cim_obj.py.

- docs/changes.rst
- pywbem/cim_obj.py
- pywbem/cim_types.py
> Fixes #268 #269: Enhanced CIM integer data types with concept of a valid value range, and int() constructor args

- docs/changes.rst
- pywbem/cim_types.py
- testsuite/test_cim_types.py
> Fixes #270, fixes #275: Add unit test cases for cim_types, fixed str() for CIMDateTime interval

- INSTALL.md
- os_setup.py
- setup.py
This PR rolls the change of PR #282 forward into the master branch.
It will be merged along with merging PR #282.
> Improved installation and its description for Swig failures (master branch)

- docs/changes.rst
- pywbem/cim_http.py
- pywbem/cim_operations.py
This PR merges the changes from PR #290 into the master branch.
Review should be done on PR #290. This PR can merge automatically once PR #290 is approved.
> IndexError when handling exception from send(); Added debug prints for those ignored exceptions.

- pywbem/NEWS
- pywbem/__init__.py
This PR was created in order to address a side issues described in issue #179.
This PR targets the 0.8 release stream, there will be a separate one targeting the master branch.
> Added runtime check for minimum Python 3 version 3.4 (for 0.8 branch)

- docs/changes.rst
- pywbem/cim_http.py
This is currently untested since all tests fail in hotel once you use ip address.  Think they are blocking everything.
Even if it passes, it is not tested
>  Fixed issues in SSL support for Python 3.

- docs/changes.rst
- pywbem/cim_http.py
This PR merges the changes from PR #310 into 0.9.
> Removed half-baked code for HTTP proxy/tunneling support.

- pywbem/NEWS
- pywbem/cim_http.py
Ready to be merged. Addresses issue #296.
Please review and test.
> Removed half-baked code for tunneling support.

- wbemcli
This PR fixes that for the master branch.
Note: The last commit to PR #309 fixes that for v0.8.
> Fixed wbemcli ec calling ecn.

- pywbem/NEWS
- pywbem/cim_operations.py
- pywbem/wbemcli.py
Addresses issue #308.
Ready to be merged into 0.8.
Please review and test.
> Upgraded wbemcli script to 0.9 level of code, in support of certificates

- pywbem/cim_obj.py
- testsuite/test_cim_obj.py
Ready to be merged. Also updated the testcases.
Please review.
> Added escaping of single quotes to mofstr().

- pywbem/NEWS
- pywbem/__init__.py
- setup.py
> Release v0.8.4

- pywbem/_listener.py
- pywbem/_server.py
- pywbem/cim_constants.py
- testsuite/test_mof_compiler.py
Fixed some lint errors in various modules we are not touching right now.
There was one code change. change variable that was unknown. keyword was unknown variable in list of tests against word. changed it to word
That was the only code change.  Just trying to cut the pylint down a bit to see my new ones.
> Fix a number of pylint errors. 

- .gitignore
- docs/conf.py
- docs/index.rst
- docs/notebooks/connections.ipynb
- docs/tutorial.rst
> Added first Jupyter notebook on a new tutorial page.

- pywbem/cim_operations.py
> Fixes #323: Added links to WBEM operations section to WBEMConnection and to all of its operation methods

- docs/changes.rst
- testsuite/run_cim_operations.py
Add tests of all of the functions of the server class
to run_cim_operations including comparison of results
against results from other function to access data
and/or expected results.
Add note to changes.rst
> fixes #346 Add tests to run_cimoperations.py for server class

- docs/changes.rst
- mof_compiler
Please review.
Details:
- Changed cmd line options as agreed in issue #216.
- FIxed bug that pywbem.Error was used but not imported.
- Fixed bug that exceptions (e.g. ConnectionError because server not found) were not reported but the program just exited with rc=1.
> Fixes #216: Changed cmd line options of mof_compiler to standard, and fixed some bugs

- examples/explore.py
This has been added hard coded, without getting it from the command line.
> Added no_verification=True to explore.py

- pywbem/_server.py
Ready to be merged. PLease review.
> Fixes #393: Added list() around zip() to fix TypeError on Python 3

- examples/explore.py
- pywbem/_listener.py
- pywbem/_server.py
> Fixes #387: In WBEMListener methods, changed server URL to server ID. Shortened output of repr() for WBEMServer

- pywbem/cim_http.py
Just adds HTTPError to list of imports.
> fixes #415 Add missing export label from new HTTPError exception

- README.md
Added a simple section to README.md to document 0.9.0 and 0.10.0.  Feel free to argue about exactly what I said.  Just want to document:
1. best estimate of release date.
2. Where to find more info.
> fixes #425 Add a project plans section to the README.md

- README.md
Reword couple of lines and bold some paragraph headers for schedule.. No Issue filed for this change.
> Minor cleanup to README.md

- docs/changes.rst
Add the basic definition of the new functionality for server and
listener to changes.rst. No code changes
> fixes #408 Add the initial definition of WBEMServer and listener

- README.md
Notice that we are delaying release date for 0.9.0
+1.  
Ready for review
> Notice on change to release date for README.md

- examples/explore.py
- pywbem/_server.py
Ready for Review:
This fixes the known issue (incorrect exception catch.
It fixes a couple of pylint issues in one of the examples.
Note that the fact that the server in error is doing other strange things is outside scope of this fix.
> Fixes #433: Bad exception. Fix couple of pylints in example.

- setup.py
> Fixes #460: Moved PyYAML and ordereddict packages from develop to install.

- testsuite/run_operationtimeouts.py
+1
This is editorial cleanup to a test program that only runs against OpenPegasus and only I run.  There should be little risk to doing this as part of 0.9.0.  I listed the issue as 0.9.0 optional but might as well get this in.  Fixed the help where some EOLs were missing, a variable name, and added back the else component of getting name password on cmd line.
> Fixes #472: Documentation and help editorial cleanup for run_operationtimeouts.py

- docs/changes.rst
Some items have been merged (e.g. items for indication support).
Cleaned up formatting.
Moved a few items between Enhancements and Bug fixes.
> Cleaned up change log.

- DEVELOP.md
> Updated DEVELOP.md to correct namespace use and formatting.

- testsuite/run_cim_operations.py
Found some code errors in the pull tests and also cleaned up to code and
added another test for instance equality.
Fixed those issues.  Note that since I am the only user and we are down to the end, I made this one 0.9.0 optional
> Fixes #479: Clean up run_cimoperations.py

- DEVELOP.md
Based upon experience with the 0.9.0 release.
> Fixed some omissions in DEVELOP.md

- examples/listen.py
- examples/send_indications.py
Extend listen.py to count indications received by host rather than
overall count. Change name of logger from _logger to logger to
be easier to work with and consistent with python logger examples
Change send_indications.py to correct issue in argparser.
Clean up send_indicatons server cert verification
Add a new property to indication so in the future we can id source.
Clean up code around server cert verification. We had disabled it before
since the requests module has a different pattern than other ssl code in
that it combines the no-verification and server cert into a single
variable. If False, no verification of server cert. If a file, it is the
server cert file.
> Fixes #502: Extend examples for indications

- testsuite/run_cim_operations.py
Ready for review
Fixed the existing tests so that it does not fail.  The issue was not the code but the fact that we were enumerating CIM_ManagedElement and one of the subclasses is threads.  The count of threads varies continuously so that even a open/pull sequence immediatly followed by an enumerate often ended up being slightly different. Changed the test so that we do approximate counts and it does not fail if the counts are slightly different.
We will add one more test with another issue where we know the exact count expected and can test easily but that will be pegasus only since it depends on a specific provider.
> Fixes #485: run_cimoperations.py fail with instance count error

- docs/changes.rst
- pywbem/_subscription_manager.py
This PR merges the fix for issue #500 into the 0.9 fix stream.
> Correct var used before setting issue - for 0.9 fix stream

- docs/changes.rst
> Updated change log up to now.

- docs/appendix.rst
- docs/changes.rst
- docs/development.rst
- docs/index.rst
- docs/intro.rst
Please review.
This is improves the installation documentation in response to issue #506.
> Docs: Added installation and development sections.

- .travis.yml
- README.md
> Added support for coveralls service.

- setup.py
> Added retry in setup script for pypi xmlrpc failures.

- docs/changes.rst
- examples/pegasusindicationtest.py
- examples/send_indications.py
- flake8.rc
- makefile
- os_setup.py
- pywbem/_listener.py
- pywbem/_recorder.py
- pywbem/_subscription_manager.py
- pywbem/cim_constants.py
- pywbem/cim_http.py
- pywbem/cim_obj.py
- pywbem/cim_operations.py
- pywbem/cim_types.py
- pywbem/cim_xml.py
- pywbem/exceptions.py
- pywbem/mof_compiler.py
- pywbem/tupleparse.py
- setup.py
- testsuite/compat_args.py
- testsuite/run_cim_operations.py
- testsuite/test_cim_obj.py
- testsuite/test_indicationlistener.py
- testsuite/test_mof_compiler.py
- testsuite/unittest_extensions.py
Make a number of minor changes including both editorial changes to eliminate flake8 issues and some actual code changes.
Ready For Review:
> fixes #523:  flake8 cleanup of issues and more ignores

- pywbem/_subscription_manager.py
> Fixes #483: Added check for referencing subscriptions in remove filter + destination

- makefile
Please review.
It turned out that Pylint also does not run on py26 anymore.
> Fixes #533: In make check, skipping flake8 and pylint on py26.

- pywbem/_recorder.py
Please test with run_operations.py.
Details:
- Fixed the 'TypeError: must be str, not bytes' reported in issue #531 by treating thge HTTP response payload as binary bytes and decoding them into unicode.
- Fixed the follow on error that a text mode file cannot write binary bytes, by removing the encoding into binary bytes when serializing to yaml.
- Fixed the error that Uint16 was not properly prepared in toyaml(), by moving the check for int after the check for CIMInt.
> Fixes #531: Fixed several errors in recorder on Python 3.

- setup.py
> Fixes #545: Fixed UnboundLocalError for exc in setup.py.

- pywbem/_subscription_manager.py
This PR does not include a testcase.
Please review.
Details:
- Inserted an indicator for ownership into the `Name` property of filters and destinations (`"owned"` vs. `"permanent"`).
- Made subscription manager ID mandatory (must not be None), because it is now used for recognizing owned instances.
- Made filter ID mandatory for the same reason.
- Added code in `add_server()` to determine owned destinations and filters by matching their `Name` property, and to determine owned subscriptions if they reference an owned filter or an owned destination.
> Fixes #461: Recovering owned destination, filter and subscriptions upon server add.

- wbemcli
Reduce the flake 8 messages to zero for this file
> fixes # 567 Clean up flake8 errors with wbemcli.

- testsuite/run_cim_operations.py
1. Fix a global that disappeared
2. Fix pylint issues
3. Fix issue with indication tests where we were getting errors with no
subscription or filter ids
4. Fix issues with latest changes to subscription manager
> fixes  #571 Minor fixes to cim_operations.py

- docs/changes.rst
- docs/intro.rst
This PR rolls back the change from PR #549 into pywbem v0.9.
> Added description of prereq OS packages.

- makefile
- mof_compiler
- pywbem/_recorder.py
- pywbem/cim_http.py
- pywbem/cim_xml.py
- pywbem/mof_compiler.py
- setup.py
- testsuite/run_cim_operations.py
- testsuite/test_cim_http.py
- testsuite/validate.py
- wbemcli
> Fixes #560: Added scripts to flake8 and pylint checks; fixed flake8 erros in mof_compiler.

- docs/changes.rst
- docs/indication.rst
- pywbem/_server.py
> Fixes #495: Declared indication API and server API to be final.

- docs/changes.rst
- setup.py
> Fixes #556: Added git as an OS-level dependency for development.

- docs/changes.rst
- pywbem/_version.py
> Fixes #580: Release 0.9.1

- makefile
This PR will be merged quickly if it passes Travis.
> Fixes #600: Changed makefile to skip Sphinx on Python 2.6

- makefile
This PR rolls back the fix for issue #600 into the 0.9.x fix stream.
> For 0.9: Changed makefile to skip Sphinx on Python 2.6

- pywbem/_subscription_manager.py
This PR fixes items 3 and 4 in issue #616.
> Issue #616: Fixed double CreateInstance in _create_subscription() and __enter__() return value.

- pywbem/_recorder.py
This PR covers the subset of PR #613 that fixes the access to None in the recorder.
I consider this one approved.
> Issue #588: Fixed access to None in recorder.

- pywbem/cim_operations.py
Ready for review if it passes tests.
For some reason I had to manually create the pull request on this one.  I pushed it and the branch showed up but the button to do a pr never did. It adds one real fix, some editorials and a doc fix. If that turns out to be an Issue we can cancel this one and do a new pr.
+1
> fixes #624 some minor fixes to cim_operations.py

- docs/changes.rst
- pywbem/cim_operations.py
We reviewed the text in the call today, so I'm going to assume approval for merging this one.
> Improved description of default timeout.

- testsuite/test_install.sh
Needed for release, to make test_install.sh work again.
> Adjusted test_install.sh to current build.

- DEVELOP.md
This reflects the experience from releasing 0.10.0.
The only significant change is to check out master and update it from upstream in a couple of places.
> Streamlined DEVELOP.md somewhat.

- DEVELOP.md
- README.md
- docs/changes.rst
- pywbem/_version.py
The second commit updates the change log from the commit log.
It should be complete now.
> Release 0.10.0

- pywbem/cim_http.py
- pywbem/mof_compiler.py
- testsuite/run_cim_operations.py
- testsuite/test_cim_xml.py
- wbemcli.py
This is the start of an attempt to remove pylint messages from at least
the pywbem module. Still working but wanted to start the pr. Goal is to remove the erro pylints completely and almost all of the others except todos from the pywbem module and wbemcli.py
> WIP Remove a number of pylint messages

- docs/changes.rst
- docs/compiler.rst
- docs/intro.rst
- pywbem/__init__.py
- pywbem/mof_compiler.py
> Fixes #634: Added MOF compiler API to pywbem namespace

- pylintrc
Please review.
Details:
- Set number of parallel pylint jobs to 4 for speedup.
- Disabled full pylint report because it added large amounts of source code.
> Pylint config changes.

- docs/changes.rst
- docs/mof_compiler.help.txt
- mof_compiler
- wbemcli.py
Added a statement for version to all of the current cli tools
> Fixes #630: Add --version (-V) to argparse for wbemcli and mof_compiler

- docs/changes.rst
- docs/development.rst
- docs/notebooks/connections.ipynb
- docs/notebooks/iterablecimoperations.ipynb
- docs/notebooks/pulloperations.ipynb
- docs/notebooks/subscriptionmanager.ipynb
- docs/notebooks/wbemserversclass.ipynb
- docs/tutorial.rst
- testsuite/run_cim_operations.py
- tools/ipython_toc.py
Added notebooks for
*  Pull operations - A single notebook with TOC
* Iter... operations - A single notebook
*  WBEMServer class
WIP Today because there are a number of TODOs, primarily sections and examples that are incomplete.
I included a toc generator in the tools directory. It is manual now so you have create the toc and manually insert into the notebook.  You also have to update when you change the sections in a notebook
Extended the tutoral page to include the new notebooks
Added to changes.rst
Comments welcome but I know I have more work on this one.  There are several TODOs and I think I was messy in some of my text.
> [WIP] Fixes #682: Add new ipython notebooks

- pywbem/_server.py
I did this one just to retest travis.
> Fixes #670: Add documentation about case sensitivity

- docs/changes.rst
- wbemcli.py
Correct dest error. Add display of enable_stats for connection
> Fixes #709: Correct code error in wbemcli.py

- docs/changes.rst
- pywbem/cim_operations.py
Remove extra print statement left from earlier commit
> Fixes #704: Remove extra print statement

- docs/changes.rst
- docs/intro.rst
- pywbem/cim_operations.py
Adds section to intro to document a) not-spec features, b) level of testing against servers.
> Fixes #653 Add documenation to document non-specific server features

- docs/changes.rst
- docs/client.rst
Includes comment in changes.rst
> Fixes #740: Fix statistics ref in docs/clients.rst

- DEVELOP.md
> Improved release instructions in DEVELOP.md.

- docs/changes.rst
- makefile
- pywbem/_logging.py
**Note:** This PR is on top  of PR #766.
Details in the commit message.
> Fixes #754: Fixed possibility for incorrect hashbang lines in pywbem scripts

- docs/changes.rst
- pywbem/cim_operations.py
- setup.py
**Note:** This PR is on top of PR #769.
> Fixes #762: Fixed the incorrect doc ref to tuple.

- docs/changes.rst
- makefile
- setup.py
**Note:** This PR is now on top  of PR #769.
> Fixes #759, #760: Fixed issues with older versions of pip and setuptools

- DEVELOP.md
- README.rst
- docs/intro.rst
- pywbem_os_setup.sh
It would be good to test the script on some Linux distributions.
For details, refer to the commit message.
> Fixes #673: pywbem_os_setup.sh script for installing prereq. OS packages

- .travis.yml
- appveyor.yml
- docs/changes.rst
- docs/intro.rst
- makefile
- os_setup.py
- pywbem/cim_constants.py
- pywbem/cim_types.py
- setup.py
- testsuite/test_cim_types.py
- testsuite/test_nocasedict.py
- tools/debug_dll_dependencies.bat
- tox.ini
- uninstall_pbr_on_py26.py
The main motivation for this PR was to roll back PRs #668 and #715 in order to solve issue #755.
The rest of the PRs in this PR were needed due to various environmental changes.
> Fixes #755: Rollback of various PRs from 0.11.0 into 0.10.1 including #715

- docs/appendix.rst
- docs/changes.rst
- pywbem/cim_obj.py
- pywbem/cim_operations.py
> Doc improvements: editorial + Iter...() methods + glossary

- .travis.yml
- appveyor.yml
For merging into master, if it works.
> Prepared Travis control file for OS-X checks.

- makefile
- pylintrc
Ready to be merged; no review needed.
> PyLint: Enabled reports; cleaned up command line

- .gitignore
- coveragerc
- makefile
> Minor improvements in coverage reporting.

- testsuite/test_statistics.py
Replaced display code with tests of the generated output.
> Fixes #779: test_statistics displays instead of testing results

- pywbem/cim_obj.py
> Pylint: Removed disabled code in cim_obj.py and restructured type check.

- pywbem/cim_obj.py
> Pylint: Removed TODO about classname checks.

- pywbem/cim_obj.py
> Pylint: Removed TODO about removing toinstance parameter.

- pywbem/cim_xml.py
> Pylint: Corrected calls to superclass init in cim_xml module.

- pywbem/_recorder.py
> Pylint: Fixed that long was not covered in toyaml().

- pywbem/_subscription_manager.py
> Pylint: Removed TODO for adding user-defined filter name in sub.mgr.

- testsuite/unittest_extensions.py
> Pylint: Fixed unused arg in assertion methods in unittest_extensions.

- pywbem/cim_http.py
> Pylint: Fixed incorrect disabling of no-member warning.

- pywbem/cim_operations.py
> Pylint: Disabled warning about unbalanced tuple unpacking

- .gitignore
> Added blah.yaml to .gitignore

- pywbem/cim_obj.py
- pywbem/cim_types.py
> Removed unused _convert_*() functions in cim_obj.py.

- makefile
Ready for review and merge. For details, see commit message. When reviewing, please note the consequence for the test quality of the install process mentioned in the commit message.
> Fixes #849: Addressed issue that test_wbem.py does not find wbemcli on RHEL

- testsuite/test_statistics.py
Need to merge this quickly to make it run with the manual_ci_run cron job.
After that, we can conclude whether it fixed the issue.
> Fixed statistic test error by extending allowable delta.

- docs/changes.rst
- pywbem/cim_operations.py
> Fixes #852: Improved the description of the ModifyInstance operation.

- testsuite/test_wbemcli.py
This PR was split out from PR #857 and is ready for review and merge.
> Fixed and simplified invocation of wbemcli in test_wbemcli.py

- testsuite/test_statistics.py
This PR was split out from PR #857 and is ready for review and merge.
> Added diagnostic message to time delta asserts in test_statistics.py.

- docs/client.rst
- docs/conf.py
> Fixes #869: Cleaned up :special-members: option in docs; fixed duplicate logger

- pywbem/_server.py
> Fixes #873: Cleaned up statement about experimental vs final of WBEM server API

- docs/changes.rst
- pywbem/_statistics.py
- pywbem/cim_operations.py
> Fixes #876: Finalized time statistics support

- DEVELOP.md
> Fixes #785: Updated DEVELOP for pbr, fixes, simplification.

- docs/changes.rst
- docs/indication.rst
- pywbem/_listener.py
- pywbem/_logging.py
- pywbem/_recorder.py
- pywbem/_subscription_manager.py
- pywbem/cim_constants.py
- pywbem/cim_obj.py
- pywbem/cim_operations.py
- pywbem/config.py
- pywbem/exceptions.py
This is for general docs improvement.
> Docs: Added 'New in pywbem M.N...' text since 0.8

- docs/development.rst
- docs/intro.rst
- pywbem_os_setup.sh
**Note:** This PR is on top of PR #857.
One caveat worth having an eye on, is that the information about installing the development environment in the Development section is not as nicely separated by operating system (as the Installation section is). Please review.
> Fixes #557, #864: Docs: Major update of Installation & Development sections; pywbem_os_setup

- docs/changes.rst
- pywbem/cim_http.py
- pywbem/cim_operations.py
> Fixes #888: Docs: Clarified use of ca_certs parameter and its defaults.

- pywbem/_logging.py
- pywbem/cim_obj.py
As agreed upon when discussing issue #850.
> Fixes #850: Cleanup on public symbols

- docs/changes.rst
- pywbem/cim_operations.py
- wbemcli.py
**Note:** This PR is on top of PR #881 and needs to wait for that one. No other changes needed here.
> Fixes #875: Finalized Iter support

- pywbem/_logging.py
- pywbem/_recorder.py
- pywbem/config.py
- wbemcli.py
> Fixes #883: Dropped duplicate logging symbols from config module, Improved logging docs

- docs/changes.rst
- pywbem/cim_http.py
> Fixes #891: Caught more M2Crypto exceptions.

- pywbem/cim_http.py
This addresses a number of items in the list of TODOs for `cim_http.py` in issue #812. 
> Resolved comment-related TODOs in cim_http.py

- pywbem/cim_obj.py
- testsuite/test_cim_obj.py
For details, see commit message
The fixes in cim_obj are for issues that were discovered as part of improving the test cases (they don't have an issue in GitHub).
> Improved and converted more of test_cim_obj to py.test; Fixes in cim_obj

- docs/changes.rst
- pywbem/cim_obj.py
- pywbem/cim_operations.py
- pywbem/cim_types.py
- pywbem/config.py
- testsuite/test_cim_obj.py
**Note:** This PR is on top of PR #905.
> Improvements in issuing Python warnings

- docs/changes.rst
- pywbem/_recorder.py
- pywbem/cim_obj.py
- pywbem/cim_operations.py
- pywbem/cim_types.py
- pywbem/config.py
- testsuite/test_cim_obj.py
- testsuite/test_cim_operations.py
- testsuite/test_cim_xml.py
- testsuite/test_mof_compiler.py
- testsuite/test_tupleparse.py
- testsuite/validate.py
**Note:** This PR is on top of PR #907.
> Fixed some more Python warnings

- pywbem/cim_operations.py
> Fixes #917: Clarified TODO about setattr in EnumerateInstances

- docs/changes.rst
- pywbem/cim_operations.py
> Fixes #918: Docs: Clarified namespace in path returned by CreateInstance

- docs/changes.rst
- pywbem/cim_obj.py
- pywbem/cim_types.py
- testsuite/test_cim_obj.py
- testsuite/testclient/README.md
- testsuite/testclient/associatorinstances.yaml
- testsuite/testclient/embeddedobjects.yaml
- testsuite/testclient/enumerateclasses.yaml
- testsuite/testclient/enumerateinstancenames.yaml
- testsuite/testclient/enumerateinstances.yaml
- testsuite/testclient/getalltypes.yaml
- testsuite/testclient/getclass.yaml
- testsuite/testclient/getinstance.yaml
- testsuite/testclient/invalidresponseerror.yaml
- testsuite/testclient/networkerror.yaml
- testsuite/testclient/openenumerateinstancepaths.yaml
- testsuite/testclient/openenumerateinstanceswithpath.yaml
**Note:** This PR is on top of PR #911.
This PR grew somewhat larger than the original issue described in #903. The changes belong together, though.
For details, see the (one) commit message added by this PR.
> Fixes #903: Fixes and cleanup for tocimxml()

- pywbem/cim_types.py
> Fixed pylint issue about invalid name number_types

- docs/changes.rst
- pywbem/cim_http.py
- pywbem/cim_operations.py
**Note:** This PR is on top of PR #896.
To see the changes of just this PR, click on tab "Commits" and select the one named similar to this PR.
**Attention:** This change should be tested against a real environment, with connection error situations.
> Fixes #916: Cleanup and improvements in exc handling in and around wbem_request()

- pywbem/cim_obj.py
- testsuite/test_cim_obj.py
Particular review points worth mentioning:
* Extensions to WBEM URI format (see docstrings of the two `from_wbem_uri()` methods), particularly the support for omitting the leading slash in "local" WBEM URIs.
* DeprecationWarnings that are issued in the two `from_wbem_uri()` methods.
> Fixes #898: Removed limitations on from_wbem_uri()

- pywbem/cim_obj.py
- testsuite/test_cim_obj.py
> Fixes #900, #897, #815, #343: Major overhaul of logic in CIM object's tomof() and underlying functions

- docs/changes.rst
- pywbem/_listener.py
- pywbem/cim_operations.py
- pywbem/tupleparse.py
- pywbem/tupletree.py
- testsuite/test_cim_operations.py
- testsuite/test_tupleparse.py
- testsuite/test_tupletree.py
This PR is a preparation for improving the testclient yaml testcases for embedded objects (issues #436, #437, #440). Without these changes, it was very hard to figure out what was going on. The actual solutions to these issues will be in another PR on top of this one.
> Improved and fixed exception handling of CIM-XML parsing

- docs/changes.rst
- pywbem/_listener.py
- pywbem/cim_operations.py
- pywbem/tupleparse.py
- pywbem/tupletree.py
- testsuite/test_cim_operations.py
- testsuite/test_tupleparse.py
- testsuite/test_tupletree.py
- testsuite/testclient/embeddedobjectclasses.yaml
**Note:** This PR is on top of PR #945. To review this PR, look at only its last commit.
> Fixes #436 (part1): Added testclient yaml testcases for embedded objects with classes

- docs/changes.rst
- pywbem/_listener.py
- pywbem/cim_operations.py
- pywbem/tupleparse.py
- pywbem/tupletree.py
- testsuite/test_cim_operations.py
- testsuite/test_tupleparse.py
- testsuite/test_tupletree.py
- testsuite/testclient/embeddedobjectinstances.yaml
**Note:** This PR is on top of PR #945. To review this PR, look at only its last commit.
> Fixes #436 (part2): Added testclient yaml testcases for embedded objects with instances

- docs/changes.rst
- pywbem/cim_obj.py
- testsuite/testclient/embeddedobjectinstances.yaml
> (2) Fixed missing embedded_object in CIMProperty equality test

- pywbem/_recorder.py
> Fixes minor Pylint TODOs in _recorder.py

- docs/intro.rst
This PR implements the solution recommended in RTD issue rtfd/readthedocs.org#3391.
Once it is merged, the solution can be verified by inspecting the "latest" build on RTD.
> Fixes #864: Fixed RTD download link of pywbem_os_setup.sh

- rtd-requirements.txt
Needs to be merged in order to verify that this change works -> setting priority.
> Fixed RTD build failures by adding pbr

- docs/appendix.rst
- docs/conf.py
- docs/development.rst
- docs/intro.rst
- makefile
- pywbem/_logging.py
- pywbem/_subscription_manager.py
- pywbem/cim_http.py
- pywbem/cim_obj.py
- pywbem/cim_operations.py
- pywbem/cim_types.py
- pywbem/mof_compiler.py
- pywbem/tupleparse.py
- pywbem/tupletree.py
> Removed warnings in Sphinx doc build; Improved operation_recorder docs

- docs/conf.py
- docs/intro.rst
- makefile
- pywbem/_version.py
Again, a change that can only be verified once it is merged. -> priority.
> RTD docs: Fixed pywbem version; Fixed 2nd link to pybewm_os_setup.sh

- docs/changes.rst
- pywbem/_recorder.py
- pywbem/cim_operations.py
Review point: Note that the operation_recorder property was not finalized, as we had discussed, because that would be the only one of the set of operation recorder related stuff we would finalize.
> Fixes #976: Added operation_recorders property and other cleanup

- DEVELOP.md
- docs/changes.rst
- docs/intro.rst
- makefile
- pywbem/_version.py
> Minor docs fixes and updates

- pywbem/cim_http.py
- pywbem/cim_obj.py
- pywbem/cim_operations.py
- pywbem/mof_compiler.py
This helps to sort out TODOs that have an issue, when re-generating the TODOs with Pylint.
> Added issue number to some TODOs and clarified TODO text

- pywbem/cim_obj.py
> Replaced TODOs in cim_obj.py with Notes

- docs/appendix.rst
- docs/changes.rst
- pywbem/cim_obj.py
- pywbem/mof_compiler.py
- testsuite/run_cim_operations.py
- testsuite/test_cim_obj.py
- testsuite/test_mof_compiler.py
- testsuite/test_nocasedict.py
- testsuite/test_recorder.py
- testsuite/test_wbemconnection_mock.py
**Note:** This is PR is on top of PR #955.
> (2) Docs: Explained WBEM URI instance path comparison

- docs/changes.rst
- pywbem/cim_obj.py
- testsuite/test_cim_obj.py
This is part 1, which just extends CIMParameter as needed. Part 2 will be separate and will exploit that in InvokeMethod.
> Issue #950, part 1: Extended CIMParameter to represent parameter values

- pywbem/cim_obj.py
- testsuite/test_cim_obj.py
> Pylint: Fixed some minor issues.

- docs/changes.rst
- docs/client.rst
- pywbem/cim_types.py
- testsuite/test_cim_types.py
> Fixes #993: Made cimtype() and type_from_name() conversion functions part of public API

- pywbem_mock/_wbemconnection_mock.py
- testsuite/test_wbemconnection_mock.py
I misinterpreted the Params vs params options in invoke method and did not incorporate both Params and params into fake  InvokeMethods cleanly.  I fact, we really do not have an example that shows the various options for calling InvokeMethod  to make it easy for the client writer but that is a different question.
This cleans up the InvokeMethod and callback interface and adds more tests.
> Fix invoke method interface. 

- rtd-requirements.txt
> Docs: Added PyYAML package to RTD prereqs.

- pywbem_mock/_wbemconnection_mock.py
- testsuite/test_wbemconnection_mock.py
Fixes  the display_repository to output unicode for python 2. Also removed a couple
of worthless TODOs.
> Add test compile and display with unicode mof. 

- pywbem/mof_compiler.py
- pywbem/tupleparse.py
- testsuite/test_cim_obj.py
- testsuite/test_client.py
- testsuite/test_nocasedict.py
> Fixes #1009: Removed UserWarnings about loosing order preservation

- docs/changes.rst
- docs/intro.rst
> Docs: Clarified that multi-requests are not supported.

- appveyor.yml
- docs/development.rst
- docs/intro.rst
- pywbem_os_setup.sh
This PR has priority because it fixes the Appveyor CI issue that recently popped up. Some other PRs depend on this PR.
> Fixes #1019: (1) Corrected install of xmllint and of lxml prereqs

- appveyor.yml
- docs/development.rst
- docs/intro.rst
- pywbem/_valuemapping.py
- pywbem/tupleparse.py
- pywbem_os_setup.sh
**Note:** This PR is on top of PR #1020.
For details, see the TODO list in PR #812.
> (2) Addressed TODOs in tupleparse.py and _valuemapping.py

- appveyor.yml
- docs/development.rst
- docs/intro.rst
- pywbem/_valuemapping.py
- pywbem/tupleparse.py
- pywbem_os_setup.sh
**Note:** This PR is on top of PR #1014.
For details, see commit message (of only the last commit).
> (3) Improved exception messages in tupleparse.py

- appveyor.yml
- docs/development.rst
- docs/intro.rst
- pywbem/_valuemapping.py
- pywbem/tupleparse.py
- pywbem_os_setup.sh
- testsuite/test_tupleparse.py
**Note:** This PR is on top of PR #1016.
The test cases are the same as before (they will be extended in another PR).
> (4) Migrated unittest of tupleparse.py from unittest2 to py.test

- pywbem/cim_operations.py
- testsuite/testclient/invokemethod.yaml
> (4x) Fixed error when invoking Invokemethod() with keyword params

- dev-requirements.txt
- docs/changes.rst
- minimum-constraints.txt
- pywbem/cim_http.py
- pywbem/cim_obj.py
- pywbem/cim_operations.py
- pywbem/tupleparse.py
- testsuite/test_client.py
- testsuite/test_tupleparse.py
- testsuite/testclient/associatorinstances.yaml
- testsuite/testclient/embeddedinstances.yaml
- testsuite/testclient/embeddedobjectclasses.yaml
- testsuite/testclient/embeddedobjectinstances.yaml
- testsuite/testclient/enumerateinstances.yaml
- testsuite/testclient/execquery.yaml
- testsuite/testclient/getalltypes.yaml
- testsuite/testclient/getclass.yaml
- testsuite/testclient/getinstance.yaml
- testsuite/testclient/invalidresponseerror.yaml
- testsuite/testclient/invokemethod.yaml
- testsuite/testclient/openassociators.yaml
- testsuite/testclient/openenumerateinstanceswithpath.yaml
- testsuite/testclient/openqueryinstances.yaml
- testsuite/testclient/openreferenceinstanceswithpath.yaml
- testsuite/testclient/pullinstances.yaml
- testsuite/testclient/pullinstanceswithpath.yaml
- testsuite/testclient/referenceinstances.yaml
**Note:** This PR is on top of PR #1018.
Note my update to issue #1024.
> Fixes #1024: (6a) Verify that single quoted attr values work in tupleparser

- dev-requirements.txt
- docs/changes.rst
- minimum-constraints.txt
- pywbem/cim_http.py
- pywbem/cim_obj.py
- pywbem/cim_operations.py
- pywbem/tupleparse.py
- testsuite/test_client.py
- testsuite/test_tupleparse.py
- testsuite/testclient/associatorinstances.yaml
- testsuite/testclient/embeddedinstances.yaml
- testsuite/testclient/embeddedobjectclasses.yaml
- testsuite/testclient/embeddedobjectinstances.yaml
- testsuite/testclient/enumerateinstances.yaml
- testsuite/testclient/execquery.yaml
- testsuite/testclient/getalltypes.yaml
- testsuite/testclient/getclass.yaml
- testsuite/testclient/getinstance.yaml
- testsuite/testclient/invalidresponseerror.yaml
- testsuite/testclient/invokemethod.yaml
- testsuite/testclient/openassociators.yaml
- testsuite/testclient/openenumerateinstanceswithpath.yaml
- testsuite/testclient/openqueryinstances.yaml
- testsuite/testclient/openreferenceinstanceswithpath.yaml
- testsuite/testclient/pullinstances.yaml
- testsuite/testclient/pullinstanceswithpath.yaml
- testsuite/testclient/referenceinstances.yaml
**Note:** This PR is on top of PR #1018.
> Fixes #1022: (6b) Added support for VALUE.NULL in tupleparse.py

- dev-requirements.txt
- docs/changes.rst
- minimum-constraints.txt
- pywbem/cim_http.py
- pywbem/cim_obj.py
- pywbem/cim_operations.py
- pywbem/tupleparse.py
- testsuite/test_cim_obj.py
- testsuite/test_client.py
- testsuite/test_nocasedict.py
- testsuite/test_tupleparse.py
- testsuite/testclient/associatorinstances.yaml
- testsuite/testclient/embeddedinstances.yaml
- testsuite/testclient/embeddedobjectclasses.yaml
- testsuite/testclient/embeddedobjectinstances.yaml
- testsuite/testclient/enumerateinstances.yaml
- testsuite/testclient/execquery.yaml
- testsuite/testclient/getalltypes.yaml
- testsuite/testclient/getclass.yaml
- testsuite/testclient/getinstance.yaml
- testsuite/testclient/invalidresponseerror.yaml
- testsuite/testclient/invokemethod.yaml
- testsuite/testclient/openassociators.yaml
- testsuite/testclient/openenumerateinstanceswithpath.yaml
- testsuite/testclient/openqueryinstances.yaml
- testsuite/testclient/openreferenceinstanceswithpath.yaml
- testsuite/testclient/pullinstances.yaml
- testsuite/testclient/pullinstanceswithpath.yaml
- testsuite/testclient/referenceinstances.yaml
**Note:** This PR is on top of PR #1018.
> Fixes #1026: (6c) Fixed support for unnamed keys in instance paths

- testsuite/run_cim_operations.py
**Note:** This PR is on top of PR #1037.
For status of tests that are still missing, see PR #1021.
> (5) Fixes, more tests and some cleanup for CIM-XML tupleparser

- docs/changes.rst
- pywbem/tupleparse.py
- pywbem/tupletree.py
- testsuite/run_cim_operations.py
- testsuite/test_tupleparse.py
**Note:** This PR is on top of PR #1018.
For details, see the commit message (of just the last commit).
> Fixes #1021: (6) Added more tupleparse test cases (part 2); tupleparse fixes

- docs/changes.rst
- pywbem/tupleparse.py
- pywbem/tupletree.py
- testsuite/run_cim_operations.py
- testsuite/test_tupleparse.py
**Note:** This PR is on top of PR #1029.
> Fixes #1031: (7) Added support for ARRAYSIZE to PROPERTY.ARRAY in tupleparser; test cases

- docs/changes.rst
- docs/intro.rst
- pywbem/tupleparse.py
- testsuite/test_tupleparse.py
**Note:** This PR is on top of PR #1048.
> Fixes #1042: (9) Added mixed case bool attr values to QUALIFIER in tupleparser

- pywbem/cim_obj.py
- pywbem/tupleparse.py
- testsuite/run_uprint.py
- testsuite/test_cim_obj.py
- testsuite/test_nocasedict.py
- testsuite/test_tupletree.py
- testsuite/test_wbemconnection_mock.py
> Removed some Pylint issues.

- docs/changes.rst
- pywbem/tupleparse.py
- testsuite/test_tupleparse.py
For details, see commit message (of only the last commit)
> Fixes #1030: Added support for instance qualifiers in tupleparser

- docs/changes.rst
- pywbem/tupleparse.py
- testsuite/test_tupleparse.py
> Fixes #1041: Checked for invalid boolean values in QUALIFIER.DECLARATION in tupleparser

- docs/changes.rst
- pywbem/mof_compiler.py
- pywbem/tupleparse.py
- testsuite/test_mof_compiler.py
- testsuite/test_tupleparse.py
> Fixes #1063: Improved and fixed error handling in MOF compiler

- docs/changes.rst
- pywbem/cim_obj.py
- testsuite/test_cim_obj.py
- testsuite/test_wbemconnection_mock.py
> Fixes #1043: Added checking of CIM type names in CIM objects

- pywbem/_valuemapping.py
> Resolved Pylint issues for _valuemapping.py

- pywbem_mock/_wbemconnection_mock.py
- testsuite/test_wbemconnection_mock.py
Extend Fake_createclass to cover the use of Override qualifier on methods and properties.  This extends the method and also rewrites the tests for this method.
Note that we found a couple of other minor issues and corrected them
and also removed a couple of other TODOs
Since this is part of the initial mock work, there is no separate issue filed for this pr
I have 2 TODOs marked in what is committed covering the following requirements from DSP0200
- Any qualifiers defined in the superclass with a TOSUBCLASS attribute value of true shall 884 appear in the resulting subclass. Qualifiers in the superclass with a TOSUBCLASS 885 attribute value of false shall not be propagated to the subclass. 886
– Any qualifier propagated from the superclass cannot be modified in the subclass if the 887 …
> Extend Fake_createclas for Override qualifier

- docs/changes.rst
- pywbem/_statistics.py
- pywbem/cim_operations.py
- pywbem_mock/_wbemconnection_mock.py
- testsuite/run_cim_operations.py
- testsuite/test_cim_operations.py
- testsuite/test_client.py
- testsuite/test_recorder.py
- testsuite/testclient/associatorinstances.yaml
- testsuite/testclient/createinstance.yaml
- testsuite/testclient/enumerateclasses.yaml
- testsuite/testclient/enumerateinstancenames.yaml
- testsuite/testclient/enumerateinstances.yaml
- testsuite/testclient/getinstance.yaml
- testsuite/testclient/openenumerateinstanceswithpath.yaml
- testsuite/testclient/pullinstanceswithpath.yaml
- wbemcli.py
Note that this change contains some incompatible changes (see change log).
> Fixes #1068: Change WBEMConnection public attributes to become properties

- docs/appendix.rst
- docs/changes.rst
- docs/development.rst
- docs/intro.rst
- pywbem/_version.py
- pywbem_os_setup.sh
**Note:** This PR targets pywbem 0.11.1.
> Fixes #1065: Docs: Fixed installation on Windows

- pywbem/_recorder.py
- pywbem_mock/_wbemconnection_mock.py
This addresses an item from issue #1067.
> Docs: Fixed Sphinx build warnings

- testsuite/run_cim_operations.py
- testsuite/test_cim_obj.py
- testsuite/test_mof_compiler.py
- testsuite/test_statistics.py
- testsuite/unittest_extensions.py
> Fixes #1086: Test: Renamed pywbem assertion methods to avoid unittest conflicts

- docs/intro.rst
> Docs: Fixes and improvements in Standards Conformance section

- docs/intro.rst
This PR addresses a first part of changes to the "Installation" chapter of the documentation, and addresses some items from issue #1067 in that area (see there for status).
Ready for review and merge. Review is best done via the built HTML docs.
> Docs: Fixes and improvements in Installation section, part 1

- docs/intro.rst
> Docs: Improved deprecation and compatibility

- testsuite/test_tupleparse.py
> Avoided UserWarning in test_tupleparse

- testsuite/test_wbemconnection_mock.py
> Avoided output of MOF compile error in mock tests

- testsuite/test_cim_obj.py
> Avoided DeprecationWarning in cim_obj tests

- testsuite/test_cim_operations.py
> Avoided DeprecationWarning in cim_operations.

- testsuite/test_logging.py
> Avoided debug print in test_logging.py

- pywbem_mock/_wbemconnection_mock.py
- testsuite/test_wbemconnection_mock.py
Completely remove the logging from the mocker since it is little
different from the cim_operations api logger and that logger can be used
to accomplish effectively the same thing. The only real difference
between the two is that that small bits of code that emulates
_imethodcall and _method_call return mapping from pure object to tuples
of data for each response.
> Remove the logging functionality from pywbem_mock

- pylintrc
- testsuite/test_cim_obj.py
- testsuite/test_cim_types.py
- testsuite/test_client.py
- testsuite/test_indicationlistener.py
- testsuite/test_nocasedict.py
- testsuite/test_tupleparse.py
- testsuite/test_tupletree.py
- testsuite/test_valuemapping.py
> Addressed more Pylint issues in testsuite sources

- docs/intro.rst
- docs/utilities.rst
- wbemcli.py
> Docs: Simplified description of utility commands

- docs/changes.rst
- docs/intro.rst
- docs/utilities.rst
- pywbem/cim_operations.py
- wbemcli.py
**Note:** This PR is on top of PR #1108. Review only the last commit!
> Fixes #1067: Docs: Fixed and improved ops in WBEMConnection and in wbemcli

- docs/changes.rst
- docs/intro.rst
- docs/utilities.rst
- pywbem/cim_operations.py
- wbemcli.py
**Note:** This PR is on top of PR #1110 (review only the last commit).
> Fixes #1112: Fixed the *params parameter of the wbemcli.im() function

- docs/client/conversion.rst
- docs/client/logging.rst
- docs/client/recording.rst
- docs/client/statistics.rst
- docs/client/valuemappings.rst
- makefile
- pywbem/cim_operations.py
- pywbem/mof_compiler.py
> Fixes #1111: Docs: Fixes and improvements in chapter 4 and chapter 7

- pywbem/_recorder.py
- pywbem/cim_obj.py
- pywbem/cim_xml.py
- pywbem/exceptions.py
> Docs: Improvements and fixes in sections 4.2 to 4.6

- docs/changes.rst
- pywbem/_statistics.py
- pywbem/cim_operations.py
- testsuite/test_statistics.py
> Docs: Improved and fixed statistics section

- pywbem/cim_types.py
> Docs: Clarified how NULL is represented as a CIM typed value

- pywbem/_valuemapping.py
> Docs: Minor editorial changes in ValueMapping chapter.

- pywbem/_server.py
> Docs: Fixes and improvements in WBEM server chapter

- docs/changes.rst
- pywbem/cim_operations.py
- testsuite/testclient/invokemethod.yaml
Ready for review and test and merge.
> Fixes #1123: Fixed that InvokeMethod() rejected input parameter value of None

- docs/client/security.rst
- pywbem/cim_http.py
> Docs: Editorial changes in Security chapter

- pywbem/_listener.py
> Docs: Editorial changes for WBEM listener chapter

- docs/changes.rst
- pywbem/cim_obj.py
- pywbem/cim_operations.py
- pywbem/cim_types.py
- pywbem/cim_xml.py
- testsuite/test_cim_obj.py
- testsuite/test_cim_types.py
- testsuite/test_cim_xml.py
- testsuite/testclient/createinstance.yaml
- testsuite/testclient/embeddedinstances.yaml
- testsuite/testclient/getalltypes.yaml
- testsuite/testclient/modifyclass.yaml
> Fixes #1136: Various fixes and test case improvements for generating CIM-XML

- docs/compiler.rst
- pywbem/mof_compiler.py
> Docs: Improved and fixed MOF Compiler API section.

- pywbem_mock/_wbemconnection_mock.py
- testsuite/test_wbemconnection_mock.py
We need to return something like NOT_SUPPORTED when there are no methods
in the methods repo. The code was returning NOT_FOUND.  This was causing
issues with the get_central_instances test.
> Fix issue in pywbem_mock with incorrect error response to invokemethod

- pywbem/_subscription_manager.py
> Docs: Improvements and minor fixes in WBEMSubscriptionManager section

- wbemcli.py
> Docs: Minor fixes and reordering of functions in wbemcli.py

- docs/changes.rst
- mof_compiler
- pywbem/mof_compiler.py
> Fixes #1157: Fixes and improvements in mof_compiler script

- pywbem/cim_operations.py
- wbemcli.py
> Fixes #1116: Reordered wbemcli ops functions and WBEMConnection ops methods

- docs/changes.rst
> Reordered, improved and moved change log entries

- pywbem/_logging.py
- pywbem/_recorder.py
- pywbem/cim_operations.py
- testsuite/run_cim_operations.py
- testsuite/test_logging.py
- testsuite/test_recorder.py
- testsuite/test_wbemconnection_mock.py
> Fixes #1171: Fixes and improvements in logging code

- docs/mocksupport.rst
- pywbem_mock/_wbemconnection_mock.py
- testsuite/test_wbemconnection_mock.py
- testsuite/test_wbemserverclass.py
> Fixes #1174 Renamed compile_mof_str() to compile_mof_string() in mock support

- pywbem/cim_obj.py
- pywbem_mock/_wbemconnection_mock.py
- testsuite/test_wbemconnection_mock.py
> Fixes #1182 Fixed that FakedWBEMConnection could not add inst with path without keybindings

- docs/changes.rst
- pywbem/__init__.py
- pywbem/_listener.py
- pywbem/_logging.py
- pywbem/cim_operations.py
> Fixes #1175 Cleaned up the use of logging NullHandler

- pywbem/__init__.py
- pywbem/_listener.py
- pywbem/_logging.py
> Fixes #1186 Added NullHandler to pywbem logger on Python 2

- pywbem/__init__.py
- pywbem/_listener.py
- pywbem/_logging.py
- testsuite/test_recorder.py
Added a couple more tests to test_recorder.py as part of reviewing the changes for issues #1180 and #1186.  Also changed couple of examples where we were writing a log file that was left over after test.
> Add more log tests to confirm NullHandler dest=None changes

- docs/intro.rst
> Docs: Improved 'Standards conformance' section

- README.rst
- docs/changes.rst
This is the release PR for pywbem 0.12.0.
Approving it means you agree to release this level as pywbem 0.12.0.
> Release 0.12.0

- DEVELOP.md
- README_PYPI.rst
- setup.cfg
In order to review the new README_PYPI.rst file, use its [rendering on GitHub](https://github.com/pywbem/pywbem/blob/andy/fix-pypi-readme2/README_PYPI.rst).
>  Added a README file for Pypi

- DEVELOP.md
- README_PYPI.rst
- setup.cfg
Roll back this fix from stable_0.12 into master.
> Added a README file for Pypi

- docs/changes.rst
- docs/wbemcli.help.txt
- makefile
This PR rolls back the fix for issue #1205 into the 0.12 fix stream.
> Add pywbem.py to depends file list for recreating docs/wbemcli_help_txt file

- dev-requirements.txt
- minimum-constraints.txt
> fixes #1224 Fixed version incompatibility message for coverage package

- docs/changes.rst
- docs/client/conversion.rst
- pywbem/cim_obj.py
- pywbem/cim_operations.py
- pywbem/mof_compiler.py
- testsuite/test_cim_obj.py
> fixes #904 Deprecated tocimobj() and fixed integer repr in from_wbem_uri()

- testsuite/testclient/test_conftest.py
Just a fix for Karl's last review comment on PR #1219, which I forgot to commit. Fast path.
> Fixed description of test_conftest.py module.

- makefile
> Fixes #1231 Improved dependencies in makefile.

- testsuite/pytest_extensions.py
- testsuite/test_cim_obj.py
- testsuite/test_cim_types.py
- testsuite/test_nocasedict.py
- testsuite/test_tupleparse.py
Fast path because needed as a basis for reporting a pytest issue .
> Issue #1201 Small improvements in test_function decorator and its test functions

- PKG-INFO
- makefile
**Discussion point:** Do we want to do this at all?
> Fixes #1245 Added PKG-INFO file to support install from GitHub tarball

- testsuite/test_logging.py
Converted the remainder of test_logging.py to pytest based tests including one use
of simplified_test_function.
> Convert test_logging to use only pytest

- docs/changes.rst
> Start 0.12.3

- README.rst
- docs/changes.rst
> Release 0.12.3

- testsuite/test_recorder.py
> Corrected reason why test_recorder.py imports unittest2

- docs/changes.rst
- pywbem/mof_compiler.py
- testsuite/test_mof_compiler.py
> Fixes #1278 Fixed MOFCompiler unicode parsing

- testsuite/run_uprint.py
- testsuite/test_recorder.py
- testsuite/test_subscriptionmanager.py
- testsuite/test_wbemconnection_mock.py
- testsuite/test_wbemserverclass.py
> Removed prints from test runs

- DEVELOP.md
- PKG-INFO
- makefile
> Fixes #1207 Fixed incorrect package version in make after adding a git tag

- docs/changes.rst
- pywbem/_server.py
- pywbem/_valuemapping.py
- testsuite/test_valuemapping.py
> Fixes #1281 Improved exception messages for ValueMapping and WBEMServer

- testsuite/test_wbemconnection_mock.py
> Relaxed tolerance for expected delay in test_response_delay()

- appveyor.yml
> adjusted appveyor.yml to new choco req to have pkg checksums

- PKG-INFO
- appveyor.yml
- docs/changes.rst
- makefile
> Fixes #1288 Eliminated confusing pbr import error message in make

- .travis.yml
- makefile
This change fixes an error introduced in PR #1289, that failed on Linux.
> Fixed determination of package version for Linux.

- pywbem/_valuemapping.py
- testsuite/run_uprint.py
- testsuite/simple_mock_add_obj.py
- testsuite/test_valuemapping.py
- testsuite/test_wbemserverclass.py
- testsuite/testclient/conftest.py
- testsuite/testclient/test_conftest.py
> Resolved some more pylint findings

- makefile
> Improved makefile in some areas

- pywbem/tupleparse.py
- testsuite/test_tupleparse.py
As discussed at https://github.com/pywbem/pywbem/issues/1241
My apologies if I'm doing this wrong, I haven't worked with OS projects in a very long time.
> Add support for TYPE attribute in PARAMVALUE

- docs/changes.rst
This change updates the change log for the change in PR #1274.
> Added change log for TYPE attribute of PARAMVALUE (PR #1274)

- docs/changes.rst
- pywbem/__init__.py
- pywbem/config.py
- testsuite/test_itermethods.py
> Fixes #1302 Fixed issue with updating pywbem config variables.

- makefile
- pywbem_os_setup.bat
- pywbem_os_setup.sh
- testsuite/test_wbemcli.py
> Fixes for CygWin and native Windows in makefile and setup scripts

- README.rst
> Fixed error in quickstart example in README.

- docs/changes.rst
> Editorial cleanup in change log.

- docs/changes.rst
- pywbem/cim_operations.py
- pywbem/config.py
- testsuite/testclient/invokemethod.yaml
> Fixes #1326 Added support for HTTP header for SFCB UpdateExpiredPassword()

- appveyor.yml
> Disabled py27-x64 on Appveyor CI to reduce elapsed time

- docs/changes.rst
- pywbem/_listener.py
- pywbem/cim_operations.py
- pywbem/tupleparse.py
- pywbem/tupletree.py
- testsuite/test_tupleparse.py
> Fixes #1155 Add connection ID to ParseError raised in tupleparse and tupletree

- docs/changes.rst
- pywbem/exceptions.py
> Fixes #1350 Added status code name to CIMError string representation

- testsuite/test_wbemserverclass.py
And a few fixes in comment text.
> Fixed a pytest collection warning about test_wbemserver_basic()

- pywbem/_logging.py
- pywbem/_valuemapping.py
- pywbem/cim_http.py
- pywbem/cim_obj.py
- pywbem_mock/_wbemconnection_mock.py
- testsuite/run_cim_operations.py
- testsuite/test_cim_obj.py
- testsuite/test_cim_operations.py
- testsuite/test_logging.py
- testsuite/test_subscriptionmanager.py
- testsuite/test_valuemapping.py
- testsuite/test_wbemconnection_mock.py
- testsuite/test_wbemserverclass.py
- testsuite/testclient/conftest.py
**Note: This PR is on top of PR #1352**
> Fixed pylint issues

- makefile
> Improvements for 'make test'

- docs/changes.rst
- pywbem/cim_operations.py
- testsuite/testclient/createinstance.yaml
> Fixes #1319 Improved exception for CreateInstance without instance name

- docs/appendix.rst
- docs/changes.rst
- pywbem/_server.py
- pywbem_mock/_wbemconnection_mock.py
- testsuite/schema/OpenPegasus/PG_Namespace.mof
- testsuite/test_wbemserverclass.py
- testsuite/wbemserver_mock.py
This PR addresses item 1 described in issue #29.
It would be good to run WBEMServer.create_namespace() against a life server.
> Added WBEMServer.create_namespace() and .cimom_inst.

- pywbem/mof_compiler.py
**Note: This PR is on top of PRs #1318 and #1357. It is sufficient to review only the last commit of this PR**
> Fixes #29 Use new WBEMServer.create_namespace() in MOF compiler

- setup.cfg
> Added Pypi project links

- docs/changes.rst
- pywbem_mock/_wbemconnection_mock.py
- testsuite/test_wbemconnection_mock.py
WIP. I think this is correct. It passes tests but I want to review once more before I ask for review.
This only changes things associated with the case-sensitivity issue.
> WIP Ks/#1355 rollback

- docs/changes.rst
- pywbem_mock/_wbemconnection_mock.py
- testsuite/test_recorder.py
- testsuite/test_wbemconnection_mock.py
The commit message details all changes, explains the background, and should be read before reviewing.
> Changed namespace handling in mock support to be explicit

- testsuite/test_wbemconnection_mock.py
**Note: This PR is on top of PR #1366**
Ready for review and merge (review only the last commit).
> Made expected exceptions in test_wbemconnection_mock.py more consistent

- docs/changes.rst
- pywbem/_server.py
- testsuite/test_wbemserverclass.py
**Note: This PR is on top of PR #1366**
Ready for review and merge (review only the last commit).
> Fixes #1356: Added WBEMServer.delete_namespace()

- docs/changes.rst
- pywbem/cim_operations.py
- pywbem/exceptions.py
- pywbem/tupleparse.py
- testsuite/test_exceptions.py
- testsuite/testclient/conftest.py
- testsuite/testclient/getinstance.yaml
Needs to be rolled back to 0.12.
> Fixes #1380: Fixed issue of missing support for INSTANCE child elements of ERROR

- docs/changes.rst
- pywbem/cim_operations.py
- pywbem/exceptions.py
- pywbem/tupleparse.py
- testsuite/test_exceptions.py
- testsuite/testclient/getinstance.yaml
This PR rolls back PR #1383 into 0.12.6.
> 0.12: Fixed issue of missing support for INSTANCE child elements of ERROR

- docs/changes.rst
- docs/conf.py
- pywbem/cim_constants.py
- pywbem/cim_operations.py
- testsuite/test_cim_operations.py
> Ensure default connection namespace is not None

- TODO.md
> Emptied TODO.md to reference issue tracker

- INSTALL.md
> Simplified INSTALL.md to be in sync with README

- docs/changes.rst
- pywbem/_logging.py
> Finalized logging support

- docs/changes.rst
- pywbem/cim_operations.py
> Finalized use_pull_operations property

- pywbem/_utils.py
- testsuite/test_utils.py
This PR is a first step towards addressing issue #1072.
> Added _utils._format() for enhanced ASCII formatting

- testsuite/test_recorder.py
**Note: This PR is on top of PR #1400.**
> [Review 2] Improved impl. of test_recorder.py

- pywbem_mock/_wbemconnection_mock.py
- testsuite/run_uprint.py
- testsuite/test_utils.py
> [Review 3] Improved _uprint() by supporting byte strings

- pywbem/_utils.py
- pywbem/mof_compiler.py
- testsuite/run_uprint.py
- testsuite/test_exceptions.py
- testsuite/test_utils.py
- testsuite/test_wbemconnection_mock.py
> Resolved pylint issues

- design/listener.md
- docs/conf.py
- pywbem/cim_operations.py
- pywbem/exceptions.py
> Docs: Removed sphinx warnings; improved keyword args

- testsuite/cmd_line_test_utils.py
- testsuite/run_cim_operations.py
- testsuite/test_wbemcli.py
- testsuite/test_wbemconnection_mock.py
- testsuite/testclient/conftest.py
For details see the commit message.
> Resolved pylint issues; Turned off verbose in wbemcli tests

- pywbem/_nocasedict.py
- pywbem/cim_http.py
- pywbem/mof_compiler.py
- pywbem/tupleparse.py
- testsuite/test_cim_obj.py
> Changed TODO comments with issues to issues to avoid double counting by pylint

- dev-requirements.txt
- docs/changes.rst
- docs/client/exceptions.rst
- docs/client/objects.rst
- docs/client/operations.rst
- docs/client/recording.rst
- docs/client/statistics.rst
- docs/client/types.rst
- docs/client/valuemappings.rst
- docs/compiler.rst
- docs/conf.py
- docs/indication.rst
- docs/mocksupport.rst
- docs/server.rst
- docs/wbemcli.help.txt
> Fixes #1417: Docs: Added auto summary of methods and attributes

- docs/changes.rst
- pywbem/_listener.py
- pywbem/_server.py
- pywbem/_subscription_manager.py
> Fixes #1424: Added __str__() to WBEMServer,Listener,SubscriptionManager

- docs/changes.rst
- pywbem/_server.py
This PR works in the results of Karl's test scripts.
Ready for review, **test**, and merge.
> Improved WBEMServer brand and version a 2nd time.

- .flake8
- dev-requirements.txt
- setup.cfg
- testsuite/run_operationtimeouts.py
- testsuite/test_statistics.py
- testsuite/testclient/conftest.py
- wbemcli.py
The complete collection of 3 commits is needed to address recent issues in CI runs that were caused or detected by new versions of flake8 and pytest.
For details, see the commit messages.
> Fixes #1435: Fixed flake8 and pytest issues

- tox.ini
> Fixed tox and added Python 3.7 support

- dev-requirements.txt
- docs/changes.rst
- minimum-constraints.txt
- requirements.txt
> Upgraded dependent package versions

- testsuite/test_utils.py
> Fixed random test for _utils._format()

- pywbem/cim_operations.py
This PR is a result of the discussion on PR #1439 about setting `last_reply`.
> Improved description of WBEMConnection.last_reply

- docs/changes.rst
- pywbem/exceptions.py
- testsuite/test_exceptions.py
This change is needed as a basis for PR #1538.
> Added ServerWarning class and its base class Warning

- docs/changes.rst
- testsuite/end2end/_utils.py
- testsuite/end2end/profiles.yml
- testsuite/end2end/pytest_end2end.py
- testsuite/end2end/test_profile_generic.py
This is an attempt to get some of the functionality in Karl's scripts into end2end testcases.
Ready for review and test against a real WBEM server.
How to test:
* Have a `testsuite/end2end/server_file.yml` prepared with the servers to test against
* Run `make end2end` and verify that the tests succeed.
> Added profile definitions and more end2end testcases

- docs/client/exceptions.rst
Doc build fix, no review needed.
> Fixed a Sphinx build warning on CIMError

- docs/changes.rst
- pywbem/_server.py
Note: This PR is part of PR #1560 and is tested as part of it, so a separate test is not needed.
> [1] Fixes in WBEMServer.get_central_instances()

- docs/changes.rst
- pywbem/_server.py
- testsuite/end2end/profiles.yml
- testsuite/end2end/pytest_end2end.py
- testsuite/end2end/test_profile_generic.py
**Note: This PR is on top of PR #1561. Review only the delta!**
> [2] Added reference direction to profile definitions; made some items optional

- makefile
This change only affects the `make end2end` test and gets rid of the many DeprecationWarning and ResourceWarning occurrences. It also shortens the lengthy tracebacks. If they are needed, they can be re-enabled by setting `TESTOPTS='--tb=auto'`. The review is more or less the question whether we want to have this shortening.
> Shortened end2end test reports.

- .flake8
- pywbem/_nocasedict.py
- pywbem/_recorder.py
- pywbem/_utils.py
- pywbem/cim_obj.py
- pywbem/cim_operations.py
- testsuite/end2end/server_file.py
> Fixed DeprecationWarning about collections.abc in py3

- testsuite/end2end/pytest_end2end.py
**Note: This PR is on top of PR #1578, review only the last 1 commit**
> [3] End2end: Optimized access to profile defs via dict

- testsuite/end2end/pytest_end2end.py
- testsuite/end2end/test_profile_generic.py
**Note: This PR is on top of PR #1584, review only the last 1 commit.**
> [4] End2end: Warn if server advertises undefined profiles

- testsuite/end2end/test_profile_generic.py
- testsuite/end2end/test_profile_snia_server.py
- testsuite/end2end/test_server.py
> End2end: Moved wbem_connection to end

- testsuite/end2end/assertions.py
- testsuite/end2end/profiles.yml
- testsuite/end2end/test_profile_snia_smis.py
**Note: This PR is on top of PR #1585, review only the last commit**
No separate test needed, this can be tested along with PR #1591 which is based on this PR.
> End2end: Updated profile.yml to reflect comments by Mike

- testsuite/end2end/pytest_end2end.py
- testsuite/end2end/server_file.py
- testsuite/end2end/server_file_example.yml
Testing: Create nested groups in server definition file and check whether they run as expected.
> Fixes #1594: End2end: Support for groups in groups in server definition file

- testsuite/end2end/pytest_end2end.py
> End2end: Fixed optimization for unreachable servers

- tests/servers/server_file.py
- tests/unittest/servers/test_server_file.py
**Note: This PR is on to of PR #1606. Review only the last commit.**
Testing: Test with duplicate servers in various ways.
> Fixed duplicate server error in server_file.py; added unit tests

- docs/development.rst
- tests/README
> Small fixes in Testing section and tests/README

- tests/unittest/pywbem/test_cim_xml.py
> Started converting test_cim_xml.py from unittest to pytest

- docs/changes.rst
- pywbem/exceptions.py
- tests/unittest/pywbem/test_exceptions.py
- tests/unittest/pywbem/test_logging.py
- tests/unittest/pywbem/test_warnings.py
> Removed Connection ID from exception and warning messages

- .gitignore
- docs/changes.rst
- docs/development.rst
- tests/README
- tests/end2endtest/utils/pytest_extensions.py
- tests/server_definitions/example_server_definition_file.yml
- tests/server_definitions/server_definition_file.py
- tests/unittest/server_definitions/test_server_definition_file.py
Testing: I already performed a small local end2end test, which I think is sufficient for this change.
**Note: You need to move and rename your own server definition file:**
From:
`tests/servers/server_file.yml`
to:
`tests/server_definitions/server_definition_file.yml`
> Fixes #1608: End2end: Renamed server_file to server_definition_file

- tests/server_definitions/server_definition_file.py
- tests/unittest/server_definitions/test_server_definition_file.py
> Fixes #1610: Added list_all_server() to ServerDefinitionFile, and fix

- tests/end2endtest/test_profile_generic.py
**Note: This PR is on top of PR #1618. Review only the last commit.**
Testing: end2end test.
> End2end: Changed warning about undefined profiles to error

- PKG-INFO
- makefile
- pywbem_os_setup.bat
This may help with issue #1631, but it is just a very rough guess.
I tested this under native Windows.
> Try: No longer use percent formatting strings in makefile

- .flake8
- pywbem/_recorder.py
- tests/end2endtest/test_profile_generic.py
- tests/end2endtest/test_profile_snia_server.py
- tests/end2endtest/test_profile_snia_smis.py
- tests/end2endtest/test_server.py
> Fixed F811 and E117 issues reported by new flake8 3.7

- docs/appendix.rst
- docs/changes.rst
- pywbem/_server.py
COMMENT: Karl is sitting on approval for thisuntil we get issue #1411 sorted out.
> Fixes #1398: Clarified how to determine scoping class/path if not specified in profile

- PKG-INFO
- docs/changes.rst
- docs/mocksupport.rst
- pywbem_mock/__init__.py
- pywbem_mock/_mockmofwbemconnection.py
- pywbem_mock/_resolvermixin.py
- pywbem_mock/_wbemconnection_mock.py
- tests/unittest/pywbem/test_recorder.py
- tests/unittest/pywbem/test_wbemserverclass.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
WIP
Status
Currently code finished and passes most of the tests. 
Also, in process of rework code to simplify since it duplicates the same code 3 times to resolve properties, methods, parameters.
> [WIP] Fixes #1540: Extend WBEMConnection_mock  class resolution

- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
Fixed issues in:
1. Indent misallignment in
tests/unittest/pywbem_mock/test_wbemconnection_mock.py
> Fix number of pylint issues

- docs/changes.rst
- minimum-constraints.txt
- pywbem_os_setup.bat
- requirements.txt
- rtd-requirements.txt
> Increased M2Crypto to 0.31.0

- docs/changes.rst
- makefile
- minimum-constraints.txt
- pywbem_os_setup.bat
- requirements.txt
- rtd-requirements.txt
Note: This PR is on top of PR #1643, review only the delta.
> Improved makefile for switching between Python versions

- makefile
> Improved dependencies in makefile

- makefile
- pywbem/_recorder.py
- pywbem/_statistics.py
- pywbem/_subscription_manager.py
- pywbem/_valuemapping.py
- pywbem_mock/_resolvermixin.py
- tests/end2endtest/test_profile_generic.py
- tests/end2endtest/test_profile_snia_smis.py
- tests/unittest/pywbem/test_cim_obj.py
I tried to fix several more pylints and removed a couple of prints (surrounded by verbose) in the python_mock module.
See commit for more details
I consider this optional for 0.13.0 but if it passes tests I would propose commiting it.
> Fixed several more pylints

- DEVELOP.md
> Updated develop instructions

- dev-requirements.txt
- docs/changes.rst
- minimum-constraints.txt
- tox.ini
Details:
- Added tox package to development dependencies.
- Added new indirect dependencies of tox to minimin-consiraints.txt
- Fixes in tox.ini
> Fixed tox support

- docs/changes.rst
> Start 0.14.0

- DEVELOP.md
> Fixed heading in new changelog in DEVELOP.md

- tests/manualtest/run_response_performance.py
This does not change the overall execution but adds a couple of columns to report output and cleans up a couple of pieces code.
It also fixes one mispelling that puts bad name into the output files (defiult instead of default)
> Fix some code issues in run_response_performance.py

- tests/manualtest/run_response_performance.py
This eliminates the vertical cell lines on the table so it is easier to
grab the data.  Changes the table fmt from grid to simple
> Change output table format to simple.

- PKG-INFO
- pylintrc
- pywbem/__init__.py
- pywbem/_recorder.py
- pywbem/_server.py
- pywbem/_statistics.py
- pywbem/_subscription_manager.py
- pywbem/_utils.py
- pywbem/_valuemapping.py
- pywbem/cim_obj.py
- pywbem/cim_operations.py
- pywbem/cim_types.py
- pywbem/mof_compiler.py
- tests/functiontest/conftest.py
- tests/manualtest/run_cim_operations.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
Fixes pylint issues primarily associated with no-else-return.
> Fix pylint issues

- README.rst
Added  two badges to README.rst. 
I did it initially as a test for me on writing new badges but they do add information.
There is no firm requirement for this and not sure of the colors at this point
> Add badges to pywbem for python version and license.

- appveyor.yml
- docs/changes.rst
- makefile
- pywbem_os_setup.bat
This PR applies the fix in PR #1683 to the master branch.
> Master: Fixed pip version issue on Appveyor

- docs/changes.rst
- pywbem/cim_types.py
- tests/unittest/pywbem/test_cim_types.py
> Fixes #1681: 0.13: Fixed AttributeError on __offset in CIMDateTime.repr()

- docs/changes.rst
- pywbem/cim_types.py
- tests/unittest/pywbem/test_cim_types.py
This PR applies the fix for issue #1681 to the master branch.
> Master: Fixed AttributeError on __offset in CIMDateTime.repr()

- tests/manualtest/run_enum_performance.py
> Clean up manual test program run_enum_performance.py

- pywbem_os_setup.bat
This is to address connection issues during curl downloads that
occur during Appveyor runs.
> Added retries to curl in pywbem_os_setup.bat

- tests/unittest/pywbem/test_recorder.py
Changed the logs from stderr to file which clears up the problem
> Fix issue #1222 Displays log output during tests

- PKG-INFO
- README.rst
- README_PYPI.rst
- docs/changes.rst
> Release 0.14.0

- docs/changes.rst
> Start 0.14.1

- PKG-INFO
- README.rst
- docs/changes.rst
> Release 0.14.1

- docs/changes.rst
> Start 0.14.2

- docs/changes.rst
- tests/end2endtest/utils/assertions.py
- tests/end2endtest/utils/utils.py
This PR resolves some of the issues reported in issue #1714.
> 0.14: Fixed AttributeError in end2end assertion functions

- docs/changes.rst
- pywbem/_server.py
> 0.14: Changed GetCentralInstances methodology to be bypassed by default

- docs/changes.rst
**Discussion point:** Do we want to go to 1.0.0 as the next version.
> Start 1.0.0

- docs/changes.rst
- makefile
- tests/end2endtest/utils/assertions.py
- tests/end2endtest/utils/utils.py
This fixes a part of the issues reported in issue #1714.
This PR has been rolled back to 0.14.2 in PR #1725.
> 02 Fixed AttributeError in end2end assertion functions

- docs/changes.rst
This PR rolls the fix in PR #1709 (0.14.1) forward into master.
> Fixed change history of 0.14.0

- tests/manualtest/run_response_performance.py
The test directly calls the tuple parser but this call channged from a
direct method call to a Class.method call with the release of pywbem
0.13 so we test the version and create an appropriate method.
This change allows the test to be executed with earlier versions of pywbem so that we can compare results between pywbem versions.
Added pywbem version to runid since we are using this tool to test across multiple pywbem versions
I assume that this is for 1.0.0 so is marked to be rolled back to 14.2
> Fix issue with calling tupleparser in this test

- docs/changes.rst
- tests/profiles/profiles.yml
This PR resolves some of the issues reported in issue #1714.
This PR has been rolled back to 0.14.2 in PR #1724.
> Added and fixed profile definitions for end2end tests

- docs/changes.rst
- pywbem/tupleparse.py
This PR rolls back PR #1727 into 0.14.2.
No separate review needed.
> Add changes to gain more performance in tupleparser

- docs/changes.rst
- pywbem/cim_operations.py
> Fixes #1736: Improved quality of TypeError exceptions raised for WBEMConnection ops args

- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
Remove display_repository() statements that were outputting data during tests but not contributing to the test.
Enable test that we had marked bypassed originally
Clean up a couple of TODOs in test_wbemconnection_mock.py
> Minor changes to testPwbemconnection_mock.py

- docs/changes.rst
- docs/notebooks/iterablecimoperations.ipynb
- pywbem/cim_operations.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
Rollback of PRs #1739, #1742, and #1740 into 0.14.
> Rollback of recent PRs into 0.14

- docs/changes.rst
- pywbem_mock/_wbemconnection_mock.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
This PR rolls back PR #1747 into 0.14.
> Fix issue in mocker with property list (rollback)

- appveyor.yml
- docs/changes.rst
- docs/intro.rst
- makefile
- pywbem_os_setup.bat
- pywbem_os_setup.sh
- tox.ini
> Fixes #1729: Fixed Appveyor CI setup for UNIX environments under Windows

- appveyor.yml
- docs/changes.rst
- docs/intro.rst
- makefile
- pywbem_os_setup.bat
- pywbem_os_setup.sh
- tox.ini
This rolls back PR #1732 into 0.14.2.
No separate review needed.
> Fixed setup for UNIX environments under Windows for Appveyor and locally (rollback)

- PKG-INFO
- README.rst
- docs/changes.rst
> Release 0.14.2

- docs/changes.rst
> Start 0.14.3

- docs/changes.rst
> Updated fix level up to 0.14.2 in change log of 1.0.0

- docs/appendix.rst
- docs/changes.rst
- pywbem_os_setup.bat
> 0.14: Upgraded Win32/Win64 OpenSSL from 1.1.0j to 1.1.0k

- docs/appendix.rst
- docs/changes.rst
- pywbem_os_setup.bat
> Fixes #1754: Upgraded Win32/Win64 OpenSSL from 1.1.0j to 1.1.0k

- .travis.yml
- PKG-INFO
- dev-requirements.txt
- docs/appendix.rst
- docs/changes.rst
- docs/intro.rst
- examples/pegasusindicationtest.py
- makefile
- minimum-constraints.txt
- pywbem/__init__.py
- pywbem/_listener.py
- pywbem/_logging.py
- pywbem/cim_http.py
- requirements.txt
- rtd-requirements.txt
- setup.cfg
- setup.py
- tests/unittest/pywbem/test_cim_obj.py
- tests/unittest/pywbem/test_mof_compiler.py
- tests/unittest/pywbem/test_recorder.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
- tests/unittest/utils/unittest_extensions.py
- tox.ini
> Fixes #330: Removed Python 2.6 support

- docs/changes.rst
> Start 0.14.4

- .gitignore
> Added *.py,cover files to Git ignore list

- docs/changes.rst
- pywbem/cim_http.py
Rolls back PR #1777 into 0.14.4
> 0.14: Fix issue # 1769, load_cert.

- PKG-INFO
- README.rst
- docs/changes.rst
> Release 0.14.4

- docs/changes.rst
> Start 0.14.5

- docs/changes.rst
- pywbem/cim_operations.py
- pywbem_mock/_wbemconnection_mock.py
- tests/functiontest/openenumerateinstanceswithpath.yaml
- tests/functiontest/openreferenceinstanceswithpath.yaml
- tests/unittest/pywbem/test_itermethods.py
This PR rolls back PR #1785 into 0.14.5.
> 0.14: Fixed incorrectly supported LocalOnly parm in OpenEnumerateInstances

- dev-requirements.txt
- docs/changes.rst
> Pinned docutils to version 0.14

- dev-requirements.txt
- docs/changes.rst
This PR rolls back PR #1789 into 0.14.5.
> 0.14: Pinned docutils to version 0.14

- docs/changes.rst
- pywbem/cim_operations.py
- pywbem_mock/_wbemconnection_mock.py
- tests/functiontest/openenumerateinstances.yaml
- tests/functiontest/openreferenceinstances.yaml
- tests/unittest/pywbem/test_itermethods.py
> Fixed incorrectly supported LocalOnly parm in OpenEnumerateInstances

- pywbem/cim_operations.py
- tests/functiontest/openenumerateinstancepaths.yaml
- tests/functiontest/openenumerateinstances.yaml
- tests/functiontest/openreferenceinstances.yaml
**Note: This PR is on top of PR #1794 - review only the last commit**
> Removed incorrect params LocalOnly and IncludeQualifiers from Open..()

- docs/changes.rst
- tests/manualtest/run_cim_operations.py
This rolls back PR #1786 into 0.14.5.
> 0.14: Add test for LocalOnly to manual test

- dev-requirements.txt
- docs/changes.rst
> Fixes #1807: Pinned lxml to <4.4.0

- docs/changes.rst
- pywbem_mock/_resolvermixin.py
> Fixes #1817: Fixed incorrect format specifiers in pywbem_mock

- docs/changes.rst
- pywbem_mock/_resolvermixin.py
Rolls back PR #1818 into 0.14.5.
> 0.14: Fixed incorrect format specifiers in pywbem_mock

- docs/changes.rst
- pywbem_mock/_resolvermixin.py
> Fixes #1820: Fixed handling of ANY scope in mock; improved exceptions

- docs/changes.rst
- pywbem_mock/_resolvermixin.py
This PR rolls back the fix into 0.14.
> 0.14: Fixed handling of ANY scope in mock; improved exceptions

- PKG-INFO
- docs/changes.rst
> Fixed change history of 0.14.4 for LocalOnly; updated PKG-INFO

- tests/unittest/test_wbemcli.py
- wbemcli.py
> 0.14: Fixes #1826: Format of wbemcli option

- PKG-INFO
- pywbem_mock/_wbemconnection_mock.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
> Fixes #1802 in 0.14:  mock enum inst propertylist issue

- docs/changes.rst
> Added change history for PR 1827/1830

- docs/changes.rst
> 0.14: Added change history for PR 1827/1830

- tests/utils.py
This PR picks the commit "Wrap mof file import" from Tony's PR #1815.
> 0.14: Skip tests if moftab files do not exist

- tests/utils.py
This PR rolls PR #1835 forward into master.
> Skip tests if moftab files do not exist

- tests/unittest/test_wbemcli.py
This PR rolls PR #1833 forward into master.
> Fix tests to support flexible wbemcli naming

- tests/__init__.py
- tests/unittest/pywbem/test_cim_obj.py
> Test: Print pywbem path and version and no longer CHECK_0_12_0

- docs/development.rst
- makefile
- tests/README
- tests/utils.py
> 0.14: Improvements for TEST_INSTALLED

- docs/development.rst
- makefile
- tests/README
- tests/utils.py
> Improvements for TEST_INSTALLED

- PKG-INFO
- docs/wbemcli.help.txt
> Updated PKG-INFO and wbemcli help text

- docs/changes.rst
- pywbem_os_setup.sh
> Fixed the issue with 'dnf makecache fast' during pywbem_os_setup.sh on Fedora

- PKG-INFO
- docs/changes.rst
- docs/intro.rst
- docs/wbemcli.help.txt
**Note: This PR is on top of PR #1845. Review only the delta**
> Fixes #1804: 0.14: Docs: Improved installing to a native Windows environment

- docs/changes.rst
- docs/intro.rst
Rolls forward PR #1846 to master.
> Docs: Improved installing to a native Windows environment

- .travis.yml
- pywbem_os_setup.sh
Roll back of. PR #1799 to 0.14.5.
> 0.14: Fixed pyzmq install error on Travis with MacOS 10.13 / Python 3.7

- PKG-INFO
- docs/changes.rst
- pywbem_mock/_wbemconnection_mock.py
- tests/unittest/test_wbemcli.py
- wbemcli.py
This PR rolls back PR #1853 into 0.14.5.
> 0.14: Improved pywbem mock and wbemcli error handling and messages

- PKG-INFO
- README.rst
- docs/changes.rst
> Release 0.14.5

- docs/changes.rst
- pywbem_mock/_wbemconnection_mock.py
- tests/unittest/test_wbemcli.py
- wbemcli.py
> Fixes #1851: Improved wbemcli and pywbem mock error handling and messages

- docs/changes.rst
> Start 0.14.6

- .travis.yml
> Travis: Fixed coveralls to run again for py34/latest

- .travis.yml
> 0.14: Travis: Fixed coveralls to run again for py34/latest

- docs/changes.rst
- pywbem_mock/_wbemconnection_mock.py
> Fixes #1859: Fixed case sensitive class name in ModifyInstance mock support

- docs/changes.rst
- pywbem/_listener.py
- pywbem/_subscription_manager.py
> Fixes #1768: Docs: Fixed issues in Listener and SubscriptionManager examples

- pywbem/_statistics.py
- pywbem/_subscription_manager.py
- pywbem/cim_http.py
- pywbem/cim_operations.py
> Docs: Fixed formatting in WBEMOperations.OpenEnumerateInstances; parm consistency

- dev-requirements.txt
- docs/changes.rst
- minimum-constraints.txt
- requirements.txt
Ready, see commit message. No review needed.
> Fixed minimum version of testfixtures, pytest and PyYAML

- .travis.yml
- dev-requirements.txt
> Fixed coveralls invocation

- .travis.yml
- dev-requirements.txt
Rolls back PR #1885 into 0.15.0.
> 0.15: Fixed coveralls invocation

- docs/changes.rst
- pywbem_mock/_wbemconnection_mock.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
Rolls back PR #1884 into 0.15.0.
> 0.15: Property case on CreateInstance

- docs/changes.rst
- pywbem_mock/_wbemconnection_mock.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
Rolls back PR #1889 to 0.15.0.
> 0.15: Mock Modify Instance property case sensitivity

- docs/changes.rst
- pywbem/mof_compiler.py
Rolls back PR #1895 into 0.15.0.
> 0.15: Fixes #1894: duplicate instance compile loses instance

- appveyor.yml
- dev-requirements.txt
- makefile
- minimum-constraints.txt
- tox.ini
Rolls back PR #1899 into 0.15.0
> 0.15: Test: Fixed Python version on Appveyor CI

- appveyor.yml
- dev-requirements.txt
- makefile
- minimum-constraints.txt
- tox.ini
> Fixes #1898: Test: Fixed Python version on Appveyor CI

- docs/changes.rst
- pywbem_mock/_mockmofwbemconnection.py
- pywbem_mock/_wbemconnection_mock.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
Rolls back PR #1892 into 0.15.0
> 0.15: Fixes #1852: Fix issue with possible dup instances in mock repo

- docs/appendix.rst
- docs/development.rst
- docs/intro.rst
Ready, see commit message.
This includes the py34/win trouble shooting hint for lxml, as well as further changes.
> Docs: Fixes and improvements in development section

- docs/appendix.rst
- docs/development.rst
- docs/intro.rst
Rolls back PR #1901 to 0.15.0.
> 0.15: Docs: Fixes and improvements in development section

- .travis.yml
> Enabled coveralls on Travis for all event types and branches

- pywbem/cim_obj.py
> Applied review comment on docs of CIMInstance.update_existing()

- docs/changes.rst
- docs/mocksupport.rst
- pywbem/mof_compiler.py
- pywbem_mock/_mockmofwbemconnection.py
- tests/unittest/pywbem/test_mof_compiler.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
Rolls back PR #1909 into 0.15.0.
> 0.15: Fixes #1890: Modify mof compiler and mocker to clean up CreateInstance (#1909)

- .travis.yml
- appveyor.yml
- dev-requirements.txt
- docs/changes.rst
- minimum-constraints.txt
- pywbem/cim_types.py
- setup.py
- tests/unittest/pywbem/test_cim_types.py
- tests/unittest/utils/validate.py
- tox.ini
Rolls back PR #1893 into 0.15.0.
> 0.15: Added support for Python 3.8 (Appveyor still commented out)

- docs/changes.rst
- pywbem/cim_operations.py
For details, see the commit message. Ready for review.
I don't think that this PR should be rolled back into 0.15.
> Fixes #1572: Improved performance when setting WBEMConnection.debug

- pywbem/cim_obj.py
- tests/unittest/pywbem/test_cim_obj.py
> Fixes #1927: Removed 'methodname' parameter from CIMMethod

- docs/changes.rst
- pywbem/_valuemapping.py
- tests/unittest/pywbem/test_valuemapping.py
> Fixes #1429: Changed exceptions raised in ValueMapping

- dev-requirements.txt
- docs/changes.rst
- minimum-constraints.txt
> Fixes #1946: Workaround for pywin32 issue on Appveyor python 2.7 32-bit

- minimum-constraints.txt
- pywbem_mock/_wbemconnection_mock.py
- requirements.txt
- tests/unittest/pywbem_mock/conftest.py
- tests/unittest/pywbem_mock/test_complexassoc.py
- tests/unittest/pywbem_mock/test_wbemconnection_mock.py
Rolls back PR #1918 into 0.15.0
> 0.15: Fixes #1917: Issues with mock assocs

- dev-requirements.txt
- docs/conf.py
- docs/index.rst
- docs/mof_compiler.help.txt
- minimum-constraints.txt
- rtd-requirements.txt
This PR rolls back #1960 into 0.15.0
> 0.15: Fixes #1941 - documentation full TOC

- appveyor.yml
Disabled,only providing the basis for the manual-ci-run branch. No review needed.
> Added 32-bit cygwin environments to Appveyor (disabled)

- appveyor.yml
> 0.15: Added 32-bit cygwin environments to Appveyor (disabled)

- README.rst
- README_PYPI.rst
> Minor fixes in README files

- README.rst
- README_PYPI.rst
Rolls back PR #1973 to 0.15.0.
> 0.15: Minor fixes in README files

- docs/appendix.rst
- docs/changes.rst
- pywbem/cim_http.py
The reported SSL errors were in issues #1950 and #1966.
> Added troubleshooting for SSL issues; added OpenSSL version to ConnectionError raised for SSL issues

- docs/appendix.rst
- docs/changes.rst
- pywbem/cim_http.py
This PR rolls back PR #1967 into 0.15.0.
> 0.15: Added troubleshooting for SSL issues; added OpenSSL version to ConnectionError raised for SSL issues

- dev-requirements.txt
- docs/changes.rst
- makefile
- minimum-constraints.txt
See commit messages.
Ready for merge.
> Fixes #1975,#1980: Fixed various install issues on Python 3.8 on native Windows (lxml,pywin32,flake8,pip)

- DEVELOP.md
> 0.15: Updated DEVELOP.md to reflect recent change in README_PYPI.md

- DEVELOP.md
> Updated DEVELOP.md to reflect recent change in README_PYPI.md

- README.rst
- README_PYPI.rst
- docs/changes.rst
- pywbem/_version.py
> Release 0.15.0

- README_PYPI.rst
- setup.py
Rolls forward PR #1986 into master.
> Fixed README for Pypi; Added long_description_content_type to setup()

- docs/changes.rst
- pywbem/_version.py
> Start 0.16.0
